### ISSUE TITLE
node server.js fails in sonos-http-api, player.js:259

### ISSUE THREAD

**Issue by pmonday** [jishi/node-sonos-http-api#100]
Hi, I'm just starting to run this, maybe I pulled the code at an inopportune time?  I'm running on CentOS 7, after I install I attempt to run and receive the following (the log is included after this):

npm start

> sonos-http-api@0.17.0 start /data/software/node-sonos-http-api-master
> node server.js
[npm-debug.zip](https://github.com/jishi/node-sonos-http-api/files/60156/npm-debug.zip)

/data/software/node-sonos-http-api-master/node_modules/sonos-discovery/lib/player.js:259
      .then((highResAlbumArtUrl) => {
                                  ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/data/software/node-sonos-http-api-master/node_modules/sonos-discovery/lib/sonos.js:11:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! Linux 3.10.0-229.20.1.el7.x86_64
npm ERR! argv "node" "/usr/bin/npm" "start"
npm ERR! node v0.10.41
npm ERR! npm  v2.14.14
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@0.17.0 start: `node server.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the sonos-http-api@0.17.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/software/node-sonos-http-api-master/npm-debug.log
[paul.monday@nas-servicefoundry-com node-sonos-http-api-master]$ npm owner lis sonos-http-api
npm ERR! Usage: 
npm ERR! npm owner add <username> <pkg>
npm ERR! npm owner rm <username> <pkg>
npm ERR! npm owner ls <pkg>

**Comment by jishi** [comment]
Yes, you now require node 4+, try to upgrade using the official binaries.

**Comment by pmonday** [comment]
That did it, thank you for the quick response ... my own lUser error ;-)  Obviously I haven't coded node in a while since my new install.  Thanks again!
