### ISSUE TITLE
Docker container broken

### ISSUE THREAD

**Issue by haplm** [jishi/node-sonos-http-api#101]
Not sure if this repo is the right place to mention it, but it seems to be the only place available.

Docker image provided by @riemers is currently failing to start, with the error mentioned in issue #100  (old version of node.js used).

@riemers, would it be possible to update the node.js version in that image, please?

Thank you!

**Comment by riemers** [comment]
I think https://github.com/jishi/node-sonos-http-api/pull/102 should be sufficient. Please check :)

**Comment by jishi** [comment]
Great, @riemers, have you pushed this to the docker repo as well?

**Comment by riemers** [comment]
I did yes.

**Comment by haplm** [comment]
Maybe I'm doing something wrong, but the container don't seem to be able to start the actual server. It only seems to install the stuff, but then it ends:

```
request-promise@1.0.2 node_modules/request-promise
├── bluebird@2.10.2
├── continuation-local-storage@3.1.4 (emitter-listener@1.0.1, async-listener@0.5.6)
├── cls-bluebird@1.0.1 (shimmer@1.1.0)
├── lodash@3.10.1
└── request@2.67.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.2, oauth-sign@0.8.0, caseless@0.11.0, form-data@1.0.0-rc3, is-typedarray@1.0.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.1, node-uuid@1.4.7, qs@5.2.0, combined-stream@1.0.5, mime-types@2.1.8, hawk@3.1.2, bl@1.0.0, http-signature@1.1.0, har-validator@2.0.3)
npm info ok 
```

I have tried with Kitematic, CLI and QNAP Virtualization Station, the result is always the same - after a while, it shuts down.

**Comment by riemers** [comment]
If it shutdowns after a while, you should start it up with "restart always" option. I didn't include any pm2/forever node tools for it since docker can restart a container just fine. Maybe something changed, i only updated the docker file to include the node4 version. If its something else, let me know.. i'll take a look at it more then.

**Comment by haplm** [comment]
What I mean is that the server doesn't even start. The startup script only installs things, that's it.

I'm not a node.js expert (in fact I know nothing about it), but "node ." doesn't seem to start it. When I try it locally, "npm start" seems to do the job.

**Comment by riemers** [comment]
Seems that doesn't work anymore for some reason, changed it to npm start (i normally used node . so it would take the file from the root, but npm start can check the package.json) https://github.com/jishi/node-sonos-http-api/pull/104 should fix that.

**Comment by haplm** [comment]
I can confirm that this fixed the problem.

Thank you!
