### ISSUE TITLE
Using prerecorded mp3s with sayall

### ISSUE THREAD

**Issue by tnemrap** [jishi/node-sonos-http-api#107]
Hi
Is it possible to use prerecorded mp3's with sayall.
nerd tts is not so good at swedish.
/Mike

**Comment by jishi** [comment]
Well, not right know. In theory it is possible, yes, but the main focus will be to support the registered version of voicerss which will have language support and better voice simulation. 

If you want to use pre-recorded audio, I suggest that you experiment by creating your own actions and replace the part where it tries to play the tts stream, and instead point it to a webserver hosting mp3 files.

Follow https://github.com/jishi/node-sonos-http-api/issues/97 if you want a status update in the voicerss progress.
