### ISSUE TITLE
newbie question

### ISSUE THREAD

**Issue by jolerius** [jishi/node-sonos-http-api#112]
Hi there.

I am totally new to this thing. 

Were exactly do i put the adress to make sonos do something?
And is it the IP for my rpi i should use or the sonos?

**Comment by NovaGL** [comment]
You put the address in your web browser, the IP is the IP of the Rpi.

If you want it to pause the music in the living room you would do the following.

http://Raspberry-pi-ip:5005/living room/pause

Make sure you have Node installed on the Pi and it is v4 or newer, look on the web how to install node.

**Comment by jolerius** [comment]
Still nothing.

Don't i need to put any files somewhere on the rpi?

Is the room case sensitive?

/Joakim Olerius
Den 22 dec 2015 7:53 AM skrev "NovaGL" <notifications@github.com>:

**Comment by jishi** [comment]
You need to be a bit more specific in your feedback. What kind of error do you receive in your browser, timeout, blank page? Is it instant? Connection refused?

And specify the output from the terminal where you started the script on (where you wrote npm start) after you have tried to invoke the commands in the browser.

No, room names are not case sensitive.

**Comment by jolerius** [comment]
in chrome i get ERR_CONNECTION_REFUSED

and this is what i get when trying npm start

root@osmc:~# ndm start
-bash: ndm: command not found
root@osmc:~# npm start
npm ERR! Linux 4.3.0-10-osmc
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! path /root/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/root/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by jishi** [comment]
You need to stand in the folder where you unzipped the http api, where the package.json file is, or the server.js file is. 

Probably /root/node-sonos-htt-api

Then run npm start

**Comment by jolerius** [comment]
how can i find that folder?

2015-12-22 11:36 GMT+01:00 Jimmy Shimizu <notifications@github.com>:

> You need to stand in the folder where you unzipped the http api, where the
> package.json file is, or the server.js file is.
>
> Probably /root/node-sonos-htt-api
>
> Then run npm start
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jishi/node-sonos-http-api/issues/112#issuecomment-166577596>
> .
>



-- 
//Joakim Olerius

**Comment by jolerius** [comment]
is it a problem that iäm trying to do this on a rpi containing osmc?

**Comment by jolerius** [comment]
i tried logging in with winSCP to see the file structure. But i cant find anything helpfull.
What am i doing wrong?

**Comment by jishi** [comment]
Should work on OSMC if node 4+ is running correctly. Looks like you are running 5.3.0, which should be fine. 

It was you who cloned the git-repo somewhere on the device. If you run:

git clone https://github.com/jishi/node-sonos-http-api.git

it will create a folder, where you stand, named "node-sonos-http-api". do:

cd node-sonos-http-api

then: 

npm start

Considering your line of questions here, I'm not sure what you want to use this for? This is primarily targeted for automation purposes, the "invoke in browser" is merely just a simple way of testing it out as a troubleshooting measure.

**Comment by jolerius** [comment]
osmc@osmc:~$ git clone https://github.com/jishi/node-sonos-http-api.git
-bash: git: command not found

i got this???

**Comment by jishi** [comment]
Okay, you don't have git installed, I confused it with another ticket that was opened today.

You can use this zip archive:

https://github.com/jishi/node-sonos-http-api/archive/master.zip

Unzip that, somehow on your device (in your case, maybe it's better to unzip it on your computer, then transfer the files onto the rpi using winscp). Then, from that folder, invoke the npm install --production followed by npm start.
