### ISSUE TITLE
Feature Request: Play from Spotify URL/Search

### ISSUE THREAD

**Issue by KarimGeiger** [jishi/node-sonos-http-api#113]
First things first: You are awesome. Your API is exactly what I was searching for and it works almost perfectly for my needs. The only thing I'm missing is a deeper Spotify integration.

What I'd love to see is to directly search for a song on Spotify and play the first hit, then the next one and so on.

If that's not possible due to limitations on either side, another cool feature would be to play a Spotify URL. I've seen that the currentTrack object returns some spotifyish URI when playing. Would it be possible to convert and set that URI?

**Comment by jishi** [comment]
Hi, thank you very much, glad you like it. 

What you are asking for is very possible. I actually have a prototype of starting playing a spotify URI directly (spotify:track:4GVPLHHswg8DaWFsKnquLM) which could be used in conjunction with the Spotify Web Api. However, without authentication, you can only use it as a generic search with no connection to your user. If interested, I could add that to this project for you to play around with. This was done before they introduced multiple accounts per service, so it doesn't take that into consideration. For most people, this is fine though.

**Comment by KarimGeiger** [comment]
That'd be great. I would love to play around with that! Thanks a lot :)

**Comment by jishi** [comment]
Fixed this in the latest commit, see README for info.
