### ISSUE TITLE
install problem node sonos http api

### ISSUE THREAD

**Issue by bran2000** [jishi/node-sonos-http-api#118]
Hi,
Firstly thanks for your work !
However i have a install problem when i typed npm install, i have this error message :
npm WARN engine require-fu@1.0.0: wanted: {"node":"0.10.x"} (current: {"node":"0.12.1","npm":"2.5.1"})
require-fu@1.0.0 node_modules/require-fu

this is the all the message :
pi@DomoticzSam ~/node-sonos-http-api $ npm install
npm WARN engine require-fu@1.0.0: wanted: {"node":"0.10.x"} (current: {"node":"0.12.1","npm":"2.5.1"})
require-fu@1.0.0 node_modules/require-fu

async@1.5.0 node_modules/async

node-static@0.7.7 node_modules/node-static
├── mime@1.3.4
├── colors@1.1.2
└── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)

request-promise@1.0.2 node_modules/request-promise
├── bluebird@2.10.2
├── continuation-local-storage@3.1.4 (emitter-listener@1.0.1, async-listener@0.5.6)
├── cls-bluebird@1.0.1 (shimmer@1.1.0)
├── request@2.67.0 (is-typedarray@1.0.0, aws-sign2@0.6.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.5, tunnel-agent@0.4.2, oauth-sign@0.8.0, form-data@1.0.0-rc3, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.7, combined-stream@1.0.5, qs@5.2.0, tough-cookie@2.2.1, mime-types@2.1.8, bl@1.0.0, har-validator@2.0.3, http-signature@1.1.0, hawk@3.1.2)
└── lodash@3.10.1

sonos-discovery@0.16.1 node_modules/sonos-discovery
├── easysax@0.1.14
├── html-entities@1.0.10
├── async@0.2.10
├── rewire@2.5.1
├── winston@0.8.3 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, isstream@0.1.2, colors@0.6.2, pkginfo@0.3.1)
├── bluebird@2.10.2
└── xml2js@0.4.15 (sax@1.1.4, xmlbuilder@4.2.0)

i don't know if it affects the installation but if i continue and type this time : 
i have this error message : 
/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/player.js:259
      .then((highResAlbumArtUrl) => {
                                 ^^
SyntaxError: Unexpected token =>

see the complete log :
pi@DomoticzSam ~/node-sonos-http-api $ node server.js
/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/player.js:259
      .then((highResAlbumArtUrl) => {
                                 ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/sonos.js:11:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

thanks for your help, i tried so many times to make it works

**Comment by bran2000** [comment]
i forgot when i type this command in my browser :
http://localhost:5005/zones

nothing happens, i have a white page
i replaced the localhost by the rasp IP or by the computer i use but nothing happens

**Comment by bran2000** [comment]
i checked the other ticket you have resolved, it seems i have a problem with my node version : 
node -v
v0.12.1

how i downgrade the version ?

**Comment by okoeth** [comment]
I had the same issue but up(!)graded to 4.x.x. It then worked like a charm. I'm running on a Raspberry Pi Model B+.

**Comment by bran2000** [comment]
Thanks i'll do this

**Comment by bran2000** [comment]
Thanks it works !
However i have a another problem, i try to start the api node at boot but i have this message error :
[PM2][ERROR] script not found : /home/pi/node-sonos-http-api/node_modules/node-sonos-http-api/server.js  

the complete log :
pi@DomoticzSam ~/node-sonos-http-api $ pm2 -x start node_modules/node-sonos-http-api/server.js --name "node-sonos"
[PM2][ERROR] script not found : /home/pi/node-sonos-http-api/node_modules/node-sonos-http-api/server.js  

For information  i can' t find the "server.js "  i only found here : 
/home/pi/node-sonos-http-api

**Comment by NovaGL** [comment]
Yeh, the latest version needs v4 or higher

**Comment by okoeth** [comment]
Bran2000, do you still have the issue? Did not see the comment from the below email on GitHub. PM2 works for me. Needed one fix as described here
https://github.com/Unitech/pm2/issues/1654
Merci!
mfg OK

Oliver Koeth | Executive Architect | NTT DATA Deutschland | M. +49 163 4212394 | Follow me on T<http://twitter.com/okoeth> | Learn more at www.nttdata.com/de<http://www.nttdata.com/de>

**Comment by bran2000** [comment]
Thanks for all your help i typed this command : 
pi@DomoticzSam ~/node-sonos-http-api $pm2 -x start server.js --name "node-sonos"
and it works now !
the only problem, it's when i rebooted node-sonos not working anymore
how can i save my configuration at the boot ?

**Comment by okoeth** [comment]
There are two things you may want to check: First, which PM2 home does your /etc/init.d/pm2-init.sh script use? I had to change mine manually to export PM2_HOME="/home/pi/.pm2". It had pointed to /root/.pm2. Next question is whether your root user has access to the node binaries. I have created symlinks in /usr/local/bin for npm, pm2 and node. With these changes, my node.js server survives a reboot and "pm2 list" outputs
...
 server   │ 0  │ fork │ 2076 │ online │ 0       │ 9h     │ 41.563 MB 
...

**Comment by bran2000** [comment]
Thanks, i did the first step and manually changed the PM2_HOME="/home/pi/.pm2 in the sh file.
For the next step, sorry but can you explain the symlinks things ? i don't know how i can create symlinks in /usr/local/bin for npm, pm2 and node

**Comment by bran2000** [comment]
This the access i have 
pi@DomoticzSam /usr/local/bin $ ls -l
total 21092
lrwxrwxrwx 1 root staff           41 déc.  29 10:28 airsonos -> ../lib/node_
modules/airsonos/bin/index.js
lrwxrwxrwx 1 root staff           39 déc.  27 23:28 forever -> ../lib/node_m
odules/forever/bin/forever
drwxrwsr-x 2 root indiecity     4096 janv. 31  2015 indiecity
-rwxr-xr-x 1 root staff     21591845 déc.  28 14:30 node
lrwxrwxrwx 1 root staff           38 déc.  28 14:38 npm -> ../lib/node_modul
es/npm/bin/npm-cli.js
lrwxrwxrwx 1 root staff           31 déc.  28 15:48 pm2 -> ../lib/node_modul
es/pm2/bin/pm2
lrwxrwxrwx 1 root staff           35 déc.  28 15:48 pm2-dev -> ../lib/node_m
odules/pm2/bin/pm2-dev

**Comment by bran2000** [comment]
I guess i should do something like this : 
ln -s target source
so it should be
 ln-s  /usr/local/bin/npm  /home/pi/node-sonos-http-api
ln-s pm2 /usr/local/bin/pm2 /home/pi/node-sonos-http-api
ln-s pm2 /usr/local/bin/node /home/pi/node-sonos-http-api
am i right ?

**Comment by okoeth** [comment]
Yes, "ln -s" (mind the space) is correct, I did 
cd /usr/local/bin
sudo ln -s /home/pi/workspace/node-v4.2.4-linux-armv7l/bin/pm2 pm2 
sudo ln -s /home/pi/workspace/node-v4.2.4-linux-armv7l/bin/node node 
sudo ln -s /home/pi/workspace/node-v4.2.4-linux-armv7l/bin/npm npm 
Then ls -l will show the symlinks and sudo / root should always have access to the binaries.

**Comment by bran2000** [comment]
ok thanks i understand now.
the only thing i missed is the folder pm2, it's not in the folder "node-v4.2.1-linux-armv6l"
pi@DomoticzSam ~/node-v4.2.1-linux-armv6l/bin $ ls
node  npm

in your case, it is but not mine

**Comment by okoeth** [comment]
Ok. Great to here this. @jishi I think this one can be closed now.

**Comment by jishi** [comment]
Thanks for helping out guys!
