### ISSUE TITLE
play mp3 files and radio streams

### ISSUE THREAD

**Issue by tgdkere2** [jishi/node-sonos-http-api#12]
Hi,
This is more a feature request or general question than an issue. 
Is it technically possible to play a mp3 file located on the harddisk or a mp3 radio stream based on the url. The files are not known in the sonos library. 
Reason: I try to implement the http api to my home automation control system. 
There, I already have a media manager knowing all the local mp3 files and radio stations. Now I would like to play these files or playlists or stations by sending an http API command.

Something like: play uri: 
"x-file-cifs%3a2f%2fMEDIASERVER%2fiTunes%2520Music%2fMarc%2520Seales.mp3"
or
"x-rincon-mp3radio://players.creacast.com/creacast/klassik/playlist.pls"

or to put the files directly to the queue and play it by playing the queue. 
I appreciate any hint or tipp and thanks a lot for your sonos github projects here. 
Regards
Kenny

**Comment by robmathieson** [comment]
Hi, does anyone have an example of the setavtransporturi http call using a direct url call? i cant seem to get this working

**Comment by jishi** [comment]
@robmathieson Please open a new issue for this request.
