### ISSUE TITLE
Say: Title not coded correctrly

### ISSUE THREAD

**Issue by rhalbheer** [jishi/node-sonos-http-api#122]
Hi,
this is really a great piece of work! Thank you.
I tried to use the command "say" and then my SONOS tells me that it cannot play the mp3 file as "it is not coded correctly" (free translation from German).
Any idea what this could be?
Thank you
Roger

**Comment by jishi** [comment]
This usually occurs when the mp3 is corrupted or missing. Can you verify that the cached version of the file show up in the file system where you run the http api? And an you access the file from your browser or similar? I think the actual url that Sonos is trying to play is outputted to the console.

**Comment by rhalbheer** [comment]
I found the files. Interestingly the files are empty (I tried three different ones)

**Comment by jishi** [comment]
Check permissions, but it could also be some issue with the tts - service.
The say stuff is really unstable at the moment and was more a proof of
concept. I will try to work on it soon and fix the issues that are ongoing.

**Comment by rhalbheer** [comment]
I love the functionality as I would like to use my rpi as an extension of my home automation and have sonos announcing the necessary stuff.
to test, I changed permissions on the tts folder to 777, the file still has -rw--r--r- and is empy

**Comment by rhalbheer** [comment]
I have to admit that I am not a Linux pro but is there anything I can do to figure out, what is happening?

**Comment by rhalbheer** [comment]
OK, found it. You TTS URL seems not to resolve in my environment. I used www.voicerss.org now and currently I guess it seems to work

**Comment by jishi** [comment]
ok, great. Follow this issue if you want to track progress. https://github.com/jishi/node-sonos-http-api/issues/97
