### ISSUE TITLE
mac os x error

### ISSUE THREAD

**Issue by fredgalpern** [jishi/node-sonos-http-api#126]
When I run: npm install --production 
i get: npm WARN package.json sonos-http-api@0.17.0 No license field.
any thoughts?

**Comment by jishi** [comment]
That's just a warning, you can ignore that. Are you having trouble starting
it?

**Comment by fredgalpern** [comment]
Yes, it doesn't seem to be running.

**Comment by fredgalpern** [comment]
​brew list returns node, nothing else​

**Comment by jishi** [comment]
Well, sounds like you missed a step. You need to start it manually using
"npm start". It will run as long as the terminal is open, it doesn't run as
a daemon.

**Comment by fredgalpern** [comment]
Hmm, I did that but will try again now.

**Comment by fredgalpern** [comment]
when i run npm i start i get:
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@0.17.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sonos-http-api@0.17.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/fgalpern/Downloads/Echo2Sonos/node-sonos-http-api-master/npm-debug.log

**Comment by jishi** [comment]
Hm, weird that you don't get any error output. Try invoking it directly using node:

node server.js

And give me the output.

**Comment by fredgalpern** [comment]
no settings file found, will only use default settings
error: port in use 3500 trying new one
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::5005
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1238:14)
    at listen (net.js:1274:10)
    at Server.listen (net.js:1370:5)
    at Object.<anonymous> (/Users/fgalpern/Downloads/Echo2Sonos/node-sonos-http-api-master/server.js:57:8)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

**Comment by jishi** [comment]
Weird, sounds like you are already running an instance of the HTTP API, or some other process that happens to use both ports that it expect to be free. Are you sure you haven't already started it? Try to find which processes that is using port 3500 and 5005, I think you can use lsof for it:

http://unix.stackexchange.com/questions/26887/lsof-and-listening-ports

**Comment by fredgalpern** [comment]
btw, thanks for helping!
lsof -i -sTCP:LISTEN returns:
COMMAND    PID     USER   FD   TYPE           DEVICE SIZE/OFF NODE NAME
UserEvent  512 fgalpern    4u  IPv4 0x5c27a73cced82b      0t0  UDP *:*
SystemUIS  523 fgalpern    9u  IPv4 0x5c27a73ccec283      0t0  UDP *:*
SystemUIS  523 fgalpern   10u  IPv4 0x5c27a73e6e403b      0t0  UDP *:*
SystemUIS  523 fgalpern   13u  IPv4 0x5c27a73e6e3dd3      0t0  UDP *:55702
SystemUIS  523 fgalpern   15u  IPv4 0x5c27a73e6e3b6b      0t0  UDP *:*
SystemUIS  523 fgalpern   17u  IPv4 0x5c27a73f1b99bb      0t0  UDP *:*
sharingd   531 fgalpern   12u  IPv4 0x5c27a73ccedcfb      0t0  UDP *:*
sharingd   531 fgalpern   16u  IPv4 0x5c27a73e6e4773      0t0  UDP *:*
WiFiAgent  585 fgalpern    7u  IPv4 0x5c27a73ccf0ab3      0t0  UDP *:*
Adium      623 fgalpern   17u  IPv4 0x5c27a73e711433      0t0  UDP *:49836
WiFiProxy  635 fgalpern    6u  IPv4 0x5c27a73f1bd5e3      0t0  UDP *:*
Transmiss  875 fgalpern   10u  IPv4 0x5c27a73ccee433      0t0  UDP *:57998
Transmiss  875 fgalpern   11u  IPv4 0x5c27a74a97ded3      0t0  TCP *:nimcontroller (LISTEN)
Transmiss  875 fgalpern   12u  IPv6 0x5c27a740111503      0t0  TCP *:nimcontroller (LISTEN)
Transmiss  875 fgalpern   13u  IPv4 0x5c27a73ccecc23      0t0  UDP *:nimcontroller
Transmiss  875 fgalpern   15u  IPv4 0x5c27a73ccec753      0t0  UDP 192.168.2.185:58898->router.asus.com:nat-pmp
ARDAgent  4767 fgalpern    7u  IPv6 0x5c27a73f23682b      0t0  UDP *:net-assistant
ARDAgent  4767 fgalpern    8u  IPv4 0x5c27a73f2365c3      0t0  UDP *:net-assistant
iTunes    6047 fgalpern   31u  IPv4 0x5c27a7540b2cc3      0t0  TCP *:53921 (LISTEN)
iTunes    6047 fgalpern   34u  IPv4 0x5c27a750de2cc3      0t0  TCP *:daap (LISTEN)
iTunes    6047 fgalpern   35u  IPv6 0x5c27a74e01cfe3      0t0  TCP *:daap (LISTEN)
node      9484 fgalpern   21u  IPv6 0x5c27a74e01e563      0t0  TCP *:rtmp-port (LISTEN)
node      9484 fgalpern   22u  IPv6 0x5c27a740112fe3      0t0  TCP *:avt-profile-2 (LISTEN)

**Comment by jishi** [comment]
Add -P and -n to avoid port name lookup, I can't see which ones are using 5005 or 3500 there

**Comment by fredgalpern** [comment]
COMMAND    PID     USER   FD   TYPE           DEVICE SIZE/OFF NODE NAME
UserEvent  512 fgalpern    4u  IPv4 0x5c27a73cced82b      0t0  UDP *:*
SystemUIS  523 fgalpern    9u  IPv4 0x5c27a73ccec283      0t0  UDP *:*
SystemUIS  523 fgalpern   10u  IPv4 0x5c27a73e6e403b      0t0  UDP *:*
SystemUIS  523 fgalpern   13u  IPv4 0x5c27a73e6e3dd3      0t0  UDP *:55702
SystemUIS  523 fgalpern   15u  IPv4 0x5c27a73e6e3b6b      0t0  UDP *:*
SystemUIS  523 fgalpern   17u  IPv4 0x5c27a73f1b99bb      0t0  UDP *:*
sharingd   531 fgalpern   12u  IPv4 0x5c27a73ccedcfb      0t0  UDP *:*
sharingd   531 fgalpern   16u  IPv4 0x5c27a73e6e4773      0t0  UDP *:*
WiFiAgent  585 fgalpern    7u  IPv4 0x5c27a73ccf0ab3      0t0  UDP *:*
Adium      623 fgalpern   17u  IPv4 0x5c27a73e711433      0t0  UDP *:49836
WiFiProxy  635 fgalpern    6u  IPv4 0x5c27a73f1bd5e3      0t0  UDP *:*
Transmiss  875 fgalpern   10u  IPv4 0x5c27a73ccee433      0t0  UDP *:57998
Transmiss  875 fgalpern   11u  IPv4 0x5c27a74a97ded3      0t0  TCP *:48000 (LISTEN)
Transmiss  875 fgalpern   12u  IPv6 0x5c27a740111503      0t0  TCP *:48000 (LISTEN)
Transmiss  875 fgalpern   13u  IPv4 0x5c27a73ccecc23      0t0  UDP *:48000
Transmiss  875 fgalpern   15u  IPv4 0x5c27a73ccec753      0t0  UDP 192.168.2.185:58898->192.168.2.1:5351
ARDAgent  4767 fgalpern    7u  IPv6 0x5c27a73f23682b      0t0  UDP *:3283
ARDAgent  4767 fgalpern    8u  IPv4 0x5c27a73f2365c3      0t0  UDP *:3283
iTunes    6047 fgalpern   31u  IPv4 0x5c27a7540b2cc3      0t0  TCP *:53921 (LISTEN)
iTunes    6047 fgalpern   34u  IPv4 0x5c27a750de2cc3      0t0  TCP *:3689 (LISTEN)
iTunes    6047 fgalpern   35u  IPv6 0x5c27a74e01cfe3      0t0  TCP *:3689 (LISTEN)
node      9484 fgalpern   21u  IPv6 0x5c27a74e01e563      0t0  TCP *:3500 (LISTEN)
node      9484 fgalpern   22u  IPv6 0x5c27a740112fe3      0t0  TCP *:5005 (LISTEN)

**Comment by jishi** [comment]
so a node process with pid 9484 is already running. Where did you start that? I'm guessing your computer is already answering requests to http://localhost:5005/

**Comment by fredgalpern** [comment]
sheesh, i have no idea. if you couldn't already tell, i'm a noob with this stuff. any ideas on how to track it down?

**Comment by fredgalpern** [comment]
perhaps from following info here: https://github.com/rgraciano/echo-sonos

**Comment by jishi** [comment]
I mean, you should have some terminal window open that is actually running this :). I'm not sure what you are trying to do, but since it is running, you don't have to start it again.

If you really want to start over, you could probably just quit iTerm (Cmd + Q) and start over again.

**Comment by fredgalpern** [comment]
ok, i'll try starting over again. just to be sure, should step 1 be npm start?

**Comment by jishi** [comment]
npm install --production is a one time command, just to download all the necessary libraries. If you delete everything and redownload the http api, you will need to reinvoke it.

npm start is to start it, and is the only command that should be necessary subsequent startups.

**Comment by fredgalpern** [comment]
see results below. fwiw, when i invoke http://localhost:5005/zones, or any of the other commands, i get nothing, just a cursor.


> sonos-http-api@0.17.0 start /Users/fgalpern/Downloads/Echo2Sonos/node-sonos-http-api-master
> node server.js

no settings file found, will only use default settings
http server listening on port 5005
loaded presets { test: 
   { players: [ [Object] ],
     state: 'PLAYING',
     favorite: 'Rock',
     uri: 'x-rincon-stream:RINCON_0000000000001500',
     playMode: 'SHUFFLE',
     pauseOthers: true },
  rap: 
   { players: [ [Object], [Object], [Object], [Object], [Object] ],
     state: 'PLAYING',
     favorite: 'Rap',
     uri: 'x-rincon-stream:RINCON_0000000000001500',
     playMode: 'SHUFFLE',
     pauseOthers: true },
  'pop rap': 
   { players: [ [Object], [Object], [Object], [Object], [Object] ],
     state: 'PLAYING',
     favorite: 'Rap (Pop)',
     uri: 'x-rincon-stream:RINCON_0000000000001500',
     playMode: 'SHUFFLE',
     pauseOthers: true },
  rock: 
   { players: [ [Object], [Object], [Object], [Object], [Object] ],
     state: 'PLAYING',
     favorite: 'Rock',
     uri: 'x-rincon-stream:RINCON_0000000000001500',
     playMode: 'SHUFFLE',
     pauseOthers: true } }

**Comment by jishi** [comment]
What do you mean by "just a cursor"?

**Comment by fredgalpern** [comment]
i hit enter after the command, then the gray cursor appears on a new line. there is no return text, which is what i think is expected.

**Comment by fredgalpern** [comment]
sorry, i don't actually hit enter. i'm pasting http://localhost:5005/zones in, immediately after the paste the cursor jumps to a new line.

**Comment by fredgalpern** [comment]
same result typing it in and hitting enter

**Comment by jishi** [comment]
But you are supposed to test that in your browser, not in the terminal...

**Comment by fredgalpern** [comment]
ha! it works. told you i was a noob! thanks a ton!!!

**Comment by jishi** [comment]
No problem, we were all a noob at one time :) Good luck!
