### ISSUE TITLE
Cannot find devices when connected to VPN

### ISSUE THREAD

**Issue by thejase** [jishi/node-sonos-http-api#129]
The machine running this server is usually connected to a VPN for psuedo-privacy.  When not connected to the VPN, it finds the Sonos devices in a few seconds.  However, when connected, this repeats over and over:

```
scanning for players in ip 10.0.1.100
scanning for players in ip 10.4.18.107
```

The first address is the server's local IP.  I'm confused as to why it cannot pick up the broadcast.  If I try to hit that IP from another machine, it does reach it.

Forgive me if this is outside of the scope of this project (it may just be that I don't understand VPNs), but I'm hoping I'm not the first to experience this.

**Comment by jishi** [comment]
There are a few issues when having multiple interfaces, that I have been trying to mitigate. What you could try, is to create a settings.json file (if none exist), and add the following content:

```
{
  "disableIpDiscovery": true
}
```

to see if that helps you. This is more of a temporary fix, and I would like to know the outcome of it for future reference.

**Comment by thejase** [comment]
Thanks so much for a lightning-fast suggestion!  I tried this, and now I just see this looped:

```
scanning for players in dummy
```

I'm reaching out to AirVPN to make sure I've set the right IP range for keeping local traffic outside the tunnel (just in case), but any other temporary suggestions would definitely be welcome.  I'm so close to telling Alexa to "Begin Program!" (A little Star Trek hyperbole never hurt anyone).

Thank you for such an awesome interface!

**Comment by jishi** [comment]
okay, so that didn't solve it, which indicates that you actually do need to use each interface individually to find them. 

Could you give me the IPs and metric from the route-command and mark them which interface is which? Also, if you could verify that you don't activate any iptables rules when you activate the vpn, iptables -L should give you a hint about that.
