### ISSUE TITLE
Just installed fresh update error will not run any one thank you

### ISSUE THREAD

**Issue by robertw** [jishi/node-sonos-http-api#131]
root@raspberrypi:/home/pi/node-sonos-http-api# npm start

> sonos-http-api@0.17.0 start /home/pi/node-sonos-http-api
> node server.js

/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/player.js:259
      .then((highResAlbumArtUrl) => {
                                  ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/sonos.js:11:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! sonos-http-api@0.17.0 start: `node server.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the sonos-http-api@0.17.0 start script.
npm ERR! This is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.1.13+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! cwd /home/pi/node-sonos-http-api
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/node-sonos-http-api/npm-debug.log
npm ERR! not ok code 0

**Comment by jishi** [comment]
You need to use node 4+, you are using 0.10.40 it seems. Install it from
the official download.

**Comment by robertw** [comment]
i will the previous build worked fine just as a fyi no errors will loaad the 4 version thank you.....

**Comment by robertw** [comment]
i reran install and humm do go again


root@raspberrypi:/home/pi/node-sonos-http-api# npm install --production
npm WARN engine require-fu@1.0.0: wanted: {"node":"0.10.x"} (current: {"node":"4                     .0.0","npm":"2.14.2"})
npm WARN peerDependencies The peer dependency continuation-local-storage@~3 incl                     uded from cls-bluebird will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD                     ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it                      explicitly.

**Comment by jishi** [comment]
These are just warnings, it should be okay.
