### ISSUE TITLE
Is it possible to un-group using the API 

### ISSUE THREAD

**Issue by Jvigeant1969** [jishi/node-sonos-http-api#132]
I'm able to create goups on the fly using my echo/alexa and saying  < Play XYZ in the den , the kitchen and the bedroom >  using the Preset/{JSON} aproach... this is working perfectly.... No i'd like to know if there is a way to 'ungroup' this group of speaker using the API .

Is this possible ? 

Cheers
Jacques

**Comment by jishi** [comment]
Yes, there is. It's not documented though, but this gives you an idea on how it works:

https://github.com/jishi/node-sonos-http-api/pull/37

I hope that gives you what you are looking for.

**Comment by Jvigeant1969** [comment]
Thanks a ton.  Works perfectly 
On Jan 17, 2016 5:46 AM, Jimmy Shimizu <notifications@github.com> wrote:Yes, there is. It's not documented though, but this gives you an idea on how it works:

#37

I hope that gives you what you are looking for.
