### ISSUE TITLE
Group and Ungroup - With sonos factory client breaks api

### ISSUE THREAD

**Issue by robertw** [jishi/node-sonos-http-api#133]
Step by step bug

If I call 

   "house": {
      "players": [
        { "roomName": "Office", "volume": 30},
        { "roomName": "Family Room", "volume": 30},
        { "roomName": "Living Room", "volume": 30},
        { "roomName": "Master Bedroom", "volume": 30},
        { "roomName": "Bathroom", "volume": 40},
        { "roomName": "Portable", "volume": 50}
      ],
      "state": "PLAY",
      "favorite": "90s, 2000s, Today's Hits Radio",
      "playMode": "NORMAL",
      "pauseOthers": true
    },
    "party": {
      "players": [
        { "roomName": "Office", "volume": 30},
        { "roomName": "Family Room", "volume": 30},
        { "roomName": "Living Room", "volume": 30},
        { "roomName": "Master Bedroom", "volume": 30},
        { "roomName": "Bathroom", "volume": 40},
	{ "roomName": "Patio", "volume": 40},
        { "roomName": "Portable", "volume": 50}
      ],
      "state": "STOP",
      "favorite": "90s, 2000s, Today's Hits Radio",
      "playMode": "NORMAL",
      "pauseOthers": true

call House then call party then house all is fine but if i unlink group in the factory sonos client winndows to no linked zones then try to run house or party it will link the first 2 zones but stop i can not relink the zones with in your api unless i reboot the node server then it links just fine I hope this helps it happens every time i unlink with the sonos client.....then try to regroup with a preset in the api

**Comment by jishi** [comment]
With link, do you mean pairing (stereo)?

**Comment by robertw** [comment]
No link I meant group sorry group and ungroup it does not matter if the zone is paired or not

**Comment by jishi** [comment]
What kind of setup is the living room?

**Comment by robertw** [comment]
Sonos connect the Bedroom is a sonos amp  the rest are s5 and s1

**Comment by jishi** [comment]
I found the culprit, let me know if it works! Please make sure your node_module gets updated.

**Comment by robertw** [comment]
https://github.com/jishi/node-sonos-discovery/archive/0.16.2.tar.gz not found

**Comment by jishi** [comment]
Ah, sorry, I upped version using npm now, which rendered a tag with name v0.16.2 instead. I fixed the package.json moments ago, please try again.

**Comment by robertw** [comment]
ok loaded fresh install groupin gnot working here is error output on screen


no settings file found, will only use default settings
info: binding SSDP to port 1905
info: discovering all IPs from lo
info: discovering all IPs from eth0
info: relevant IPs 192.168.1.160=null
info: notification server listening on port 3500
http server listening on port 5005
loaded presets { office: { players: [ [Object] ], pauseOthers: true },
  house:
   { players: [ [Object], [Object], [Object], [Object], [Object] ],
     state: 'PLAY',
     favorite: '90s, 2000s, Today\'s Hits Radio',
     playMode: 'NORMAL',
     pauseOthers: true },
  party:
   { players: [ [Object], [Object], [Object], [Object], [Object], [Object]
],
     state: 'STOP',
     favorite: '90s, 2000s, Today\'s Hits Radio',
     playMode: 'NORMAL',
     pauseOthers: true },
  hparty:
   { players:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     state: 'PLAYING',
     favorite: 'Rock',
     playMode: 'NORMAL',
     pauseOthers: true } }
info: scanning for players in ip 192.168.1.160
info: subscribing to topology 192.168.1.112
info: using local endpoint 192.168.1.160
Initializing player Bathroom
Initializing player Portable
Initializing player Isa Room
Initializing player Living Room
Initializing player Office
Initializing player Garage
Initializing player Family Room
Initializing player Master Bedroom
Initializing player Patio
debug: received avtransport
debug: received avtransport
debug: received avtransport x-rincon-queue:RINCON_B8E937BF378001400#0
debug: received avtransport
x-sonosapi-radio:GdZqiWUEuTpuRwU5PNhcahmlSmKW-m1hNz_
             FrsNH4zEY82e3mYYk5Q?sid=151&flags=8300&sn=8
debug: received avtransport
debug: received avtransport
debug: received avtransport
debug: received avtransport
debug: received avtransport
debug: emitting group-volume
info: applying preset players=[roomName=Office, volume=30, roomName=Family
Room,                                     volume=30, roomName=Living Room,
volume=30, roomName=Master Bedroom, volume=30,
        roomName=Bathroom, volume=40], state=PLAY, favorite=90s, 2000s,
Today's Hits Ra                                    dio, playMode=NORMAL,
pauseOthers=true
info: skipping breakout because already coordinator
debug: checking if Family Room needs to be grouped
debug: RINCON_000E5822185201400 RINCON_000E5822152801400
 x-rincon:RINCON_000E58                                    22185201400
debug: adding to group
debug: checking if Living Room needs to be grouped
debug: RINCON_000E5822185201400 RINCON_000E5850693601400
 x-rincon:RINCON_000E58                                    22185201400
debug: adding to group
debug: checking if Master Bedroom needs to be grouped
debug: RINCON_000E5822185201400 RINCON_000E5813DC7201400
 x-rincon:RINCON_000E58                                    22185201400
debug: adding to group
debug: checking if Bathroom needs to be grouped
debug: RINCON_000E5822185201400 RINCON_000E5851BA2A01400
 x-rincon:RINCON_000E58                                    22185201400
debug: adding to group
Expected statusCode 200, but got 500 [ 'pausing Bathroom' ]



what else can i supply you with ? to help wish I knew more .....

Thanks Robert

On Wed, Jan 27, 2016 at 5:32 PM, Jimmy Shimizu <notifications@github.com>
wrote:

> Ah, sorry, I upped version using npm now, which rendered a tag with name
> v0.16.2 instead. I fixed the package.json moments ago, please try again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jishi/node-sonos-http-api/issues/133#issuecomment-175895043>
> .
>



-- 
Regards

Robert

**Comment by jishi** [comment]
Could you elaborate? It doesn't group anything at all anymore? Could you try and simplify the preset and try it out, and add more instructions to see where it breaks? Like, start with only grouping of players, then add volumes, add state, favorites etc and run it each time, to see when it works, and when not.

**Comment by robertw** [comment]
It does not group at all here is a simpler try with vol sane spot it seems
to stop at

bathroom last line: Expected statusCode 200, but got 500 [ 'pausing
Bathroom' ]

i removed bathroom from the preset house and all vol calls and still no
grouping at all


no settings file found, will only use default settings
info: binding SSDP to port 1905
info: discovering all IPs from lo
info: discovering all IPs from eth0
info: relevant IPs 192.168.1.160=null
info: notification server listening on port 3500
http server listening on port 5005
loaded presets { office: { players: [ [Object] ], pauseOthers: true },
  house:
   { players: [ [Object], [Object], [Object], [Object], [Object] ],
     state: 'PLAY',
     favorite: '90s, 2000s, Today\'s Hits Radio',
     playMode: 'NORMAL',
     pauseOthers: true },
  party:
   { players: [ [Object], [Object], [Object], [Object], [Object], [Object]
],
     state: 'STOP',
     favorite: '90s, 2000s, Today\'s Hits Radio',
     playMode: 'NORMAL',
     pauseOthers: true },
  hparty:
   { players:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     state: 'PLAYING',
     favorite: 'Rock',
     playMode: 'NORMAL',
     pauseOthers: true } }
info: scanning for players in ip 192.168.1.160
info: subscribing to topology 192.168.1.99
info: using local endpoint 192.168.1.160
Initializing player Bathroom
Initializing player Patio
Initializing player Isa Room
Initializing player Garage
Initializing player Master Bedroom
Initializing player Office
Initializing player Portable
Initializing player Living Room
Initializing player Family Room
debug: received avtransport pndrradio:2518980799960216585?sn=1
debug: received avtransport x-rincon-queue:RINCON_B8E937BF378001400#0
debug: received avtransport
debug: emitting group-volume
debug: received avtransport
debug: received avtransport
debug: received avtransport pndrradio:2518980799960216585?sn=1
debug: received avtransport
debug: received avtransport
debug: received avtransport
debug: emitting group-volume
debug: emitting group-volume
info: applying preset players=[roomName=Office, roomName=Family Room,
roomName=Living Room, roomName=Master Bedroom, roomName=Patio], state=PLAY,
favorite=90s, 2000s, Today's Hits Radio, playMode=NORMAL, pauseOthers=true
info: skipping breakout because already coordinator
debug: checking if Family Room needs to be grouped
debug: RINCON_000E5822185201400 RINCON_000E5822152801400
 x-rincon:RINCON_000E5822185201400
debug: adding to group
debug: checking if Living Room needs to be grouped
debug: RINCON_000E5822185201400 RINCON_000E5850693601400
 x-rincon:RINCON_000E5822185201400
debug: adding to group
debug: checking if Master Bedroom needs to be grouped
debug: RINCON_000E5822185201400 RINCON_000E5813DC7201400
 x-rincon:RINCON_000E5822185201400
debug: adding to group
debug: checking if Patio needs to be grouped
debug: RINCON_000E5822185201400 RINCON_000E5813DC2801400
 x-rincon:RINCON_000E5822185201400
debug: adding to group
Expected statusCode 200, but got 500 [ 'pausing Bathroom' ]


On Thu, Jan 28, 2016 at 4:31 AM, Jimmy Shimizu <notifications@github.com>
wrote:

> Could you elaborate? It doesn't group anything at all anymore? Could you
> try and simplify the preset and try it out, and add more instructions to
> see where it breaks? Like, start with only grouping of players, then add
> volumes, add state, favorites etc and run it each time, to see when it
> works, and when not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jishi/node-sonos-http-api/issues/133#issuecomment-176081684>
> .
>



-- 
Regards

Robert

**Comment by jishi** [comment]
Okay, but could you try with a preset that doesn't have any options, something like this?

```
{
  "players": [
    {
      "roomName": "Office"
    },
    {
      "roomName": "Family Room"
    },
    {
      "roomName": "Living Room"
    },
    {
      "roomName": "Master Bedroom"
    },
    {
      "roomName": "Bathroom"
    },
    {
      "roomName": "Portable"
    }
  ]
}
```

**Comment by robertw** [comment]
Ok they grouped fine and i can ungroup in client and regroup from api
preset as above

On Thu, Jan 28, 2016 at 8:29 AM, Jimmy Shimizu <notifications@github.com>
wrote:

> Okay, but could you try with a preset that doesn't have any options,
> something like this?
>
> {
>   "players": [
>     {
>       "roomName": "Office"
>     },
>     {
>       "roomName": "Family Room"
>     },
>     {
>       "roomName": "Living Room"
>     },
>     {
>       "roomName": "Master Bedroom"
>     },
>     {
>       "roomName": "Bathroom"
>     },
>     {
>       "roomName": "Portable"
>     }
>   ]
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jishi/node-sonos-http-api/issues/133#issuecomment-176186026>
> .
>



-- 
Regards

Robert

**Comment by jishi** [comment]
Okay, can you now succesively add options like volume, test again?
Then, add favorite, test again. 

And finally, add pauseOthers, and try again (I believe this might be the culprit here).

**Comment by robertw** [comment]
Yes sir added one at a time and the one that causes the coe to halt is
"pauseOthers": true


On Thu, Jan 28, 2016 at 8:44 AM, Jimmy Shimizu <notifications@github.com>
wrote:

> Okay, can you now succesively add options like volume, test again?
> Then, add favorite, test again.
>
> And finally, add pauseOthers, and try again (I believe this might be the
> culprit here).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jishi/node-sonos-http-api/issues/133#issuecomment-176190420>
> .
>



-- 
Regards

Robert

**Comment by robertw** [comment]
another prob when you call preset to change grouping here is error log and
server dies

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart sonos-http-api@0.17.1
6 info start sonos-http-api@0.17.1
7 verbose unsafe-perm in lifecycle true
8 info sonos-http-api@0.17.1 Failed to exec start script
9 verbose stack Error: sonos-http-api@0.17.1 start: `node server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous>
(/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous>
(/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:211:5)
10 verbose pkgid sonos-http-api@0.17.1
11 verbose cwd /home/pi/node-sonos-http-api
12 error Linux 4.1.13+
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.0.0
15 error npm  v2.14.2
16 error code ELIFECYCLE
17 error sonos-http-api@0.17.1 start: `node server.js`
17 error Exit status 1
18 error Failed at the sonos-http-api@0.17.1 start script 'node server.js'.
18 error This is most likely a problem with the sonos-http-api package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server.js
18 error You can get their info via:
18 error     npm owner ls sonos-http-api
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]


On Thu, Jan 28, 2016 at 8:56 AM, Robert Wyman <wymanrobert@gmail.com> wrote:

> Yes sir added one at a time and the one that causes the coe to halt is
> "pauseOthers": true
>
>
> On Thu, Jan 28, 2016 at 8:44 AM, Jimmy Shimizu <notifications@github.com>
> wrote:
>
>> Okay, can you now succesively add options like volume, test again?
>> Then, add favorite, test again.
>>
>> And finally, add pauseOthers, and try again (I believe this might be the
>> culprit here).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jishi/node-sonos-http-api/issues/133#issuecomment-176190420>
>> .
>>
>
>
>
> --
> Regards
>
> Robert
>



-- 
Regards

Robert

**Comment by robertw** [comment]
for got this if it will help


o settings file found, will only use default settings
info: binding SSDP to port 1905
info: discovering all IPs from lo
info: discovering all IPs from eth0
info: relevant IPs 192.168.1.160=null
info: notification server listening on port 3500
http server listening on port 5005
loaded presets { office: { players: [ [Object] ], pauseOthers: true },
  house:
   { players:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     state: 'STOP',
     playMode: 'NORMAL',
     favorite: '90s, 2000s, Today\'s Hits Radio' },
  party:
   { players: [ [Object], [Object], [Object], [Object], [Object], [Object]
],
     state: 'STOP',
     favorite: '90s, 2000s, Today\'s Hits Radio',
     playMode: 'NORMAL' },
  hparty:
   { players:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     state: 'PLAYING',
     favorite: 'Rock',
     playMode: 'NORMAL',
     pauseOthers: true } }
info: scanning for players in ip 192.168.1.160
info: subscribing to topology 192.168.1.113
info: using local endpoint 192.168.1.160
Initializing player Isa Room
Initializing player Garage
Initializing player Bathroom
Initializing player Patio
Initializing player Master Bedroom
Initializing player Portable
Initializing player Office
Initializing player Living Room
Initializing player Family Room
debug: emitting group-volume
debug: received avtransport x-rincon:RINCON_000E5822185201400
debug: received avtransport pndrradio:2518980799960216585?sn=1
debug: received avtransport x-rincon:RINCON_000E5822185201400
debug: emitting group-volume
debug: received avtransport x-rincon-queue:RINCON_B8E937BF378001400#0
debug: received avtransport x-rincon:RINCON_000E5822185201400
debug: received avtransport
debug: received avtransport x-rincon:RINCON_000E5822185201400
debug: received avtransport x-rincon:RINCON_000E5822185201400
debug: received avtransport x-rincon:RINCON_000E5822185201400
info: applying preset players=[roomName=Office, volume=30, roomName=Family
Room, volume=30, roomName=Living Room, volume=30, roomName=Master Bedroom,
volume=30, roomName=Bathroom, volume=40, roomName=Patio, volume=40],
state=STOP, favorite=90s, 2000s, Today's Hits Radio, playMode=NORMAL
info: skipping breakout because already coordinator
/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/sonos.js:618
        this.log.debug('removing', coordinator.roomName, 'should be removed
from group');
            ^

TypeError: Cannot read property 'log' of undefined
    at
/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/sonos.js:618:13
    at Array.forEach (native)
    at Discovery.applyPreset
(/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/sonos.js:615:18)
    at Object.presetsAction [as preset]
(/home/pi/node-sonos-http-api/lib/actions/preset.js:12:22)
    at handleAction
(/home/pi/node-sonos-http-api/lib/sonos-http-api.js:80:28)
    at HttpAPI.requestHandler
(/home/pi/node-sonos-http-api/lib/sonos-http-api.js:62:5)
    at /home/pi/node-sonos-http-api/server.js:51:13
    at Server.finish
(/home/pi/node-sonos-http-api/node_modules/node-static/lib/node-static.js:111:13)
    at finish
(/home/pi/node-sonos-http-api/node_modules/node-static/lib/node-static.js:170:14)
    at
/home/pi/node-sonos-http-api/node_modules/node-static/lib/node-static.js:144:17
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Linux 4.1.13+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@0.17.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sonos-http-api@0.17.1 start script 'node server.js'.
npm ERR! This is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/node-sonos-http-api/npm-debug.log
root@raspberrypi:/home/pi/node-so

On Thu, Jan 28, 2016 at 9:07 AM, Robert Wyman <wymanrobert@gmail.com> wrote:

> another prob when you call preset to change grouping here is error log and
> server dies
>
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
> 2 info using npm@2.14.2
> 3 info using node@v4.0.0
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info prestart sonos-http-api@0.17.1
> 6 info start sonos-http-api@0.17.1
> 7 verbose unsafe-perm in lifecycle true
> 8 info sonos-http-api@0.17.1 Failed to exec start script
> 9 verbose stack Error: sonos-http-api@0.17.1 start: `node server.js`
> 9 verbose stack Exit status 1
> 9 verbose stack     at EventEmitter.<anonymous>
> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
> 9 verbose stack     at emitTwo (events.js:87:13)
> 9 verbose stack     at EventEmitter.emit (events.js:172:7)
> 9 verbose stack     at ChildProcess.<anonymous>
> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
> 9 verbose stack     at emitTwo (events.js:87:13)
> 9 verbose stack     at ChildProcess.emit (events.js:172:7)
> 9 verbose stack     at maybeClose (internal/child_process.js:817:16)
> 9 verbose stack     at Process.ChildProcess._handle.onexit
> (internal/child_process.js:211:5)
> 10 verbose pkgid sonos-http-api@0.17.1
> 11 verbose cwd /home/pi/node-sonos-http-api
> 12 error Linux 4.1.13+
> 13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
> 14 error node v4.0.0
> 15 error npm  v2.14.2
> 16 error code ELIFECYCLE
> 17 error sonos-http-api@0.17.1 start: `node server.js`
> 17 error Exit status 1
> 18 error Failed at the sonos-http-api@0.17.1 start script 'node
> server.js'.
> 18 error This is most likely a problem with the sonos-http-api package,
> 18 error not with npm itself.
> 18 error Tell the author that this fails on your system:
> 18 error     node server.js
> 18 error You can get their info via:
> 18 error     npm owner ls sonos-http-api
> 18 error There is likely additional logging output above.
> 19 verbose exit [ 1, true ]
>
>
> On Thu, Jan 28, 2016 at 8:56 AM, Robert Wyman <wymanrobert@gmail.com>
> wrote:
>
>> Yes sir added one at a time and the one that causes the coe to halt is
>> "pauseOthers": true
>>
>>
>> On Thu, Jan 28, 2016 at 8:44 AM, Jimmy Shimizu <notifications@github.com>
>> wrote:
>>
>>> Okay, can you now succesively add options like volume, test again?
>>> Then, add favorite, test again.
>>>
>>> And finally, add pauseOthers, and try again (I believe this might be the
>>> culprit here).
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/jishi/node-sonos-http-api/issues/133#issuecomment-176190420>
>>> .
>>>
>>
>>
>>
>> --
>> Regards
>>
>> Robert
>>
>
>
>
> --
> Regards
>
> Robert
>



-- 
Regards

Robert

**Comment by jishi** [comment]
Ah, stupid mistake. I will look into this tonight. I\ll keep you posted. Thanks for investigating this!

**Comment by robertw** [comment]
Thank you for taking the time also any thought as to a command to ungroup
all players maybe a preset if the cor is called in a preset with no other
player that group would ungroup just a thought

On Thu, Jan 28, 2016 at 9:40 AM, Jimmy Shimizu <notifications@github.com>
wrote:

> Ah, stupid mistake. I will look into this tonight. I\ll keep you posted.
> Thanks for investigating this!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jishi/node-sonos-http-api/issues/133#issuecomment-176212717>
> .
>



-- 
Regards

Robert

**Comment by jishi** [comment]
Could you explain in what scenario it makes sense to just arbitrary ungroup all players? I don't really see what I personally would use it for.

**Comment by jishi** [comment]
I think I fixed the logging, but I could not reproduce the pauseOther issue. I made it a bit more loose though, so it won't stop if it fails to pause the zones. I'm not sure which state that player was in, but something made it return an error which prevented the preset to move forward.

Try it out and let me know the result, thanks!

**Comment by robertw** [comment]
Seems to be ok   I will bang it around a bit the pauseOthers I believe was that the zone was already paused when it throws the err......Great job thanks so very much!

Other Point

I maybe was not clear not to arbitrary ungroup all players but ungroup a group based on the coordinator this way it is like a reset to that group 

example group bedroom and bathroom and familyroom

group2 livingroom and patio and gargage

if i just wanted to have the bedroom running i run a preset with just bedroom in it thus relaxing the familyroom and bathroom

and not effecting group 2 nor 3 etc

I hope that clear it up a bit....

**Comment by robertw** [comment]
Ok found some thing:

here is preset
 "office": {
      "players": [
        { "roomName": "Office", "volume": 30}
      ],
      "pauseOthers": true
    },
   "house": {
      "players": [
        { "roomName": "Office", "volume": 30},
        { "roomName": "Family Room", "volume": 30},
        { "roomName": "Living Room", "volume": 30},
        { "roomName": "Master Bedroom", "volume": 30},
        { "roomName": "Bathroom", "volume": 40},
        { "roomName": "Portable", "volume": 40},
	{ "roomName": "Patio", "volume": 40}
      ],
      "state": "STOP",
      "playMode": "NORMAL",
      "favorite": "90s, 2000s, Today's Hits Radio"
    },
    "party": {
      "players": [
        { "roomName": "Office", "volume": 30},
        { "roomName": "Family Room", "volume": 30},
        { "roomName": "Living Room", "volume": 30},
        { "roomName": "Master Bedroom", "volume": 30},
        { "roomName": "Bathroom", "volume": 40},
	{ "roomName": "Patio", "volume": 40}
      ],
      "state": "STOP",
      "favorite": "90s, 2000s, Today's Hits Radio",
      "playMode": "NORMAL",
      "pauseOthers": true
     },

If i run house then party then house all is fine if i run office then back to house office does not reconnect to the house group.....

It does detach from the house group and plays but will not reconnect and other presets fail to work after that have to restart.

**Comment by jishi** [comment]
About the grouping idea, could you file a new issue where you give a detailed explanation of the state that you start from, and the state that you would like to end up with? Sounds a bit like you want to "detach" bedroom and keep playing on only bedroom player, correct? 

Regarding the remaining issue of the preset errors. When you have invoked the Office preset, where only office is playing, all the other presets fails? Completely, or does it work halfway through? Please post a clean log with the minimal steps you need to take in order to trigger this error, it might give me some idea.

**Comment by robertw** [comment]
Ok I will post it after I think in detail to make it simple:

Ok I invoked house worked fine then office worked fine then tried to run house again and fail office still playing not grouped ( could it be that zone Office is the coordinator of the group house and fails because it is playing just my 2 cents)

2185201400 x-rincon:RINCON_000E5822185201400
debug: checking if Living Room needs to be grouped
debug: RINCON_000E5822185201400 RINCON_000E5850693601400 x-rincon:RINCON_000E5822185201400 x-rincon:RINCON_000E5822185201400
debug: checking if Master Bedroom needs to be grouped
debug: RINCON_000E5822185201400 RINCON_000E5813DC7201400 x-rincon:RINCON_000E5822185201400 x-rincon:RINCON_000E5822185201400
debug: checking if Bathroom needs to be grouped
debug: RINCON_000E5822185201400 RINCON_000E5851BA2A01400 x-rincon:RINCON_000E5822185201400 x-rincon:RINCON_000E5822185201400
debug: checking if Portable needs to be grouped
debug: RINCON_000E5822185201400 RINCON_B8E937BF3D7801400 x-rincon:RINCON_000E5822185201400 x-rincon:RINCON_000E5822185201400
debug: checking if Patio needs to be grouped
debug: RINCON_000E5822185201400 RINCON_000E5813DC2801400 pndrradio:2518980799960216585?sn=1 x-rincon:RINCON_000E5822185201400
debug: adding to group
info: found it title=90s, 2000s, Today's Hits Radio, uri=pndrradio:2518980799960216585?sn=1, albumArtURI=http://mediaserver-cont-dc6-1-v4v6.pandora.com/images/public/rovi/albumart/6/2/8/5/093624705826_500W_500H.jpg, metaData=<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="OXOX2518980799960216585" parentID="0" restricted="true"><dc:title>90s, 2000s, Today&apos;s Hits Radio</dc:title><upnp:class>object.item.audioItem.audioBroadcast</upnp:class><desc id="cdudn" nameSpace="urn:schemas-rinconnetworks-com:metadata-1-0/">SA_RINCON3_me@t-pak.com</desc></item></DIDL-Lite>
Expected statusCode 200, but got 500 [ 'set volume, coordinator', 'applying favorite' ]
debug: emitting group-volume

**Comment by robertw** [comment]
Just thinking this is kinda what I am talking about I wanted the office to keep playing and the rest of the group to ungroup so when i call house again it will regroup as per the preset and keep playing Does that make sense to you?

**Comment by robertw** [comment]
I hope maybe this help after playing around for a few hours it is clear that the way the coordinator is invoked is one of the problems if I do not remove the coordinator from the group i can add or remove zones but if i move the coordinator out of the group and then try to add it back it fails and does not allow me to group anything through the api i can group fine in the client but the api does not function as per grouping I hope this helps a little regards Robert

**Comment by jishi** [comment]
I've looked into this and found something that I have missed to implement. I'm doing a major rewrite of the underlying library, and it doesn't make sense to try and fix this in the current version since it will be addressed by the rewrite. I can't say when it will be finished, but I have been working hard the last week and done real good progress. You'll have to be patient.

**Comment by robertw** [comment]
I am more than greatfull and thank you for all your efforts .......
