### ISSUE TITLE
Ability to list sonos favorites

### ISSUE THREAD

**Issue by Connor-Knabe** [jishi/node-sonos-http-api#134]
Would it be possible to implement a route when hitting localhost:5005/living room/favorites to display JSON that contains the names of all of the favorites from sonos?  

The same could be said about playlists.

**Comment by jishi** [comment]
This already exist:

http://localhost:5005/favorites

There is none for playlists however, I had a discussion about this with someone else, but can't find it now. It just wasn't implemented in the contributed code that I got, that's why it's missing.

**Comment by Connor-Knabe** [comment]
O awesome I didn't know that. Thanks!!
