### ISSUE TITLE
Feature Request: sayall custom mp3

### ISSUE THREAD

**Issue by lukehoverman** [jishi/node-sonos-http-api#136]
The sayall command generally works great for me but I would love the option to use a custom audio file instead of TTS. Would this be currently possible?

Thank you for your work on this, I use it every day!

**Comment by jishi** [comment]
Hi, and thank you.

Right now it isn't currently supported. It wouldn't be a big thing to add, but right now I'm doing a major refactoring of the underlying library, hopefully it will be easier to fix all outstanding issues once that is done. 

Just for reference, are you planning on hosting these mp3-files on a separate webserver, or do you want to put it in the filesystem where you run the sonos-http-api from?

**Comment by lukehoverman** [comment]
Thanks for the response! For me, personally, either file location would work although I suppose hosting them locally would be much faster. Thanks again!

**Comment by danvwgit** [comment]
I agrree I would like to play a custom Mp3 for a doorring with the sayall command.

**Comment by dolphinkite** [comment]
Alternatively, if this makes it easier, the custom mp3 could be stored in my Sonos favorites. It could also be stored in the /tts folder, as are the downloaded mp3 files from tts. 

I look forward to testing this.

**Comment by nibi79** [comment]
hi, it would be so great to have such an enhancement for my smarthome. I also looking for a **smart** possibility to integrate a doorbell. My proposal is to store these mp3 files in a seperate folder like /mp3 beside the /tts folder.  
Thank you for your great job

**Comment by VisioLogic** [comment]
Thank you for this great project!!! 
I also need a doorbell mp3 that interrupt current play (like sayall). But no text, rather a mp3 file. Is this possible? If you realize this function, i will spend you 20$.

**Comment by Ptrvh** [comment]
I'm a big fan of this project. I'm using it in my home automation project. I am dying for a doorbell mp3. This would be a great feature. A friend of mine has a very expensive home automation system which does the job and it would be great if I can do the same with my 40 euro RPI!

**Comment by jishi** [comment]
I got some feeling tonight, and managed to whip together audio clip announcement for a single player. Should be fairly trivial to fix it for whole system as well, stay tuned!

**Comment by GregRocket** [comment]
@Ptrvh What hardware are planning on using for the doorbell. How would you send the doorbell press to the node-sonos-http-api?

**Comment by jishi** [comment]
Now part of the api since commit https://github.com/jishi/node-sonos-http-api/commit/ef5fe8ca757f00a655c6ff3aa5e6d583f16f36c2

**Comment by Ptrvh** [comment]
Great!! Will check it out tomorrow!
@GregRocket I'm using a RPI 2 with Pimatic for my homedomotica. I have a RF433 MHz sender / receiver. I have a klikaanklikuit (433 MHz) doorbell which is linked to my original doorbell (via a relais). When somebody rings the bell the original doorbell rings and the 433MHz doorbell sends a signal to the RPI.

**Comment by Ptrvh** [comment]
Works perfect!!! Tnx you. Finally a real doorbell via my Sonos system.
