### ISSUE TITLE
node server.js fails

### ISSUE THREAD

**Issue by jaimerosales** [jishi/node-sonos-http-api#139]
Hi,

I'm trying to check out this repo, but I get a fail when running npm start command. I'm including the npm-debug.log file as well. 

Is there something I'm missing ? The npm install --production went ok and also found that npm install sonos will work, but maybe it is an older version. 

Thanks for your quick response just curious to try this with my Sonos :)

Cheers,
Jaime

[npm-debug log text.txt](https://github.com/jishi/node-sonos-http-api/files/108734/npm-debug.log.text.txt)

**Comment by jishi** [comment]
You are running an old version of node.js, 0.12.7. You need to upgrade to 4.0.0 or higher.

**Comment by jaimerosales** [comment]
Aha, ok thank Jimmy for the quick response. Will try it now. 

Cheers,
Jaime
