### ISSUE TITLE
Playlist is not start playing

### ISSUE THREAD

**Issue by noesberger** [jishi/node-sonos-http-api#147]
Hi

the command /playlist/<name> is replacing the queue successfully, but doesn't start playing. The Sonos player stays on pause.
In the log I see that it's replacing the queue but no start command is send:
found playlist Kinder_traditionell file:///jffs/settings/savedqueues.rsq#7
debug: received avtransport x-rincon-queue:RINCON_B8E937B74F7E01400#0

Does anybode else have the same problem since the last update?
(since the last update the tts is working fine, also resuming the spotfiy tracks is working perfect)

**Comment by noesberger** [comment]
It looks like, the success is not comming back correct. Because when I'm trying an else statement, it's going into the else and there I started the play command as well (for testing only)

if (success) {
            console.log("replaced queue with playlist "+ item.title + ".");
            player.coordinator.play();
          } else {
            console.log("ELSE selfmade, try playing");
            player.coordinator.play();
          }

**Comment by jishi** [comment]
Hi, yeah I forgot that I got a pull request to the discovery-library which changed the callback signature. I have fixed the actions that I believe has been affected in 0.18.1, please update and see if it works now. 

Thanks for pointing it out!
