### ISSUE TITLE
say command seems not to work with Sonos Connect

### ISSUE THREAD

**Issue by tomkxy** [jishi/node-sonos-http-api#150]
I just installed node-sones-http-api on my Raspberry. Issuing the say command against my Play:1 and my Connect:AMP work as expected. However, if I am issuing the same request against my Connect it just starts to play the queue. Are there any limitations with respect to the Sonos components supported?

**Comment by jishi** [comment]
Are you using fixed volume on your connect?

**Comment by tomkxy** [comment]
Yes, I have fixed volume.

**Comment by jishi** [comment]
That explains it. I'll see what I can do about it.

**Comment by tomkxy** [comment]
Would be great, if you could do something since I need to keep it at fixed volume.

**Comment by tomkxy** [comment]
When I uncomment the volume in the assignment in say.js
 
```
var ttsPreset = {
    "players": [
      { "roomName": player.roomName, "volume": announceVolume }
    ],
    "state": "playing",
    "playMode": "NORMAL"
  }
```

it works. 

May be it is a possibility to check for fixed volume in  applyPreset or even temporary remove the fixed volume?

**Comment by jishi** [comment]
I think I track if the device has fixed volume configured or not, preferably the setVolume method should just ignore if that is on. I haven't had time to look into it, but I have a general idea on how to solve it. If you want to take a stab at it in sonos-discovery and send a pull request, I'll happily merge it.

**Comment by tomkxy** [comment]
I sent a pull request. I made the change to the file installed by node-sonos-http-api. The GIT repos Sonos-discovery and the install seem not to be fully in sync.

**Comment by tomkxy** [comment]
Did a quick test and it seems to work. Thanks!
