### ISSUE TITLE
Fails to start playing with Favorites

### ISSUE THREAD

**Issue by 2MuchTech** [jishi/node-sonos-http-api#151]
I thought this used to work, but with the current code I'm seeing an issue when I try to play a Favorite.  The favorite item will load, but playback remains paused.  Looking at the function favorite(player, values) in favorite.js, it appears that the call to player.coordinator.replaceWithFavorite expects an "error" return value, but the replaceWithFavorite function in players.js thinks it's returning a "success" value.  So essentially the calling function is inverting the check for success/failure.  Changing the favorite function to the following seems to correct the problem:

```javascript
function favorite(player, values) {
  player.coordinator.replaceWithFavorite(values[0], function (success) {
    if (success)
      player.coordinator.play();

  });
}
```

**Comment by jishi** [comment]
Sounds like you are using an old version of sonos-discovery. This behavior was switched for consistency (returning error, result insteaf of success, result) and I changed the http-api to conform to this.

Try running `npm install` again and see if the error goes away.

**Comment by 2MuchTech** [comment]
Well, for some reason `npm install` isn't updating my sonos-discovery files, but after I manually updated them from a downloaded zip file everything is working now.

I'm new to npm (and JS in general), but if I run `npm install` from the directory that contains the node-sonos-htpp-api project, shouldn't it download ALL updated versions of every dependency?  I even tried `npm install` from within the sonos-discovery directory and that didn't update the files either.  I did notice a warning about sones-discovery not being in the npm registry, in case that matters.

**Comment by jishi** [comment]
Hi, npm install should update dependencies if the versions specified in package.json doesn't matched the ones currently installed. It has been my understanding that when the url for the tarball changes, it also forcefully updates the dependency.

It doesn't version upgrade dependencies to the "latest" version, however, `npm install -f` will reinstall everything, and `npm update` will try to install the latest, allowed version of a package. However, `npm update` does seem to have some issue with tarball dependencies, but don't recall exactly what it was right now.
