### ISSUE TITLE
Fresh install

### ISSUE THREAD

**Issue by hmatos-rogers** [jishi/node-sonos-http-api#152]
I'm trying to install with your instructions -- currently have other node.js servers running on this ubuntu box-- get the following:

hmatos@homebridge:~/node-sonos-http-api-a03e134c8756c12256ba89aa8d1c3c7ede4de3e2$ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.9
3 info using node@v0.12.8
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart sonos-http-api@0.18.1
6 info start sonos-http-api@0.18.1
7 verbose unsafe-perm in lifecycle true
8 info sonos-http-api@0.18.1 Failed to exec start script
9 verbose stack Error: sonos-http-api@0.18.1 start: `node server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1016:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1088:5)
10 verbose pkgid sonos-http-api@0.18.1
11 verbose cwd /home/hmatos/node-sonos-http-api-a03e134c8756c12256ba89aa8d1c3c7ede4de3e2
12 error Linux 4.2.0-16-generic
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v0.12.8
15 error npm  v2.14.9
16 error code ELIFECYCLE
17 error sonos-http-api@0.18.1 start: `node server.js`
17 error Exit status 1
18 error Failed at the sonos-http-api@0.18.1 start script 'node server.js'.
18 error This is most likely a problem with the sonos-http-api package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server.js
18 error You can get their info via:
18 error     npm owner ls sonos-http-api
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
hmatos@homebridge:~/node-sonos-http-api-a03e134c8756c12256ba89aa8d1c3c7ede4de3e2$ 

Thanks,

**Comment by jishi** [comment]
You are running node 0.12 which is unsupported, my app requires 4.0.0 or higher. If you don't want to upgrade globally, it is possible to just add a node binary in any other folder and use that when starting node. 

However, I advice you to test if your other stuff works with node 4 or 5 since 0.12 has been deprecated and is unsupported. I see lower memory footprint in node 4 vs 0.12 too.

**Comment by cricenog** [comment]
Hey jishi, I pulled the new code today and when trying to run I receive pretty much the same error, although I do have 4.0.0 or higher of node, and the files I pulled previously seem to run fine, any ideas? Thank you!

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.12
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart sonos-http-api@0.18.1
6 info start sonos-http-api@0.18.1
7 verbose unsafe-perm in lifecycle true
8 info sonos-http-api@0.18.1 Failed to exec start script
9 verbose stack Error: sonos-http-api@0.18.1 start: `node server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid sonos-http-api@0.18.1
11 verbose cwd /home/pi/node-sonos-http-api-master-2-19/node-sonos-http-api-master-2-19
12 error Linux 4.1.13+
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.2.6
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error sonos-http-api@0.18.1 start: `node server.js`
17 error Exit status 1
18 error Failed at the sonos-http-api@0.18.1 start script 'node server.js'.
18 error This is most likely a problem with the sonos-http-api package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server.js
18 error You can get their info via:
18 error     npm owner ls sonos-http-api
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by cricenog** [comment]
For reference, on the install that does work:
root@raspberrypi:/home/pi/node-sonos-http-api-master/node-sonos-http-api# npm start

> sonos-http-api@0.17.1 start /home/pi/node-sonos-http-api-master/node-sonos-http-api
> node server.js

no settings file found, will only use default settings
info: binding SSDP to port 1905
info: discovering all IPs from lo
info: discovering all IPs from eth0
info: relevant IPs 192.168.1.41=null
{ [Error: Cannot find module './settings.json'] code: 'MODULE_NOT_FOUND' }
info: notification server listening on port 3500
http server listening on port 5005

Are the two installations causing issues? Thank you!!

**Comment by jishi** [comment]
I assume that you aren't running the two at the same time, then it shouldn't be a problem. It's a very weird error, and I can't not identify the cause of it from that stack trace.

What is the error you receive if you start it using:

`node server.js`

is it different? What are you running this on, a rpi or x86/x64 linux?

**Comment by cricenog** [comment]
Thanks for such a quick reply, here's what happens when I try start with node server.js, I am running on a rasberry pi, I do a clean reboot between server instances. 

root@raspberrypi:/home/pi/node-sonos-http-api-master-2-19/node-sonos-http-api-master-2-19# node server.js
no settings file found, will only use default settings
info: binding SSDP to port 1905
info: discovering all IPs from lo
info: discovering all IPs from eth0
info: relevant IPs 192.168.1.41=null
/home/pi/node-sonos-http-api-master-2-19/node-sonos-http-api-master-2-19/lib/actions/._clearqueue.js:1
(function (exports, require, module, __filename, __dirname) { 
                                                              

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at requirePath (/home/pi/node-sonos-http-api-master-2-19/node-sonos-http-api-master-2-19/node_modules/require-fu/lib/index.js:14:22)
    at /home/pi/node-sonos-http-api-master-2-19/node-sonos-http-api-master-2-19/node_modules/require-fu/lib/index.js:21:9
    at Array.forEach (native)
    at fuDirectory (/home/pi/node-sonos-http-api-master-2-19/node-sonos-http-api-master-2-19/node_modules/require-fu/lib/index.js:20:34)
    at /home/pi/node-sonos-http-api-master-2-19/node-sonos-http-api-master-2-19/node_modules/require-fu/lib/index.js:25:5
    at new HttpAPI (/home/pi/node-sonos-http-api-master-2-19/node-sonos-http-api-master-2-19/lib/sonos-http-api.js:36:24)
    at Object.<anonymous> (/home/pi/node-sonos-http-api-master-2-19/node-sonos-http-api-master-2-19/server.js:43:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
root@raspberrypi:/home/pi/node-sonos-http-api-master-2-19/node-sonos-http-api-master-2-19#

**Comment by jishi** [comment]
Aha, looks like you have gotten some OS X meta files in some of the directories. Please see if you have any dot-files within the /home/pi/node-sonos-http-api-master-2-19/node-sonos-http-api-master-2-19/lib/actions/ folder, looks like you atleast got a ._clearqueue.js file in there, maybe more. 

use `ls -a` to show hidden files (prefixed with dot) otherwise they wont show.

**Comment by cricenog** [comment]
Yep you got it!! Not sure how that happened?! I assume I need to delete them?  Thank you!!!!

..		  mute.js	     preset.js		     sleep.js
._clearqueue.js   ._nextprevious.js  ._queue.js		     ._spotify.js
clearqueue.js	  nextprevious.js    queue.js		     spotify.js
._favorite.js	  ._pauseall.js      ._reindex.js	     ._state.js
favorite.js	  pauseall.js	     reindex.js		     state.js
._favorites.js	  ._playlist.js      ._say.js		     ._volume.js
favorites.js	  playlist.js	     say.js		     volume.js
._group.js	  ._playmode.js      ._seek.js		     ._zones.js
group.js	  playmode.js	     seek.js		     zones.js
._lockvolumes.js  ._playpause.js     ._setavtransporturi.js
lockvolumes.js	  playpause.js	     setavtransporturi.js

**Comment by jishi** [comment]
I think these pop up when you first keep the files on an OS X machine, then copy it to another system. I could be wrong though.

**Comment by cricenog** [comment]
Working like a charm now, thanks again, I can't emphasize how awesome this is!!!

**Comment by vmsman** [comment]
My install appeared to go well but after starting the server, I can't seem to connect to it.
# npm start                                                                                                                                                     
npm info it worked if it ends with ok                                                                                                                           
npm info using npm@3.10.9                                                                                                                                       
npm info using node@v6.9.2                                                                                                                                      
npm info lifecycle sonos-http-api@1.2.5~prestart: sonos-http-api@1.2.5                                                                                          
npm info lifecycle sonos-http-api@1.2.5~start: sonos-http-api@1.2.5                                                                                             
                                                                                                                                                                
> sonos-http-api@1.2.5 start /node_modules/sonos-http-api                                                                                                       
> node server.js                                                                                                                                                
                                                                                                                                                                
2016-12-08T19:35:21.357Z INFO no settings file found, will only use default settings                                                                            
2016-12-08T19:35:22.658Z INFO Presets loaded: {}                                                                                                                
2016-12-08T19:35:23.440Z INFO http server listening on port 5005  

Any suggestions?

**Comment by jishi** [comment]
What are you running it on for system? My best guess is some firewall
software, but then localhost requests should work.

**Comment by vmsman** [comment]
I am running it on a QNAP server.

**Comment by jishi** [comment]
@vmsman It's hard to answer without more context. I also suggest opening a new issue to avoid notifying the other participant in this thread.

**Comment by vmsman** [comment]
I discovered that the Docker container instance was running inside a NAT 
that had no visibility to the main network.  By default, Docker 
containers on Synology and QNAP NAS run on their own 10.0.x.y NAT and so 
the node-sonos-http-api instance has no visibility to find SONOS on the 
home network.  My fix was to create the container in "HOST" network 
mode.  Since the API uses port 5005 and that is not used by anything 
else on the NAS, that is an acceptable solution.  Interesting problem 
now that container virtualization is more common.

**Comment by jishi** [comment]
If you would have mentioned Docker to start with, I would have known that answer instantly ;) https://github.com/jishi/node-sonos-http-api/issues/80

But glad you managed to get it to work!
