### ISSUE TITLE
applyPreset not setting "mute" flag

### ISSUE THREAD

**Issue by 2MuchTech** [jishi/node-sonos-http-api#153]
I'm trying to set `mute: false` in the preset.js file, but from what I can tell the applyPreset function in sonos.js doesn't check for this flag, so it has no effect.  I'd like to have this capability because I'm working on getting rgraciano's echo-sonos to work, and feedback from the Echo device is fairly limited (due mostly to not pushing a status back to it, so this could be fixed I suppose), and when Echo just says "OK" and nothing seems to happen on the Sonos system, it can be hard to determine what Echo told Sonos to do.  If a speaker or group is muted when Echo tells Sonos to apply a Preset, it won't be obvious to the user that they need to then tell Echo to unmute the speaker.

**Comment by jishi** [comment]
Well, mute has never been supported in the preset.js file. It might make sense to always unmute if you have a player volume defined, meaning that there would be no explicit flag for it. I'll think about it for a while and see what makes most sense.

**Comment by jishi** [comment]
I'm trying to figure out what the exact use case was for this. Basically, you want it to unmute players when applying a preset, correct? Not actually mute any players?

**Comment by 2MuchTech** [comment]
Jimmy,

It’s been awhile, but yes, I believe I only wanted an UnMute.  I think the issue I was running into was the unexpected lack of music playing after a preset was selected, due to the selected player(s) being in the Mute state when the preset was activated.

— Wendell Morris

**Comment by teadawg** [comment]
If I apply a preset and set a volume for a player, I think the Player should be unmuted. Otherwise I have to unmute all players in the group to make sure they are playing

**Comment by jishi** [comment]
The style of the preset is that non-existing properties are left as is:

If no volume is specified for a player, it would maintain it's current volume. 
If no playmode is specified, it would maintain the current playmode 
etc...

I would then suggest we do the same with mute. Meaning, supporting adding a `mute` property to every player, to explicitly state the mute mode when applying a preset. This way, both expecations can be met. 

Sounds good?

**Comment by jishi** [comment]
I finally got around to fixing this. You specify mute at the same level as volume, per player. Takes true/false value. Example:

```
{
  players: [{ roomName: 'Kitchen', volume: 1 }, { roomName: 'Other room', volume: 2 }, {
    roomName: 'Office',
    volume: 3,
    mute: true
  }]
}
```
