### ISSUE TITLE
TTS not playing

### ISSUE THREAD

**Issue by mckinneypl** [jishi/node-sonos-http-api#154]
Installed on virtual machine ubuntu 15.10 server and everything else appears to work except for TTS. I have  voiceRSS key and I created the settings.json file. Below is the output message. It stop the sonos but does not play the text message. 

Using cached tts message file: 2c6f9f252c549b31a21071df86df2fc4d1323999-en.mp3
info: applying preset players=[roomName=Percy's Office, volume=40], state=playing, playMode=NORMAL, uri=http://192.168.1.199:5005/tts/2c6f9f252c549b31a21071df86df2fc4d1323999-en.mp3
debug: ungrouping Percy's Office to prepare for grouping
debug: received avtransport http://192.168.1.199:5005/tts/2c6f9f252c549b31a21071df86df2fc4d1323999-en.mp3
STOPPED http://192.168.1.199:5005/tts/2c6f9f252c549b31a21071df86df2fc4d1323999-en.mp3
debug: received avtransport http://192.168.1.199:5005/tts/2c6f9f252c549b31a21071df86df2fc4d1323999-en.mp3
STOPPED http://192.168.1.199:5005/tts/2c6f9f252c549b31a21071df86df2fc4d1323999-en.mp3
debug: emitting group-volume

**Comment by jishi** [comment]
Are you using say or sayall? And do the mp3-file that gets cached in the static/tts folder actually get a size/is playable manually?

**Comment by mckinneypl** [comment]
I used say. I verified the mp3 files are in the static/tts folder but I will check tonight to see if they are playable. 
Thanks for the quick response. You've done  great work and I appreciate your efforts.

**Comment by Snowfire01** [comment]
Hello

I have the same problem. I checked the generated mp3 files and they're not playable with any media player (Also the size is only 36 bytes)
Is this a known problem?

**Comment by jishi** [comment]
Try open the files in a text editor. I guess they contain some sort of
error message.

**Comment by Snowfire01** [comment]
Yes indeed, it says the API key is not available. Could this be caused by using the free Version of VoiceRSS with only plain text input and a maximum size of 100 kB per request?

**Comment by jishi** [comment]
Could very well be. I have never hit the limit so I'm not sure what error
you receive

**Comment by Snowfire01** [comment]
So you also use the free version and it already worked for you?
I only used http://[IP-Address]:5005/[Sonos]/say/Hello and got the error. So if you've ever sent longer messages than that using the free version and it worked, I guess the problem is a different one. The error message in the mp3 file says the API key is not available. 

And by the way, thank you very much for your help and your fast replies. I really appreciate that :)

**Comment by jishi** [comment]
Yeah, I've only tested the free version. Are you 100% sure that you've entered the correct key? It will give you a warning if you haven't entered a key at all, but if you enter the wrong key, it will just error out on the voicerss end.

**Comment by Snowfire01** [comment]
Yes I am 100% sure. Is my settings.json maybe wrong?
At the moment it ONLY contains

{
    "voicerss": "[API Key]"
}

**Comment by mckinneypl** [comment]
Found my error - pilot error. Opened the mp3 file in  nano and it said Error:language not supported
Added /en-au after my text and it's working.  Thanks 

ip address/room/text to speak/en-au

**Comment by mckinneypl** [comment]
Should has said en-us for us speech.

**Comment by jishi** [comment]
Good catch, forgot to fix the default language code to the new voicerss language codes. 

@Snowfire01 Are you still having issues? That settings.json looks correct to me, have you tested to invoke it directly?

like this:

`http://api.voicerss.org/?key=[API key]&f=22khz_16bit_mono&hl=en-gb&src=This%20is%20a%20test`
