### ISSUE TITLE
Missing your presets.json file

### ISSUE THREAD

**Issue by TheHavocHero** [jishi/node-sonos-http-api#156]
Can you post your example presets.json file? I created one, but cannot figure out how to reference All as a preset name. Would like to see the example you mention, but there is no file in the package. 

Also, you reference the file preset.json in the Readme, but it should be presets.json.

**Comment by NovaGL** [comment]
You are correct it is a typo in the readme, here is an example for you
```xml
{
	"TV": {
		"players": [
			{"roomName": "Bedroom"}			
		],
		"uri": "x-sonos-htastream:spdif"
	}
}
```

**Comment by jishi** [comment]
I've added the example directly in the README, thanks for pointing that out. The name is the "key" in the object literal. Basically, the format is this:

```
{  
  all: { ... This is the data of the "all" preset } ,
  anotherPreset: { ... data for another preset }
}
```

Does this make sense? If you are familiar with terminology like hashtable, dictionary, associative array and similar.

**Comment by TheHavocHero** [comment]
Thanks @jishi. I got my presets file working. Now, if I could just get a Pandora favorite to work in the preset. Is that possible if I am trying to play one of my Pandora Favorites from a uri? I have not tried it yet.

**Comment by jishi** [comment]
@TheHavocHero I believe pandora stations as favorite works. I don't think it works as a uri, since it relies on a specific type of metadata which would reference your pandora account. TuneIn station do work, I think.

I will look into the metadata support for the preset somewhere in the future.
