### ISSUE TITLE
Can't find my players

### ISSUE THREAD

**Issue by 88fingerslukee** [jishi/node-sonos-http-api#157]
I get the "No system has yet been discovered. Please see https://github.com/jishi/node-sonos-http-api/issues/77 if it doesn't resolve itself in a few seconds." error

How do I fix this?

**Comment by jishi** [comment]
Tell me what kind of platform you are running it on (linux, osx, windows), and how that device is connected to your home network. 

You could also try and create the file settings.json, with the following content:

```
{
  "disableIpDiscovery": true
}
```

Put it in the same folder as server.js, and see if that helps.

**Comment by 88fingerslukee** [comment]
Fedora 22.  There are 5 different devices in the house.  A Playbar, a Sub, two Play:1's as surrounds and an old-school Connect:Amp.  The Amp is wired and the 5.1 system is wireless.  It can't find any of them.

I tried disableIpDiscovery and it just changed the STDOUT messages from "info: scanning for players in ip 10.0.0.3" to "info: scanning for players in ip dummy"

What ports need to be opened on the server?

**Comment by jishi** [comment]
It requires tcp 3500 inbound and udp 1905 inbound.

Outbound is tcp 1400, udp 1900 as well as multicast with destination
239.255.255.250 (ssdp).

If you have iptables active, they are probably the cause of it.

**Comment by 88fingerslukee** [comment]
That worked, thanks.

May I suggest putting that information in the instructions? It seems like a key component, no?

**Comment by jishi** [comment]
Good point, but you are actually the first one to have this problem. Seems like most people run them from linux systems that doesn't have iptables configured, and for windows/os x you primarily allow based on application rather than ports.
