### ISSUE TITLE
Pandora favorites don't play if they were already loaded and paused

### ISSUE THREAD

**Issue by tlc** [jishi/node-sonos-http-api#159]
An inconsistency between Pandora favorites and other favorites.
Playlist and "Radio by TuneIn" favorites play after this sequence.
Pandora favorites don't.

```
http://localhost:5005/kitchen/favorite/Ska
http://localhost:5005/kitchen/pause
http://localhost:5005/kitchen/favorite/Ska
```

**Comment by jishi** [comment]
Okay, that's weird. Do you get any relevant log output after the second favorite call?

**Comment by tlc** [comment]
Looks the same to me.  Here is the log from the sequence.

```
info: found it title=Ska Radio, uri=pndrradio:number_redacted?sn=1, albumArtURI=http://cont-sv5-2.pandora.com/images/public/rovi/albumart/8/2/3/1/601215301328_500W_500H.jpg, metaData=<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="OXOXnumber_redacted" parentID="0" restricted="true"><dc:title>Ska Radio</dc:title><upnp:class>object.item.audioItem.audioBroadcast</upnp:class><desc id="cdudn" nameSpace="urn:schemas-rinconnetworks-com:metadata-1-0/">SA_RINCON3_email_redacted</desc></item></DIDL-Lite>
debug: received avtransport pndrradio:number_redacted?sn=1
info: found it title=Ska Radio, uri=pndrradio:number_redacted?sn=1, albumArtURI=http://cont-sv5-2.pandora.com/images/public/rovi/albumart/8/2/3/1/601215301328_500W_500H.jpg, metaData=<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="OXOXnumber_redacted" parentID="0" restricted="true"><dc:title>Ska Radio</dc:title><upnp:class>object.item.audioItem.audioBroadcast</upnp:class><desc id="cdudn" nameSpace="urn:schemas-rinconnetworks-com:metadata-1-0/">SA_RINCON3_email_redacted</desc></item></DIDL-Lite>
```

Actually, I guess node-sonos-http-api's behavior is consistent with the phone app.  If I'm playing a favorite Pandora station, pause it, and instead of hitting play try to load it from favorites again, I get a dialog:

```
Unable to play the Pandora Radio station -- this station is already playing.
```

You might consider whether node-sonos-http-api would be more consistent with itself to add a /play call there.  I've already done that for my calling app.

**Comment by jishi** [comment]
I don't try to follow behaviors from the official controller, I try to be consistent throughout the API and be simple to use. This sounds more like an underlying bug, where the call to setting a pandora station fails, if it already has that station loaded. Because it fails, the subsequent play will never be invoked. 

If course, if I can mitigate that issue somehow, then I will try and fix it. And I understand it correctly, that this only affect pandora, not other radio-features from other music services?

**Comment by nchezrony** [comment]
I just found that if I send a request to play Pandora, then a second command to "play", this will work regardless of what source you started with (Pandora or other).

**Comment by tlc** [comment]
I've only tested Pandora, TuneIn and Playlist favorites.  Of those, I only saw it on Pandora.  I can try Amazon later.  That's the only other service I use.

**Comment by jishi** [comment]
Has anyone filed an issue with Sonos about this? If they have acknowledged it, maybe I wouldn't have to make a workaround for pandora.

**Comment by tlc** [comment]
I doubt Sonos will care.  Because when it happens on their UI, the play button is right in front of you.  And they may have paid Pandora to write the app.

BTW, on their UI, it happens whether you're using Pandora from the Favorites menu or from the Pandora Radio menu.

I tested Amazon Prime and Amazon (My Owned) Music as Favorites.  Neither one had the issue on your API or the official UI.

**Comment by jishi** [comment]
Is this still an issue?

**Comment by jishi** [comment]
wontfix

**Comment by jishi** [comment]
I actually fixed this now, use the beta.21 version!
