### ISSUE TITLE
Port 5005 gets tied up in node process and server will not start in Synology NAS

### ISSUE THREAD

**Issue by TheHavocHero** [jishi/node-sonos-http-api#162]
FYI, I have had this happen twice now where the service would not start after a reboot of my NAS. When I went to restart the NAS, it would not. Looking at the logs, I saw that port 5005 was in use. The first time this happened, I could not get my docker container to restart, so I removed the container and Docker. I then ran the server natively on the NAS filesystem and still had the issue.

I issued the following commands to kill the node process that was tying the port up and this fixed the problem.

```
$ sudo netstat -ap | grep :5005
tcp6       0      0 [::]:5005               [::]:*                  LISTEN      14884/node
``` 

In this case, process 14884 was the process that node was stuck using. To kill it, issue
`sudo kill -9 14884`

Not sure why this happens. Seems to be after a reboot of the NAS, which is rare.

**Comment by jishi** [comment]
The only explanation I can see for this is that you previously had added some sort of automatic start of the node process. You said that " When I went to restart the NAS, it would not". Are you saying that this process was preventing the NAS from rebooting all together? Because that is very weird.

**Comment by TheHavocHero** [comment]
No, when I restarted my NAS, the docker containers would not start. They would try and then crash. Looking at the logs, revealed that the port 5005 was in use and it was tied to a node process. The container would not start until I killed that process. Same issue if I was not using docker and ran the server natively. The server debug showed the port in use by the node process.

**Comment by jishi** [comment]
Are you sure that you haven't previously added some sort of autostart script that starts the http api outside of docker? some rc.local or other stuff? 

What happens when you try and access port 5005 from a browser after the reboot and without the docker container started?

**Comment by TheHavocHero** [comment]
No, nothing extra than the normal Synology stuff. Since the server is not running, I am not able to get to the webpage. I have another docker container for homebridge and it too does not start. It does not have a port in use and instead, fails with the following:

Homebridge is running on port 51826.
stdout
20:56:40
/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56
stderr
20:56:40
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
stderr
20:56:40
         ^
stderr
20:56:40
stderr
20:56:40
Error: dns service error: unknown
stderr
20:56:40
    at Error (native)
stderr
20:56:40
    at new Advertisement (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56:10)
stderr
20:56:40
    at Object.create [as createAdvertisement] (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:64:10)
stderr
20:56:40
    at Advertiser.startAdvertising (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
stderr
20:56:40
    at Bridge.Accessory._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:498:20)
stderr
20:56:40
    at emitNone (events.js:80:13)
stderr
20:56:40
    at HAPServer.emit (events.js:179:7)
stderr
20:56:40
    at HAPServer._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:169:8)
stderr
20:56:40
    at emitNone (events.js:80:13)
stderr
20:56:40
    at EventedHTTPServer.emit (events.js:179:7)

Eventually, homebridge will start, so, I am not convinced that it is specific to the node-sones-http-api. Maybe something weird with Synology.

**Comment by jishi** [comment]
Maybe the EXPOSE configuration leaves some weird remnants during a reboot... I'm out of ideas then, sorry!

**Comment by TheHavocHero** [comment]
I’m running the beta 6 of the Synology DSM manager, so it could be something with that. Will keep my eye on it. Thanks for the input.

**Comment by rjhilgefort** [comment]
@TheHavocHero You were able to upgrade node to a suitable version? I know it's off topic of this, but do you mind pointing me to a resource on how to do so? I didn't find that synology supported anything beyond the node `12.x` release.

**Comment by TheHavocHero** [comment]
@rjhilgefort With the beta DSM 6 on Synology, you can officially install Node.js v4, also in beta. That was all it took to get Node.js working. I have it supporting both Homebridge and node-sones-http-api. Have been running the beta DSM 6 for about a month now and have not really had any issues, other than node  holding onto the ports for the node-sones-http-api.

**Comment by TheHavocHero** [comment]
FYI. After loading the latest RC candidate for the Synology DSM 6, all my weird problems went away. No more crashes.

**Comment by autofrank** [comment]
Hi psmith
I have the node.js http api running on a Pi and all working well. I want to move to Synology NAS.
I have node.js v4 installed on my DS415Play.

I think I also need NPM but I have no clue how to install that ?
I also don't know how to install the api. I used all command lines on the pi but dont know how its done with the NAS

Any help would be appreciated ?

Thanks
Frank

**Comment by psmith3** [comment]
Hi,

I installed node.js v4 via the Synology Package Center and did not do it via command line. I did not have to install NPM manually. I believe NPM was already buried in the system. Hope this helps.
