### ISSUE TITLE
setavtransporturi doesn't work for SiriusXM streams

### ISSUE THREAD

**Issue by Snicka** [jishi/node-sonos-http-api#164]
I've tried sayall, but it doesn't seem to resume what is currently playing if it is a SiriusXM station, i've tried manually setting the URI but it doesn't catch either, this is one of the URIs i've been trying:
http://localhost:5005/Kitchen/setavtransporturi/x-sonosapi-hls%3Ar%253afirstwave%3Fsid%3D37%26flags%3D8480%26sn%3D4

(this value comes from the state JSON for the player)

**Comment by jishi** [comment]
It probably requires metadata as well. This is not supported yet. I think we have the same issue with Pandora. The underlying setavtransporturi support metadata, but the preset does not unfortunately.

**Comment by jishi** [comment]
This is actually fixed in the beta branch (restore on sayall), so I'm closing this. 

The setavtransporturi still doesn't take metadata as parameter though, but this is kind of clunky with path parameters only anyway (probably need to add POST support instead).
