### ISSUE TITLE
Queue not working

### ISSUE THREAD

**Issue by DamianHartin** [jishi/node-sonos-http-api#166]
Apologies, but don't have much experience with this script/node.js so I can't give a very helpful diagnoses..

executing http://<IP Address>:5005/Office/queue returns {"err":"no queue data found"} even though there is a queue for that room in the Andorid app.

I am getting JSON responses to favorites/state/etc.. so the general install is working.

Not sure where to start looking?

**Comment by jishi** [comment]
Are your Office player grouped with other players? Seems like the queue command doesn't act on the coordinator of the group, which might be expected (had the same issue with clearQueue). 

I did an update: https://github.com/jishi/node-sonos-http-api/blob/master/lib/actions/queue.js#L16

Try and see if that works.

**Comment by DamianHartin** [comment]
Thank you for the quick reply (and awesome app)

No, I have both a grouped set (PlayBar and Sub) and a single Play:3 (the Office), neither of which return the queue.

Applied your update, but still nothing :(

**Comment by jishi** [comment]
Okay, then I need to investigate why it returns an error when I'm at home. I have never used the queue command personally, so I'm not sure if it ever worked.

**Comment by jishi** [comment]
Okay, I have tested it at home, and it works on my system. I'm not even sure where that error message comes from, I can't figure out where it would be generated.

Could you check the following page and see what the "shared/EntriesUsed" gives you? 

`http://player_ip:1400/status/track_queue_summary`

**Comment by jishi** [comment]
Highly unlikely the cause for this, I'm afraid. Even with an empty queue, I still get a correct response although with 0 tracks. 

Very weird. I'll have to think a bit more. If you can come up with any more details of the state of your players, it might help. 

BTW, have you made sure that you also have the latest version of sonos-discovery library? If you have the latest version of sonos-http-api, you can just invoke:

`npm install --production`

And it would fetch the version explicitly specified in package.json (should be 0.16.3)

**Comment by wallee9000** [comment]
Hi, 
I think i have the same problem overhere. State command is working. queue command is giving empty output.

**Comment by jishi** [comment]
I consider this fixed for now.

**Comment by wallee9000** [comment]
Hi,
I made a mistake to install the first version.. After installing newest everything is ok.
Thanks.

**Comment by DamianHartin** [comment]
Hi Jishi and Wallee - apologies but I hadn't had a chance to get back to testing on this.

I believe I was running the latest version - but will have another look in case that's all the problem is :)
