### ISSUE TITLE
Feature Request / Question: Queue'ing Spotify Playlists

### ISSUE THREAD

**Issue by ahaugen** [jishi/node-sonos-http-api#167]
Hey Jishi - 

This is awesome -- sending a donation your way now. 
I've modified spotify.js quite a bit to enable it to take a search term, use Spotify's search API to search over tracks, artists, albums and playlists with that search term, then figure out the best match based on popularity of the object (num_followers for playlists) and how closely the name of the object matches the search term. 
(I should note that getting tracks on a playlist requires authentication, but I'm just searching over public playlists at the moment, so the authentication doesn't require user permissions / token refreshes, etc) 

It then queues up the relevant songs (for artists it pulls the artist's top tracks), but I end up queue'ing songs one by one. It isn't a huge deal b/c I queue and start playing the first song, then continue queue'ing the others (so music is playing while the queue'ing is happening) but for a playlist with 100 songs it takes a long time to complete. 

I'd love to just queue a playlist rather than songs one by one. Do you know the scheme for queue'ing a Spotify playlist? I've tried using the URI of the playlist in the same way you queue a track and no good. 

Thanks!
Austin

**Comment by jishi** [comment]
It works if you do like this:

as URI: `x-rincon-cpcontainer:0006206cspotify%3auser%3aspotify%3aplaylist%3a7b9XqnXw5J47tmn0Y0IZeW`

Note the prefix x-rincon-cpcontainer:0006206c followed by an urlencoded Spotify uri. In addition, you need to send the following metadata:

`<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="0006206cspotify%3auser%3aspotify%3aplaylist%3a7b9XqnXw5J47tmn0Y0IZeW" parentID="00082064featured_pls" restricted="true"><dc:title>Dinner with Friends</dc:title><upnp:class>object.container.playlistContainer</upnp:class><desc id="cdudn" nameSpace="urn:schemas-rinconnetworks-com:metadata-1-0/">SA_RINCON2311_X_#Svc2311-0-Token</desc></item></DIDL-Lite>` 

The content of the metadata is not that relevant, but the `<desc id="cdudn"` is the reference to which spotify account you are using.

**Comment by jishi** [comment]
Also, this is done via AddUriToQueue action.

**Comment by johannesstock** [comment]
Hey Guys,
i just implemented so code to transparently deal with playlists and albums. 
I opened a pull request for that: https://github.com/jishi/node-sonos-http-api/pull/183

Cheers,
Johannes
