### ISSUE TITLE
Feature Request: Get Sonos Favorites

### ISSUE THREAD

**Issue by taddat** [jishi/node-sonos-http-api#169]
It would be great if you could implement the ability to get the list of sonos favorites from the Sonos unit(s).  This would allow us to integrate with other tools to display the favorites and allow user selection, and then use your play favorite function to start playing the favorite station.

**Comment by jishi** [comment]
This should already be support with the /favorites endpoint? Is it not?

**Comment by taddat** [comment]
Jishi - my apologies, I didn't see this listed in the list of commands, but now I see that it appears to be already supported.  Thanks for your hard work and disregard!

**Comment by maddox** [comment]
Any chances we could fetch the art for these favorites?

**Comment by jishi** [comment]
@maddox please raise new issues to not notify all participant in old issues when you comment.
