### ISSUE TITLE
Server not responding after 2 weeks of continuous running

### ISSUE THREAD

**Issue by TheHavocHero** [jishi/node-sonos-http-api#170]
Server started responding sluggishly and TTS was not processing. Looked in my logs tonight in my Docker terminal and found the following error. I looked at my zone player IP addresses and this address does not match my players. May have been an old address. I do have a Sonos Soundbar with a Connect Amp as the rear speakers. If I recall, port 1400 is the web address that you configure the Soundbar for adding the Connect Amp as the rear speakers. The folioing was flooding the terminal. Ever see this? 2nd time it has happened.

```
error: { [Error: connect ETIMEDOUT 172.30.17.242:1400]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  sys call: 'connect',
  address: 172.30.17.242',
  port: 1400 } undefined '/MediaRenderer/RenderingControl/Event'
```

**Comment by jishi** [comment]
Yeah, the underlying library doesn't handle IP switches very well today. I suggest you add IP reservations in your router to resolve it for now.

**Comment by TheHavocHero** [comment]
Thanks. I can do that.
