### ISSUE TITLE
Can't install on Mac

### ISSUE THREAD

**Issue by bopeterson** [jishi/node-sonos-http-api#171]
node-sonos-web-controller works like a charm on my mac, but node-sonos-http-api won't install. I get warnings when installing:
npm WARN engine require-fu@1.0.0: wanted: {"node":"0.10.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN peerDependencies The peer dependency continuation-local-storage@~3 included from cls-bluebird will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
require-fu@1.0.0 node_modules/require-fu
basic-auth@1.0.3 node_modules/basic-auth
async@1.5.2 node_modules/async

npm isn't my strong side, what am I doing wrong?

**Comment by jishi** [comment]
The warnings are fine, but you are running node 0.12 which works for the
web-controller (for now) but the http api requires node 4.0.0+.
