### ISSUE TITLE
preset.json doesn't work with sonos-playlist

### ISSUE THREAD

**Issue by badantlerday** [jishi/node-sonos-http-api#172]
trying to set up preset so that the will play a sones-playlist.
It just mutes for a second and goes to what to what it was playing.

Maybe playlists is not supported in preset?
The workaround right now is to add the playlist to favorites.

**Comment by jishi** [comment]
Yeah, no playlists are not supported yet. It's kinda low priority since it is possible to make it work as you said, with favorites, but I agree that it would be useful. 

I'll keep this ticket open for now.

**Comment by mattnewham** [comment]
I don't get how to do this - if I have a playlist, either a spotify playlist or a sonos playlist, I can't add it to sonos favourites? 

How would one add multiple albums for example to a favourite and then set that in the preset?

For me, calling the preset with the shuffle feature is what I am most interested in, as shuffling playlists is obviously useful when it contains multiple albums.

**Comment by mattnewham** [comment]
Interestingly I had a leftover test in the code from yesterday where I hard coded SQ: into the objectID of the browse function which caused playlists to be returned no matter what was requested.

Adding a "playlist" to the preset "favorite" field then worked, as the code believed it was requesting a favourite but it was actually requesting a playlist (SQ:)

There might be a simple change to enable playlists in presets. I'll patch this unless someone has an answer to my issues above? (I can't seem to add a playlist, or anything other than a station or single album to favourites)

**Comment by mattnewham** [comment]
Added a pull request for the bits required for this to work in #201 - however will also need updates to sones-discovery added here https://github.com/jishi/node-sonos-discovery/pull/59

**Comment by jishi** [comment]
This is now resolved.
