### ISSUE TITLE
Need a way to each TTS files when server starts

### ISSUE THREAD

**Issue by TheHavocHero** [jishi/node-sonos-http-api#174]
Jimmy, I am trying to come up with a creative way to cache all of my TTS files when the server starts so that there is no delay when I press a keypad button to announce and launch a preset. Sometimes there is a delay and I have my ISY994i program setup to say the TTS, wait x seconds and then launch the preset. When the TTS fetch is delayed, it messes my program up and the preset never plays or the TTS gets cut off mid-sentence. I built a program that plays all the TTS files one-by-one with a 10 second timer in between and that works, except I don't want to hear them play at 4am in the morning. I can't figure out how to adjust the volume of the TTS since it is hard coded at 40%. Any suggestions?

**Comment by jishi** [comment]
Best would probably be to download and save the mp3 files with another tool. Basically, the filename is the actual phrase requested with a SHA1 checksum (utf-8 character encoding), and then attached with the language code. 

But why would you hear it 4 in the morning? This is basically a one time thing, nothing will ever clear the tts folder (the cache), so ones it has been downloaded, it will never request the same phrase from voicerss again.

**Comment by TheHavocHero** [comment]
The only way that I knew how to cache the file was to actually have the file play through one of my players. That is why I would have the file play at 4 AM through one of the players. I'll look into a way to have it downloaded outside server. I am doing this through a Docker container, though. Makes it a little more difficult.

**Comment by TheHavocHero** [comment]
Solved my issue. In docker, I was able to change the tts cache directory to /opt/app and then link a volume in docker to a folder on my NAS. On my Synology NAS, I have a shared folder called DOCKER/SONOS/CACHE and I reference it with the following docker run command. Also my settings,json are in the DOCKER/SONOS directory on the NAS too. 

My settings.json files looks like this:
```
{
  "voicerss": "my_voice_rss_key",
  "cacheDir": "/opt/app/"
}
```
I now also have a script that runs every night at 2am to restart the container to keep it healthy. Using the Synology task scheduler, I run a script that I created that kills the container if running; removes the container if it exists and then issues the run command above. I also have another task that starts the container when the system boots up. This is what my script looks like. 

```
#!/bin/bash
docker kill sonos
docker rm sonos
docker run --name=sonos --net=host --restart=always --volume /volume1/docker/sonos/presets.json:/opt/app/presets.json --volume /volume1/docker/sonos/cache:/opt/app/static/tts -d jishi/node-sonos-http-api
```
