### ISSUE TITLE
Feature Request: line-in

### ISSUE THREAD

**Issue by mitchelludwig** [jishi/node-sonos-http-api#175]
First off, amazing api, and just great to use.  So I'm trying to prepare for the arrival of my echo-dot, and what I want to do is pipe the output of my dot using the line-in on one of my SONOS amps.  I've got it set up and working for now using a basic audio source.  I've named the line-in in SONOS "echodot" in preparation.  My issue is that SONOS doesn't let me use line-in as a favorite, so things don't just work.  What I'd ideally want to do is pass /play/favorites/echodot to the room I want to play in, but that doesn't seem in the cards.  So the question is, am I missing something and this is already possible?  And if not, could it be done?  I'm new to all of this and will be dinking around with it myself, but obviously if it's out there, or something already planned, I'd rather wait and see.

Again, thanks.

**Comment by jishi** [comment]
Thank you! Yes, what you want to do is achievable but not as straight-forward as one would hope for. We had a discussion about it in this ticket: https://github.com/jishi/node-sonos-http-api/issues/109, if you want to follow that.

To answer your question, you can use the setavtransporturi action for it, but you would need to identify which UUID your Connect:AMP has. Once you have done that, you can send the following command to any player:

http://localhost:5005/RoomName/setavtransporturi/x-sonos-stream:RINCON_XXXXXXXXXXXX01400

Replace RINCON_XXXXXXXXXXXX01400 with the UUID of your Connect:AMP. You can find the UUID from the `/zones` command, or directly from the players with this: `http://[IP of any of your player]:1400/status/topology`

**Comment by mitchelludwig** [comment]
Ok, so I followed the steps above.  I pulled the UUID from the topology call and generated the following:

http://192.168.1.42:5005/patio/setavtransporturi/x-sonos-stream:RINCON_000E58D3185201400

When I call it, it works "sometimes", and then only after a long delay.  If I watch the logs from the server, I see nothing and then, after a few attempts, and only after a pause, I see the debug statements showing the avtransport switch.

Any thoughts on why this would only work sporadically, and then only after a delay?  Because it's exactly what I'm looking for :)

And again, thanks.

**Comment by jishi** [comment]
Hm, yeah, I'm sorry, it supposed to be "x-rincon-stream", not "x-sonos-stream". Suprised that it worked at all, to be honest.

**Comment by mitchelludwig** [comment]
Yep, figured it out looking at the debugs :)

**Comment by jishi** [comment]
Cool!
