### ISSUE TITLE
connection refused errors

### ISSUE THREAD

**Issue by bjseiler** [jishi/node-sonos-http-api#176]
The errors at the bottom of this repeat over and over. I am confused because the ip in the error is the raspberry pi's ip. Not sure why it is look for port 1400 of the pi. Any help would be appreciated.

pi@raspberrypi:~/Downloads/node-sonos-http-api-master $ node server.js
no settings file found, will only use default settings
info: binding SSDP to port 1905
info: discovering all IPs from lo
info: discovering all IPs from wlan0
info: relevant IPs 192.168.1.11=null
[SyntaxError: /home/pi/Downloads/node-sonos-http-api-master/settings.json: Unexpected end of input]
info: notification server listening on port 3500
http server listening on port 5005
loaded presets { test: 
   { players: [ [Object] ],
     state: 'PLAYING',
     favorite: 'Rock',
     uri: 'x-rincon-stream:RINCON_0000000000001500',
     playMode: 'SHUFFLE',
     pauseOthers: true } }
info: scanning for players in ip 192.168.1.11
info: subscribing to topology 192.168.1.17
info: using local endpoint 192.168.1.11
Initializing player Living Room
Initializing player Media Room
Initializing player Master Bedroom
error: { [Error: connect ECONNREFUSED 192.168.1.11:1400]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.11',
  port: 1400 } undefined '/MediaRenderer/AVTransport/Event'
error: { [Error: connect ECONNREFUSED 192.168.1.11:1400]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.11',
  port: 1400 } undefined '/MediaRenderer/RenderingControl/Event'
error: { [Error: connect ECONNREFUSED 192.168.1.11:1400]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.11',
  port: 1400 } undefined '/MediaRenderer/GroupRenderingControl/Event'
error: { [Error: connect ECONNREFUSED 192.168.1.11:1400]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.11',
  port: 1400 } undefined '/MediaServer/ContentDirectory/Event'
debug: received avtransport 
debug: received avtransport x-rincon-queue:RINCON_000E58D1B53801400#0
debug: emitting group-volume
error: { [Error: connect ECONNREFUSED 192.168.1.11:1400]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.11',
  port: 1400 } undefined '/MediaRenderer/AVTransport/Event'
error: { [Error: connect ECONNREFUSED 192.168.1.11:1400]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.11',
  port: 1400 } undefined '/MediaRenderer/RenderingControl/Event'
error: { [Error: connect ECONNREFUSED 192.168.1.11:1400]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.11',
  port: 1400 } undefined '/MediaRenderer/GroupRenderingControl/Event'
error: { [Error: connect ECONNREFUSED 192.168.1.11:1400]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.11',
  port: 1400 } undefined '/MediaServer/ContentDirectory/Event'

**Comment by jishi** [comment]
That sounds very weird. From what I can gather, it finds a player at 192.168.1.17, which it will use for topology updates. It will receive a list of players from that ZonePlayer, and try to subscribe to the different events available (and here is where it seems to fail). The 192.168.1.17 is an IP to one of your players, correct? If you visit `http://192.168.1.17:1400/status/topology` and chec the Zone Players list, I'm guessing there is no mention of your rpi IP?

**Comment by jishi** [comment]
And this happens instantly after startup, right?

**Comment by bjseiler** [comment]
Thanks a ton for the help. My pi had grabbed the same ip that one of the media players had. No idea why that happened but once I changed the ip, everything works. Thanks!

**Comment by jishi** [comment]
I recommend that you set DHCP reservations for your Sonos players, since my library doesn't handle IP changes very well atm.

**Comment by noesberger** [comment]
Hi

I had similar issues:
address: '192.168.1.44' } undefined '/MediaRenderer/AVTransport/Event'
error: { [Error: bind EADDRNOTAVAIL 192.168.1.44]
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'bind',
  address: '192.168.1.44' } undefined '/MediaRenderer/AVTransport/Event'
error: { [Error: bind EADDRNOTAVAIL 192.168.1.44]
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'bind',
  address: '192.168.1.44' } undefined '/MediaRenderer/AVTransport/Event'
error: { [Error: bind EADDRNOTAVAIL 192.168.1.44]
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'bind',
  address: '192.168.1.44' } undefined '/MediaRenderer/RenderingControl/Event'

I found out, that my raspberry is getting an addional IP over DHCP. I've configured a static IP in /etc/network/interfaces. But since the latest updates this seems not to work anymore. In the interfaces file i had to put:
auto eth0
allow-hotplug eth0
iface eth0 inet manual

Then at the end of /etc/dhcpcd.conf
# Static IP configuration
static ip_address=192.168.1.251/24
static routers=192.168.1.1
static domain_name_servers=192.168.1.1

This worked then for my raspberry.

**Comment by PhilOtt** [comment]
Same here on a raspberry, used to work, not working anymore, but all my devices are setup with DHCP reservation, so I'm not sure what would be causing this...

> sonos-http-api@0.19.0 start /var/node/node-sonos-http-api-master
> node server.js
no settings file found, will only use default settings
info: binding SSDP to port 1905
info: discovering all IPs from lo
info: discovering all IPs from wlan0
info: relevant IPs 192.168.0.203=null
{ [Error: Cannot find module './settings.json'] code: 'MODULE_NOT_FOUND' }
info: notification server listening on port 3500
http server listening on port 5005
loaded presets { test:
   { players: [ [Object] ],
     state: 'PLAYING',
     favorite: 'Rock',
     uri: 'x-rincon-stream:RINCON_0000000000001500',
     playMode: 'SHUFFLE',
     pauseOthers: true },
  piano:
   { players: [ [Object] ],
     state: 'PLAYING',
     favorite: 'Piano',
     uri: 'x-rincon-stream:RINCON_0000000000001500',
     playMode: 'SHUFFLE',
     pauseOthers: true } }
info: scanning for players in ip 192.168.0.203
info: subscribing to topology 192.168.0.211
info: using local endpoint 192.168.0.203


If I refresh the target page: http://192.168.0.203:5005/zones I get a new error message in the pi console: `No system has yet been discovered. Please see https://github.com/jishi/node-sonos-http-api/issues/77 if it doesn't resolve itself in a few seconds.`

Sonos player is ip .211 and I can access http://192.168.0.211:1400/status/topology without any problem (not listing the rpi anywhere though..)

**Comment by jishi** [comment]
@PhilOtt your problem is a bit different than most others, since it finds your system: 

`info: subscribing to topology 192.168.0.211`

And the rpi should not be listed in the topology, but it should show up under controllers.
