### ISSUE TITLE
"Ungroup All"

### ISSUE THREAD

**Issue by BrekiTomasson** [jishi/node-sonos-http-api#177]
Hi all!

Just wondering. Is there any way of making a preset that simply stops playing all sounds from all speakers and ungroups any groups that may have been created? I'm trying to get `node-sonos-http-api` to play nice with other Sonos plugins via both OpenHAB and Homebridge, since they all have features the others are missing, and this seems to be the only thing that I'm having real trouble doing.

Essentially, what I want is simply a "reset all players to ungrouped and silent" preset.

**Comment by BrekiTomasson** [comment]
More details: The reason I need this is that the current way I use my Sonos <-> Siri integration doesn't allow me to start playing from a speaker in a group unless it's the leader of that group, and playing from the leader automatically plays from everything else in the group. I'd like to create a scene like "Siri, Ungroup the Speakers" so that I can then do things to individual speakers.

**Comment by jishi** [comment]
Well, you could always issue several presets, one for each player and that would break them up. Not the cleanest solution. Another option would be to make your own action, that would call .becomeCoordinatorOfStandaloneGroup() on each player. This is a highly specific use case, so I'm not sure how suitable it would be to maintain. I mean, the optimal solution would be to break out the player you would want to interact with only, right?

**Comment by BrekiTomasson** [comment]
Yes, but with multiple players in the system, I would like an ability to just reset everything to its default state, so that I know that when I next want to interact with, any of my speakers, it'll be ready for me. Otherwise, I'll end up trying to start a scene, the speakers won't start, then I'll remember that they were grouped, will run a preset that ungroups them, then start the scene again.

Instead, I'd like my "turn things off" preset to simply ungroup them at the same time.

**Comment by jishi** [comment]
Then I suggest you create a custom action that just ungroups all speakers from each other. You could perhaps look into this action as a reference:

https://github.com/jishi/node-sonos-http-api/blob/master/lib/actions/group.js

**Comment by BrekiTomasson** [comment]
Having some issues with this, what's the best way to discover all `uuid`s and cycle through them? The action that I've built now seems to stop after the first iteration of `becomeCoordinatorOfStandaloneGroup`.

**Comment by jishi** [comment]
One thing that comes to mind, is that you can check if the avTransportUri property of each player begins with `x-rincon:`, that indicates that it is grouped.  If not, you wouldn't need to ungroup it.

Secondly, right now you are sending this trigger to all players simultaneously, which might overload it (since every action on one player is propagated to all the other players for synchronizing the state). This is a bit complex to fix, since you basically need to wait for the callback before invoking the next one. A library like `async` can help with that. I am rewriting it to be promised based which would probably make it a bit simpler to do this, but I'm not finished (and nor do I know when I will be).

**Comment by BrekiTomasson** [comment]
That's a good point. Also, I was thinking; why isolate _all_ players? If I have _n_ players, surely it would be enough to isolate _n-1_ players since the last would be ungrouped by definition. But yeah; the check for `avTransportUri` starting in `x-rincon:` makes a lot of sense; I'll look into it today.
