### ISSUE TITLE
Presets - Without a Room?

### ISSUE THREAD

**Issue by mitchelludwig** [jishi/node-sonos-http-api#178]
Hey all.

I posted a few days back about grabbing the line-in to use via the API.  I've found (with guidance from jimmy and ryan) two options; one with presets and the other by using setavtransporturi.  Both work, but neither is exactly what I'm looking for.  My issue is that the preset option doesn't allow me to select a room (it's embedded in the preset).  and the setavtransport option forces me to have the RINCON string (rather than something more polite).  What I want to do is be able to operate like I can with favorites, and say localhost:5005/RoomName/Preset/PresetName.  In fact it seems like the API is set up for this, but when I eliminate the room information from my preset I crash the node server when I try to run it.  

My plan is to see if I can figure this out within the code, but I figured I'd ask for help as well, since I'm way rusty on JavaScript, need to figure out how all the code hangs together, and probably not the first to consider this.

Thanks!

**Comment by jishi** [comment]
I'm not really following, what exactly are you trying to achieve? Seems like you want to achieve something that isn't really the task for a preset, just because it has the functionality of the preset?

What stuff from the preset do you want to apply to a room, and do you want that to be applied to the whole group that the room belongs to?

**Comment by mitchelludwig** [comment]
Ultimately, I'm trying to get the system to set the source for a specific room to the line in on one of my amps.  I was just trying to avoid having to use the RINCON line all the time in the URL.  I can certainly get along with it as is :)

**Comment by jishi** [comment]
Well, are you doing this manually in browser? Then I understand why it feel clunky, but that is not really the way I pictured people using it :)

But I'm planning on adding it eventually, you can follow this issue if you want to be notified when it's done, https://github.com/jishi/node-sonos-http-api/issues/109. Right now I'm occupied with a complete rewrite though.

**Comment by jishi** [comment]
No more feedback, closing
