### ISSUE TITLE
Feature Request: Thumbs Up/Down

### ISSUE THREAD

**Issue by taddat** [jishi/node-sonos-http-api#179]
It would be awesome if you could add support for thumbs-up and thumbs-down.  Both Pandora and Google Music use this functionality.

**Comment by jishi** [comment]
Unfortunately that probably require credentials for the various services that I have yet to find a solution for, since that is exchanged encrypted between the controller and players.

**Comment by NovaGL** [comment]
I asked another developer and they said they are using the native api's of Pandora to do it, but wouldn't tell me how they did the authentication

**Comment by jishi** [comment]
Well, once you would have credentials, both the SMAPI or the native API is usable. One could request credentials separetely from the user, but it becomes a bit bulky and hard to maintain.

**Comment by jishi** [comment]
At the moment I don't see this getting implemented in the near future, sorry.

**Comment by lemketron** [comment]
I would love to see this for Pandora.  I currently get out of the shower to grab my phone and thumbs-up music.  It would be awesome to just ask Alexa to do it for me, but I understand that it's a non-trivial feature.  Just curious: Does Alexa offer this when playing Pandora on the Echo?
