### ISSUE TITLE
Feature request: Configuration value for `say`/`sayAll` volume

### ISSUE THREAD

**Issue by tdlm** [jishi/node-sonos-http-api#184]
I looked in the say.js and noticed that the `announceVolume` is statically set to 40 and isn't configurable.

**Comment by tdlm** [comment]
Here's what I've been using in my Pi project to compensate: http://i.imgur.com/fqwAOQf.png

Just realized I left in the console.log statement, but you get the idea.

**Comment by jishi** [comment]
Sounds good, could you send a pull request with your changes?

**Comment by tdlm** [comment]
@jishi Oh, yes. I'll do that.

**Comment by jishi** [comment]
Part of beta version
