### ISSUE TITLE
Feature request: Use this coordinator when you have multi groups

### ISSUE THREAD

**Issue by robertw** [jishi/node-sonos-http-api#187]
Could you or can you expand the command line for group functions to include a var for the name of the coordinator of a specific group. 

ex: http://192.168.1.160:5005/groupVolume/familyroom/70

this way if we have more than 2 groups set in preset or created by another app we can make a call to a specific group by this method 

Many thanks

**Comment by jishi** [comment]
Hm, I'm not sure if I'm following you. The structure is:

`/familyroom/groupvolume/70`

That should already adjust the group volume for the group that familyroom is part of. When you call groupvolume directly, it will just use the last player or something (which is actually an unsupported feature).

**Comment by robertw** [comment]
Did not realize it worked that way many thanks works perfect.......Closed....
