### ISSUE TITLE
Say doesn't work with fixed volumn

### ISSUE THREAD

**Issue by csteenwyk** [jishi/node-sonos-http-api#188]
I have a Sonos Connect that is connected to a Onkyo Stereo. I have the output of the connect set to "Fixed" instead of variable which effectively sets the output volume to max. Anyway, it appears that the "/say" command fails when the connect is set to fixed output. If I switch the output to "variable" everything works fine but with fixed I never hear the output (nor do I see the output switch within the sonos application)

**Comment by jishi** [comment]
I think we fixed this in https://github.com/jishi/node-sonos-http-api/issues/150

Make sure you are running the latest master version of the http-api, and that it has installed the latest version of sonos-discovery (v0.16.4) via npm install

**Comment by csteenwyk** [comment]
Yup. Well played. Worked great. I thought I was on the latest. Sorry!
