### ISSUE TITLE
Webhook JSON data is not updated when setting Sonos volume

### ISSUE THREAD

**Issue by Home-Control9000** [jishi/node-sonos-http-api#190]
Hi,

I want to use the webhook JSON data for monitoring Sonos player statuschanges. This is working well for next, pause and play etc changes. Unfortunally volumes changes are not reported. 

Thanks.

**Comment by jishi** [comment]
I'm very close to finishing my complete rewrite of the http api and it's depending library. I will add a volume change event to the webhook in that version.

**Comment by Home-Control9000** [comment]
Hi Jimmy,

Thanks for your effort. I will test it for you when new release is coming.

**Comment by jishi** [comment]
This has now been rolled out into beta. 

Today you only receive volume and UUID of the player, this might not be the most user friendly thing. Let me know what you think.

**Comment by Home-Control9000** [comment]
Hi Jimmy,

Thanks for your effort!
I will install the beta asap and keep you informed.

Best regards,

Walter Leemput


Jimmy Shimizu schreef op 2016-06-01 20:23:

**Comment by Home-Control9000** [comment]
Hi Jimmy,

I Installed the betaversion.
I get the volume change now. Is it possible to include 'roomname' in de JSON output? The same i get with other state changes. I can use the uuid but then i have to map between roomname and uuid which is not neccesary when you include the roomname in the JSON output.
I notice some fieldname changes when issuing state with: http://localhost:5005/{room name}/state

'playerState' is changed in 'playbackState'
'absoluteAlbumArtURI' -> 'absoluteAlbumArtUri'
'zonePlayMode' -> 'playMode'

Therefore my JSON tro perl variable script will fail. Is it possible to keep the original field names as it was in the master version to be compatible with old versions? 

Thanks,
Walter

**Comment by jishi** [comment]
I've included the roomName in the response now. Regarding the fieldname changes, they are consistent with the way I represent state data in the underlying library. I have no intention in keeping backward compatibility for the legacy version since that one just grew organically with no to little consistency. 

I could however consider adding a version property, which could simplify compatibility with external parties relying on this info (if you have a single version that might talk to both older and newer versions of my API). Then you could use the version property to consider which transformation you need to make to keep compatibility.

**Comment by Home-Control9000** [comment]
Hi Jimmy,

Thanks, i will install this evening the latest beta to check the 
roomname field.
When fieldnames in the JSON output is changed, thats no problem for me 
because i will change my software for that.
Version property is a good idea i think as many users will rely on the 
standard fieldnames and they don't have to change there software.

What about putting the settings.json in the /etc directory to maintain 
the configuration when updating package?

Best regards,

Walter

Op 06-06-16 om 22:13 schreef Jimmy Shimizu:

**Comment by jishi** [comment]
I will look into the possibility to define a src folder for settings etc with a command line parameter or ENV variable since that would help out in certain installations. Just blindly move it to /etc wouldn't really work since it is cross-platform.

However, I don't distribute a settings.json so it shouldn't be overwritten unless you manually remove it.

**Comment by Home-Control9000** [comment]
Hi Jimmy,

Just installed the newest beta. I changed the JSON fieldnames in my 
software and it works like a charm. The roomname is also availlabe in 
the webhook. I wil change now my update logic.
Now i poll every second and this is to intensive. With the webhook i get 
only changed status which is a better system.
I run the beta the next week and keep you informed about stability etc.
Thanks.

Best regards,
Walter

Op 08-06-16 om 07:14 schreef Familie Leemput:

**Comment by jishi** [comment]
Hi, great to hear. The webhook is still pretty chatty, it announces state change for all players in a group and volume changes are evented for all increments, which could be a strain for some implementations.

Let me know if you feel like this is a problem, it would be good to know.

**Comment by Home-Control9000** [comment]
Hi Jimmy,

My application parse the JSON data with a Perlmodule and will update the 
Perl variables. Mabe you can help me with my following problem:
At this moment i send every second a 'state' request to get the uptodate 
status from the Sonos devices. I want to change my application to use 
the webhook so only statechanges are read which is efficient. The 
problem is, that i have a song 'elapsed time' indicator in my GUI. 
Elapsed time will change always and this is not implemented in the 
webhook. Is there another way to update the gui without have to poll 
every second?
Thanks in advance,

Walter


Op 11-06-16 om 17:34 schreef Jimmy Shimizu:

**Comment by jishi** [comment]
Hi. The way I do it, since I have the same issue with the Sonos eventing system, is that I keep a state time from when I last received data. Every time I want to know elapsed time, I would use current timestamp, and subtract the state time, then add that amount of time to the elapsed time that you got from the webhook. 

Then, in addition, you would also need some scheduled task in your perl script to update whatever GUI you havev, every second or half a second or similar.

**Comment by Home-Control9000** [comment]
Hi Jimmy,

Thank you for this. I was thinking about the same method to get the 
elapsed time to avoid polling the Sonos every 1 second. I will implement 
this asap and make use of the webhook state.
I shall explain my configuration a bit.

My home-control system is based on a old 'Misterhouse' distribution 
which is based on Perl. Im running this for more as 12 years now on a 
Ubuntu server. Very stable and its the ideal way to 'glue' Internet of 
things together. The core application is very simple. It only receives 
and send Xpl messages to/from Xpl agents. It process cron, appliance 
event triggers  etc. Every appliance has a Xpl agent which communicates 
with a particular device. For example xbmc, RFXcom transeiver, Fritzbox 
telephone, Sonos, dreambox. remotes The agent will only send and receive 
Xpl messages to the Misterhouse core application and will be processed. 
Im using Demopad for GUI which is a slik interface! . I can send you 
some more info / pictures if you want?
Im busy with a remote toggle button to select new Sonos playlist based 
on genre. It would be nice if i can play first a mp3 to announce the 
playlist name and then load and play it. Are you planning to support mp3 
playing?

Thanks, Walter


Op 13-06-16 om 21:56 schreef Jimmy Shimizu:

**Comment by jishi** [comment]
Impressive that such a system has managed to stay relevant for so many years, there are a lot of competition in this field, especially during the last few years. Believe it or not, I'm not using any home automation system personally :)

There is an issue for just that: 

https://github.com/jishi/node-sonos-http-api/issues/160

which has been dependent on my rewrite to have better control over when stuff has "finished".  This also relates to this one https://github.com/jishi/node-sonos-http-api/issues/136 if you want an actual custom mp3 and not a TTS generated one.

**Comment by Home-Control9000** [comment]
Hi Jimmy,

Yes, there are many home-control system on the market today with slik 
GUI's. But when you want the perfect integration in a home environment 
you have the work with custom scripts. At my home i have already 10 
years 'The Internet Of Things' where everbody is talking about :) The 
Misterhouse system is the ideal way to glue things together.
The whole Misterhouse system is programmed in Perl which is very 
flexible and there you have CPAN with many modules. Sure you will find 
one that you need.
The system is very reliable, the processes are monitored by the linux 
program 'MONIT' which monitors the complete system and restart processes 
if needed.
I cant believe you not using any homeautomation :) With your software i 
can control all of my Sonos speakers and i run customised playlist each 
time of day. In the morning 'lounge music' in daytime '80s' and so on. I 
have little simple remotes in each roome where i can control the sonos 
volume and stop/play/next song. For audio notification im using a old 
'MUSICPAL' in each room with soundserver software. I want to replace 
these units with the Sonos system in each room but then we should be 
able to play mp3's or wav files. For example when somebody rings the 
doorbell or callerid announcement etc. After that the original playlist 
should be loaded again. This feature would be great and hopefully this 
will be implemented in you software. This week i will do some Paypal 
donation for you effort.
Thank you for this great software, keep up the good work!

Walter

Jimmy Shimizu schreef op 2016-06-15 10:22:

**Comment by Home-Control9000** [comment]
Hi Jimmy,

Just managed to write a simple Perl script to capture the webhook JSON 
data in Perl variables. See attachement. You can include it in your 
distribution if you want as a examplecode for Perl programmers.
This is working well. There are 2 things i noticed:

1 When setting the volume via the http API the volume status is reported 
like this:
previousVolume: 10
newVolume: 10

previousVolume is the same als newVolume which is not true. When setting 
the volume via the Sonos APP output is ok.

2 #print "x-rincon-queue: $obj[0]{data}{x-rincon-queue}\n";
the '-' in the field name is not accepted as a JSON fieldname and the 
json decoder will complain

Now i can disable the 1 second update method and only read changes with 
the webhook. I will test it this week in my productionsystem and keep 
you informed.
Thanks!

Best regards,

Walter


Op 15-06-16 om 10:22 schreef Jimmy Shimizu:
>
> Impressive that such a system has managed to stay relevant for so many 
> years, there are a lot of competition in this field, especially during 
> the last few years. Believe it or not, I'm not using any home 
> automation system personally :)
>
> There is an issue for just that:
>
> #160 <https://github.com/jishi/node-sonos-http-api/issues/160>
>
> which has been dependent on my rewrite to have better control over 
> when stuff has "finished". This also relates to this one #136 
> <https://github.com/jishi/node-sonos-http-api/issues/136> if you want 
> an actual custom mp3 and not a TTS generated one.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/jishi/node-sonos-http-api/issues/190#issuecomment-226120569>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ARv8CJSqTS_tueQNDuGgAyhHH_E-ZtoUks5qL7ZggaJpZM4INZvM>.
>


#!/usr/bin/perl -w
##############################################################################
# Functional Description:
# -----------------------
#
# Sonos xPL JSON agent
##############################################################################
#
use strict;
use warnings;

use CGI qw/ :standard /;
use Data::Dumper;
use HTTP::Daemon;
use HTTP::Response;
use HTTP::Status;
use POSIX qw/ WNOHANG /;
use JSON;
use Data::Dumper;

# xPL device
my $vendorid = 'bnz';

# sonos-http-api-master JSON host
my $node_sonos_http_api_master_json_host = '127.0.0.1';

# sonos-http-api-master JSON port
my $node_sonos_http_api_master_json_port = '5007';

my $d = HTTP::Daemon->new(
    LocalAddr => $node_sonos_http_api_master_json_host,
    LocalPort => $node_sonos_http_api_master_json_port,
    Reuse => 1,
) or die "Can't start http listener at $node_sonos_http_api_master_json_host:$node_sonos_http_api_master_json_port";
print "Started HTTP listener at " . $d->url . "\n";

while (1) {
       http_child($d);
      }


sub http_child {
    my $d = shift;

        my $c = $d->accept;
        my $r = $c->get_request();
        $c->autoflush(1);

        my $output = $r->content;

        # convert json to perl
        my @obj = from_json ($output);

        # for debug
        #print Dumper(@obj)."\n";

      if ($obj[0]{type} eq 'transport-state') {     
        print "\n";
        print "type: $obj[0]{type}\n";
        print "uuid: $obj[0]{data}{uuid}\n";
        print "coordinator: $obj[0]{data}{coordinator}\n";
        print "roomName: $obj[0]{data}{roomName}\n";
        print "currentTrack artist: $obj[0]{data}{state}{currentTrack}{artist}\n";
        print "currentTrack title: $obj[0]{data}{state}{currentTrack}{title}\n";
        print "currentTrack album: $obj[0]{data}{state}{currentTrack}{album}\n";
        print "currentTrack albumArtUri: $obj[0]{data}{state}{currentTrack}{albumArtUri}\n";
        print "currentTrack duration: $obj[0]{data}{state}{currentTrack}{duration}\n";
        print "currentTrack uri: $obj[0]{data}{state}{currentTrack}{uri}\n";
        print "currentTrack radioShowMetaData: $obj[0]{data}{state}{currentTrack}{radioShowMetaData}\n";
        print "currentTrack absoluteAlbumArtUri: $obj[0]{data}{state}{currentTrack}{absoluteAlbumArtUri}\n";

        print "nextTrack artist: $obj[0]{data}{state}{nextTrack}{artist}\n";
        print "nextTrack title: $obj[0]{data}{state}{nextTrack}{title}\n";
        print "nextTrack album: $obj[0]{data}{state}{nextTrack}{album}\n";
        print "nextTrack albumArtUri: $obj[0]{data}{state}{nextTrack}{albumArtUri}\n";
        print "nextTrack duration: $obj[0]{data}{state}{nextTrack}{duration}\n";
        print "nextTrack uri: $obj[0]{data}{state}{nextTrack}{uri}\n";
        #print "nextTrack radioShowMetaData: $obj[0]{data}{state}{nextTrack}{radioShowMetaData}\n";
        print "nextTrack absoluteAlbumArtUri: $obj[0]{data}{state}{nextTrack}{absoluteAlbumArtUri}\n";

        print "volume: $obj[0]{data}{state}{volume}\n";
        print "mute: $obj[0]{data}{state}{mute}\n";
        print "trackNo: $obj[0]{data}{state}{trackNo}\n";
        print "elapsedTime: $obj[0]{data}{state}{elapsedTime}\n";
        print "elapsedTimeFormatted: $obj[0]{data}{state}{elapsedTimeFormatted}\n";
        print "playbackState: $obj[0]{data}{state}{playbackState}\n";
        print "playMode repeat: $obj[0]{data}{state}{playMode}{repeat}\n";
        print "playMode shuffle: $obj[0]{data}{state}{playMode}{shuffle}\n";
        print "playMode crossfade: $obj[0]{data}{state}{playMode}{crossfade}\n";
        print "avTransportUri: $obj[0]{data}{avTransportUri}\n";
        #print "x-rincon-queue: $obj[0]{data}{x-rincon-queue}\n";
        print "avTransportUriMetadata: $obj[0]{data}{avTransportUriMetadata}\n";
      }
      elsif ($obj[0]{type} eq 'volume-change') {     
        print "roomName: $obj[0]{data}{roomName}\n";
        print "previousVolume: $obj[0]{data}{previousVolume}\n";
        print "newVolume: $obj[0]{data}{newVolume}\n";
        print "uuid: $obj[0]{data}{uuid}\n";
      }

        $c->close();
        undef $c;
    }

# {"type":"transport-state","data":{"uuid":"RINCON_B8E937DD6CC801400","coordinator":"RINCON_B8E937DD6CC801400","roomName":"Woonkamer","state":{"currentTrack":{"artist":"The Chainsmokers","title":"Don't Let Me Down","album":"Don't Let Me Down","albumArtUri":"/getaa?s=1&u=x-sonos-spotify%3aspotify%253atrack%253a1i1fxkWeaMmKEB4T7zqbzK%3fsid%3d9%26flags%3d8224%26sn%3d1","duration":208,"uri":"x-sonos-spotify:spotify%3atrack%3a1i1fxkWeaMmKEB4T7zqbzK?sid=9&flags=8224&sn=1","radioShowMetaData":"","absoluteAlbumArtUri":"https://i.scdn.co/image/506b3aee8a743d125460453499a56cb64e5a43ec"},"nextTrack":{"artist":"Maan","title":"Ride It","album":"Ride It","albumArtUri":"/getaa?s=1&u=x-sonos-spotify%3aspotify%253atrack%253a7xdiXcJgNfDsergXOa3gTH%3fsid%3d9%26flags%3d8224%26sn%3d1","duration":220,"uri":"x-sonos-spotify:spotify%3atrack%3a7xdiXcJgNfDsergXOa3gTH?sid=9&flags=8224&sn=1","absoluteAlbumArtUri":"https://i.scdn.co/image/dc64b0cddeab92f5901b2cc26ad92444cbe80db2"},"volume":10,"mute":false,"trackNo":51,"elapsedTime":0,"elapsedTimeFormatted":"00:00:00","playbackState":"TRANSITIONING","playMode":{"repeat":true,"shuffle":true,"crossfade":false}},"avTransportUri":"x-rincon-queue:RINCON_B8E937DD6CC801400#0","avTransportUriMetadata":""}}

**Comment by jishi** [comment]
I know why the volume is t he same when you update it directly in the http api, I would need to event volume change directly and ignore the event that comes from Sonos in this case.

"2 #print "x-rincon-queue: $obj[0]{data}{x-rincon-queue}\n";
the '-' in the field name is not accepted as a JSON fieldname and the
json decoder will complain" I don't see how this would happen. That value would never be a field name, it is the value of avTransportUri-field. That let me believe that your JSON decoder is acting up. The data is serialized using a JSON serializer in the server end, so it shouldn't be non-compliant.

**Comment by Home-Control9000** [comment]
Hi Jimmy,

Im using the JSON cpan perl module to decode stuff
# convert json to perl
         my @obj = from_json ($output);
Im will contact the developer but its no issue because im not using this 
field.

Thanks.

Walter


Op 26-06-16 om 19:29 schreef Jimmy Shimizu:

**Comment by Home-Control9000** [comment]
Hi Jimmy,

The JSON update process is running stable in my production system at 
this moment.
Some notice:

Why when volume changes, 'transport-state' is not sending a JSON update? 
This volume field is also included in this message.
At this moment i read seperated the 'volume-change' JSON message in my 
system but why is this seperated?

Thanks,
Walter


Jimmy Shimizu schreef op 2016-06-26 19:29:

**Comment by jishi** [comment]
A volume change isn't considered a transport-state, that only happens when it's changing track or seeking within a track.

The reason for including the volume in the transport-state was merely because it is the same data that one would receive from polling the /state action from the HTTP api, there we aggregate all relevant info about the current state of the player. 

It is enough to only act on volume changes from the volume-change event, and disregard that data in transport-state events.

**Comment by Home-Control9000** [comment]
Hi Jimmy,

Ok i understand. I already adapted my code to this situation, The system 
is running stable now.
Now i have to implement the 'elapsed time' for my progress bar without 
polling the Sonos. I will take a look at your suggestion:

--
 > Hi. The way I do it, since I have the same issue with the Sonos 
eventing system, is that I keep a state time from when I last received 
data. Every time I want to know elapsed time, I would use current 
timestamp, and subtract the state time, then add that amount of time to 
the elapsed time that you got from the webhook.
 > Then, in addition, you would also need some scheduled task in your 
perl script to update whatever GUI you havev, every second or half a 
second or similar.
--

Thanks,

Walter

Op 28-06-16 om 15:32 schreef Jimmy Shimizu:
