### ISSUE TITLE
sonos-http-api/node_modules/sonos-discovery/lib/services/ not found on Raspberry Pi

### ISSUE THREAD

**Issue by andyadler** [jishi/node-sonos-http-api#191]
I am working to get your package working on a Raspberry Pi 3.   I installed node v4.4.0 and when I start the package I get the following:

pi@pi-sonos:~/node_modules/sonos-http-api $ npm start

> sonos-http-api@0.19.0 start /home/pi/node_modules/sonos-http-api
> node server.js

module.js:327
    throw err;
    ^

Error: Cannot find module '/home/pi/node_modules/sonos-http-api/node_modules/sonos-discovery/lib/services/'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at requirePath (/home/pi/node_modules/sonos-http-api/node_modules/require-fu/lib/index.js:14:22)
    at /home/pi/node_modules/sonos-http-api/node_modules/require-fu/lib/index.js:21:9
    at Array.forEach (native)
    at fuDirectory (/home/pi/node_modules/sonos-http-api/node_modules/require-fu/lib/index.js:20:34)
    at /home/pi/node_modules/sonos-http-api/node_modules/require-fu/lib/index.js:25:5
    at Object.<anonymous> (/home/pi/node_modules/sonos-http-api/node_modules/sonos-discovery/lib/musicservices.js:5:35)

npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@0.19.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sonos-http-api@0.19.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sonos-http-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/node_modules/sonos-http-api/npm-debug.log

**Comment by jishi** [comment]
seems kind of odd that you would have the sonos-http-api in a sub-folder of node_modules...? How did you install this?

**Comment by andyadler** [comment]
Never mind.  I read issue 35 and reinstalled with git clone and all is well.

Sorry for the false alarm.

aa
