### ISSUE TITLE
Request: Announcement volume configurable from the settings file

### ISSUE THREAD

**Issue by kolaf** [jishi/node-sonos-http-api#193]
It would be great if the announcement volume used with the "sayAll" command was configurable using a keyword in the settings file. The default value of "40" is not always loud enough.

**Comment by jishi** [comment]
There is already a pull request for this, I just need to update the documentation and verify that it will not break of configuration is missing.

https://github.com/jishi/node-sonos-http-api/pull/189

I have been waiting for the documentation change, but he seems to have gone AWOL :)
