### ISSUE TITLE
Artist not appear in State

### ISSUE THREAD

**Issue by ADN182** [jishi/node-sonos-http-api#195]
Hi, 

Artist not appear in state status for the current song, but it's appear for the next song. See example beelow : 

{"currentTrack":{"artist":"Coldplay","title":"05 - Clocks","album":"A Rush of Blood to The Head","albumArtURI":"/getaa?s=1&u=x-sonosapi-stream%3as2339%3fsid%3d254%26flags%3d32%26sn%3d0","duration":307,"uri":"x-file-cifs://xxxx/music/.....","radioShowMetaData":"","absoluteAlbumArtURI":"","streamInfo":"","type":"track"},"nextTrack":{"uri":"x-file-cifs://xxxxx/music/.....","title":"06 - Daylight",**"artist":"Coldplay"**,"album":"A Rush of Blood to The Head"},"volume":27,"mute":false,"trackNo":5,"elapsedTime":4,"elapsedTimeFormatted":"00:04","zoneState":"PLAYING","playerState":"PLAYING","zonePlayMode":{"shuffle":false,"repeat":false,"crossfade":false}}

**Comment by NovaGL** [comment]
what do you mean???

{"currentTrack":{"artist":"Coldplay"

It clearly does show the artist.

**Comment by ADN182** [comment]
Yes you're right.... i'm buging sorry....
