### ISSUE TITLE
Service stopping when closing terminal

### ISSUE THREAD

**Issue by nisak80** [jishi/node-sonos-http-api#196]
First let me state that I am a beginner on raspberry so might be something obvious (for you guys) that I have not done.
Installed sonos-http-api on raspberry-pi mod B and got all up and running and working controlling my Play:1 by html commands.
But as soon as I close terminal (putty) the service seems to stop.
Connecting to raspberry by putty and starting service will fix problem as long as terminal window is open.

Anyone?

**Comment by jishi** [comment]
Hi, yes that is how the terminal works in Linux. You can either run it using "screen" or "tmux" which keeps a terminal alive even when you disconnect, or use a process handler for node.js (I recommend this approach). Personally I prefer pm2, see this issue for instructions:

https://github.com/jishi/node-sonos-http-api/issues/20

**Comment by nisak80** [comment]
Excelent, thank you very much for help.
Implemented and working like a charm. Thanks for great efford making this code. Keep up the good work.
