### ISSUE TITLE
Grouping Problem if working with controller 

### ISSUE THREAD

**Issue by robertw** [jishi/node-sonos-http-api#198]
Grouping error new beta

if you call in the following order you will see what i am talking about

If I call house first office is the controller then party office still controlling the group all seems fine then call office office is removed from the group but the previous group is left without a controller since office is removed
But when you recall house the group does not rebuild itself and only players that are not grouped fro the past are grouped but the others are left out in their own group

Maybe a flag in preset called group and options if controller being removed from group ungroup 1st group before creating new preset

Just a thought 

{
    "office": {
      "players": [
        { "roomName": "Office", "volume": 30}
      ],
      "pauseOthers": true
    },
   "house": {
      "players": [
        { "roomName": "Office", "volume": 30},
        { "roomName": "Family Room", "volume": 30},
        { "roomName": "Living Room", "volume": 30},
        { "roomName": "Master Bedroom", "volume": 30},
        { "roomName": "Bathroom", "volume": 40},
        { "roomName": "Portable", "volume": 40},
	{ "roomName": "Patio", "volume": 40}
      ],
      "state": "STOP",
      "playMode": "NORMAL",
      "favorite": "Carlos Radio"
    },
    "party": {
      "players": [
        { "roomName": "Office", "volume": 30},
        { "roomName": "Family Room", "volume": 30},
        { "roomName": "Living Room", "volume": 30},
        { "roomName": "Master Bedroom", "volume": 30},
        { "roomName": "Bathroom", "volume": 40},
	{ "roomName": "Patio", "volume": 40}
      ],
      "state": "STOP",
      "favorite": "Marvin Gaye Radio",
      "playMode": "NORMAL",
      "pauseOthers": true
     },
    "hparty": {
      "players": [
        { "roomName": "Office", "volume": 30},
        { "roomName": "Family Room", "volume": 30},
        { "roomName": "Living Room", "volume": 30},
        { "roomName": "Master Bedroom", "volume": 30},
        { "roomName": "Bathroom", "volume": 40},
	{ "roomName": "Patio", "volume": 40},
        { "roomName": "Portable", "volume": 50}
      ],
      "state": "PLAYING",
      "favorite": "Thumbs up",
      "playMode": "NORMAL",
      "pauseOthers": true
    }
}

Many Thanks Robert

**Comment by jishi** [comment]
Is this the same as this? https://github.com/jishi/node-sonos-http-api/issues/192

**Comment by jishi** [comment]
Aha, this is in the new beta, missed that detail. 

Could you just describe really simple, which presets are you calling, in which order, and what is the last state?

**Comment by robertw** [comment]
Will take screen shots and details to try to help ...

**Comment by robertw** [comment]
The order is house then party then office then house afteroffice.. hope this helps
![house](https://cloud.githubusercontent.com/assets/725783/14957413/43dd2564-1053-11e6-951c-b43d4c7b99cb.jpg)
![houseafteroffice](https://cloud.githubusercontent.com/assets/725783/14957414/43de8332-1053-11e6-9896-97a5f8ad149b.jpg)
![office](https://cloud.githubusercontent.com/assets/725783/14957411/43dc2592-1053-11e6-8da1-35830fbfb839.jpg)
![party](https://cloud.githubusercontent.com/assets/725783/14957412/43dcb66a-1053-11e6-8e96-c82f09645c1f.jpg)

**Comment by jishi** [comment]
Okay, could you also provide what your expectation on the last state would be? That would be helpful.

**Comment by robertw** [comment]
since house was called it should look like the first one i would think if a controller was called in a preset 
and was already grouped that group it is coming from should be canceled and all of the players should return to std mode nothing playing and no grouping first then act on the preset  just my thought


![house](https://cloud.githubusercontent.com/assets/725783/14958817/7f48ef64-105a-11e6-9ff0-f1f8754fa9c9.jpg)

**Comment by jishi** [comment]
Could you please retry the beta and see if this is still an issue?
