### ISSUE TITLE
Find By IP

### ISSUE THREAD

**Issue by MrBeanzy** [jishi/node-sonos-http-api#199]
I dont seem to be able to find the players on my network. Is it possible to specify their IPs in the config?

**Comment by jishi** [comment]
No, unfortunately not. Have you tried adding a  `{ disableIpDiscovery: true }` to settings.json? That bypasses a feature that tries to search on all network interfaces which seems to help for certain setups.

**Comment by MrBeanzy** [comment]
Yeah i did try with and without but no joy. I can browse the status page of all the players so very off. Ill keep playing about and post what i find. Thanks Jishi

**Comment by jishi** [comment]
Explain what you are running it on and how it is connected to the network, maybe it will bring a clue on what blocks the traffic. 

The discovery that you rely on is multicast traffic which differs from regular traffic to the status pages, and some equipment tend to block it. However, if you are running official controller on the same device, it seems weird that it doesn't work.

**Comment by MrBeanzy** [comment]
@jishi Very strange, im running it from a Hyper-V VM. The Sonos controller app works fine. I got around it by using a physical machine in the end. Maybe its something to do with the visualized NIC?

**Comment by jishi** [comment]
Did you run the Sonos Controller in the same Hyper-V virtual machine? Most virtualization software run the machines using a NAT network (virtualbox, VMWare) by default, and that will definitely not work. Usually there is an option to use "bridged" network which would directly expose the virtal machine NIC to your network (thus getting an IP from your regular DHCP device).

With a quick look, it sounds like in Hyper-V terms, this is called "External". Of course, there could still be other stuff that would block traffic in Hyper-V, but this is a good start. Basically, the virtual machine should receive an IP from your physical IP range by your regular DHCP server. Hope that helps if you want to explore this route once again.
