### ISSUE TITLE
feature request: ability to play specified line-in from within a network of sonos devices

### ISSUE THREAD

**Issue by draring** [jishi/node-sonos-http-api#2]
Apologies if this is the wrong forum for feedback, but I think it would be awesome if you were able to specify a parameter set after the "play" action.  Specifically, I'm looking for a way to play a line in.

Any way, awesome utility, thanks for sharing.

**Comment by jzajac2** [comment]
Were these questions answered and I'm just missing it somewhere in the thread (or another sep. thread)?:

 'is SetAVTransportURI suppose to capitilized as such?
do I need "x-rincon-stream:" before the URI?
am i missing a parameter in the above url?"

I can't seem to get the `http://localhost:5006/Office/SetAVTTransportURI/RINCON_{MY_UUID}` to work, I just get `{"error":"action 'setavttransporturi' not found"}`

**Comment by jishi** [comment]
It is case insensitive, but you have a 'T' too much. And you need the
prefix x-rincon-stream: in order to trigger a line-in. You use
x-rincon-queue: to restore it back to queue playback.

**Comment by robertw** [comment]
Using this to set line in and not working in preset file any thoughts was working just stopped


"uri":"x-rincon-stream:RINCON_000E5822185201400"



here is preset:
{
  "players": [
    {
      "roomName": "Office",
      "volume": 20
    },
    {
      "roomName": "Family Room",
      "volume": 30
    },
    {
      "roomName": "Bathroom",
      "volume": 20
    },
    {
      "roomName": "Master Bedroom",
      "volume": 20
    },
	{
      "roomName": "Guest Room",
      "volume": 20
    },
	{
      "roomName": "Patio",
      "volume": 30
    },
    {
      "roomName": "Living Room",
      "volume": 30
    }
  ],
  "state": "PLAYING",
  "pauseOthers": false,
  "uri":"x-rincon-stream:RINCON_000E5822185201400"
}

many thanks

**Comment by jishi** [comment]
Weird. You haven't replaced your player or something like that? Or re-arranged them some way? The uri points to a UUID of a specific player, and needs to be the player you want line-in from. 

Does the manual line-in command work?
