### ISSUE TITLE
Autostart Sonos Api in a Raspberry Pi

### ISSUE THREAD

**Issue by wadoline** [jishi/node-sonos-http-api#20]
Hi

First of all I thank you for your effort.

I'm trying to autostart this API on a Raspberry Pi, but have not been successful. I can start it manually
Could you tell me how?

Best regards

**Comment by leecollings** [comment]
Hi there, I've been following these steps, and they seem to work fine without any fatal errors or anything, but after restarting the Pi, the service on port 5005 isn't running.

Is there anywhere I can go to check for errors?

Your suggestions are most welcome.

**Comment by jishi** [comment]
I've had some experiences that the pm2.dump file is cleared when rebooting for some odd reason, and I'm not alone: https://github.com/Unitech/pm2/issues/1035

However, this is not consistent, and my workaround was to run `pm2 dump` and then make the dump file immutable. You can find instructions on how to do that in that thread, but basically:

`sudo chattr +i  /your/path/to/dump.pm2`

**Comment by jishi** [comment]
I thought that they had fixed it, but apparently it is still an open issue.

**Comment by dghenderson** [comment]
Even making the pm2.dump immutable didn't help on reboot for me. Any additional suggestions?

**Comment by GregRocket** [comment]
@dghenderson The way I have been using PM2 with raspberry pi 3 works for me. After a reboot the sonos api autostarts.

cd /your/http-api/folder/
pm2 start npm -- start
pm2 save

I'm not an expert but this is how I managed to get it to work.

**Comment by jishi** [comment]
@dghenderson Did you install the startup scripts using `pm2 startup`? 

If you see the PM2 process in your process list after bootup, the startup works, but the resurrection does not. If you don't see the PM2 process at all, startup hasn't been installed correctly. 

It might identify the incorrect startup system, for a clean debian/raspbian jessie, it should be `systemd`, you can specify it manually when calling `pm2 startup systemd`. For an upgraded raspbian/debian, it might still use systemv (or more commonly known as SysV ).

**Comment by leecollings** [comment]
Just to let you guys know, I was a bit impatient saying it won't load on boot, because it took a few seconds, but I noticed the script was running after a reboot of the Pi by itself, and I was able to access the index page on port 5005.

**Comment by dghenderson** [comment]
Ah @jishi I think I did NOT do the startup scripts correctly, and needed to specify systemd. Working on reboot now, thanks! Haven't needed to keep dump.pm2 immutable either (so far).

**Comment by leecollings** [comment]
This is no longer working anymore, I did what @GregRocket  described, rebooted the Pi and the service doesn't run anymore.

Is there a solid way of autostart?

**Comment by joohann** [comment]
https://www.axllent.org/docs/view/nodejs-service-with-systemd/ 

This works for me!

**Comment by leecollings** [comment]
I'll try this, although looking at, I have no idea what to do. Can you output your terminal steps please? I have done what was listed above in this issue, but when restarting the Pi, the service is not running.

**Comment by joohann** [comment]
`sudo vim (or nano) /etc/systemd/system/sonos.service

**File**
`[Unit]
Description=server.js Sonos Server
#Requires=After=mysql.service       # Requires the mysql service to run first

[Service]
**#I'm running this from the local user I renamed pi to johann**
ExecStart=/usr/local/bin/node /home/johann/node-sonos-http-api/server.js
# Required on some systems
#WorkingDirectory=/opt/nodeserver
Restart=always
 # Restart service after 10 seconds if node service crashes
 RestartSec=10
 # Output to syslog
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=sonsos-sever
#User=<alternate user>
#Group=<alternate group>
Environment=NODE_ENV=production PORT=5005

[Install]
WantedBy=multi-user.target
`

**Enable the service**
`systemctl enable nodeserver.service`
`ls -s /etc/systemd/system/multi-user.target.wants/sonos.service /etc/systemd/system/sonos.service`

**Start the service**
`systemctl start sonos.service`

**Status the service**
`systemctl status sonos.service`

**Comment by leecollings** [comment]
@jishi Sorry, I didn't see your comment about instaling the startup scripts. I did this, which I don't remember doing before, have just rebooted, and I believe the Sonos API is running on boot now! Will do a couple more tests, but I believe I'm now sorted, thanks.

FYI I think this should be added onto the main ReadMe file
