### ISSUE TITLE
Discovery failed with Issue 77

### ISSUE THREAD

**Issue by fazworld** [jishi/node-sonos-http-api#202]
I am having the issue where the system is not finding my Sonos network.  Can you please help with this?  Would love to get this working so I can integrate my Echo with Sonos!

> sonos-http-api@0.19.0 start c:\..\node-sonos-http-api-master
> node server.js

no settings file found, will only use default settings
info: binding SSDP to port 1905
info: discovering all IPs from Ethernet
info: discovering all IPs from Wi-Fi
info: discovering all IPs from Loopback Pseudo-Interface 1
info: discovering all IPs from Teredo Tunneling Pseudo-Interface
info: relevant IPs [localhost]=null, [localhost]=null
{ [Error: Cannot find module './settings.json'] code: 'MODULE_NOT_FOUND' }
info: notification server listening on port 3500
http server listening on port 5005
no preset file, ignoring...
info: scanning for players in ip [localhost]
info: scanning for players in ip [localhost]
info: subscribing to topology [localhost]
info: using local endpoint [localhost]
No system has yet been discovered. Please see https://github.com/jishi/node-sonos-http-api/issues/77 if it doesn't resolve itself in a few seconds.
No system has yet been discovered. Please see https://github.com/jishi/node-sonos-http-api/issues/77 if it doesn't resolve itself in a few seconds.

**Comment by jishi** [comment]
Could you please describe what you are running it on (OS, version), which node version you are using, how it is connected to your network?

Maybe the output from an ifconfig or similar (if linux or OS X). 

The output seems a bit weird, it is listing names instead of IPs.

**Comment by fazworld** [comment]
Thank you for the quick reply.  I am using the following:

 

Windows 10

Connected via WiFI and Ethernet

 

Here is the output:

 

C:\Users\fazwo\Documents\node-sonos-http-api-master>npm start

 

> sonos-http-api@0.19.0 start C:\Users\fazwo\Documents\node-sonos-http-api-master

> node server.js

 

no settings file found, will only use default settings

info: binding SSDP to port 1905

info: discovering all IPs from Ethernet

info: discovering all IPs from Wi-Fi

info: discovering all IPs from Loopback Pseudo-Interface 1

info: discovering all IPs from Teredo Tunneling Pseudo-Interface

info: relevant IPs 192.168.1.5=null, 192.168.6.114=null

{ [Error: Cannot find module './settings.json'] code: 'MODULE_NOT_FOUND' }

info: notification server listening on port 3500

http server listening on port 5005

no preset file, ignoring...

info: scanning for players in ip 192.168.1.5

info: scanning for players in ip 192.168.6.114

info: subscribing to topology 192.168.6.141

info: using local endpoint 192.168.6.114

**Comment by jishi** [comment]
Well, apparently it seems to find a system considering this output:

info: subscribing to topology 192.168.6.141
info: using local endpoint 192.168.6.114

One of your Sonos devices has the IP 192.168.6.114, right? Are you saying it doesn't work after that line is outputted?

**Comment by fazworld** [comment]
One of the Sonos devices has an address of 192.168.6.141.

 

However, when I try step #4 in Ryan’s integration steps:  

4.    Test it by hitting http://yourserverip:5005/zones

Using 192.168.6.141:5005/zones OR http://192.168.1.5:5005/zones OR http://192.168.6.114:5005/zones  

 

I get a blank screen or the following error:

 

This site can’t be reached

192.168.6.141 refused to connect.

IPCONFIG:

 

C:\Users\fazwo\Documents\node-sonos-http-api-master>ipconfig

 

Windows IP Configuration

 

 

Wireless LAN adapter Local Area Connection* 2:

 

   Media State . . . . . . . . . . . : Media disconnected

   Connection-specific DNS Suffix  . :

 

Ethernet adapter Ethernet:

 

   Connection-specific DNS Suffix  . : home

   Link-local IPv6 Address . . . . . : fe80::d991:3c76:9e8d:1dda%2

   IPv4 Address. . . . . . . . . . . : 192.168.1.5

   Subnet Mask . . . . . . . . . . . : 255.255.255.0

   Default Gateway . . . . . . . . . : 192.168.1.1

 

Wireless LAN adapter Wi-Fi:

 

   Connection-specific DNS Suffix  . : home

   Link-local IPv6 Address . . . . . : fe80::496:4041:ed83:e842%3

   IPv4 Address. . . . . . . . . . . : 192.168.6.114

   Subnet Mask . . . . . . . . . . . : 255.255.255.0

   Default Gateway . . . . . . . . . : 192.168.6.1

 

Ethernet adapter Bluetooth Network Connection:

 

   Media State . . . . . . . . . . . : Media disconnected

   Connection-specific DNS Suffix  . :

 

Tunnel adapter isatap.home:

 

   Media State . . . . . . . . . . . : Media disconnected

   Connection-specific DNS Suffix  . : home

 

Tunnel adapter Teredo Tunneling Pseudo-Interface:

 

   Connection-specific DNS Suffix  . :

   IPv6 Address. . . . . . . . . . . : 2001:0:5ef5:79fd:24a3:311b:93c7:de9

   Link-local IPv6 Address . . . . . : fe80::24a3:311b:93c7:de9%4

   Default Gateway . . . . . . . . . : ::

 

 

C:\Users\fazwo\Documents\node-sonos-http-api-master>npm start

 

> sonos-http-api@0.19.0 start C:\Users\fazwo\Documents\node-sonos-http-api-master

> node server.js

 

no settings file found, will only use default settings

info: binding SSDP to port 1905

info: discovering all IPs from Ethernet

info: discovering all IPs from Wi-Fi

info: discovering all IPs from Loopback Pseudo-Interface 1

info: discovering all IPs from Teredo Tunneling Pseudo-Interface

info: relevant IPs 192.168.1.5=null, 192.168.6.114=null

{ [Error: Cannot find module './settings.json'] code: 'MODULE_NOT_FOUND' }

info: notification server listening on port 3500

http server listening on port 5005

no preset file, ignoring...

info: scanning for players in ip 192.168.1.5

info: scanning for players in ip 192.168.6.114

info: subscribing to topology 192.168.6.121

info: using local endpoint 192.168.6.114

No system has yet been discovered. Please see https://github.com/jishi/node-sonos-http-api/issues/77 if it doesn't resolve itself in a few seconds.

No system has yet been discovered. Please see https://github.com/jishi/node-sonos-http-api/issues/77 if it doesn't resolve itself in a few seconds.

 

 

Any ideas?

 

Thanks,

-Faz

**Comment by jishi** [comment]
Have you checked your firewall settings? You could start by disabling the firewall in windows 10 completely as a test. After it has subscribed to the topology, it expects a request from the Sonos player to your machine on port 3500, if that is blocked, it would not have received info about the topology.

**Comment by jishi** [comment]
No feedback, closing.

**Comment by fazworld** [comment]
Sorry for not responding sooner, but I allowed the port on the firewall and that did the trick. Thanks very much for providing this information.

However, I didn't realize that enabling this Sonos – Amazon echo integration would end up costing money (DynDns). I've decided to just use the old-fashioned method of pulling out my iPhone to control Sonos for now.

Faz
