### ISSUE TITLE
Expected statusCode 200, but got 500 on Favourites & Playlists

### ISSUE THREAD

**Issue by jhammant** [jishi/node-sonos-http-api#207]
Hey,

Currently having a few issues with this - I'm getting the message

Expected statusCode 200, but got 500

Whilst trying to play favourites/playlists - any ideas?

Log below:

on at Falcon in ~/dev/house_control/sonos_server/node-sonos-http-api on master
$ npm start

> sonos-http-api@0.19.0 start /Users/jon/dev/house_control/sonos_server/node-sonos-http-api
> node server.js

info: binding SSDP to port 1905
info: discovering all IPs from lo0
info: discovering all IPs from en0
info: discovering all IPs from awdl0
info: discovering all IPs from utun0
info: relevant IPs 10.0.1.150=null
info: notification server listening on port 3500
http server listening on port 5005
no preset file, ignoring...
info: scanning for players in ip 10.0.1.150
info: subscribing to topology 10.0.1.62
info: using local endpoint 10.0.1.150
Initializing player Living Room
Initializing player Nursery
Initializing player Master Bedroom
debug: emitting group-volume
debug: emitting group-volume
^[[A^[[Aerror: error when fetching favorites
Expected statusCode 200, but got 500
^[[AExpected statusCode 200, but got 500
Expected statusCode 200, but got 500
error: error when fetching favorites

(other window)

$ curl "http://localhost:5005/Nursery/favorite/Dawn"
jon at Falcon in ~
$ curl "http://localhost:5005/Nursery/playlist/test
→
→
jon at Falcon in ~
$ curl "http://localhost:5005/Nursery/playlist/test"
jon at Falcon in ~
$ curl "http://localhost:5005/Nursery/playlist/test"
jon at Falcon in ~
$
jon at Falcon in ~
$
jon at Falcon in ~
$ curl "http://localhost:5005/Nursery/playlist/test"
jon at Falcon in ~
$ curl "http://localhost:5005/Nursery/favorite"
jon at Falcon in ~

**Comment by jishi** [comment]
Does any other actions work? Seems like the Browse command fails for you, without seeing the request payload, it would be hard to say what is wrong.

**Comment by jhammant** [comment]
Play/pause and volume seem to work (and other basic stuff) - however anything playlist based seems to not.

Anyway I can dump the request payload?

**Comment by jishi** [comment]
You could try running `tcpdump -A -s 0 'tcp port 1400'` right before you send a playlist action, it should give you the HTTP headers and body of the request in plain text.

**Comment by jhammant** [comment]
Dump below from wireshark:

POST /MediaServer/ContentDirectory/Control HTTP/1.1
CONTENT-TYPE: text/xml; charset="utf-8"
SOAPACTION: "urn:schemas-upnp-org:service:ContentDirectory:1#Browse"
CONTENT-LENGTH: 389
Host: 10.0.1.63:1400
Connection: close

<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><u:Browse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"><ObjectID></ObjectID><BrowseFlag>BrowseDirectChildren</BrowseFlag><Filter /><StartingIndex></StartingIndex><RequestedCount></RequestedCount><SortCriteria /></u:Browse></s:Body></s:Envelope>HTTP/1.1 500 Internal Server Error
CONTENT-LENGTH: 347
CONTENT-TYPE: text/xml; charset="utf-8"
EXT: 
Server: Linux UPnP/1.0 Sonos/32.10-28251-DaftPunk (ZPS3)
Connection: close

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>701</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>

**Comment by jhammant** [comment]
Vs a dump from the sonos app
````
POST /MediaRenderer/AVTransport/Control HTTP/1.1
CONNECTION: close
ACCEPT-ENCODING: gzip
HOST: 10.0.1.63:1400
USER-AGENT: Linux UPnP/1.0 Sonos/32.10-28251-DaftPunk (MDCR_x86_64_MacBookPro11,1)
CONTENT-LENGTH: 1104
CONTENT-TYPE: text/xml; charset="utf-8"
X-SONOS-BUILDTYPE: alpha
X-SONOS-TARGET-UDN: uuid:RINCON_B8E937D939AC01400
SOAPACTION: "urn:schemas-upnp-org:service:AVTransport:1#AddURIToQueue"

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:AddURIToQueue xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><InstanceID>0</InstanceID><EnqueuedURI>file:///jffs/settings/savedqueues.rsq#0</EnqueuedURI><EnqueuedURIMetaData>&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;SQ:0&quot; parentID=&quot;SQ:&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Baby_sleep&lt;/dc:title&gt;&lt;upnp:class&gt;object.container.playlistContainer&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;RINCON_AssociatedZPUDN&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;</EnqueuedURIMetaData><DesiredFirstTrackNumberEnqueued>0</DesiredFirstTrackNumberEnqueued><EnqueueAsNext>1</EnqueueAsNext></u:AddURIToQueue></s:Body></s:Envelope>HTTP/1.1 200 OK
CONTENT-LENGTH: 382
CONTENT-TYPE: text/xml; charset="utf-8"
EXT: 
Server: Linux UPnP/1.0 Sonos/32.10-28251-DaftPunk (ZPS3)
Connection: close

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:AddURIToQueueResponse xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><FirstTrackNumberEnqueued>1</FirstTrackNumberEnqueued><NumTracksAdded>13</NumTracksAdded><NewQueueLength>13</NewQueueLength></u:AddURIToQueueResponse></s:Body></s:Envelope>
````

**Comment by jishi** [comment]
Are you running node 6 by any chance?

**Comment by jhammant** [comment]
Yes 6.2.0

Worth downgrading?

**Comment by jhammant** [comment]
perfect - downgraded to 4.4.4 and working perfectly! 

thanks very much for the help!

**Comment by jishi** [comment]
I thought that I had fixed this in the current verison, but apparently I only fixed it in beta. Glad that it got resolved. Will support 6.x from beta and onwards.
