### ISSUE TITLE
Presets playMode and State not working

### ISSUE THREAD

**Issue by GregRocket** [jishi/node-sonos-http-api#210]
I thought I'd just start a new thread on this issue.

If I have this in my preset.json the server will not load.
"playMode": {
      "repeat": true,
      "shuffle": true
    }

**and/or**

"state": "PLAYING",

**Comment by jishi** [comment]
It's "state":"play" nowadays, but play is the default.

I think there is an issue with shuffle/repeat if a radio station is playing
while applying a preset.

**Comment by GregRocket** [comment]
I tried suffle/repeat with just an mp3 playlist preset and 'npm start' would crash when loading.

I tried with just "state":"play" with same result. If I remove these then playlist works.

**Console Error:**
root@minibian:~/node-sonos-http-api-beta# npm start
> sonos-http-api@1.0.0-beta.9 start /root/node-sonos-http-api-beta
> node server.js
sending M-SEARCH...
http server listening on port 5005
module.js:427
    throw err;
    ^
SyntaxError: /root/node-sonos-http-api-beta/presets.json: Unexpected token ]
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:424:27)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /root/node-sonos-http-api-beta/lib/actions/preset.js:28:17
    at FSReqWrap.cb [as oncomplete] (fs.js:212:19)

npm ERR! Linux 4.4.9-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.3.2
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@1.0.0-beta.9 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sonos-http-api@1.0.0-beta.9 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sonos-http-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /root/node-sonos-http-api-beta/npm-debug.log

**Comment by jishi** [comment]
But that error looks like your presets.json is invalid syntax though

**Comment by GregRocket** [comment]
Below is my preset.json for this test. It has only one entry. 

If I remove   "playMode": {  "repeat": true,  "shuffle": true } the preset works.

{
    "today's hits": {
      "players": [
        { "roomName": "Hall Bathroom", "volume": 40},
		{ "roomName": "Master Bedroom", "volume": 50},
		{ "roomName": "Ladies Room", "volume": 50},		
		{ "roomName": "Master Bathroom", "volume": 50},
		{ "roomName": "Media Room", "volume": 50},
		{ "roomName": "Office", "volume": 20}
      ],	
      "favorite": "Today's Hits",
      "uri": "x-rincon-stream:RINCON_0000000000001500",
      "playMode": {
      "repeat": true,
      "shuffle": true
      }
      "pauseOthers": true
    }
}

**Comment by jishi** [comment]
Yeah, you are missing a comma before "pauseOthers" :)

It's always good to run it through an online json-parser to validate the
syntax,thsy really helps.

**Comment by GregRocket** [comment]
OK thanks. I'll be sure to learn and use a json-parser. I put the common in and it worked.
