### ISSUE TITLE
Ungrouping Function 

### ISSUE THREAD

**Issue by robertw** [jishi/node-sonos-http-api#216]
One ask could we get a ungroup function to destroy all groups or selected
group by preset name maybe?

**Comment by jishi** [comment]
It wouldn't be hard to do, but I'm not really seeing the usefulness of it for the general mass. What is your intended use of it?

**Comment by jishi** [comment]
Could you provide a use case for this please? Otherwise I will go ahead and close this one.

**Comment by robertw** [comment]
Sorry have been away example if you want to reset your whole system to return all players to a normal state thus allowing a clean start used for scripting or easy turnoff af allplayers upon leaving home etc like the deselect  group function in sonos app thus turning off all players 

Many Thanks

**Comment by jishi** [comment]
No worries.

I feel like scripting should work regardless of state, unless you are using some 3rd party library that would brake unless otherwise? 

And regarding stopping playback, you can still issue a /pauseall for that, ungrouping everything for that seems a bit crude. I'm still not convinced this is a good feature, but if you need it, I can provide you with a file that you could drop in your actions-folder.

**Comment by robertw** [comment]
many thanks for your consideration and if you can that would be amazing

Regards

Robert

On Tue, Jun 7, 2016 at 9:21 AM, Jimmy Shimizu <notifications@github.com>
wrote:

> No worries.
>
> I feel like scripting should work regardless of state, unless you are
> using some 3rd party library that would brake unless otherwise?
>
> And regarding stopping playback, you can still issue a /pauseall for that,
> ungrouping everything for that seems a bit crude. I'm still not convinced
> this is a good feature, but if you need it, I can provide you with a file
> that you could drop in your actions-folder.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jishi/node-sonos-http-api/issues/216#issuecomment-224278175>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAsTF1q3gaPcD2_htiOsdKtcrA-y3_QBks5qJXBtgaJpZM4Iozvd>
> .
>



-- 
Regards

Robert

**Comment by jishi** [comment]
Here you go, add this to a file called whatever (ungroupall.js or something) and drop it into the lib/actions folder:

```
'use strict';
const logger = require('sonos-discovery/lib/helpers/logger');
let system;

function ungroupAll() {
  return system.players.reduce((promise, player) => {
    return promise.then(() => player.becomeCoordinatorOfStandaloneGroup()
      .catch((err) => {
        // mitigate any errors that occurs.
        logger.warn(err);
      }))
  }, Promise.resolve());
}

module.exports = function (api) {
  api.registerAction('ungroupall', ungroupAll);
  system = api.discovery;
};
```
