### ISSUE TITLE
I cannot get any presets to run, but I can send commands via the browser

### ISSUE THREAD

**Issue by RickStirling** [jishi/node-sonos-http-api#218]
If I send any commands to the server via the browser, they work, such as:

http://localhost:5005/office/favorite/games
http://localhost:5005/office/volume/20

I can hear the music playing and see the volume change in the Sonos app.

However, I can't get ANYTHING to run via presets.json. I've validated the json too.

{
    "test": {
      "players": [
        {"roomName": "Office", "volume": 60},
        {"roomName": "Den", "volume": 10}
      ],
      "state": "PLAYING",
      "favorite": "games",
      "uri": "x-rincon-stream:RINCON_0000000000001500",
      "playMode": "SHUFFLE",
      "pauseOthers": true
    },
  "groupall": {
    "players": [
      {"roomName": "Bathroom Connect","volume": 10},
      {"roomName": "Den", "volume": 10},
      {"roomName": "Office","volume": 10},
      {"roomName": "Master Bedroom", "volume": 10},
      {"roomName": "Living Room","volume": 15}
    ],
    "pauseOthers": true,
    "playMode": "NORMAL"
  }
}

Running OSX, I have presets.json in the same folder as server.js and package.json

In the web browser, all I see after trying a preset is this:

[]

Which is the same thing I get if I try to run a preset that doesn't exist.

The console log has no updates when I try to run a preset, but if I play a favourite, playlist or even a spotify URL I get those details in the console.

**Comment by RickStirling** [comment]
OK, so.....


You can't edit presets AFTER you've started the server.

I have some suggestions for the documentation page:





presets.json

You can create a file with pre made presets, called presets.json. This file should live in the same folder as server.js. This file is parsed on startup - to load changes you will need to restart the server.

Most errors in the presets are due to bad formatting. Please validate the .json file - there are several online services that will do this. 






Also, it might be useful have a /reloadpresets/ command that allows people to edit the presets on the fly.

**Comment by jishi** [comment]
Good point. I have been thinking about having a file watch that would
reload upon change, but haven't had the time. It could probably be helpful
to have edit functionality in the browser as well.

**Comment by jishi** [comment]
I have updated documentation for beta branch, closing this.
