### ISSUE TITLE
Webhook: I'm not getting any transport-state events

### ISSUE THREAD

**Issue by agawley** [jishi/node-sonos-http-api#219]
I get events for topology-change as expected but have not seen any transport-state updates. What events on the system are supposed to fire that? I was hoping to get a notification each time the track changed on any player on the system.

**Comment by agawley** [comment]
I'm using the beta branch

**Comment by jishi** [comment]
Yes, that functionality got lost in the beta rewrite, but I was working on
that yesterday and is almost done, will release it within a day or two.

And yes, that is exactly how it will work, so your assumption was correct
:)

**Comment by jplourde5** [comment]
With Apple Music behind me, I’m working on two additional capabilities that I want for Pandora and SiriusXM.

Question:  Can your browse function be used to browse a user’s Pandora account or SiriusXM account?  I think that the answer is no, but the Pandora API will take some time to build for Promises and I want to make sure that the browse can’t do it before I head down that path.


Another question.  I actually have SXM working using brute force to build a hard coded array holding the needed channel information used in a siriusXM.js function that I built.  I needed to incorporate the Fuse npm for a fuzzy search on the channel descriptions.  Would you be opposed to adding the Fuse module to your solution?  It will be useful for any other fuzzy searches that may be needed.


[cid:image001.gif@01D1BB2A.520EFEB0]<http://www.infor.com/>

Jim Plourde | VP Cloud Services
mobile: 864.270.7677 | office: 864.546.5089 | jim.plourde@infor.com<mailto:jim.plourde@infor.com> | http://www.infor.com<http://www.infor.com/>

**Comment by jishi** [comment]
It's a correct assumption that the browse function doesn't work with music services. A few music services is possible to authenticate against using collectable data, but they are few (Basically, the ones still using username/password authentication, IIRC). I have yet to figure out the encryption scheme for the account tokens (and I haven't spent much time on it). 

I'm okay with adding fuse, seems to have 0 dependencies so it won't clutter the project that much. Are you able to search siriusXM without authenticating?

**Comment by jishi** [comment]
Oh, and please create new issues so we don't bother other people when replying.

**Comment by agawley** [comment]
Thanks! Really excited for this update. BTW - this library is great. Well done.

**Comment by jishi** [comment]
This should be fixed now, please try it out and let me know if you have any improvement suggestions. Today you only get the UUID of the players. That might not be the most user friendly kind of data, maybe room name would be helpful as well.

**Comment by agawley** [comment]
It works great. Modulo the other issue I raised about the correct content header not being set.
