### ISSUE TITLE
TTS say command not playing

### ISSUE THREAD

**Issue by ahielg** [jishi/node-sonos-http-api#223]
Installed on RPi3 nodeJs v6.2, the file created fine (I can play it) but sonos not playing it.
running this command: 
http://192.168.1.12:5005/kitchen/say/This%20is%20a%20test/en-us
Logs:
> sonos-http-api@0.19.0 start /home/user/sonos
> node server.js

info: binding SSDP to port 1905
info: discovering all IPs from lo
info: discovering all IPs from wlan0
info: relevant IPs 192.168.1.12=null
info: notification server listening on port 3500
http server listening on port 5005
no preset file, ignoring...
info: scanning for players in ip 192.168.1.12
info: subscribing to topology 192.168.1.14
info: using local endpoint 192.168.1.12
Initializing player Kitchen
debug: emitting group-volume
Using cached tts message file: 65d725119a670a24dd0ffd022dae16aac386efc2-en-us.mp3
info: applying preset players=[roomName=Kitchen, volume=40], state=playing, playMode=NORMAL, uri=http://192.168.1.12:5005/tts/65d725119a670a24dd0ffd022dae16aac386efc2-en-us.mp3
debug: ungrouping Kitchen to prepare for grouping
STOPPED
STOPPED
debug: emitting group-volume

Thanks ahead.

**Comment by jishi** [comment]
There are still some quirks with node 6+. Please try with node 4 or 5
instead.

And also try the beta branch instead, the say functionality is a lot more
robust in that version.
