### ISSUE TITLE
Beta: Webhook: Request does not set application/json as Content-Type

### ISSUE THREAD

**Issue by agawley** [jishi/node-sonos-http-api#229]
I notice that on line 113 of sonos-http-api you set `json: true` but that parameter is not parsed in sonos-discovery/lib/helpers/request.js so the Content-Type header is not set. This causes Express middleware like body-parser to fail. By the looks of the request library, that `json: true` line should be replaced by:

`headers: { 'Content-Type': 'application/json' }`

I have confirmed this fixes the issue.

**Comment by jishi** [comment]
Nice observation, totally slipped my mind. Thank you for investigating and suggesting that simple fix!
