### ISSUE TITLE
Beta: Spotify: Internal server error on spotify/now

### ISSUE THREAD

**Issue by agawley** [jishi/node-sonos-http-api#232]
If I try to hit: `/kitchen/spotify/now/spotify:track:44lgx472S5WgeF7N7p52F7`

I get:

```
{
status: "error",
error: "Error: Internal Server Error at ClientRequest.<anonymous> (/home/pi/Code/EchoSonos/node-sonos-http-api/node_modules/sonos-discovery/lib/helpers/request.js:22:21) at ClientRequest.g (events.js:273:16) at emitOne (events.js:90:13) at ClientRequest.emit (events.js:182:7) at HTTPParser.parserOnIncomingClient (_http_client.js:469:21) at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23) at Socket.socketOnData (_http_client.js:359:20) at emitOne (events.js:90:13) at Socket.emit (events.js:182:7) at readableAddChunk (_stream_readable.js:153:18) at Socket.Readable.push (_stream_readable.js:111:10) at TCP.onread (net.js:534:20)"
}
```

**Comment by jishi** [comment]
I can not reproduce this. Do you get any more errors in the console? 

Could you please tell me the name of the token for spotify if you check this page of one of your players:

`http://[ip of player]:1400/status/accounts`

the UN column, for service type 2311 or perhaps 3079.

**Comment by agawley** [comment]
Service 3079 has two entries:

X_#Svc3079-0-Token
and
X_#Svc3079-6a50ffb8-Token

**Comment by jishi** [comment]
Okay, that's it then. This requires discovery of added services to be in place before I can adjust Spotify accordingly, right now it is hard-coded for EU only.

**Comment by jishi** [comment]
If you want to fix it temporarily, you can manually change in the XML snippet in lib/actions/spotify.js and replace 2311 with 3079 for now. It will always use the account associated with token `X_#Svc3079-0-Token` though, but maybe that's fine. Otherwise you can use the other token. There is no way to specify which account that should be used right now.

**Comment by agawley** [comment]
Ah got it! Thanks.

**Comment by jishi** [comment]
Tip, if you don't want it to be overwritten everytime you update, you could just copy it to another file and change the action name to "spotify_us" or something
