### ISSUE TITLE
Echo Dot?

### ISSUE THREAD

**Issue by smwilson** [jishi/node-sonos-http-api#239]
Hi, just a real quick question. I've started putting this together and am having a modicum of success. I do not yet own an Echo or Echo Dot. Since I'm not interested in the Echo speaker, I just want to make sure that this implementation will work with the Echo Dot.

Thanks,
Susan

**Comment by jishi** [comment]
I have no idea, you are better of asking that question at the echo-sonos
repository. I don't own any echo either, they have used my library for the
sonos part only :)

**Comment by smwilson** [comment]
Okay. Thanks jishi.

**Comment by smwilson** [comment]
You are awesome, dude. Us older folks just trying to keep up.
Susan

> On Jun 10, 2016, at 2:51 PM, Jimmy Shimizu <notifications@github.com> wrote:
> 
> I have no idea, you are better of asking that question at the echo-sonos
> repository. I don't own any echo either, they have used my library for the
> sonos part only :)
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/jishi/node-sonos-http-api/issues/239#issuecomment-225292411>, or mute the thread <https://github.com/notifications/unsubscribe/AG0wlloyTt8BwEVI8RKaVIZlvZuawEWAks5qKc5TgaJpZM4IzUHL>.
> 

“ Education is that which remains when one has forgotten everything he learned in school. ”
— Albert Einstein
