### ISSUE TITLE
Spotify now/next/queue actions not working

### ISSUE THREAD

**Issue by ereesman** [jishi/node-sonos-http-api#240]
I have reviewed the previous issue opened for this topic here: https://github.com/jishi/node-sonos-http-api/issues/137 - and I am still unable to get this working (tried the metadataTemplate change X_#Svc3079-0-Token)
Here's my uri + metadata log: 
`x-sonos-spotify:spotify%3Atrack%3A63WdJvk8G9hxJn8u5rswNh?sid=9&flags=32&sn=1<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="00030020spotify%3Atrack%3A63WdJvk8G9hxJn8u5rswNh" restricted="true"><upnp:class>object.item.audioItem.musicTrack</upnp:class><desc id="cdudn" nameSpace="urn:schemas-rinconnetworks-com:metadata-1-0/">SA_RINCON3079_X_#Svc3079-0-Token</desc></item></DIDL-Lite>`

I am unable to use spotify now/next/queue actions such as:

http://localhost:5005/living%20room%202/spotify/now/spotify:track:6PBZN8cbwkqm1ERj2BGXJ1

Basic debugging didn't expose and useful error messages or exceptions. Any guidance would be extremely appreciated.

**Comment by jishi** [comment]
Hm, right, forgot to tell you that the sid-parameter for the uri needs to be changed from 9, to 12 I think. Please try that and see if it works (the sid is the servce ID, which correlates to the 3079 which also is the service ID but with some extra stuff padded to it)

**Comment by jplourde5** [comment]
Also be aware that the sid for some services can vary from region to region. The easiest way that I have found to check it is to add a Sonos Favorite for the service and see what it is.  Also, if the sid is different, the service type code will be different also. The type = sid X 256 + 7

**Comment by jishi** [comment]
This is fixed in the latest master, I lookup the sid and type id automatically

**Comment by jplourde5** [comment]
How do you lookup the valid SID?  Accounts?  If so, how would you know which entry is for Spotify?

Just checking to see if I can use it for the same purpose in musicSearch.
