### ISSUE TITLE
Group Command / Multiple groups ? 

### ISSUE THREAD

**Issue by robertw** [jishi/node-sonos-http-api#243]
I am not seeing the ability  to select which group to use the group commands example I have 3 presets running 3 groups and I want to mute one or raise the vol using the group vol command is there a way?

I have to say the activity and work everyone is putting in is amazing and I want to thank all for supporting all of Jimmy amazing hard work.......Thank You!

**Comment by jishi** [comment]
Everytime you invoke an action against any player in a group, you will affect the coordinator (whole group) except for volume calls and mute. Those have corresponding groupvolume/groupmute actions, that will affect the whole group.

My thought was that a call is usually correlated to a single player (think, physical buttons in a room, scenery functions etc), so it made sense to build it this way.

Does that answer your question?

**Comment by robertw** [comment]
I am sorry

If i have 2 presets called one bedroom which has 3 players playing jazz

and another called outside 4 players playing rock

and i want to increase the vol the bedroom group how would i call the vol
function

if i understand i would just call the vol to any player in the group and it
will default to the coordinator of the group and act as a group vol call


Am i understanding right?



On Tue, Jun 21, 2016 at 6:48 AM, Jimmy Shimizu <notifications@github.com>
wrote:

> Everytime you invoke an action against any player in a group, you will
> affect the coordinator (whole group) except for volume calls and mute.
> Those have corresponding groupvolume/groupmute actions, that will affect
> the whole group.
>
> My thought was that a call is usually correlated to a single player
> (think, physical buttons in a room, scenery functions etc), so it made
> sense to build it this way.
>
> Does that answer your question?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jishi/node-sonos-http-api/issues/243#issuecomment-227405122>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAsTFx3o25cPJMfHEpyNrU5UGhbcJ-NCks5qN8GSgaJpZM4I6Qt4>
> .
>



-- 
Regards

Robert

**Comment by jishi** [comment]
Yes, if you have a player in that group called "Bedroom", just do:

/Bedroom/groupvolume/+5

to raise all players in that group with 5%

When you think in the concepts of "presets", it becomes a bit diffuse since it will not enforce a preset, you always act on a group, and that group might have changed from that preset.

**Comment by robertw** [comment]
Thank you! Got it.....

On Tue, Jun 21, 2016 at 8:11 AM, Jimmy Shimizu <notifications@github.com>
wrote:

> Yes, if you have a player in that group called "Bedroom", just do:
>
> /Bedroom/groupvolume/+5
>
> to raise all players in that group with 5%
>
> When you think in the concepts of "presets", it becomes a bit diffuse
> since it will not enforce a preset, you always act on a group, and that
> group might have changed from that preset.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jishi/node-sonos-http-api/issues/243#issuecomment-227420955>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAsTF0hf9qSgcMmbcqG2ouuWY6f18BeRks5qN9TUgaJpZM4I6Qt4>
> .
>



-- 
Regards

Robert
