### ISSUE TITLE
beta(latest): error on isolate command

### ISSUE THREAD

**Issue by kshartman** [jishi/node-sonos-http-api#245]
https://example.com:5005/shanesoffice/isolate gets error.  Using auth and https. 

{"status":"error","error":"Error: Internal Server Error\n    at ClientRequest.<anonymous> (/usr/local/src/beta/node_modules/sonos-discovery/lib/helpers/request.js:22:21)\n    at ClientRequest.g (events.js:260:16)\n    at emitOne (events.js:77:13)\n    at ClientRequest.emit (events.js:169:7)\n    at HTTPParser.parserOnIncomingClient (_http_client.js:430:21)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)\n    at Socket.socketOnData (_http_client.js:320:20)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:153:18)\n    at Socket.Readable.push (_stream_readable.js:111:10)\n    at TCP.onread (net.js:531:20)"}

Log:

undefined
Error: Internal Server Error
    at ClientRequest.<anonymous> (/usr/local/src/beta/node_modules/sonos-discovery/lib/helpers/request.js:22:21)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:430:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at Socket.socketOnData (_http_client.js:320:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)

Topology: ShanesOffice is a stereo pair.  Not a coordinator.  

Ubuntu 14.04.  Node 4.4.5

**Comment by kshartman** [comment]
I think this what it was doing:

{"method":"POST","path":"/MediaRenderer/AVTransport/Control","host":"192.168.4.64","port":1400,"headers":{"CONTENT-TYPE":"text/xml; charset=\"utf-8\"","SOAPACTION":"\\
"urn:schemas-upnp-org:service:AVTransport:1#SetPlayMode\"","CONTENT-LENGTH":301}}

**Comment by jishi** [comment]
The isolate shouldn't send such an action, but the action it takes when the player is not a coordinator seems a bit wonky. I will have to do some digging to see what the expected action is. I would think that restoring the queue is a more sane option, not trying to group it to itself...

**Comment by kshartman** [comment]
Well this code

function isolate(player) {
  if (player.coordinator == player) {
    return player.becomeCoordinatorOfStandaloneGroup();
  } else {
    return attachTo(player, player);
  }
}

in group.js is called when it the isolate request determines that the player is not a coordinator.  So it is trying to attach to itself.  The issue, I think, is that in this case, the payer named ShanesOffice is a member of a stereo pair (and there are two players named ShanesOffice with different IP addresses because they each use the name of the pair).  The behavior I observe when I issue the isolate command is that one of the players stops playing briefly, then it resumes playing as a pair member.  The isolate command fails and you get the exception above.

**Comment by kshartman** [comment]
https://github.com/gotwalt/sonos/blob/master/lib/sonos/endpoint/a_v_transport.rb says that code like this will fail on a stereo pair. So far I haven't found how you DO handle a stereo pair.

  # Add another speaker to this group.
  # Trying to call this on a stereo pair slave will fail.
  def group(slave)
    slave.join(self)
  end

  # Ungroup from its current group.
  # Trying to call this on a stereo pair slave will fail.
  def ungroup
    parse_response send_transport_message('BecomeCoordinatorOfStandaloneGroup')
  end

**Comment by jishi** [comment]
The slave speaker of a stereopair is ignored in my system, so it should
never try and send any commands to it. Are you saying that it does work on
a non stereopair speaker?

**Comment by kshartman** [comment]
Yes it works correctly on non stereo-pairs.

**Comment by kshartman** [comment]
This could be related. It would be nice if the sonos UPNP protocol was documented ;0


https://github.com/gotwalt/sonos/pull/52

commands in AVTransport are sent to the group master by default. this is correct for most commands, like play for example. sending the ungroup command to the master results in removing the master from the group instead of the referenced speaker.

I guess it is also open for discussion if other commands are falsely sent to the master. 
Might also fix #46 since the party_mode does a party_over which does not properly ungroup the existing speakers.

**Comment by jishi** [comment]
Took a look on this, got the same error as you (probably only worked for coordinators before). Anyway, calling becomeCoordinatorOfStandaloneGroup() actually restores the radio or queue that was active prior to grouping, as expected.
