### ISSUE TITLE
When REPEAT ON, SHUFFLE also put ON

### ISSUE THREAD

**Issue by Home-Control9000** [jishi/node-sonos-http-api#246]
Hi Jimmy,

When REPEAT ON, SHUFFLE is also put ON.
If REPEAT is ON i cant put SHUFFLE OFF. 
Installed latest beta.
I can test more if you want.

Thanks,
Walter

**Comment by jishi** [comment]
I'm aware of some discrepancy in the playmodes, I'm evaluating different
options. Thanks for reporting though.

**Comment by Home-Control9000** [comment]
Hi Jimmy,

If you need testing please ask me.

Thanks,
Walter

**Comment by jishi** [comment]
I can no longer reproduce this. Please re-open if this still occurs.

**Comment by Home-Control9000** [comment]
Hi Jimmy,

The problem is solved. I test it in my production system and now the 
shuffle and repeat are responding as it should be.
Thanks for your effort!

Beste regards,

Walter

Op 26-11-16 om 15:00 schreef Jimmy Shimizu:
