### ISSUE TITLE
WebHook trigger on volume change

### ISSUE THREAD

**Issue by HubertusH** [jishi/node-sonos-http-api#247]
i work with the webhook and openhab - very fine - but is it posible to get a post from the webhook if the volume is changed? Thank you

**Comment by jishi** [comment]
Hi, this has been added recently for the beta. Are you running the beta or are you using the master branch?

There are a few differences between the beta and the master version, just so you know. But most of the actions are identical.

**Comment by HubertusH** [comment]
Hi,

 

i think i use the master – where can i found the beta so i can test it.

 

Thank you

**Comment by jishi** [comment]
Just checkout the beta branch and do the usual npm installation process, or get the downloadable zip from here: https://github.com/jishi/node-sonos-http-api/archive/beta.zip

**Comment by HubertusH** [comment]
Thank you jishi, i found, download and install it - and the volume change is triggered. Perfekt!
