### ISSUE TITLE
How Autostart in Raspbian Jessie

### ISSUE THREAD

**Issue by IsaTTeN** [jishi/node-sonos-http-api#248]
Hi!

I need some help for autostart de NPM START in my Raspbian Jessie. I have working the http-api but I dont know how to autostart it if, for example, a power failure ocurrs.

I saw that there is a docker file but I dont know how to use it.

Any help will be apreciated

Best regards

**Comment by jishi** [comment]
Hi, you could try this: https://github.com/jishi/node-sonos-http-api/issues/20

jessie uses systemd, which changed from the previous version, so you should probably specify "systemd" as parameter to `npm startup systemd`

**Comment by IsaTTeN** [comment]
No luck!

I tryed with `pm2 startup systemd` and `sudo pm2 startup systemd -u pi`

But it doesnt startup

**Comment by GregRocket** [comment]
Try
pm2 start npm --start

Then to auto start 
pm2 save

Stop service
pm2 delete 0

**Comment by jishi** [comment]
Did you really follow all steps?

**Comment by GregRocket** [comment]
Daemonize App:
pm2 start npm -- start

Then to Auto Start:
pm2 save
