### ISSUE TITLE
Is it possible to have the api sending a response to a command

### ISSUE THREAD

**Issue by wmn79** [jishi/node-sonos-http-api#249]
I am wondering if it is possible to have the api send a response (can be as simple as 'OK') when a command is received? 

The reason I am asking this is that I am using the node-sonos-http-api in combination with Domoticz, a home automation program, and everytime Domoticz sends a Http command to the api I get an error in my Domoticz log while the command is executed (Sonos starts playing for example). Apparently this is due to the fact that Domoticz does not get a response on the command and therefore thinks is fails.

This link gives some more info on the issue: https://www.domoticz.com/forum/viewtopic.php?f=6&t=10211
This link gives some more info on my setup: https://www.domoticz.com/forum/viewtopic.php?f=38&t=10940

Thanks!

**Comment by jishi** [comment]
Hi, try the new beta branch, this one includes a change so I always send back a JSON response object on every request. This version also waits for any TTS or preset action to finish completely before ending the request, which is useful if you want to chain actions yourself.

**Comment by jishi** [comment]
It is almost identical API-wise to the old version. There are a few small differences and one or two actions that aren't implemented yet (sleep, is one of them)

**Comment by wmn79** [comment]
Thanks, I'll look into it this weekend!
