### ISSUE TITLE
TTS not working

### ISSUE THREAD

**Issue by autofrank** [jishi/node-sonos-http-api#251]
Hi
Great api.. thanks 
Sorry for posting in a issue tab but I didn't see anywhere for a question.

I am trying to get the TTS working. All other aspects of the node-http-api are working okay
the api is installed on a RPi. My version is V0.19.0 from the package.json file

I created the settings.json file ( in the same folder as the server.js file)
it just contains { "voicerss": "my api key" }

I used the following to check that voicerss is working and it is
http://api.voicerss.org/?key=3faeef39d33a40748cc65d8ce7525410&f=22khz_16bit_mono&hl
=en-gb&src=This%20is%20a%20test

.....but when I run  http://192.168.1.89:5005/bed5_office/say/hello 

all I get is the message " you need to register an api key to use the feature...."
If I remove the last 4 chars of the api key in the settings.json file, I get the same behaviour, no errors, just the "recorded message"

I'm sure I'm doing something basic wrong but cannot see how to fix
Any suggestions ?

Thanks
Frank

**Comment by jishi** [comment]
Could you attach the output from the console when you start the api?

I would also suggest that you test the beta branch of the api.

**Comment by autofrank** [comment]
Thanks
I'm using putty to connect and running the Pi headless (it's in my mech room in the rack) so when I reboot the Pi the api start sequence is complete before I can connect/capture
Is there a way to restart your api without restarting the Pi ?

**Comment by autofrank** [comment]
found it (npm start)

console output as follows

`pi@raspberrypi:~/node-sonos-http-api $ npm start

> sonos-http-api@0.19.0 start /home/pi/node-sonos-http-api
> node server.js

info: binding SSDP to port 1905
info: discovering all IPs from lo
info: discovering all IPs from eth0
info: relevant IPs 192.168.1.89=null
error: port in use 3500 trying new one
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::5005
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at Object.<anonymous> (/home/pi/node-sonos-http-api/server.js:95:8)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

npm ERR! Linux 4.4.11-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@0.19.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sonos-http-api@0.19.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/node-sonos-http-api/npm-debug.log
`

Thanks

**Comment by autofrank** [comment]
npm-debug.log contents

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart sonos-http-api@0.19.0
6 info start sonos-http-api@0.19.0
7 verbose unsafe-perm in lifecycle true
8 info sonos-http-api@0.19.0 Failed to exec start script
9 verbose stack Error: sonos-http-api@0.19.0 start: `node server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid sonos-http-api@0.19.0
11 verbose cwd /home/pi/node-sonos-http-api
12 error Linux 4.4.11-v7+
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.0.0
15 error npm  v2.14.2
16 error code ELIFECYCLE
17 error sonos-http-api@0.19.0 start: `node server.js`
17 error Exit status 1
18 error Failed at the sonos-http-api@0.19.0 start script 'node server.js'.
18 error This is most likely a problem with the sonos-http-api package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server.js
18 error You can get their info via:
18 error     npm owner ls sonos-http-api
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
`

**Comment by jishi** [comment]
You need to stop the background task, it errors out because the api port is
occupied so we don't see the real output

**Comment by autofrank** [comment]
npm-debug.log contents

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart sonos-http-api@0.19.0
6 info start sonos-http-api@0.19.0
7 verbose unsafe-perm in lifecycle true
8 info sonos-http-api@0.19.0 Failed to exec start script
9 verbose stack Error: sonos-http-api@0.19.0 start: `node server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid sonos-http-api@0.19.0
11 verbose cwd /home/pi/node-sonos-http-api
12 error Linux 4.4.11-v7+
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.0.0
15 error npm  v2.14.2
16 error code ELIFECYCLE
17 error sonos-http-api@0.19.0 start: `node server.js`
17 error Exit status 1
18 error Failed at the sonos-http-api@0.19.0 start script 'node server.js'.
18 error This is most likely a problem with the sonos-http-api package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server.js
18 error You can get their info via:
18 error     npm owner ls sonos-http-api
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by autofrank** [comment]
Sorry, somewhat new to this
you want me to stop the "background task" before running npm start ??

if this is correct - how do I stop the "background task"

**Comment by jishi** [comment]
Depends on how you autostart it :) if it's pm2, just run "pm2 stop all"

Otherwise you could just kill the node process with the id listed from a ps
output. I don't have a computer at hand right now so I can't be more
detailed than that.

**Comment by autofrank** [comment]
i'm autostarting it in rc.local with 

`cd /home/pi/node-sonos-http-api
node server.js
`

i can comment it out, reboot the pi, putty in and start it manually

would that work ?

**Comment by jishi** [comment]
Yeah, sure

**Comment by autofrank** [comment]
okay, restarting manually seems to have sorted it so may be something go corrupt
The start up output is too long to add here 

One thing I did notice was it seemed to add 11 zones and them a comment about increasing max number of listeners and then further down it added the other 3

Is 14 zones too many ?

**Comment by jishi** [comment]
Should be fine although I haven't tested it. Shouldn't relate to TTS at
least.

If it works when invoked manually, but not with your rc.local I would guess
it is some sort of path issue finding settings.json. It looks correct to me
but apparently something is off. I'm away on vacation so I can't look into
it right now, but I still suggest you try the beta
On Jul 9, 2016 5:30 PM, "autofrank" <notifications@github.com> wrote:

okay, restarting manually seems to have sorted it so may be something go
corrupt
The start up output is too long to add here

One thing I did notice was it seemed to add 11 zones and them a comment
about increasing max number of listeners and then further down it added the
other 3

Is 14 zones too many ?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jishi/node-sonos-http-api/issues/251#issuecomment-231539971>,
or mute the thread
<https://github.com/notifications/unsubscribe/ADBNI3EkLKJyLCNlr5whAgVnDZ2AWWZRks5qT76ngaJpZM4JImhk>
.

**Comment by autofrank** [comment]
thanks and enjoy your vacation :-)

**Comment by jishi** [comment]
Is this still an issue?

**Comment by autofrank** [comment]
All working now - thanks 
One thing I did notice is that I have to insert a %20 instead of a space in the text I want it to say. (ie I have to put The%20cat%sat" instead of "The cat sat". I didn't think this was the way at the start or perhaps its fixed in the latest beta

Rgds
-Frank

**Comment by jishi** [comment]
That's regular url encoding. Most browsers will convert that transparently when writing a URL, but if you invoke it from a script or similar, you need to do that, and always had to (unless the script url encode automatically).
