### ISSUE TITLE
{"error":"action '' not found"}

### ISSUE THREAD

**Issue by robellis** [jishi/node-sonos-http-api#260]
Everything was working fine until one day i had a power cut and had to bring everything back up and now all i see when i start things is {"error":"action '' not found"} at http://domain:5005.

I dont see an error when i run npm start or node service.js, the output I see is below:

info: binding SSDP to port 1905
info: discovering all IPs from lo
info: discovering all IPs from eth0
info: relevant IPs 10.x.x.x=null
info: notification server listening on port 3500
http server listening on port 5005
no preset file, ignoring...
info: scanning for players in ip 10.x.x.x
info: subscribing to topology 10.x.x.x
info: using local endpoint 10.x.x.x
Initializing player sons1
Initializing player sonos2
Initializing player sonos3
Initializing player sonos4
Initializing player sonos5
debug: received avtransport 
debug: received avtransport 
debug: emitting group-volume
debug: received avtransport 
debug: received avtransport x-sonosapi-stream:s23234?sid=254&flags=32&sn=0
debug: received avtransport 

Any ideas how i might figure this out or what the problem might be?

Thanks

**Comment by jishi** [comment]
What command are you invoking? Sounds like it parses an empty action, so it would help to know what kind of request you are sending.

**Comment by robellis** [comment]
I get this when i use either of the commands:
run npm start 
node service.js

**Comment by jishi** [comment]
No, I meant which http commands you are testing. But I would still remember
recommend testing the beta version (branch) instead, it is very much
improved.

**Comment by robellis** [comment]
oh, sorry, that is the response i get if i go to http://domainname:5005.

I will look at installing the beta branch.

**Comment by jishi** [comment]
Well, that is to be expected if you don't send any valid command. Check the
Readme for valid examples.

**Comment by robellis** [comment]
Yeah, i realized that just as I was typing the response - sorry about that.

Thanks for the replies though, and now i updated to the beta too!
