### ISSUE TITLE
install/update to latest version of the api

### ISSUE THREAD

**Issue by johnnymossin** [jishi/node-sonos-http-api#261]
I have installed the api months ago, and wanted to update to latest version (currently running 15.0).
tried using the npm install --production from readme, didn't do anything. I installed 4.4.7 of nodejs. After some stupid attempts, I tried on a test raspberry I bought last year on black friday.
install nodejs on this machine and did:
npm install https://github.com/jishi/node-sonos-http-api

not remembering/knowing if this is the right way to do it, but it did download and install, but I ended up with error looking a lot like 'install problem node sonos http api #118', sorry for not saving the correct msg.

so question is: how do I correct update/install the latest stable version of this very nice tool ?

**Comment by jishi** [comment]
You need to start it after that, and it will respond to http requests on
port 5005. There should be detailed instructions in the Readme, and there
is also a precompiled raspberry image which runs the latest beta and has
autostart etc already configured.

Check here: http://jishi.github.io/node-sonos-http-api/

**Comment by johnnymossin** [comment]
originally I got the install warning on my 'production' pi, and afterwards it didn't work, so when I got the same warning og my test pi, I did not even care to test it, now it works on the test pi. THANX
Maybe I just need to do an uninstall on the production pi and then reinstall from scatch.
it will be later this weekend.
I will find npm uninstall instructions somewhere.
I will report back after reinstallation...

**Comment by johnnymossin** [comment]
just re-tested after reboot, and it works, even though I can find two installations of sonos-http-api, both the old and the new one, apparently the new npm/node install in different directory structure.
I did try to uninstall, to get a fresh start, but it didn't succed, some msg 'npm WARN uninstall not installed in ...', but now it works, so no reel worries.

Thanx again for all your good work.
