### ISSUE TITLE
issue returning Albumart url 

### ISSUE THREAD

**Issue by autofrank** [jishi/node-sonos-http-api#265]
hi, 
i can return the title of what is currently playing on a zone successfully 
currentTrack.title

but when try and return the albumArtURI with currentTrack.albumArtURI I get a blank string instead of "/getaa?s=1&u=x-sonosapi-stream%3as15078%3fsid%3d254"

or the full url using currentTrank.absoluteAlbumArtURI is blank as well instead of 
"http://192.168.1.69:1400/getaa?u=x-file-cifs%3a%2f%2fHomeNAS1%2fmusic%2fFrozen%2520%255bOriginal%2520Motion%2520Picture%2520Soundtrack%255d%2f03%2520For%2520the%2520First%2520Time%2520In%2520Forever.mp3&v=1306"

the full return from one of my zone states is 

"{"currentTrack":{"artist":"","title":"Cork's 96fm","album":"","albumArtURI":"/getaa?s=1&u=x-sonosapi-stream%3as15078%3fsid%3d254","duration":0,"uri":"x-sonosapi-stream:s15078?sid=254","radioShowMetaData":"Nick Richards in the Morning,p157750","absoluteAlbumArtURI":"http://192.168.1.69:1400/getaa?s=1&u=x-sonosapi-stream%3as15078%3fsid%3d254","type":"radio","streamInfo":""},"nextTrack":{"uri":"x-file-cifs://HomeNAS1/music/Frozen%20%5bOriginal%20Motion%20Picture%20Soundtrack%5d/03%20For%20the%20First%20Time%20In%20Forever.mp3","albumArtURI":"/getaa?u=x-file-cifs%3a%2f%2fHomeNAS1%2fmusic%2fFrozen%2520%255bOriginal%2520Motion%2520Picture%2520Soundtrack%255d%2f03%2520For%2520the%2520First%2520Time%2520In%2520Forever.mp3&v=1306","absoluteAlbumArtURI":"http://192.168.1.69:1400/getaa?u=x-file-cifs%3a%2f%2fHomeNAS1%2fmusic%2fFrozen%2520%255bOriginal%2520Motion%2520Picture%2520Soundtrack%255d%2f03%2520For%2520the%2520First%2520Time%2520In%2520Forever.mp3&v=1306","title":"For the First Time In Forever","album":"Frozen [Original Motion Picture Soundtrack]"},"volume":8,"mute":false,"trackNo":1,"elapsedTime":572,"elapsedTimeFormatted":"09:32","zoneState":"PLAYING","playerState":"PLAYING","zonePlayMode":{"shuffle":false,"repeat":false,"crossfade":false}}"

is the string returned too long or some other issue

thanks
frank

**Comment by jishi** [comment]
That sounds weird. How are you consuming the JSON? Since albumArtURI is shorter and that also gives you a blank string, it doesn't seem to be an issue with length (and there should be no restriction either way).

**Comment by autofrank** [comment]
I'm using a command in openremote and just returning it as a string and displaying it in a label.
I have done it a good many times and it works for "title", "volume" and that's why I thought it might be a length issue.

volume is 

![image](https://cloud.githubusercontent.com/assets/20369477/17358599/a91cf620-595a-11e6-8223-bedb8595eacc.png)

title is 

![image](https://cloud.githubusercontent.com/assets/20369477/17358618/c8660d14-595a-11e6-87e5-8897f3fcfa3e.png)

but either of my two examples above return an empty string.

I'll try and return the data later this evening using a lua script and see if the issue is with the api or with the way OR is handling it. There is a possibility OR can't handle the length...

Thanks

**Comment by autofrank** [comment]
I'll try a couple of options this evening and let you know

Thanks

**Comment by autofrank** [comment]
.... looks like its an OR issue
a 133 char string is returned okay while a 186 char string returns as blank
I posted on their forum, hopefully they can fix it

thanks again
