### ISSUE TITLE
discovery on different subnet

### ISSUE THREAD

**Issue by rjgough** [jishi/node-sonos-http-api#266]
My sonos is hosted on a different subnet 192.168.2.48 however my node server is running on 192.168.1.11 - how can i discover ?

**Comment by jishi** [comment]
Sorry for the late reply. 

You need to enable multicast forwarding for the SSDP multicast address between the subnets. This is not trivial to achieve (I have managed to do it with a Clavister firewall, but it took a lot of time to get it right). Why do you have them separated?

**Comment by rjgough** [comment]
OK thank you - i will have a go this evening. I'm using an Edge Router Pro so i think it is possible with some tweaking. I will let you know. Is there anything in the configuration i would need to address?

**Comment by jishi** [comment]
No, my library allows a TTL of 2 for the multicast discovery, so it should traverse one router hop if the network allows it.

**Comment by jishi** [comment]
There is also UPnP relay software that you can run on two machines on each network, but I haven't tested it. It's kind of clunky to require two extra machines for this, and the bridging it does is probably not suitable for a corporate environment.
