### ISSUE TITLE
currentTrack title in the beta

### ISSUE THREAD

**Issue by johnnymossin** [jishi/node-sonos-http-api#267]
I have installed the beta to get around CORS problems and now the title on the radio streams that I use, it more like a url:

on v 0.19.0:
		"state": {
			"currentTrack": {
				"artist": "",
				"title": "DR P4 København",
				"album": "",
				"albumArtURI": "/getaa?s=1&u=x-sonosapi-stream%3as37309%3fsid%3d254%26flags%3d32%26sn%3d0",
				"duration": 0,
				"uri": "x-sonosapi-stream:s37309?sid=254&flags=32&sn=0",
				"radioShowMetaData": "",
				"absoluteAlbumArtURI": "http://192.168.0.71:1400/getaa?s=1&u=x-sonosapi-stream%3as37309%3fsid%3d254%26flags%3d32%26sn%3d0",
				"streamInfo": "",
				"type": "radio"
			},
and in the beta:

		"state": {
			"currentTrack": {
				"title": "x-sonosapi-stream:s37309?sid=254&flags=32&sn=0",
				"albumArtUri": "/getaa?s=1&u=x-sonosapi-stream%3as37309%3fsid%3d254%26flags%3d32%26sn%3d0",
				"duration": 0,
				"uri": "x-sonosapi-stream:s37309?sid=254&flags=32&sn=0",
				"radioShowMetaData": "",
				"absoluteAlbumArtUri": "http://192.168.0.71:1400/getaa?s=1&u=x-sonosapi-stream%3as37309%3fsid%3d254%26flags%3d32%26sn%3d0"
			},

did I miss some setup thing or is it a bug ?

**Comment by jishi** [comment]
No, that's a known bug, just haven't gotten around to fix it yet. I have a
pull request from a contributor pending that is supposed to fix it, just
haven't verified it yet

**Comment by jishi** [comment]
This should be fixed in beta.20
