### ISSUE TITLE
Resume playback after TTS

### ISSUE THREAD

**Issue by PointPubMedia** [jishi/node-sonos-http-api#268]
Hi,

First, very nice project ;)

Is it normal, using beta, that when using /say/ it will not resume what's playing before?

**Comment by jishi** [comment]
No, it is not. What source are you playing when invoking the say command?

**Comment by PointPubMedia** [comment]
Most of the time it's a SiriusXM channel!

**Comment by jishi** [comment]
Could you check the state when you are playing sirius, and paste the state output here? Maybe it isn't identifying sirius channels correctly, they most probably restored the sam way as all other radio channels.

**Comment by PointPubMedia** [comment]
Yeah what exactly you need?    Will test that back at home!

**Comment by jishi** [comment]
If you call /RoomName/state when playing sirius, and just copy the output from the browser into a comment here. I need to check what uri it is using for streaming, to know if I identify it correctly as a radio station.

**Comment by PointPubMedia** [comment]
@jishi BTW, is it possible to run your code on a different subnet and hardcode all SONOS IP devices ?

**Comment by jishi** [comment]
In theory, it should be possible to rewrite it to support it, but you would have to have bi-directional communication possibilities between the two sub-nets since they communicate both ways (so no NAT). You would only require 1 IP-adress to find your whole system, any player or bridge/boost would do.

**Comment by PointPubMedia** [comment]
Currently both subnet have access without NAT!    But currently your code is not made for that?

**Comment by jishi** [comment]
No, it is not, it's a very specific use case. I managed to configure a firewall to actually forward the SSDP discovery data (multicast udp) between networks and that is basically the only thing missing for it to find the system. What firewall or router do you use between the nets?

**Comment by PointPubMedia** [comment]
Using Juniper SSG320
Worst case, I will setup the PINE64 with 2 network interface.

**Comment by jishi** [comment]
Maybe this would help: http://www.avsforum.com/forum/27-replaytv-showstopper-pvrs/685492-attn-ip-geeks-forwarding-upnp-ssdp-broadcasts-across-subnets.html

It is basically the same data that needs to flow, although you wouldn't want to restrict it to specific IPs like he did, but rather whole nets.

**Comment by Kamol81** [comment]
Hi,  When I listen to "Radio by Tunein" after TTS message there is silence. 
Thank you for the great work You did.


applying preset
info: applying preset players=[roomName=Living Room, volume=6], state=STOPPED, uri=http://192.168.1.172:5005/tts/cccd5eb094265b73646a9cc89bcd4dfba3c5f35e-pl-pl.mp3, playMode=NORMAL, trackNo=1, elapsedTime=0
debug: ungrouping Living Room to prepare for grouping
groupToRejoin undefined
applying preset
info: applying preset players=[roomName=Bathroom, volume=0], state=PLAYING, uri=x-sonosapi-stream:s87770?sid=254&flags=32&sn=0, playMode=NORMAL, trackNo=1, elapsedTime=102
debug: ungrouping Bathroom to prepare for grouping
debug: emitting group-volume

**Comment by jishi** [comment]
@Kamol81: Is that the regular version? That is a known issue with non-beta version, and fixed in beta.

**Comment by PointPubMedia** [comment]
@jishi 
Here's a test...

Start node-sonos-http-api
Nothing playing anywhere.
Start TTS
Works fine
Start SiriusXM on zone Kitchen
Start TTS in Kitchen

Got:
`backup preset was { players: [ { roomName: 'Kitchen', volume: 26 } ],
  state: 'PLAYING',
  uri: 'x-sonosapi-hls:r%3athebeat?sid=49&flags=288&sn=3',
  metadata: undefined,
  playMode: { repeat: false } }
undefined 'Kitchen' 'STOPPED'
undefined 'Kitchen' 'PLAYING'
undefined 'Kitchen' 'STOPPED'
announcement finished
applying preset { players: [ { roomName: 'Kitchen', volume: 26 } ],
  state: 'PLAYING',
  uri: 'x-sonosapi-hls:r%3athebeat?sid=49&flags=288&sn=3',
  metadata: undefined,
  playMode: { repeat: false } }
{ [Error: Internal Server Error] statusCode: 500 } 'Error: Internal Server Error\n    at ClientRequest.<anonymous> (/root/node-sonos-http-api/node_modules/sonos-discovery/lib/helpers/request.js:22:21)\n    at ClientRequest.g (events.js:260:16)\n    at emitOne (events.js:77:13)\n    at ClientRequest.emit (events.js:169:7)\n    at HTTPParser.parserOnIncomingClient (_http_client.js:430:21)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)\n    at Socket.socketOnData (_http_client.js:320:20)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:153:18)\n    at Socket.Readable.push (_stream_readable.js:111:10)\n    at TCP.onread (net.js:536:20)'
TypeError: Cannot read property 'then' of undefined
    at /root/node-sonos-http-api/lib/actions/say_v2.js:162:9
    at process._tickCallback (node.js:369:9)
undefined
`
Nothing start back to play

Another TTS, and works fine with

`backup preset was { players: [ { roomName: 'Kitchen', volume: 26 } ],
  state: 'STOPPED',
  uri: 'http://192.168.168.71:5005/tts/156f535254ee6a7a3c5c0f6dd0cbe46b99a1daf9-fr-fr.mp3',
  metadata: undefined,
  playMode: { repeat: false },
  trackNo: 1,
  elapsedTime: 0 }
announce file for phrase "Bonsoir%20un%20autre%20test" does not seem to exist, downloading
undefined 'Kitchen' 'PLAYING'
undefined 'Kitchen' 'STOPPED'
announcement finished
applying preset { players: [ { roomName: 'Kitchen', volume: 26 } ],
  state: 'STOPPED',
  uri: 'http://192.168.168.71:5005/tts/156f535254ee6a7a3c5c0f6dd0cbe46b99a1daf9-fr-fr.mp3',
  metadata: undefined,
  playMode: { repeat: false },
  trackNo: 1,
  elapsedTime: 0 }
undefined
`
Start again SiriusXM and another TTS

`backup preset was { players: [ { roomName: 'Kitchen', volume: 26 } ],
  state: 'PLAYING',
  uri: 'x-sonosapi-hls:r%3athebeat?sid=49&flags=288&sn=3',
  metadata: undefined,
  playMode: { repeat: false } }
announce file for phrase "Un%20dernier%20test" does not seem to exist, downloading
undefined 'Kitchen' 'STOPPED'
undefined 'Kitchen' 'PLAYING'
undefined 'Kitchen' 'STOPPED'
announcement finished
applying preset { players: [ { roomName: 'Kitchen', volume: 26 } ],
  state: 'PLAYING',
  uri: 'x-sonosapi-hls:r%3athebeat?sid=49&flags=288&sn=3',
  metadata: undefined,
  playMode: { repeat: false } }
{ [Error: Internal Server Error] statusCode: 500 } 'Error: Internal Server Error\n    at ClientRequest.<anonymous> (/root/node-sonos-http-api/node_modules/sonos-discovery/lib/helpers/request.js:22:21)\n    at ClientRequest.g (events.js:260:16)\n    at emitOne (events.js:77:13)\n    at ClientRequest.emit (events.js:169:7)\n    at HTTPParser.parserOnIncomingClient (_http_client.js:430:21)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)\n    at Socket.socketOnData (_http_client.js:320:20)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:153:18)\n    at Socket.Readable.push (_stream_readable.js:111:10)\n    at TCP.onread (net.js:536:20)'
TypeError: Cannot read property 'then' of undefined
    at /root/node-sonos-http-api/lib/actions/say_v2.js:162:9
    at process._tickCallback (node.js:369:9)
undefined
`

**Comment by PointPubMedia** [comment]
I try another test with a song from Google Music and works perfectly.... got TTS and restore the song!

**Comment by Kamol81** [comment]
It was regular version now i installed beta one. When i play something from deezer resuming its working but from "Tune in" there is a silence. 

{"status":"error","error":"TypeError: Cannot read property 'then' of undefined\n    at /home/pi/sonos/lib/actions/say_v2.js:162:9\n    at process._tickCallback (node.js:356:9)"}

**Comment by PointPubMedia** [comment]
@jishi Got a chance to have a look ?

**Comment by jishi** [comment]
No, not yet, sorry. Been busy catching up after vacations :(

**Comment by PointPubMedia** [comment]
@jishi Is it possible to "say" something at the same time to multiple zone ?    Multiple != all ;)

**Comment by jishi** [comment]
Not right now, but yeah, in theory. People have been requesting say support for presets (basically a preset announcement feature), but I assume that is not what you are requesting? You want a sayall but with some players excluded?

**Comment by PointPubMedia** [comment]
@jishi can be a preset or something like /Kitchen,Living Room/say/Something/en-en/50

I never use "all" as I have some sonos outside ;)

**Comment by jishi** [comment]
Might be easier to just allow configuration of excluded players instead, if it's a permanent scenario. On the other hand, might be uses where you want different announcement in different parts of your house. File a new issue and I will keep it as a feature suggestion.

**Comment by PointPubMedia** [comment]
@jishi Any chance to have a look at the Sirius resume bug ?

**Comment by jishi** [comment]
Should be fixed now, update and see if it works!

**Comment by PointPubMedia** [comment]
Works perfectly!
