### ISSUE TITLE
can not play/pause the speaker

### ISSUE THREAD

**Issue by scheveningen** [jishi/node-sonos-http-api#269]
Hello,

I have a small problem. I start the server.js using PM2. It is up and running with out error. 
pi@raspberrypi:~/node-sonos-http-api $ pm2 list
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ memory      │ watching │
├──────────┼────┼──────┼─────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ server   │ 0  │ fork │ 948 │ online │ 0       │ 11m    │ 35.914 MB   │ disabled │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────────────┴──────────┘

The sonos play 1 in this case have IP 192.168.178.13 and the room name is woonkamer. So I use the line: http://192.168.178.13:5005/Woonkamer/play <-- and nothing happens? Same for all other commands?

**Comment by scheveningen** [comment]
After reinstall it runs stable :)

**Comment by jishi** [comment]
But you should not use the IP of the Sonos Play:1. You should use the IP of the device you are running node on. The raspberry pi, in your case.

**Comment by scheveningen** [comment]
Oh men!!!! I feel so stupid hahaha. 
Thanks, it works. Sorry for my stupid question!
