### ISSUE TITLE
Multiple zone for say command

### ISSUE THREAD

**Issue by PointPubMedia** [jishi/node-sonos-http-api#270]
@jishi Would be nice if we can announce in multiple zone at the same time with the say command.

Personally, I would like something like

/Kitchen,Living Room, Dining Room/say/TEST/en-en/50

As I'm not always announcing in the same zones, I would like to choose each time where to send it!

**Comment by brettyj** [comment]
+1 - Imagine the scenario (which I don't have at the moment) of a outdoor zone for parties which you don't want to do announcements on

**Comment by JsChiSurf** [comment]
I know this is done in your free time and have plenty of other things to worry about, but wondering if you have had a chance to put more thought into this one, as it relates to presets for tts/clips to a group of rooms, versus one or all?

**Comment by jishi** [comment]
Hi. I was about to look at it this weekend actually, but got change in
plans.

However, I think I will fix it very soon, given that it is is a highly
anticipated feature. Be patient! :)

**Comment by jishi** [comment]
This works with saypreset since a while back, closing.
