### ISSUE TITLE
Getting track uri instead of the title for some tracks

### ISSUE THREAD

**Issue by jplourde5** [jishi/node-sonos-http-api#272]
Very sporadic.  The Sonos app is displaying the track uri for random tracks.  Usually just 1 or 2 tracks out of a list of 50.  Any idea what causes this?

**Comment by jishi** [comment]
This usually happens if the metadata is incorrect (do not refer to the correct account details). Is it different tracks every time or the same ones?

**Comment by jplourde5** [comment]
I'll check to see if it is the same track(s) each time and compare the metadata to what Favorites stores if it is the same track(s).

**Comment by jplourde5** [comment]
I found the problem.  Some special characters like &, ', and possibly others cause the problem.  I tried not encoding the title in player.js but that caused another problem.  I'm going to change the music service def's so that they blank out the title if the type is not a station, where I need the title.
