### ISSUE TITLE
dynamically load presets

### ISSUE THREAD

**Issue by jrluw** [jishi/node-sonos-http-api#274]
My apologies if this is naive, but I found it nice to have a command that reloads the presets.  I implemented this in presetsAction as /preset/reload/ using the code:

if (value == "reload") {
...
delete require.cache[require.resolve(presetsFilename)];
presets = require(presetsFilename);
...
}

**Comment by jishi** [comment]
My plan has been to implement a file-watch to the presets.json file to reload it automatically upon change, I don't have an issue for it though. I assume that would makes this request obsolete?

**Comment by jrluw** [comment]
Yes, that sounds great.
