### ISSUE TITLE
Add a response when a command is succesfully received.

### ISSUE THREAD

**Issue by Holland1** [jishi/node-sonos-http-api#275]
When a command is successfully received, e.g http://ip/Badkamer/play, there is no acknowledgment from the sonos http api, like for example; OK

It only communicates back, when a command was not correctly received.

Would it be possible to add that functionality.

I use the sonos http api in a home automation project, and this requires some acknowledgment that a command is successful send to sonos http api

**Comment by jishi** [comment]
The beta branch will always respond with a json response if successful, I
suggest you try that one to start with!

**Comment by Holland1** [comment]
Testing the beta now.

Just wondering, is there a difference in the json response in the beta ? Because I'm missing all the zone related info. e.g zoneState

From beta;
{"currentTrack":{"title":"x-sonosapi-stream:s87683?sid=254&flags=32","albumArtUri":"/getaa?s=1&u=x-sonosapi-stream%3as87683%3fsid%3d254%26flags%3d32","duration":0,"uri":"x-sonosapi-stream:s87683?sid=254&flags=32","radioShowMetaData":"","absoluteAlbumArtUri":"http://ip:1400/getaa?s=1&u=x-sonosapi-stream%3as87683%3fsid%3d254%26flags%3d32"},"nextTrack":{"artist":"","title":"","album":"","albumArtUri":"","duration":0,"uri":""},"volume":24,"mute":false,"trackNo":1,"elapsedTime":0,"elapsedTimeFormatted":"00:00:00","playbackState":"STOPPED","playMode":{"repeat":false,"shuffle":false,"crossfade":false}}

From master
{"currentTrack":{"artist":"","title":"Qmusic","album":"","albumArtURI":"/getaa?s=1&u=x-sonosapi-stream%3as87683%3fsid%3d254%26flags%3d32","duration":0,"uri":"x-sonosapi-stream:s87683?sid=254&flags=32","radioShowMetaData":"Stephan Bouwman,p795181","absoluteAlbumArtURI":"http://ip:1400/getaa?s=1&u=x-sonosapi-stream%3as87683%3fsid%3d254%26flags%3d32","streamInfo":"","type":"radio"},"nextTrack":{"artist":"","title":"","album":"","albumArtURI":"","duration":0,"uri":""},"volume":24,"mute":false,"trackNo":1,"elapsedTime":0,"elapsedTimeFormatted":"00:00","zoneState":"STOPPED","playerState":"STOPPED","zonePlayMode":{"shuffle":false,"repeat":false,"crossfade":false}}

**Comment by jishi** [comment]
Yes, there are a few differences, I have tried to simplify it. Unless info
is player specific (like volume, mute), the info is always regarding zone.
ZoneState is now playbackState.

There is also a known bug with title on radiostations, just FYI.

**Comment by Holland1** [comment]
ahh. ok. 

Will make some adjustments to my scripts. Thanks
