### ISSUE TITLE
albumArtURI Format

### ISSUE THREAD

**Issue by surrounded** [jishi/node-sonos-http-api#28]
Is it possible for the "state" response to include the entire "albumArtURI"? 

I'm assuming sonos-discovery already acquires this information anyways.  And even if I created a script to format the current output of the "state" response to prepend the "albumArtURI" with the "http://<associated ZP IP Address>:1400" that would not work as I have noticed that the ZP IP address changes occassionally.  Not sure why yet as I have not looked into the pattern but regardless the "Associated ZP IP Address" would need to be updated to reflect the current IP address 

example"

    ##Format Example##
    http://<Associated ZP IP Address>:1400/getaa?s=1&u=x-sonos-http%3atrack%253a168274267.mp3%3fsid%3d160%26flags%3d32
    ##Exact Example##
    http://10.0.0.105:1400/getaa?s=1&u=x-sonos-http%3atrack%253a168274267.mp3%3fsid%3d160%26flags%3d32

Once again this is meet the requirements for the openremote sensor to display the Album Art Image.

**Comment by jishi** [comment]
Better late than never :) let me know if this is enough.
