### ISSUE TITLE
Inconsistent Say Behaviour when listening to Radio Streams

### ISSUE THREAD

**Issue by brettyj** [jishi/node-sonos-http-api#280]
Hi,

I just had a quick play with this software with a friends system, cause I'm thinking about buying into Sonos   soon - looks good! When doing TTS when listening to a music file from Google Play Music it works perfectly, however when doing it when listening to a radio stream I find odd results.

Sometimes it won't play the TTS at all and sometimes it plays it then repeats it and then stops.

Is this a known issue?

**Comment by jishi** [comment]
Yes, try the beta branch, most of these issues are fixed there.

**Comment by brettyj** [comment]
Ah okay, i'll try later :) Thanks!

**Comment by brettyj** [comment]
Works perfect on beta. Cheers!
