### ISSUE TITLE
Custom say volume

### ISSUE THREAD

**Issue by brettyj** [jishi/node-sonos-http-api#281]
Hi,

Is there anyway to define your own say volume? Sometimes 40% is quite quiet.

Thanks

**Comment by jishi** [comment]
Yes, you can either permanently define a different announceVolume in a settings.json file, or per request basis by appending volume between 1-100 at the end of the url:

examples: 

```
/Office/say/Hello, dinner is ready
/Office/say/Hej, maten är klar/sv-se
/sayall/Hello, dinner is ready
/Office/say/Hello, dinner is ready/90
/Office/say/Hej, maten är klar/sv-se/90
```

**Comment by jishi** [comment]
I think the property is called announceVolume in settings.json, so:

```
{
  voicerss: "abceb123817326817623",
  announceVolume: 90
}
```
