### ISSUE TITLE
Clarification of sleep format on beta

### ISSUE THREAD

**Issue by mattnewham** [jishi/node-sonos-http-api#282]
Beta branch doc says sleep supports hh:mm:ss format - however this is not working for me, it does not set sleep timer at all.

In example code you have "sleep": 600 

should it be set it seconds?

**Comment by jishi** [comment]
Yes, the documentation is wrong, I scrapped that format to simplify the functionality, figured it was a bit redundant. I should probably update the documentation, but I believe the README is correct. I haven't updated the sagger docs for the beta at all.

**Comment by mattnewham** [comment]
Hey Jimmy

README on Beta branch still says hh:mm:ss thats what confused me - your
JSON example in the beta README is correct though  :)

**Comment by jishi** [comment]
Hm, I can't find any reference to it in the README, it only seem to have an example URL and no explanation... am I being dense?

**Comment by mattnewham** [comment]
Haha.

Under the Preset section of the readme, you have the example preset code
with:

"sleep": 600


Then below, last line is:

sleep is an optional value that enables the sleep timer and supports the
'HH:MM:SS' format.

**Comment by jishi** [comment]
Ah, thank you, I was being dense then :D
