### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by brettyj** [jishi/node-sonos-http-api#283]
Hi,

Was working fine for a bit, but then it started not to reset the playlist back to how it was and was returning these errors:

`undefined 'Product Team' 'PLAYING'
applying preset { players: [ { roomName: 'Product Team', volume: 25 } ],
  state: 'PLAYING',
  uri: 'x-rincon-mp3radio://stream.absoluteradio.liquidcompass.net/ABSOLUTERADIO
IRAAC?editedaspersonalinfo',
  metadata: '<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="
urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com
:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="R
:0/0/12" parentID="R:0/0" restricted="true"><dc:title>Absolute Radio</dc:title><upnp:class>object.item.audioItem.audioBroadcast</u
pnp:class><desc id="cdudn" nameSpace="urn:schemas-rinconnetworks-com:metadata-1-
0/">SA_RINCON65031_</desc></item></DIDL-Lite>',
  playMode: { repeat: false },
  trackNo: 1,
  elapsedTime: 228 }
{ [Error: Internal Server Error] statusCode: 500 } 'Error: Internal Server Error
\n    at ClientRequest.<anonymous> (F:\\node-sonos-http-api\\node_modules\\sonos
-discovery\\lib\\helpers\\request.js:22:21)\n    at ClientRequest.g (events.js:2
73:16)\n    at emitOne (events.js:90:13)\n    at ClientRequest.emit (events.js:1
82:7)\n    at HTTPParser.parserOnIncomingClient (_http_client.js:469:21)\n    at
 HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)\n    at Socket.sock
etOnData (_http_client.js:359:20)\n    at emitOne (events.js:90:13)\n    at Sock
et.emit (events.js:182:7)\n    at readableAddChunk (_stream_readable.js:153:18)\
n    at Socket.Readable.push (_stream_readable.js:111:10)\n    at TCP.onread (ne
t.js:529:20)'
TypeError: Cannot read property 'then' of undefined
    at F:\node-sonos-http-api\lib\actions\say_v2.js:162:9
    at process._tickCallback (internal/process/next_tick.js:103:7)
backup preset was { players: [ { roomName: 'Product Team', volume: 25 } ],
  state: 'PLAYING',
  uri: 'http://192.168.0.144:5005/tts/4a07e509dd2cbe4c741200202c5c29ee6588d8ba-e
n-gb.mp3',
  metadata: '',
  playMode: { repeat: false },
  trackNo: 1,
  elapsedTime: 5 }
undefined 'Product Team' 'PLAYING'
undefined 'Product Team' 'STOPPED'
announcement finished
applying preset { players: [ { roomName: 'Product Team', volume: 25 } ],
  state: 'PLAYING',
  uri: 'http://192.168.0.144:5005/tts/4a07e509dd2cbe4c741200202c5c29ee6588d8ba-e
n-gb.mp3',
  metadata: '',
  playMode: { repeat: false },
  trackNo: 1,
  elapsedTime: 5 }
`

Any idea?

**Comment by jishi** [comment]
Not sure, it lists the backup preset (which it should restore to) as the say preset, which sounds a bit odd. Do you remember what you did before this occurred? 

Does restarting the http api resolve this?

**Comment by brettyj** [comment]
I think I've found the cause of it. I've noticed this only happens when playing a radio station that I've added myself - from My Radio Stations in tune in. If I play a publicly listed one it seems to be fine. This is the error I get from the REST API:

```
{
"status": "error",
"error": "TypeError: Cannot read property 'then' of undefined\n    at E:\\sonos\\node-sonos-http-api\\lib\\actions\\say_v2.js:162:9\n    at process._tickCallback (internal/process/next_tick.js:103:7)"
}
```

Does that help?

**Comment by jishi** [comment]
Ah, good catch. I think we don't identify custom radions correctly, and tries to restore it like a playlist which would fail.

**Comment by jishi** [comment]
This should be fixed in beta.20
