### ISSUE TITLE
Calling IPADDRESS/preset/{preset name} returns []

### ISSUE THREAD

**Issue by Anchorage42** [jishi/node-sonos-http-api#284]
Hey everyone. Total beginner at this but I've managed to get everything else set up.
The one area I'm stuck is that when I try to call a preset, my browser just returns [ ] with nothing coming from the Sonos.

Using other various commands, I can get the Sonos to play mostly what I want. I've run my JSON through JSONLint to make sure it's valid.

Any ideas?

**Comment by jishi** [comment]
I suggest you start with using the beta branch instead, that one gives you much better error messages.

**Comment by jishi** [comment]
The beta has ended, it is now the official version.
