### ISSUE TITLE
Merge pull request #291

### ISSUE THREAD

**Issue by GregRocket** [jishi/node-sonos-http-api#292]
@jplourde5 Just tried the latest update and now server is returning errors when I run npm start

# npm start

> sonos-http-api@1.0.0-beta.21 start /root/node-sonos-http-api-master
> node server.js

module.js:327
    throw err;
    ^

Error: Cannot find module './build/Release/mcrypt'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/node-sonos-http-api-master/node_modules/mcrypt/index.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/node-sonos-http-api-master/node_modules/anesidora/encryption.js:1:76)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

npm ERR! Linux 4.4.9-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.3.2
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@1.0.0-beta.21 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sonos-http-api@1.0.0-beta.21 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sonos-http-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/node-sonos-http-api-master/npm-debug.log

**Comment by jplourde5** [comment]
This is being caused by a missing package for the Pandora capability that was just added.  I'll submit a fix in a minute.

**Comment by jishi** [comment]
Sounds like it is using some native module. Need to make sure this compiles
on both x86 and Arm.

**Comment by jplourde5** [comment]
I just tested and submitted the needed addition to the package.  You can fix now by simply adding

    "mcrypt": "^0.1.7",

to the package.json file and issuing

npm install --production

**Comment by GregRocket** [comment]
I'm still getting errors after adding "mcrypt": "^0.1.7",

# npm start

> sonos-http-api@1.0.0-beta.21 start /root/node-sonos-http-api-master
> node server.js

module.js:327
    throw err;
    ^

Error: Cannot find module './build/Release/mcrypt'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/node-sonos-http-api-master/node_modules/mcrypt/index.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/node-sonos-http-api-master/node_modules/anesidora/encryption.js:1:76)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

npm ERR! Linux 4.4.9-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.3.2
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@1.0.0-beta.21 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sonos-http-api@1.0.0-beta.21 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sonos-http-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/node-sonos-http-api-master/npm-debug.log

**Comment by jplourde5** [comment]
Do you see crypt in your node_modules folder?  If not, copy and paste your package.json file here so I can take a look.

**Comment by jplourde5** [comment]
Should be mcrypt, not crypt.  Spellcheck!

**Comment by GregRocket** [comment]
Yes I have a mcrypt directory

**Comment by jplourde5** [comment]
I wonder why it does not see it...

**Comment by GregRocket** [comment]
package.json

{
  "name": "sonos-http-api",
  "version": "1.0.0-beta.21",
  "description": "A simple node app for controlling a Sonos system with basic HTTP requests",
  "scripts": {
    "start": "node server.js"
  },
  "author": "Jimmy Shimizu <jimmy@shimizu.se>",
  "repository": {
    "type": "git",
    "url": "https://github.com/jishi/node-sonos-http-api.git"
  },
  "dependencies": {
    "mcrypt": "^0.1.7",
    "basic-auth": "~1.0.3",
    "fuse.js": "^2.2.0",
    "anesidora": "https://github.com/dlom/anesidora",
    "node-static": "~0.7.0",
    "request-promise": "~1.0.2",
    "sonos-discovery": "https://github.com/jishi/node-sonos-discovery/archive/v1.0.0-beta.21.tar.gz"
  },
  "engines": {
	"node": ">=4.0.0",
    "npm": "^2.0.0"
	
  },
  "main": "lib/sonos-http-api.js",
  "license": "MIT"
}

**Comment by jplourde5** [comment]
Okay, it may be something else.  I just removed the mcrypt include, deleted node_modules, issued npm install --production, checked for mcrypt, it was not there, started with no problem, tested Pandora, and everything works.  Still digging...

**Comment by GregRocket** [comment]
OK I have to leave for awhile, will be back to test later. Thanks.

**Comment by jplourde5** [comment]
Actually mcrypt IS there.  It didn't need to be added to the package.json file.  It is getting pulled down with the anesidora package used for Pandora.

**Comment by jplourde5** [comment]
Remove mcrypt from the package.json file, delete the node_modules folder, npm install --production, to get us back to a clean slate.  Try it again after that and see if the error still happens.  Probably does, and then we need to figure out why node can't find mcrypt.  One thing that I notice is that it is looking in what I think is an odd folder base on your error message:

Error: Cannot find module './build/Release/mcrypt'

What is './build/Release/' ?

**Comment by jishi** [comment]
As I said, mcrypt is probably a compiled binary. It might not work
correctly on arm.

**Comment by jplourde5** [comment]
I was just about to echo what you said earlier.  Looking closer, I found the directory and it is exactly what you are saying.  Let me see if I can find a different crypto solution to use.  Pandora requires the communication to be encrypted and I need to see if there is a compatible substitute.

**Comment by jplourde5** [comment]
I just tested on my Raspberry Pi, which has an ARM, and it works perfectly fine.  I'm using Node 6.3.1 though.  I wonder if that added better support for binaries.

GregRocket, what type of server are you using?

**Comment by GregRocket** [comment]
I am running a Raspberry PI 3 with Linux version 4.4.9-v7+, minibian jessie, latest update.
And Node v4.3.2

The readme.md calls for
This application requires node 4.0.0 or higher!
This does NOT work on Node 6+ at the moment

**Comment by jishi** [comment]
Native binaries are usually getting compiled during installation (npm install), and if you are missing the needed tools for compiling, it would fail. However, it should be noticable and npm install should error out.

**Comment by jplourde5** [comment]
I'm running on a RPI 3 also. Installed fine, is working, and I don't see that error.  I don't have much installed but I do have Homebrew installed and it may have come in with something else that I was testing. 

The good news is that I'm pretty close to getting the node native crypto to work.  The output is almost identical but I'm seeing differences on the end of the encrypted strings that I need to figure out.

On 6.3, I saw the note but I haven't had any issues with 6.3.  What are the known issues?

**Comment by jishi** [comment]
The known issues is that RegExp.$1, .$2 etc has been deprecated and removed which I have used in a few places. 

It's good to avoid native npm modules if possible, if you want to have good portability between platforms.

**Comment by jplourde5** [comment]
Standard crypto seems to work fine.  Just created a pull request.

**Comment by GregRocket** [comment]
Latest Commits have corrected the startup errors.

**Comment by jplourde5** [comment]
Excellent...  Jimmy, my further testing has been good also.  Feel free to accept the pull request.
