### ISSUE TITLE
server start failure due to fuse

### ISSUE THREAD

**Issue by k1ll4h8y73** [jishi/node-sonos-http-api#300]
Hi there,

I tried to get everything up and running following this approach: http://www.makeuseof.com/tag/send-voice-notifications-sonos-speakers/. The difference is that I'm not using an RPi, but a dedicated ubuntu server machine - So I chose a corresponding package. 

My problem is that starting the API fails with the following output:

> phate@prometheus:~/sonos$ sudo npm start
> 
> \> sonos-http-api@1.0.0-beta.22 start /home/phate/sonos
> \> node server.js
> 
> no settings file found, will only use default settings
> module.js:341
>     throw err;
>     ^
> 
> Error: Cannot find module 'fuse.js'
>     at Function.Module._resolveFilename (module.js:339:15)
>     at Function.Module._load (module.js:290:25)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/phate/sonos/lib/music_services/libraryDef.js:2:14)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/phate/sonos/lib/actions/musicSearch.js:9:20)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
> 
> npm ERR! Linux 4.4.0-36-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
> npm ERR! node v5.12.0
> npm ERR! npm  v3.10.7
> npm ERR! code ELIFECYCLE
> npm ERR! sonos-http-api@1.0.0-beta.22 start: `node server.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the sonos-http-api@1.0.0-beta.22 start script 'node server.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the sonos-http-api package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node server.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs sonos-http-api
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls sonos-http-api
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/phate/sonos/npm-debug.log
> 

When checking, the js is actually there:

> phate@prometheus:~/sonos$ cd node_modules/fuse/bin/
> phate@prometheus:~/sonos/node_modules/fuse/bin$ ls -al
> insgesamt 20
> drwxrwxr-x 2 phate phate 4096 Dez 10  2013 .
> drwxrwxr-x 6 phate phate 4096 Sep 12 17:27 ..
> -rwxrwxrwx 1 phate phate 2467 Dez 10  2013 fuse.js

I tried around a lot, including (re-)installing fuse again via npm install -g fuse and this only brings up some warning about minimatch - no error or anything.

> phate@prometheus:~/sonos$ sudo npm install -g fuse
> npm WARN deprecated minimatch@0.0.5: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> /usr/bin/fuse -> /usr/lib/node_modules/fuse/bin/fuse.js
> /usr/lib
> └── fuse@0.4.0

Do you happen to have an idea what might be the root of all evil?
npm is version 3.10.7 and node-v reveals v5.12.0 (just as in the tutorial).

I tried a lot in order to solve this problem, but did not yet have any success. It would be really great if someone had an idea. Many thanks in advance!

**Comment by jishi** [comment]
Sounds like a weird issue. Someone reported that npm 3.10.7 of npm gave him issues, but not 3.10.6, but that was related to something else. But might be worth a try to identify the cause of this.

**Comment by levelsw** [comment]
Hi Jishi, I have the same problem as k1ll4h8y73,
tried npm 3.10.6, same problem:

> root@ubuntu:~/sonos# npm -v
> 3.10.6
> root@ubuntu:~/sonos# npm start
> 
> sonos-http-api@1.0.0-beta.23 start /root/sonos
> node server.js
> 
> no settings file found, will only use default settings
> module.js:341
>     throw err;
>     ^
> 
> Error: Cannot find module 'fuse.js'
>     at Function.Module._resolveFilename (module.js:339:15)
>     at Function.Module._load (module.js:290:25)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/root/sonos/lib/music_services/libraryDef.js:2:14)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/root/sonos/lib/actions/musicSearch.js:9:20)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
> 
> npm ERR! Linux 4.4.0-21-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
> npm ERR! node v5.12.0
> npm ERR! npm  v3.10.6
> npm ERR! code ELIFECYCLE
> npm ERR! sonos-http-api@1.0.0-beta.23 start: `node server.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the sonos-http-api@1.0.0-beta.23 start script 'node server.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the sonos-http-api package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node server.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs sonos-http-api
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls sonos-http-api
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /root/sonos/npm-debug.log
> root@ubuntu:~/sonos#
> 

Thanks,

Wesley

**Comment by jishi** [comment]
I'm not seeing the same issue as you, on a clean install. However, on OS X (don't have Linux at hand right now).

fuse.js is a plain js module, so it should not be a platform problem. You guys get no error at all from the `npm install --production` call?

**Comment by levelsw** [comment]
Hi Jishi,

no error:

> root@ubuntu:~/sonos# npm install --production
> sonos-http-api@1.0.0-beta.23 /root/sonos
> ├─┬ anesidora@1.2.0
> │ └── request@2.74.0
> └── fuse.js@2.5.0
> 
> root@ubuntu:~/sonos#
>

**Comment by jishi** [comment]
You must have run npm install on a previous version and then updated, it sounds like? Anyway, glad it is resolved now.

**Comment by levelsw** [comment]
Yes ofcourse I tried npm 3.10.6 and didn't do the install --production again, thanks!

**Comment by jishi** [comment]
Are you saying that the install was incomplete with npm 3.10.7? That is something I should look into perhaps, if that is the case.

**Comment by levelsw** [comment]
I had the same issue as k1ll4h8y73 with 3.10.7, I joined this conversation after trying 3.10.6 but I did not do the install --production after I tried with NPM 3.10.6

I can try to see if I get the same error again with 3.10.7..... let's see......

Seems to be still working after going back to 3.10.7:

> root@ubuntu:~/sonos# node -v
> v5.12.0
> root@ubuntu:~/sonos# npm -v
> 3.10.7
> root@ubuntu:~/sonos# npm start
> 
> > sonos-http-api@1.0.0-beta.23 start /root/sonos
> > node server.js
> 
> no settings file found, will only use default settings
> { [Error: Cannot find module './settings.json'] code: 'MODULE_NOT_FOUND' }
> { [Error: Cannot find module './settings.json'] code: 'MODULE_NOT_FOUND' }
> { [Error: Cannot find module './settings.json'] code: 'MODULE_NOT_FOUND' }
> http server listening on port 5005
> no preset file, ignoring...
> 
>

**Comment by jishi** [comment]
the npm version will primarily affect the `npm install` invocation. `npm start`is just a thin wrapper for `node server.js` so it has little relevance.

**Comment by jishi** [comment]
I see now that the article listed from OP is actually wrong, he hasn't understood how npm works. This explains the error you guys are seeing. 

You just have to issue `npm install --production`, this will install all dependencies from the package.json file. You do not have to install them separately like he did in the guide, it's unecessary (and obsolete now, as well).

**Comment by k1ll4h8y73** [comment]
Many thanks, @jishi!
I also reveived the suggestion to delete the node_modules folder and perform a new `npm install`. This solved it for me and I can start the server from the terminal. 

However, I'd like to have it automatically started upon system boot rather than manually via a terminal session, but this does not work for some mysterious reason... I've tried to have it started via /etc/rc.local and when invoking this manually from a terminal session, everything's working out just fine: 

`phate@prometheus:~/sonos$ /etc/rc.local 
http server listening on port 5005
no preset file, ignoring...
`
This doesn't work automatically during the boot process though. When checking the status of rc.local, I'm getting confronted with the following: 

`phate@prometheus:~$  systemctl status rc-local.service
● rc-local.service - /etc/rc.local Compatibility
   Loaded: loaded (/lib/systemd/system/rc-local.service; static; vendor preset: enabled)
  Drop-In: /lib/systemd/system/rc-local.service.d
           └─debian.conf
   Active: failed (Result: exit-code) since Fr 2016-09-16 19:09:33 CEST; 3min 11s ago
  Process: 1332 ExecStart=/etc/rc.local start (code=exited, status=1/FAILURE)

Sep 16 19:09:33 prometheus rc.local[1332]: Error: Cannot find module '/home/phate/sonos/server.js'
Sep 16 19:09:33 prometheus rc.local[1332]:     at Function.Module._resolveFilename (module.js:339:15)
Sep 16 19:09:33 prometheus rc.local[1332]:     at Function.Module._load (module.js:290:25)
Sep 16 19:09:33 prometheus rc.local[1332]:     at Function.Module.runMain (module.js:447:10)
Sep 16 19:09:33 prometheus rc.local[1332]:     at startup (node.js:148:18)
Sep 16 19:09:33 prometheus rc.local[1332]:     at node.js:405:3
Sep 16 19:09:33 prometheus systemd[1]: rc-local.service: Control process exited, code=exited status=1
Sep 16 19:09:33 prometheus systemd[1]: Failed to start /etc/rc.local Compatibility.
Sep 16 19:09:33 prometheus systemd[1]: rc-local.service: Unit entered failed state.
Sep 16 19:09:33 prometheus systemd[1]: rc-local.service: Failed with result 'exit-code'.
phate@prometheus:~$ 
`

Does anybody happen to have an idea about what's going wrong here and how I can solve this problem? As rc.local commands are executed with root privileges, I don't expect there being any permission issue or alike... 
Many thanks once again for your input!

**Comment by k1ll4h8y73** [comment]
Update: For some reason, it's working now. I removed the sonos api folder, re-grabbed everything from github and performed `npm install --production` as suggested by @jishi. 
My rc.local now looks like following:

`
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.
# /usr/bin/node /home/phate/sonos/server.js
/usr/bin/node /etc/sonoshttpapi/server.js &
exit 0
`
Everything's working out like a charm now :). Many thanks!
