### ISSUE TITLE
Does SAY work in presets?

### ISSUE THREAD

**Issue by RickStirling** [jishi/node-sonos-http-api#302]
I can't get Voice to work when I try to add it to preset, but it works via a URL.

I have an api key for VoiceRSS, and I've got that in my settings.json. I can use the web UI to send text to a speaker and that works, for example:

http://MYIPHERE:5005/office/say/test%20sonos

announce file for phrase "test%20sonos" does not seem to exist, downloading
undefined 'Office' 'PLAYING'
undefined 'Office' 'STOPPED'
announcement finished

However when I add that to a preset (which returns success), the voice message is telling me that I need a register an API key.

My json is valid with jsonlint

"testsonos": {
    "players": [
      {"roomName": "Office","volume": 20}
    ],
      "say": "Sonos Active"
  },

http://MYIPHERE:5005/office/say/test%20sonos

I get this in my log:

applying preset { players: [ { roomName: 'Office', volume: 20 } ],
  state: 'STOPPED',
  uri: 'http://192.168.1.242:5005/missing_api_key.mp3',
  metadata: '',
  playMode: { repeat: 'none' },
  trackNo: 1,
  elapsedTime: 0 }

**Comment by jishi** [comment]
No, say is not supported in presets, but as you noticed, presets are used for the say command. It's kind of weird that you would get that message ("applying preset") with that preset, it should basically just group your players and then not know what to do. 

There is another issue regarding a similar thing: https://github.com/jishi/node-sonos-http-api/issues/160 and also https://github.com/jishi/node-sonos-http-api/issues/270

Is that what you actually want, or something else? Could you describe your actual need? Or does it fit in any of those suggestions?

**Comment by RickStirling** [comment]
Hmmm, good question.

The reason I was setting it up in this instance was purely as a way to test that the node was running.  I'm updating the presets.json file so much in one terminal window, and then in another I'm killing and restarting the node.

At this point it was just a quick way of testing that the server was up and running.


My actual need? Probably none, maybe this more a matter of curiosity because of the api key aspect.

**Comment by jishi** [comment]
Are you saying that after you have added that preset to preset.json, a *say* command will clain that there is no API key? Then I'm with you. But, that sounds more like you were actually editing settings.json instead of preset.json ;) 

I can't see any reason for this to happen otherwise, but sure, stranger things have happened in my life :D

**Comment by RickStirling** [comment]
Yup, that's exactly it. 

I have the api key in my settings.json and if I use a url with /say/SOME TEXT then that will come of the speaker that I sent it to.  This is the only thing in my settings.json, it's 3 lines long.

If however I have the say command in the preset, that's when the say command fails and tells me I have no api key. The preset will choose the correct speaker and set the volume, and will try to do the say command, but the voiceRSS command just returns the missing mp3 :  'http://192.168.1.242:5005/missing_api_key.mp3',


This is the preset, it's in amongst other presets:

"testsonos": {
"players": [
{"roomName": "Office","volume": 20}
],
"say": "Sonos Active"
},

**Comment by jishi** [comment]
I can't reproduce this. I'm still inclined to believe that you are somehow replacing your settings.json by mistake...
