### ISSUE TITLE
Suggestion - presets folder alongside presets.json

### ISSUE THREAD

**Issue by RickStirling** [jishi/node-sonos-http-api#303]
Having been spending more time setting up presets I find that the presets.json file has become unwieldy. Mine is several hundred lines long.

A suggestion for a future release is a presets folder, where each preset would have a single .json such as bathroomrelax01.json.

On startup this folder would be parsed and each preset added.  This would not replace the root presets.json file, giving people flexibility in the setup.

**Comment by RickStirling** [comment]
As an bonus feature to this, badly written json files could be discarded and logged so that a typo wouldn't prevent the node from restarting.

**Comment by jishi** [comment]
Yeah, I've had the same thought, and also adding a file watcher to reload upon changes (and as you said, ignore non-parsable files instead of crashing). Would probably be more intuitive.

**Comment by jishi** [comment]
Said and done, there is now a presets folder where you can put your presets in, one file per preset. Example in README.

It will also reload (not on all platforms though) when you change the content of the presets folder, automatically! Woop woop!

**Comment by RickStirling** [comment]
Hey, just got around to testing this - GREAT JOB. The live refresh of presets is great too.
