### ISSUE TITLE
Get info on playlists

### ISSUE THREAD

**Issue by ggravlingen** [jishi/node-sonos-http-api#304]
Hi,

I'm pretty sure this is as expected, as there's no [playlists]-command in the Sonos API web page, but I just wanted to make sure.

A few days ago I switched to a new raspberry pi 3 and downloaded the new version of node-sonos-http-api. Before the upgrade I was able to run http://IP/kitchenplayer/playlists and get JSON-output with all my playlists. When I run the same command today, all I get is a blank page. Favorites works as before though. Also, when I invoke http://IP/playlist/test, the system throws the following error (test is the name of my playlist, I have tried other playlists too):

```
{"status":"error","error":"Cannot read property 'find' of undefined","stack":"TypeError: Cannot read property 'find' of undefined\n    at /opt/sonos/lib/actions/playlist.js:6:37\n    at process._tickDomainCallback (node.js:407:9)"}
```

I'm on Node 4.3.2 and running RASPBIAN JESSIE LITE.

Any advise on what I could do to fix this situation is appreciated! If you require further information, please let me know.

Thanks,
Patrik

**Comment by thenickyoung** [comment]
I'm running into the same issue too

**Comment by jishi** [comment]
Looks like this action wasn't correctly converted to the new Promise-style API and is indeed broken. I'll look into it.

**Comment by ggravlingen** [comment]
Thanks and while I have your attention, many thanks (stort tack!) for the great work in building this software!

**Comment by ggravlingen** [comment]
Thanks, I can now list the playlists in the expected manner! When trying to play a specific list through the following command:
`http://192.168.0.140:5005/playlist/Home%20from%20work`

I get the following error:

`{"status":"error","error":"Cannot read property 'find' of undefined","stack":"TypeError: Cannot read property 'find' of undefined\n    at /opt/sonos/lib/actions/playlist.js:6:37\n    at process._tickDomainCallback (node.js:407:9)"}`

Please advise if you want me to provide more logs/details.

Thanks,
Patrik

**Comment by jishi** [comment]
Yeah, stupid error on my part, I probably never tested this. It should work now anyway!

**Comment by ggravlingen** [comment]
I'm afraid not :( The page loads now, which it didn't before.

Going to this URL:
``
http://192.168.0.140:5005/playlist/test
`

Throws this error, however:
`
{"status":"error"}
`

**Comment by jishi** [comment]
What is the output from the console?

**Comment by ggravlingen** [comment]
I run it in the background on my Raspberry. Have you enabled writing directly to a log file somewhere? If not, I'll see if I can enable logging somehow.

**Comment by jishi** [comment]
Either forward it if you control the startup of it with:
`node server.js > output.log`

or kill your background process and start it manually when testing.

**Comment by ggravlingen** [comment]
Long story short, it works now! Sorry about the confusion. 

Long story: while playing around to get the logging to work, I restarted the node.js-service a few times and this did the trick. I did kill the service when trying this morning as well, but apparently I somehow messed up.

**Comment by jishi** [comment]
No problem, glad that it worked itself out!
