### ISSUE TITLE
Error when trying spotify/* and musicsearch/spotify

### ISSUE THREAD

**Issue by shafiqshariff** [jishi/node-sonos-http-api#306]
Tried:  /kitchen/musicsearch/spotify/song/red+hot+chili+peppers

Got the following error:
{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error\n    at Object.invoke (C:\\Users\\shafiq\\Documents\\GitHub\\node-sonos-http-api\\node_modules\\sonos-discovery\\lib\\helpers\\soap.js:92:10)\n    at Player.play (C:\\Users\\shafiq\\Documents\\GitHub\\node-sonos-http-api\\node_modules\\sonos-discovery\\lib\\models\\Player.js:375:15)\n    at C:\\Users\\shafiq\\Documents\\GitHub\\node-sonos-http-api\\lib\\actions\\musicSearch.js:301:48\n    at process._tickCallback (node.js:369:9)"}

Tried:  /Kitchen/spotify/now/spotify:track:4LI1ykYGFCcXPWkrpcU7hn
Error:
{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error\n    at Object.invoke (C:\\Users\\shafiq\\Documents\\GitHub\\node-sonos-http-api\\node_modules\\sonos-discovery\\lib\\helpers\\soap.js:92:10)\n    at Player.addURIToQueue (C:\\Users\\shafiq\\Documents\\GitHub\\node-sonos-http-api\\node_modules\\sonos-discovery\\lib\\models\\Player.js:529:15)\n    at Object.spotify (C:\\Users\\shafiq\\Documents\\GitHub\\node-sonos-http-api\\lib\\actions\\spotify.js:27:31)\n    at handleAction (C:\\Users\\shafiq\\Documents\\GitHub\\node-sonos-http-api\\lib\\sonos-http-api.js:102:35)\n    at HttpAPI.requireDir.requestHandler.handleAction.then [as requestHandler] (C:\\Users\\shafiq\\Documents\\GitHub\\node-sonos-http-api\\lib\\sonos-http-api.js:79:5)\n    at C:\\Users\\shafiq\\Documents\\GitHub\\node-sonos-http-api\\server.js:79:13\n    at Server.finish (C:\\Users\\shafiq\\Documents\\GitHub\\node-sonos-http-api\\node_modules\\node-static\\lib\\node-static.js:111:13)\n    at finish (C:\\Users\\shafiq\\Documents\\GitHub\\node-sonos-http-api\\node_modules\\node-static\\lib\\node-static.js:170:14)\n    at C:\\Users\\shafiq\\Documents\\GitHub\\node-sonos-http-api\\node_modules\\node-static\\lib\\node-static.js:144:17\n    at FSReqWrap.oncomplete (fs.js:82:15)"}

**Comment by jishi** [comment]
Are you in the US or EU? We have some discrepancy still in this library, where music search is hard-coded for US, but the spotify/now is hard-coded for EU. 

Odd that non of them works though, could you check the output from the status page of one of your players?

http://[IP of a player]:1400/status/accounts

and check the 4 digit number for your spotify service (should be 2311 or 3xxx something)?

**Comment by jplourde5** [comment]
It looks like line 301 in musicSearch is where the Play command is issued and the 500 error means server not found.  Sounds like you might have something going on with your network but it seems like it should have failed earlier in the logic too.

The country code is not hard coded but the SID's are defaulted at the US values.  They are easy to set correctly but the error you are getting is not what I've seen in the past if the SID is wrong.

**Comment by shafiqshariff** [comment]
I am in the US.  I tried it again, and it seems to work BUT I still see the exception appear in the command window running the server.
I looked at the status page, and I see a 3079 (nothing identifies it as Spotify, though).  I also see a 6663 and 38663.  Do those help?

 

    On Friday, September 16, 2016 9:24 AM, jplourde5 <notifications@github.com> wrote:
 

 It looks like line 301 in musicSearch is where the Play command is issued and the 500 error means server not found. Sounds like you might have something going on with your network but it seems like it should have failed earlier in the logic too.The country code is not hard coded but the SID's are defaulted at the US values. They are easy to set correctly but the error you are getting is not what I've seen in the past if the SID is wrong.—

**Comment by jplourde5** [comment]
Another interesting point that I just noticed is that the two different commands you are invoking (musicSearch and Spotify) are different actions with different code.

**Comment by sisheffield** [comment]
Hi. Thx for the project. I am getting the same error when I try to use the musicsearch (stack below). I'm in the UK, and the 4 digit number for my Spotify service is 2311. Is there something obvious I can check out?
thx

{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error\n    at Object.invoke (/volume1/homes/admin/node-sonos-http-api-master/node_modules/sonos-discovery/lib/helpers/soap.js:92:10)\n    at Player.addURIToQueue (/volume1/homes/admin/node-sonos-http-api-master/node_modules/sonos-discovery/lib/models/Player.js:533:15)\n    at /volume1/homes/admin/node-sonos-http-api-master/lib/actions/musicSearch.js:299:48\n    at process._tickCallback (node.js:368:9

**Comment by jplourde5** [comment]
Yah, I believe that is different than the US default.  Do the following:

1. Add a song track from Spotify to your Sonos Favorites
2. Look in your Sonos Favorites and note the exact spelling of how it was saved
3. Invoke the URL   .../YOUR_ROOM/musicsearch/spotify/setsid/EXACT_NAME_OF_SONG

This will read the service ID from the song, save your sids on disk in lib/sids.json with the updated sid, and use them from now on. Save and return this file when you update the api, or follow the same steps again.

**Comment by sisheffield** [comment]
Thank you. I'll try this out.

**Comment by red3all** [comment]
Just followed the above from jplourde5 above and it seems to have fixed the issue for me in the UK.  Im only testing via the amazon utterance simulator as Im linking this using echo, but it appears to be working.  Can confirm 100% when I get home in a few hours.

**Comment by sisheffield** [comment]
I'm linking to echo too. Trying the fix now.

**Comment by jishi** [comment]
@jplourde5 in 1.0.1 you now have getServiceId() and getServiceType() on the SonosSystem instance that will lookup these values based on service name. Specifically:

system.getServiceId('Spotify') returns 9 in EU, 12 in US (hopefully)
system.getServiceType('Spotify') returns 2311 in EU, 3079 in US

That would mitigate the need for the favorites hack. I'm gonna try and add token lookup via nickname as well eventually.

**Comment by jplourde5** [comment]
I just saw the above which answers the question that I posted a little earlier in another thread.  I'll give it a try.

**Comment by jishi** [comment]
Both these endpoints now discover the required IDs for the region you are in.
