### ISSUE TITLE
TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by GregRocket** [jishi/node-sonos-http-api#308]
Not sure when this started. I have been updating with each new commit and pandora pull requests.

**Here is the console error I am seeing:**
[TypeError: Cannot read property 'startsWith' of undefined] 'TypeError: Cannot read property \'startsWith\' of undefined\n    at /root/node-sonos-http-api-master/node_modules/sonos-discovery/lib/models/Player.js:262:36\n    at process._tickCallback (node.js:364:9)'

Seems like whenever I issue any command now, this error shows. Although the commands work.

**Comment by jishi** [comment]
This should be resolved in beta.24
