### ISSUE TITLE
MusicSearch Albums not in Album Order

### ISSUE THREAD

**Issue by GregRocket** [jishi/node-sonos-http-api#309]
@jplourde5 
When using musicsearh to load an album from the sonos music library, the albums load but are not in album order. I've included a couple of screen shots showing the album order in sonos and the album order that is loaded with musicsearch.

Commands issued:
/media%20room/musicsearch/library/album/killers+sams+town
/media%20room/musicsearch/library/album/journey+evolution

![01](https://cloud.githubusercontent.com/assets/12052578/18600169/288a11e4-7c11-11e6-9f8d-d0e8ea820f2b.jpg)

![02](https://cloud.githubusercontent.com/assets/12052578/18600171/2a3f3488-7c11-11e6-9509-68faff060aca.jpg)

**Comment by jplourde5** [comment]
Do you have the more recent version? I added a shuffle when there was more than one song for an artist search do that you wouldn't have the same first song every time. I later changed the code to skip the shuffle if the type was an album. It should not be shuffling albums anymore.

**Comment by GregRocket** [comment]
Yes I have the latest version. MusicSearch does not seem to be shuffling the album songs, just not loading in album order. If I load the same album again, the album loads in the same order every time, just not in album order.

**Comment by jplourde5** [comment]
I see what is happening. It is loading them in the order in which they are coming back from querying Sonos when building the library file.  I'm going to need to load the album container instead of simply all of the tracks for the album.

**Comment by jplourde5** [comment]
This is fixed with the latest release

**Comment by GregRocket** [comment]
@jplourde5 I did a fresh install of api beta 2.4. I ran load and noticed an error while indexing (see below) that did not happen in previous versions. The indexing did continue after the error. I tried some albums and they did work and they were in album order (Yea!). The album search is also very fast. Nice work, Thanks for making this great API better.

As for the error, I've run load a couple of times and I get a random error when indexing. The error is not always at Count 3000. Also the indexing used to stop at 44149 but now it adds more numbers to the bottom. 

I'm not sure if the error is anything to worry about or not.

Loading Library
Count 0
Count 1000
Count 2000
Count 3000
2016-09-20T18:23:48.813Z ERROR
  TypeError: Cannot read property 'items' of undefined
    at /root/node-sonos-http-api-master/lib/music_services/libraryDef.js:224:47
Count 4000
Count 5000
...(I'm skipping numbers to make post smaller)...
Count 43000
Count 44000
Count 44149
Count 1000
Count 2000
Count 3000
Count 3087

**Comment by jplourde5** [comment]
Sounds like it is getting an empty value on a Sonos query.  Are you only getting one error?

The two counts are expected.  The first is the count of the tracks and the second is the count of the albums.  I had to build two separate indexes to solve the issue.  Apparently there is no album order in how the tracks are stored or returned.

**Comment by GregRocket** [comment]
Yes, I only get one error. The same error pops up during an index after different numbers. Could be right after 3000 one time and after 5000 the next time. I did test 5 or 6 albums and all loaded correctly, in the right order and played (and real fast too). I'm not going to worry about the error for now and I'm going to close this issue. I'll let you know if anything breaks but it seems to be working fine right now. Thanks again.
