### ISSUE TITLE
Webhook mute status

### ISSUE THREAD

**Issue by steevebrush** [jishi/node-sonos-http-api#315]
Hello,
I use webhook to handle domoticz via a small node app, very convenient !
is it possible to have the mute status when mute button is pressed ? I can see the status in the webhook json but there is no webhook update when mute is physically pressed or release...

**Comment by jishi** [comment]
Yes, it should be possible to add, I would have guessed it was part already of the volume event (that doesn't seem to be documented though...) there is a third one called "volume-change" that occurs for all players when you modify volume. 

I see now that it doesn't contain mute, but it would be easy to add. I will do it as soon as I get the time (maybe this weekend).

**Comment by jishi** [comment]
Added with the last commit

**Comment by steevebrush** [comment]
Thanx ! I 'll try as soon as possible !

**Comment by steevebrush** [comment]
Thank you, it works fine...
