### ISSUE TITLE
action pandora not found

### ISSUE THREAD

**Issue by NovaGL** [jishi/node-sonos-http-api#317]
Missing something obvious I would imagine.

/root/.nvm/versions/node/v4.2.3/lib/node_modules/sonos-http-api/lib/actions/pandora. js exists

settings.json in /root/.nvm/versions/node/v4.2.3/lib/node_modules/sonos-http-api

```
 {
      "port": 5005,
      "cacheDir": "./cache",
      "announceVolume": 40,
     "pandora": {
        "username": "xxx",
        "password": "xxx"
      }
    }
```

I have set my username and password.

**Comment by jplourde5** [comment]
What is the exact url that you are using?

**Comment by jishi** [comment]
You have installed it weirdly. sonos-htt-api should be under the global node_modules like that. I know it might work, but it will render certain file includes useless.

Just download the zip, unzip (or use git clone) and then run `npm install --production` from there.

https://github.com/jishi/node-sonos-http-api/archive/master.zip

**Comment by NovaGL** [comment]
So where should the location be? I did nom install production

**Comment by NovaGL** [comment]
Now it's going to the correct path, but it times out trying to do any pandora related commands

```
ep 29 19:10:56 pi node-sonos[16712]: /node-sonos-http-api/lib/actions/pandora.js:126
Sep 29 19:10:56 pi node-sonos[16712]: return pandoraAPI("station.addFeedback", {"stationToken" : stationToken, "trackToken" : trackToken, "isPositive" : up})
Sep 29 19:10:56 pi node-sonos[16712]: ^
Sep 29 19:10:56 pi node-sonos[16712]: ReferenceError: up is not defined
Sep 29 19:10:56 pi node-sonos[16712]: at Object.pandora (/node-sonos-http-api/lib/actions/pandora.js:126:124)
Sep 29 19:10:56 pi node-sonos[16712]: at handleAction (/node-sonos-http-api/lib/sonos-http-api.js:106:35)
Sep 29 19:10:56 pi node-sonos[16712]: at HttpAPI.requireDir.requestHandler.handleAction.then [as requestHandler] (/node-sonos-http-api/lib/sonos-http-api.js:83:5)
Sep 29 19:10:56 pi node-sonos[16712]: at /node-sonos-http-api/server.js:80:13
Sep 29 19:10:56 pi node-sonos[16712]: at Server.finish (/node-sonos-http-api/node_modules/node-static/lib/node-static.js:111:13)
Sep 29 19:10:56 pi node-sonos[16712]: at finish (/node-sonos-http-api/node_modules/node-static/lib/node-static.js:170:14)
Sep 29 19:10:56 pi node-sonos[16712]: at /node-sonos-http-api/node_modules/node-static/lib/node-static.js:144:17
Sep 29 19:10:56 pi node-sonos[16712]: at FSReqWrap.oncomplete (fs.js:82:15)
Sep 29 19:10:56 pi systemd[1]: node-sonos.service: main process exited, code=exited, status=1/FAILURE
Sep 29 19:10:56 pi systemd[1]: Unit node-sonos.service entered failed state.

```

**Comment by NovaGL** [comment]
Help please.

**Comment by jplourde5** [comment]
The problem was introduced when I did some earlier streamlining.  I just submitted the fix.  You can add the following at line 125 in pandora.js in the mean time.

        const up = (cmd == 'thumbsup');

**Comment by NovaGL** [comment]
Will try soon. It also crashes if you just do /Pandora

**Comment by jplourde5** [comment]
You have to pass addition info after Pandora. I'all take a look at the authentication problem when I get a chance, probably tomorrow

**Comment by NovaGL** [comment]
Thanks, I still think you should some error catching so it doesn't crash

**Comment by jplourde5** [comment]
Fix for authentication problem has been tested and submitted. REPLACING line 127 in pandora.js with the following TWO lines will fix your problem.

        return userLogin()
          .then(() => pandoraAPI("station.addFeedback", {"stationToken" : stationToken, "trackToken" : trackToken, "isPositive" : up}))

**Comment by NovaGL** [comment]
It works!
`{"status":"success"}
`

Do you know why I am getting this?

```
2016-10-03T06:11:42.129Z ERROR
  { error: 'action \'favicon.ico\' not found' }

```

**Comment by jishi** [comment]
This is just a browser behavior. It always tries to fetch a /favicon.ico when requesting URLs, you can ignore it.
