### ISSUE TITLE
Loading library fails

### ISSUE THREAD

**Issue by SvenRobson** [jishi/node-sonos-http-api#319]
I'm having an issue when loading the music library -- it appears to load the entire library, restart from the beginning, and then quickly fail. Output below. Any ideas? Thanks in advance for any help.

> Count 47000
Count 48000
Count 49000
Count 50000
Count 50107
Count 1000
Count 2000
c:\node-sonos-http-api-master\node_modules\sonos-discovery\lib\models\Player.js:
684
            uri: item.res.$text,
                         ^

> TypeError: Cannot read property '$text' of undefined
>     at EventEmitter.<anonymous> (c:\node-sonos-http-api-master\node_modules\sono
> s-discovery\lib\models\Player.js:684:26)
>     at emitOne (events.js:77:13)
>     at EventEmitter.emit (events.js:169:7)
>     at SAXStream.onCloseTag (c:\node-sonos-http-api-master\node_modules\xml-flow
> \lib\xml-flow.js:131:15)
>     at emitOne (events.js:77:13)
>     at SAXStream.emit (events.js:169:7)
>     at Object.me._parser.(anonymous function) [as onclosetag] (c:\node-sonos-htt
> p-api-master\node_modules\sax\lib\sax.js:258:17)
>     at emit (c:\node-sonos-http-api-master\node_modules\sax\lib\sax.js:640:35)
>     at emitNode (c:\node-sonos-http-api-master\node_modules\sax\lib\sax.js:645:5
> )
>     at closeTag (c:\node-sonos-http-api-master\node_modules\sax\lib\sax.js:905:7
> )
>     at Object.write (c:\node-sonos-http-api-master\node_modules\sax\lib\sax.js:1
> 449:13)
>     at SAXStream.write (c:\node-sonos-http-api-master\node_modules\sax\lib\sax.j
> s:239:18)
>     at Readable.ondata (_stream_readable.js:528:20)
>     at emitOne (events.js:77:13)
>     at Readable.emit (events.js:169:7)
>     at readableAddChunk (_stream_readable.js:146:16)
> 
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
> node_modules\\npm\\bin\\npm-cli.js" "start"
> npm ERR! node v4.3.2
> npm ERR! npm  v3.10.8
> npm ERR! code ELIFECYCLE
> npm ERR! sonos-http-api@1.0.0 start: `node server.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the sonos-http-api@1.0.0 start script 'node server.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the sonos-http-api packag
> e,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node server.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs sonos-http-api
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls sonos-http-api
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     c:\node-sonos-http-api-master\npm-debug.log
> 
> c:\node-sonos-http-api-master>

**Comment by jplourde5** [comment]
I just submitted a fix and log clarification on what the Count is.  The first count that you see is for the tracks and the second count is for the albums, so it isn't starting over.  I also added a check for entries missing values which is causing the exception that you are seeing.  You can pull down and replace the libraryDef.js attached in the pull request and replace the one in lib/music_services with it for now.

**Comment by jplourde5** [comment]
The fix has been merged.  You can reinstall or grab and replace the libraryDef.js file.

**Comment by SvenRobson** [comment]
Got it -- thanks a ton for the quick response -- what is the best way to figure out what missing values are causing the exception? The output after the error appears the same other than the addition of <anonymous> after EventEmitter in the TypeError description. Hoping to avoid having to retag the whole library.

> 
> . . .
> Track Count 47000
> Track Count 48000
> Track Count 49000
> Track Count 50000
> Track Count 50107
> Album Count 1000
> Album Count 2000
> c:\sonos\node_modules\sonos-discovery\lib\models\Player.js:684
>             uri: item.res.$text,
>                          ^
> 
> TypeError: Cannot read property '$text' of undefined
>     at EventEmitter.<anonymous> (c:\sonos\node_modules\sonos-discovery\lib\model
> s\Player.js:684:26)
>     at emitOne (events.js:77:13)
>     at EventEmitter.emit (events.js:169:7)
>     at SAXStream.onCloseTag (c:\sonos\node_modules\xml-flow\lib\xml-flow.js:131:
> 15)
>     at emitOne (events.js:77:13)
>     at SAXStream.emit (events.js:169:7)
>     at Object.me._parser.(anonymous function) [as onclosetag] (c:\sonos\node_mod
> ules\sax\lib\sax.js:258:17)
>     at emit (c:\sonos\node_modules\sax\lib\sax.js:640:35)
>     at emitNode (c:\sonos\node_modules\sax\lib\sax.js:645:5)
>     at closeTag (c:\sonos\node_modules\sax\lib\sax.js:905:7)
>     at Object.write (c:\sonos\node_modules\sax\lib\sax.js:1449:13)
>     at SAXStream.write (c:\sonos\node_modules\sax\lib\sax.js:239:18)
>     at Readable.ondata (_stream_readable.js:528:20)
>     at emitOne (events.js:77:13)
>     at Readable.emit (events.js:169:7)
>     at readableAddChunk (_stream_readable.js:146:16)
> 
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
> node_modules\\npm\\bin\\npm-cli.js" "start"
> npm ERR! node v4.3.2
> npm ERR! npm  v3.10.8
> npm ERR! code ELIFECYCLE
> npm ERR! sonos-http-api@1.0.0 start: `node server.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the sonos-http-api@1.0.0 start script 'node server.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the sonos-http-api packag
> e,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node server.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs sonos-http-api
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls sonos-http-api
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     c:\sonos\npm-debug.log
> 
> c:\sonos>

**Comment by jishi** [comment]
I'm assuming this is thrown when parsing the browse xml from the sonos
player.

**Comment by SvenRobson** [comment]
OK, figured this out -- I had a bunch of poorly tagged mp3s where the album name was a series of spaces. Replaced the spaces with album titles (or in some cases just deleted the spaces so there was no title), did a library update, and everything is working swimmingly. Thanks!
