### ISSUE TITLE
Server Hangs On Start

### ISSUE THREAD

**Issue by ronnycarr** [jishi/node-sonos-http-api#32]
Hi there, I just grabbed the latest version and ran npm install and the server is hanging on start after checking the presets. I tried starting without the preset file but it does the same thing, any thoughts?

Thanks for the help!

**Comment by jishi** [comment]
Hi. I did a clean download and ran npm install and it's working as expected, this is the output:

PS C:\temp\node-sonos-http-api-master> node .\server.js
no preset file, ignoring...
http server listening on port 5005

Do you see the last line in your console? Which platform are you running on?

**Comment by jishi** [comment]
Also, delete the node_modules folder before running npm install

**Comment by ronnycarr** [comment]
I did a clean install and all looks good. Sorry about that! Thanks for responding though!
