### ISSUE TITLE
issue (re)installing the api

### ISSUE THREAD

**Issue by autofrank** [jishi/node-sonos-http-api#323]
hi,
this is my own fault so sorry in advance
I wanted to upgrade to the latest version and could find an upgrade path so I deleted the node-sonos-api folder on my pi and also the settings.json file

I then tried the  new install with 
sudo npm install https://github.com/jishi/node-sonos-http-api.git

and get the following output...

`pi@raspberrypi:~/Desktop $ sudo npm install https://github.com/jishi/node-sonos-http-api.git
sonos-http-api@1.0.0 ../node_modules/sonos-http-api
├── basic-auth@1.0.4
├── node-static@0.7.9 (mime@1.3.4, colors@1.1.2, optimist@0.6.1)
├── sonos-discovery@1.0.0-beta.24 (html-entities@1.0.10, xml-flow@1.0.1)
├── anesidora@1.2.1 (underscore@1.8.3, request@2.75.0)
├── fuse.js@2.5.0
└── request-promise@1.0.2 (cls-bluebird@1.1.3, bluebird@2.11.0, request@2.75.0, lodash@3.10.1)
pi@raspberrypi:~/Desktop $`

and no new folder is created

I also tried npm install --production

and got the following...

pi@raspberrypi:~ $ npm install --production
npm ERR! install Couldn't read dependencies
npm ERR! Linux 4.4.11-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! path /home/pi/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.
npm ERR! Please include the following file with any support request:

any suggestions as to how I fix the mess I made

Thanks
-F

**Comment by autofrank** [comment]
okay - I (half) solved this a different way as I used the pre-compiled image based on the alpine image

I am trying to edit the settings.json file but the command set is much more restricted than a regular Pi image, (no ls, nano, etc commands) I search the alpine wiki but I cant see how I can edit the settings.json file to add my voicers key

**Comment by jishi** [comment]
You can install most packages by issuing:

`apk add nano`

for example. Persist it through reboots with `lbu_commit`. That way you can probably get all tools you want for editing settings.json.

**Comment by autofrank** [comment]
thanks
apk add nano worked but else worked beyond that such as apk add ls, etc
it powered up the sonos prompt - do you know where the settings.json file is relative to this.
Do I need to create it or just edit it assuming that it exists with your distribution ?

thoughts ?

**Comment by autofrank** [comment]
This is what I get when I log into the pi

login as: root
Welcome to the Sonos Utility System!

This installation is based on Alpine Linux.

The Alpine Wiki contains a large amount of how-to guides and general
information about administrating Alpine systems.
See <http://wiki.alpinelinux.org>.

-ash: /etc/profile.d/bash_completion.sh: line 5: syntax error: bad substitution
sonos:~#

I tried creating settings.json at this location but it didnt work
without ls or a structure of the folders I cant do much more 

any help appreciated
Thanks
Frank

**Comment by jishi** [comment]
I don't remember where I put the files, it's on a separate partition that is mounted in /storage or /flash if I recall correctly. Can verify later, I have an SD-card laying around with this on.

**Comment by autofrank** [comment]
thanks - I'm trying again with a new install of the image just in case something got corrupt. Its seems odd that that the alpine image doesn't come with nano or ls

-Frank

**Comment by jishi** [comment]
nano is expected, it is a very limited image, but basic file system commands like ls, cp, mv should work.

**Comment by autofrank** [comment]
the prompt is sonos:~# 
I logged in as root with no password. Do you know if there is any other login  I could use. Could the samba add on get me access to the settings.json for editing it ?

**Comment by autofrank** [comment]
These are the commands that are available


sonos:~# help
Built-in commands:
------------------
        . : [ [[ alias bg break cd chdir command continue echo eval exec
        exit export false fg getopts hash help history jobs kill let
        local printf pwd read readonly return set shift source test times
        trap true type ulimit umask unalias unset wait

**Comment by autofrank** [comment]
okay - might be something here...

pwd reveals that I'm at the root 

sonos:~# pwd
/root
sonos:~#

your notes on settings.json would seem to suggest that I need to create the file in the root

settings.json

If you want to change default settings, you can create a settings.json file and put in the root folder.

settings.json : 
If you want to change default settings, you can create a settings.json file and put in the root folder.

If this is correct I should just be able to use nano to create the file at the level I have access to 
Does this could correct ?

**Comment by autofrank** [comment]
"ls" does work.. the problem is there is no files at the root level 
I tried to create a folder using mkdir and ls displayed it 

sonos:~# mkdir frank
sonos:~# ls
frank
sonos:~#

so it seems like the issue is I'm not sure where to go to put the settings.json file in

**Comment by jishi** [comment]
Yeah, thats some poor wording on my part. What I meant was the root folder as in the sonos-http-api folder. Which should be /storage/sonos-http-api or /flash/sonos-http-api

**Comment by autofrank** [comment]
no worries
looks like I can't cd from whereever I am to either of these locations


sonos:~# cd /storage/sonos-http-api
-ash: cd: can't cd to /storage/sonos-http-api
sonos:~# cd /fash/sonos-http-api
-ash: cd: can't cd to /fash/sonos-http-api
sonos:~#

any thoughts ?
thx

**Comment by jishi** [comment]
I booted it up now, and the http-api root is: `/flash/apps/sonos-http-api` create a settings.json in there and you should be good to go. In order to restart the http-api, just kill the running process, it would restart within 10 seconds.

find it with `ps aux|grep sonos-http-api`, then invoke `kill [pid]`

**Comment by autofrank** [comment]
right - almost there

I installed Samba and then mapped a network drive to the pi

I can see a folder called "flash" and can navigate to "apps" and into a "sonos-http-api" folder
I tried dropping in a settings.json file but it didn't fix the issue but I think it may be how I am creating the file and its extension and I should be able to solve that

I assume in the folder that I'm displaying in the attached image below ??

![image](https://cloud.githubusercontent.com/assets/20369477/19022881/c41e479a-88d9-11e6-8bea-56ef05befcf4.png)


I'm out of time this evening but will give it a go tomorrow evening . If it works I'll document the few steps in case somebody else wants to use voicers and the pre-composed image

thanks again for the api and the help
will keep you posted

-Frank

**Comment by autofrank** [comment]
![image](https://cloud.githubusercontent.com/assets/20369477/19022899/2db18ae6-88da-11e6-89a5-a3a9480ee67e.png)

**Comment by jishi** [comment]
As long as the file has the actual filename settings.json (you are hiding file extensions), it should work, but the app needs to be restarted for it to take effect.

**Comment by autofrank** [comment]
That should sort it... i never rebootedWill comfirm tomorriw evening and document for other newbee's like me :)
Thanks again-f


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Jimmy Shimizu <notifications@github.com> Date: 02/10/2016  19:56  (GMT+00:00) To: jishi/node-sonos-http-api <node-sonos-http-api@noreply.github.com> Cc: autofrank <frank.tp.smith@gmail.com>, Author <author@noreply.github.com> Subject: Re: [jishi/node-sonos-http-api] issue (re)installing the api (#323) 
As long as the file has the actual filename settings.json (you are hiding file extensions), it should work, but the app needs to be restarted for it to take effect.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jishi/node-sonos-http-api","title":"jishi/node-sonos-http-api","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jishi/node-sonos-http-api"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jishi in #323: As long as the file has the actual filename settings.json (you are hiding file extensions), it should work, but the app needs to be restarted for it to take effect."}],"action":{"name":"View Issue","url":"https://github.com/jishi/node-sonos-http-api/issues/323#issuecomment-250988305"}}}

**Comment by autofrank** [comment]
I rebooted the pi and did q quick check and all seems good now. 
thanks for the help

BTW - does the readme contain all the options available with the new beta such as the say with the volume and some of the new grouping ?

-Frank
