### ISSUE TITLE
how to update to the latest master branch

### ISSUE THREAD

**Issue by autofrank** [jishi/node-sonos-http-api#327]
Hi,
I completed a fresh install using the precomposed image yesterday (which looks like it was created using beta 16)

I was about to use the presets file and noticed that the latest has a presets folder.

How do I update my precomposed pi setup to the latest master branch so i can take advantage of the presets folder and latest features ?

Thanks
-f

**Comment by jishi** [comment]
Easiest would probably be to unzip the master zip over the previous folder,
then invoking npm install from an ssh session.

**Comment by autofrank** [comment]
Thanks but im not sure how to do thatI can grab the master and pkace into the folder at the same level as the existing sonos-http-api on fpash share..but when i ssh into the pi i and up at yhe sonos prompt and dont know how to navigate from there to the new files
I imagine recreating the pre-composed image with the latest master would be very time consuming and probably not worth the efgort 
Thx


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Jimmy Shimizu <notifications@github.com> Date: 03/10/2016  15:50  (GMT+00:00) To: jishi/node-sonos-http-api <node-sonos-http-api@noreply.github.com> Cc: autofrank <frank.tp.smith@gmail.com>, Author <author@noreply.github.com> Subject: Re: [jishi/node-sonos-http-api] how to update to the latest master branch (#327) 
Easiest would probably be to unzip the master zip over the previous folder,

then invoking npm install from an ssh session.



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jishi/node-sonos-http-api","title":"jishi/node-sonos-http-api","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jishi/node-sonos-http-api"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jishi in #327: Easiest would probably be to unzip the master zip over the previous folder,\nthen invoking npm install from an ssh session.\n"}],"action":{"name":"View Issue","url":"https://github.com/jishi/node-sonos-http-api/issues/327#issuecomment-251126855"}}}

**Comment by RickStirling** [comment]
Hey, I just did this on my pi. 

For me, the old node was installed to /usr/local/lib/node_modules/ in a folder called node-sonos-http-api


I renamed that node-sonos-http-api-old

Do you have git installed? If you do you can navigate to your node_modules folder and type

sudo git clone https://github.com/jishi/node-sonos-http-api.git

That will download the latest version next to the previous version. You can then copy files from the old to the new as you see fit.

**Comment by autofrank** [comment]
Thanks Rick - I'll give this a go later

-f

**Comment by autofrank** [comment]
..sorry - I assume I install git on my pc and not the pi to do as you suggest ??

**Comment by jishi** [comment]
Might be easier to (from an SSH session), do this:

`cd /flash/apps`
`wget https://github.com/jishi/node-sonos-http-api/archive/master.tar.gz`
`tar -zxf master.tar.gz`

You now should have a folder called `node-sonos-http-api` alongside the original `sonos-http-api`. Rename the old one, and rename the new one to match the old name:

`mv sonos-http-api sonos-http-api-backup`
`mv node-sonos-http-api sonos-http-api`

Move your settings.json from the backup folder, into the new folder: 
`mv sonos-http-api-backup/settings.json sonos-http-api/`

**Comment by jishi** [comment]
I will probably update the precompiled image in the coming week. I have dropped the beta-flag and will probably start maintaining 1.0.x as a stable version from now on, because it is starting to get out of hand to just have a master branch :)

**Comment by autofrank** [comment]
Thanks Jimmy,
I'll give the SSH approach a go later when I get home and if all else fails I can wait for the pre-composed image 

really appreciate the help
-f

**Comment by autofrank** [comment]
hi,
The ssh instructions worked well and all the new files are place
.. but it looks like the service didnt start

when I try 
`http://192.168.1.89:5005/kitchen/state`

I get 

![image](https://cloud.githubusercontent.com/assets/20369477/19087017/6cce71a0-8a68-11e6-9796-4fa5e395d62e.png)

Is there some log file I can look into to see what stopped it from running ?

ironically - when I first upgraded but hadn't rebooted the PI I was able to get a response to the /state command but found that some of the information such as title was blank
.. then I rebooted and /state doesn't return anything.

I tried the fresh install again in case something got corrupted but no luck

any thoughts ?

Thx
-f

**Comment by jishi** [comment]
Sorry, forgot one last crucial step... I added it to the last comment, it's the:

`cd sonos-http-api`
`npm install --production`

It couldn't start since it was lacking the relevant libraries. Before you restarted it, it still ran the old version (from memory).

**Comment by autofrank** [comment]
okay - that did the trick, the api is up and running
state request not return what I would expect

the preset folder seem to be having an issue

i created a number of preset files and none seemed to work

![image](https://cloud.githubusercontent.com/assets/20369477/19091316/09c662fe-8a7a-11e6-8bbf-6c3fc2f9e51f.png)

I modified the example.json that came with the master install with some of my player names

`{
  "players": [
    {
      "roomName": "Garage",
      "volume": 2
    },
    {
      "roomName": "Kitchen",
      "volume": 2
    },
    {
      "roomName": "Hallway",
      "volume": 2
    },
    {
      "roomName": "Living_Room",
      "volume": 2
    },
    {
      "roomName": "Dining_Room",
      "volume": 2
    }
  ],
  "playMode": {
    "shuffle": true,
    "repeat": "all",
    "crossfade": false
  },
  "pauseOthers": false,
  "favorite": "4fm"
}`

and I get the following error in the browser

`{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error\n    at Object.invoke (/flash/apps/sonos-http-api/node_modules/sonos-discovery/lib/helpers/soap.js:92:10)\n    at Player.repeat (/flash/apps/sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:582:15)\n    at /flash/apps/sonos-http-api/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:121:48\n    at process._tickCallback (node.js:369:9)"}`

the player names are all valid and the favorite works with the /favorite request

`http://192.168.1.89:5005/playroom/favorite/4fm`
`{"status":"success"}`

Is there an issue with the format of the preset file or is there another gremlin at play here

**Comment by jishi** [comment]
I guess that is a radiostation? You can't have repeat set on a radio
station. I don't think shuffle works either. Just remove that from your
preset and try it again.

**Comment by autofrank** [comment]
I spotted that the preset works despite the error

I removed the PlayMode completely

`{
  "players": [
    {
      "roomName": "Garage",
      "volume": 2
    },
    {
      "roomName": "Kitchen",
      "volume": 2
    },
    {
      "roomName": "Hallway",
      "volume": 2
    },
    {
      "roomName": "Living_Room",
      "volume": 2
    },
    {
      "roomName": "Dining_Room",
      "volume": 2
    }
  ],
  "pauseOthers": false,
  "favorite": "4fm"
}`

No change - error still is 

`{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error\n    at Object.invoke (/flash/apps/sonos-http-api/node_modules/sonos-discovery/lib/helpers/soap.js:92:10)\n    at Player.repeat (/flash/apps/sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:582:15)\n    at /flash/apps/sonos-http-api/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:121:48\n    at process._tickCallback (node.js:369:9)"}`

Do I need to restart the api ?

**Comment by autofrank** [comment]
I restarted the api and success - thanks
