### ISSUE TITLE
Error with new presets folder, data works with previous build and presets.json

### ISSUE THREAD

**Issue by RickStirling** [jishi/node-sonos-http-api#328]
I posted this reply in the suggestions, but since that was closed I thought I'd open a new issue.

https://github.com/jishi/node-sonos-http-api/issues/303

I switched to the latest build with the new preset folder. It runs and it collects all preset jsons from the folder. I can see these update in a terminal window each time I add one, and if I refresh my browser with IP:5005/preset/ I can see them being listed.

However, these presets all give me an error. I'm getting errors. I've stripped this back to the core with a single preset in the folder and I'm still getting issues.

This is my output when I start the server with a single preset called testpiurl.json and then go to IP:5005/preset/testpiurl

sonos-http-api@1.0.0 start /usr/local/lib/node_modules/node-sonos-http-api
node server.js
2016-10-03T22:55:11.481Z INFO Presets loaded: { testpiurl: 
{ testpiurl: 
{ players: [ { roomName: 'Office', volume: 5 } ],
state: 'playing',
favorite: 'Wild World',
uri: 'x-rincon-stream:RINCON_0000000000001400' } } }
2016-10-03T22:55:11.565Z INFO http server listening on port 5005
2016-10-03T22:55:25.384Z ERROR 
TypeError: Cannot read property 'map' of undefined
at /usr/local/lib/node_modules/node-sonos-http-api/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:88:29

I have one preset in my presets folder, testpiurl.json which JSON lint says is valid:

{
"testpiurl": {
"players": [{
"roomName": "Office",
"volume": 5
}],
"state": "playing",
"favorite": "Wild World",
"uri": "x-rincon-stream:RINCON_0000000000001400"
}
}

If I kill the server and go to the old install, copy in that preset and rename it presets.json, then start that version of the server, it's working as expected.

**Comment by jishi** [comment]
This is a good catch. The presets folder file shouldn't follow the same syntax as presets.json, since now 1 file = 1 preset. It should only contain the preset, and it should not be under a property with the name (since the name will be taken from the filename).

change
```
{
  "testpiurl": {
    "players": [
      {
        "roomName": "Office",
        "volume": 5
      }
    ],
    "state": "playing",
    "favorite": "Wild World",
    "uri": "x-rincon-stream:RINCON_0000000000001400"
  }
}```

to 

```
{
  "players": [
    {
      "roomName": "Office",
      "volume": 5
    }
  ],
  "state": "playing",
  "favorite": "Wild World",
  "uri": "x-rincon-stream:RINCON_0000000000001400"
}
```

I will add a schema validator to the presets to catch these kind of errors with a useful description in the future.

**Comment by RickStirling** [comment]
Perfect, I'll give that a go and update the thread.

**Comment by GregRocket** [comment]
What is **"state": "playing",** for?

**Comment by jishi** [comment]
Which state it should restore when applying the preset. "playing" is actually the default, but you can have "stopped" which supposedly should not start playback after preset has been applied (although I don't think it would stop it if it was already playing, unless pauseOthers: true).

**Comment by GregRocket** [comment]
OK got it. Thanks.

**Comment by autofrank** [comment]
The preset folder is working for me with the latest branch

this is the example.json that works

`{
  "players": [
    {
      "roomName": "Garage",
      "volume": 2
    },
    {
      "roomName": "Kitchen",
      "volume": 2
    },
    {
      "roomName": "Hallway",
      "volume": 2
    },
    {
      "roomName": "Living_Room",
      "volume": 2
    },
    {
      "roomName": "Dining_Room",
      "volume": 2
    }
  ],
  "pauseOthers": false,
  "favorite": "4fm"
}`

**Comment by RickStirling** [comment]
Just an update to confirm that removing the extra information from the old presets makes the new ones work.

This is a much cleaner implementation than the older single file version, thanks!
