### ISSUE TITLE
Ungroup for a set of zones

### ISSUE THREAD

**Issue by autofrank** [jishi/node-sonos-http-api#329]
Hi,
Would it be possible to create an ungroup and specify the zones you want to ungroup.
...it would be almost like the reverse of a preset

My use case is as follows
I have 6 zones upstairs and 7 zones downstairs and generally operate them separately.
I like to baseline all the zones mid morning or whenever nobody is in the house and them group them (using presets now)  depending on different events - getting up in the morning, mum arriving home, kids in from school, etc

I have been doing this ungroup with a multitude of ungroup http requests from my HA but find that they don't always fire reliably plus its a lot of traffic.

It would be great to be able to issue one request to ungroup all of the upstairs zones or all of the downstairs zones  

You shared a js script for an ungroupall some time ago

`'use strict';
const logger = require('sonos-discovery/lib/helpers/logger');
let system;

function ungroupAll() {
  return system.players.reduce((promise, player) => {
    return promise.then(() => player.becomeCoordinatorOfStandaloneGroup()
      .catch((err) => {
        // mitigate any errors that occurs.
        logger.warn(err);
      }))
  }, Promise.resolve());
}

module.exports = function (api) {
  api.registerAction('ungroupall', ungroupAll);
  system = api.discovery;
};`

I could use this ungroup-all function coupled with presets if the ungroup-set-of-zones was too complicated

sorry... not sure how to label as an enhancement

Thanks for considering
-f

**Comment by jishi** [comment]
When you say "zone", you mean a player, correct? 

You don't need to ungroup before applying a preset, it would detach players that shouldn't be part of the preset so the final state should be correct.

If you still want to ungroup all upstairs players, it would be easy to write a custom action that uses a list of room names for it. I currently don't see a widespread use for it. 

Something like this:

```
'use strict';
const logger = require('sonos-discovery/lib/helpers/logger');
let system;

const sets = {
  upstairs: ["room1", "room2", "room3"],
  downstairs: ["room4", "room5"]
};


function ungroup(player, values) {
  // First parameter after action name
  const setName = values[0];

  const set = sets[setName];

  if (!set) return Promise.reject('No such set name'); // exit if invalid set name

  return set.reduce((promise, playerName) => {
    return promise.then(() => {
      const player = system.getPlayer(playerName);
      player.becomeCoordinatorOfStandaloneGroup()
        .catch((err) => {
        // mitigate any errors that occurs.
        logger.warn(err);
      });
      })   
    }, Promise.resolve());
}

module.exports = function (api) {
  api.registerAction('custom_ungroup', ungroup);
  system = api.discovery;
};
```

This would expose an action like: /custom_ungroup/upstairs

And it would isolate all players defined in the upstairs array within this file. Note, this is untested code!

**Comment by autofrank** [comment]
yes - should have said player and not a zone.
Interesting that the preset detaches all players from other groups and this may help a lot as I was ungrouping all because the join would fail depending on 'what was grouped to what' previously.
 
Thanks for the code above. I assume I just add in my player names, save as a .js and drop into the relevant folder and restart. I might give that a go.

It looks like from [https://github.com/jishi/node-sonos-http-api/issues/328](url) that there may be a bug with the separate preset files in the preset folder so I might hold off taking the latest code

**Comment by jishi** [comment]
Shouldn't be a bug, he just had the wrong format of the json (it isn't exactly the same as presets.json)

**Comment by autofrank** [comment]
Perfect.. thanks 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Jimmy Shimizu <notifications@github.com> Date: 04/10/2016  13:20  (GMT+00:00) To: jishi/node-sonos-http-api <node-sonos-http-api@noreply.github.com> Cc: autofrank <frank.tp.smith@gmail.com>, Author <author@noreply.github.com> Subject: Re: [jishi/node-sonos-http-api] Ungroup for a set of zones (#329) 
Shouldn't be a bug, he just had the wrong format of the json (it isn't exactly the same as presets.json)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jishi/node-sonos-http-api","title":"jishi/node-sonos-http-api","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jishi/node-sonos-http-api"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jishi in #329: Shouldn't be a bug, he just had the wrong format of the json (it isn't exactly the same as presets.json)"}],"action":{"name":"View Issue","url":"https://github.com/jishi/node-sonos-http-api/issues/329#issuecomment-251372157"}}}

**Comment by autofrank** [comment]
I'll give the code above a go and close this issue..
I'll reopen if it doesn't work as its a separate issue

Thx
-f
