### ISSUE TITLE
sayAll not reversing to initial grouping state

### ISSUE THREAD

**Issue by Lockzi** [jishi/node-sonos-http-api#33]
Started out with all units as individuals (no groups) with 3 of them playing different spotify tracks (Bathroom, Kitchen, Gym)

After the sayall command was played, this was what the system returned to.
https://www.dropbox.com/s/hkz76zo1s00qid0/Screenshot%202015-01-10%2018.21.29.png?dl=0

Output from console:
pi@raspberrypi ~/node-sonos-http-api $ node server.js
no settings file found, will only use default settings
http server listening on port 5005
no preset file, ignoring...
Downloading new tts message file: /home/pi/node-sonos-http-api/static/tts/31247917743076daa139d8c8007a2e8705c12b97-en.mp3

Then with a delay this came up:

error in async series when applying backup error on play [ [ 'ungrouping',
    'set volume, coordinator',
    'setting uri',
    'set playmode' ],
  [ 'ungrouping',
    'set volume, coordinator',
    'setting uri',
    'set playmode',
    'seek',
    'trackSeek' ],
  [ 'ungrouping',
    'set volume, coordinator',
    'setting uri',
    'set playmode',
    'seek',
    'trackSeek' ],
  [ 'ungrouping',
    'set volume, coordinator',
    'setting uri',
    'set playmode',
    'seek' ],
  [ 'ungrouping',
    'set volume, coordinator',
    'setting uri',
    'set playmode' ],
  [ 'ungrouping',
    'set volume, coordinator',
    'setting uri',
    'set playmode',
    'seek',
    'trackSeek' ] ]

**Comment by jishi** [comment]
Is the error intermittent, or can you reproduce it every time? Seems like it failed when trying to play the last zone, but by that time everything should have been restored. And your Bathroom says "No music", which I assume indicate that it lost everything (queue and current track?)? I observed that behavior as well during development, and I can't explain it. Hasn't happened since I was done though.

**Comment by Lockzi** [comment]
Second fresh try. One group (Kitchen + Office) various radio streams and spotify songs on each player.

Before:
https://www.dropbox.com/s/pspliex2xfkac9l/Screenshot%202015-01-10%2019.35.46.png?dl=0

After:
https://www.dropbox.com/s/bhqs5077sgy0mwt/Screenshot%202015-01-10%2019.36.40.png?dl=0


So apparently it seems to be intermittent.
I will try to use it some more and report back if it happens again.

**Comment by jishi** [comment]
This should work better now.
