### ISSUE TITLE
cannot call favourites.

### ISSUE THREAD

**Issue by red3all** [jishi/node-sonos-http-api#331]
Hi, first ever post on Github and thanks for such a gread project.

Im a complete newbie to this stuff, so apologies if I need spoon feeding.  I had never heard of GitHub, node.js, npm etc until about a few days ago.

I have managed to install and setup the server, it appears to be responding to requests and Im using it in conjunction with the instructions from here to control this with an Amazon Echo/Alexa
https://github.com/rgraciano/echo-sonos

I followed the instructions from another issue raised to resolve the spotify not working in the UK, and that has worked brilliantly.

However, one thing I cant seem to do is to get a favourite to play.

Ive added favourite songs from spotify to the sonos favourites (right click and select add to sonos favourites).  I also have radio stations listed as favourites, but no mater how I call these using the echo, it always plays the closest match it can find in spotify.

Ive tried calling:

http://localhost:5005/kitchen/favourite/BBCRadio2

but I receive an error:
2016-10-05T14:52:02. 862Z ERROR
{ error: 'action \'favicon.ico\' not found' }

Would you have a solution for this or any pointers to help a newbie out?

**Comment by red3all** [comment]
So...   newbie strikes here.

Helps if I spell favorite the US way.....

Now calling from the web page works just fine.  I will have to find a work around to call this via the echo integration.  I think it will involve a preset and using the echo command to call that.

**Comment by jplourde5** [comment]
Add the Favorites, spelled exactly as they are in Favorites, to your Presets file and it will probably fix the problem.  The Favorites does not do a fuzzy search in this api, so if the Echo does not come up with the exact spelling of what you say, the favorites will not play.

**Comment by jishi** [comment]
FYI, I just added alternative spelling for favorite to avoid this confusion in the future :)
