### ISSUE TITLE
Possible to limit music library results to 50?

### ISSUE THREAD

**Issue by SvenRobson** [jishi/node-sonos-http-api#333]
Music library search results queues all responsive results, which can sometimes be excessive. (For example, /kitchen/musicsearch/library/song/george thorogood queues 744 songs.)  Is it possible to limit it to 50 (or some other number) of random songs? I think this may already be the functionality on other music services. Thanks!

**Comment by jplourde5** [comment]
I have submitted a change to limit the number to 50 by default.  It can be set to a higher or lower limit including a "maxlibtracks" value in the settings.json file.

**Comment by SvenRobson** [comment]
Excellent; thank you!
