### ISSUE TITLE
Enhancement - Line In

### ISSUE THREAD

**Issue by autofrank** [jishi/node-sonos-http-api#335]
Hi, 
Line in works great thanks

Would it possible to set it to play once the line in is selected

thanks
-f

**Comment by jishi** [comment]
Hm, yeah, that might make sense, in the meantime, you can always just invoke `/Kitchen/play` 

I need to think about if it is a reasonable expectation.

**Comment by autofrank** [comment]
yes, true and not a big deal to add `/kitchen/play` as you say

thanks for considering
-f

**Comment by jishi** [comment]
This makes sense, I've changed to auto-play when calling line-in as per your suggestion.

**Comment by autofrank** [comment]
thanks
