### ISSUE TITLE
verified custom_ungroup code in #329 works

### ISSUE THREAD

**Issue by autofrank** [jishi/node-sonos-http-api#336]
Hi,
A quick note to say I verified the custom ungroup code you shared in 329 works

`'use strict';
const logger = require('sonos-discovery/lib/helpers/logger');
let system;

const sets = {
  upstairs: ['room1', 'room2', 'room3'],
  downstairs: ['room4', 'room5']
};

function ungroup(player, values) {
  // First parameter after action name
  const setName = values[0];

  const set = sets[setName];

  if (!set) return Promise.reject('No such set name'); // exit if invalid set name

  return set.reduce((promise, playerName) => {
    return promise.then(() => {
      const player = system.getPlayer(playerName);
      player.becomeCoordinatorOfStandaloneGroup()
        .catch((err) => {
        // mitigate any errors that occurs.
        logger.warn(err);
      });
      })   
    }, Promise.resolve());
}

module.exports = function (api) {
  api.registerAction('custom_ungroup', ungroup);
  system = api.discovery;
};`

saved as `custom_ungroup.js` to the `actions `folder

not sure of you want to add to the master branch and readme

thanks
-f

**Comment by jishi** [comment]
No, this is custom functionality tailored for your specific need, but it is good to keep as a reference here.
