### ISSUE TITLE
Autostart for Mac OS

### ISSUE THREAD

**Issue by wejstal** [jishi/node-sonos-http-api#341]
Hi,
Great application, I have been using it for a while now in combination with flic button, works every time. However I'm somewhat of a noob and I'm not sure how to make this start up every time the mac mini (in my case) starts. I suppose it's a line or two in a script that runs on every start, but I haven't figured out how to do this.

Right now I start terminal manually and writes:

`cd /Users/server/sonos/node-sonos-http-api`
`npm start`

How can I automize this?

**Comment by jplourde5** [comment]
You might look at PM2. I use it on my RPI and it works well. I think the it would work for a Mac also. 

https://github.com/Unitech/pm2

**Comment by jishi** [comment]
I don't have any good idea on how the bootup process works on mac, pm2 is a good start reference, but anything mentioned on the web about running any script at boot-time would be sufficient. It might also make sense to wrap the startup in a bash-script that would auto restart it if it crashes, I use something like this in the raspberry pi image (because pm2 is a bit heavy for a raspberry pi 1):

```
#!/bin/sh
while (true); do
    /usr/bin/node /flash/apps/sonos-http-api/server.js > /flash/logs/http-api.log
    sleep 10
done
```

**Comment by whimboo** [comment]
OS X has a native way to do that. Simply use `launchd` to setup scripts which should be run during the bootup process. There should be a couple of examples on the web. Here just one: http://alvinalexander.com/mac-os-x/launchd-examples-launchd-plist-file-examples-mac

**Comment by DeLub** [comment]
Long been closed, but maybe of help to someone: place file below in `~/Library/LaunchAgents/sonos-http-api.plist` on a Mac. Be sure to correct the paths.

```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>sonos-http-api</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/bin/node</string>
        <string>/Users/alex/src/node-sonos-http-api/server.js</string>
    </array>
    <key>StandardOutPath</key>
    <string>/Users/alex/src/node-sonos-http-api/http-api.log</string>
    <key>KeepAlive</key>
    <true/>
</dict>
</plist>
```
