### ISSUE TITLE
This won't work for me getting error

### ISSUE THREAD

**Issue by pcgirl** [jishi/node-sonos-http-api#344]
I am very new at this but I have followed all the instructions but it still won't work.  I am getting errors when I try to start the sonos node.
[npm-debug.txt](https://github.com/jishi/node-sonos-http-api/files/530588/npm-debug.txt)

**Comment by jishi** [comment]
That error doesn't include the actual error that is thrown for some reason. Could you try and start it without npm, it might reveal the exact cause. Start it instead with:

`node server.js`

**Comment by jishi** [comment]
It would also be easier to give any guidance if you could tell me what steps you took when installing this.

**Comment by pcgirl** [comment]
Hi thanks for your quick reply.  I tried this again and this time it seems to have worked.  Not sure why now because when I ran npm install -production yesterday it just gave me errors and then when I typed node server.js it gave me errors.  Today it seems to have worked, although it is giving me an error cannot find module '/settings.jason'  code MODULE_NOT_FOUND.


Thanks,
Jane Johnson


________________________________

**Comment by pcgirl** [comment]
Thanks, I got it working now.


Thanks,
Jane Johnson
++++++++++++++++++
A+ Computer Services
(905) 317-0540
++++++++++++++++++


________________________________
