### ISSUE TITLE
Crossfade doesn't work

### ISSUE THREAD

**Issue by naixra** [jishi/node-sonos-http-api#346]
Hello,

Since the last update that you propose to me, the preset "crossfade" no longer works while the repeat function and sleep function work. Whereas before it was the opposite, the crossfade function worked but not the sleep function or the repeat function.

Thanks.

**Comment by jishi** [comment]
Could you please provide the preset you are trying to apply, and the "before" state of repeat, shuffle, crossfade and the "after" state after applying the preset for a few scenarios?

Or one single reproducable example where the end crossfade setting is wrong (with before state and preset).

**Comment by naixra** [comment]
Here one of my preset "Wake Up"

`{
  "players": [
    {
      "roomName": "Chambre",
      "volume": 0
    }
    
  ],
  "playlist": "Réveil",
  "playMode": {
    "shuffle": true,
    "crossfade": true,
	"repeat":"none"
  },
  "sleep": 1800,
  "pauseOthers": false
}
`
Everything work but not "crossfade".

![img_0544](https://cloud.githubusercontent.com/assets/1829642/19452264/ae88b6da-94b0-11e6-9319-7ec03213fe39.PNG)

**Comment by jishi** [comment]
Is the player by any chance playing a radiostation or line-in prior to applying the preset?

**Comment by jishi** [comment]
Never mind, I saw my mistake now :)

**Comment by jishi** [comment]
I've fixed this in master now.

**Comment by naixra** [comment]
I get theses errors when I would like to update : 

`npm ERR! fetch failed https://github.com/jishi/node-sonos-discovery/archive/v1.1.1.tar.gz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://github.com/jishi/node-sonos-discovery/archive/v1.1.1.tar.gz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://github.com/jishi/node-sonos-discovery/archive/v1.1.1.tar.gz
npm ERR! Linux 4.4.0-42-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3

npm ERR! fetch failed with status code 404
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
`

**Comment by jishi** [comment]
My bad, forgot to push the tag. Try again, it should work now.
