### ISSUE TITLE
Multiple conditions in one line

### ISSUE THREAD

**Issue by pcgirl** [jishi/node-sonos-http-api#347]
I would like to know if I can put multiple conditions into one http request?  IE:  http://localhost:5005/Kitchen/playlist/Acoustic%20Rock/repeat/on/shuffle/on/groupvolume/30  When I did this it seemed to turn Repeat on but Shuffle wasn't on and the volume wasn't set at 30%.

**Comment by jishi** [comment]
No, they need to be invoked as separate HTTP commands. If the system you are using for invoking it only supports one action or similar, maybe you have the possibility to call a script that calls `curl` commands or similar.

**Comment by pcgirl** [comment]
Can I put it in a preset file and call the preset file? Or does the preset file load everytime the server is restarted?

**Comment by jishi** [comment]
Yes, a preset sounds like a much beter solution. It will load everytime you restart your server, why would that be a problem? You have the option to invoke using dynamic presets as well, but you need to make sure to url-escape it correctly:

`/preset/%7B%20%22players%22%3A%20%5B%20%7B%22roomName%22%3A%20%22Kitchen%22%2C%20%22volume%22%3A%2030%20%7D%20%5D%2C%20%22playlist%22%3A%20%22Acoustic%20Rock%22%2C%20%22playMode%22%3A%20%7B%20%22repeat%22%3A%20%22all%22%2C%20%22shuffle%22%3A%20true%20%7D%20%7D`

This might look incomprehensible, but is the result of:

`encodeURIComponent('{ "players": [ {"roomName": "Kitchen", "volume": 30 } ], "playlist": "Acoustic Rock", "playMode": { "repeat": "all", "shuffle": true } }')`

from the chrome console or similar. Works with the node REPL console as well (when you just start `node` without any parameters).

It might even work with `/preset/{ "players": [ {"roomName": "Kitchen", "volume": 30 } ], "playlist": "Acoustic Rock", "playMode": { "repeat": "all", "shuffle": true } }` but I wouldn't count on it. 

This would also break out Kitchen to a single player zone, which your chained commands would not.

**Comment by pcgirl** [comment]
All I am trying to do is send an HTTP request to play a specific playlist when I arrive home using my smartthings.  It works but I noticed that the shuffle and volume didn't work.  So, if I put it all in a preset and then just call that preset it should work.  What happens if I change the playlist and volumes, etc. while at home?  When I leave and call the preset, it should follow the preset configuration and set everything to what is in the preset, right?

**Comment by jishi** [comment]
yepp, anything that is declared in the preset will be restored when you call it. Anything omitted from a preset will be ignored (like volume, repeat, shuffle, playlist etc), and just keep the values that the player currently have.

**Comment by pcgirl** [comment]
Perfect!  Thanks!

**Comment by pcgirl** [comment]
Can I use the “say” command in a preset?  And if so what would the syntax be?

Thanks,
Jane Johnson

**Comment by jishi** [comment]
No, that is not supported right now. I think there is an issue issue filed
for it. What's your use case?

**Comment by pcgirl** [comment]
I use it in smartthings to play certain playlists when people arrive home, etc.  I was wanting to also have it speak when they arrived home.


Thanks,
Jane Johnson

++++++++++++++++++


________________________________

**Comment by jishi** [comment]
One issue with the say command is that it needs to wait for the announcement to finish in order to chain them with other actions. Presets doesn't work that way, inheritly. But there has been other request to allow say-announcement to selected players only, instead of just single or all players.
