### ISSUE TITLE
Error npm start

### ISSUE THREAD

**Issue by nibi79** [jishi/node-sonos-http-api#348]
hi, 
my installation was already running ... 

I tried to update to get the new CALL feature. 

So first I upgrade to node v6.9.0, then install node-sonos-http-api by npm and now I've the following problem when starting npm:

> sonos-http-api@1.1.1 start /opt/sonos
node server.js
2016-10-19T06:36:35.306Z INFO no settings file found, will only use default settings
/opt/sonos/lib/music_services/libraryDef.js:13
var randomQueueLimit = (settings.library.randomQueueLimit != undefined)?settings.library.randomQueueLimit:50;
                                        ^
TypeError: Cannot read property 'randomQueueLimit' of undefined
    at Object.<anonymous> (/opt/sonos/lib/music_services/libraryDef.js:13:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/sonos/lib/actions/musicSearch.js:9:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
npm ERR! Linux 4.4.21-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@1.1.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sonos-http-api@1.1.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sonos-http-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /opt/sonos/npm-debug.log

when I try 'npm update' I get the following Error:

> npm ERR! Linux 4.4.21-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8
npm ERR! code E404
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/sonos-discovery
npm ERR! 404
npm ERR! 404  'sonos-discovery' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! Please include the following file with any support request:
npm ERR!     /opt/sonos/npm-debug.log

can you help me?
best regards Nils

**Comment by jishi** [comment]
Sorry, that was a bug I merged without evaluating the result. I've fixed it now, if you update to the latest commit.

**Comment by nibi79** [comment]
"npm start" works now. Thank  you!
