### ISSUE TITLE
Issues with creating Music Search library

### ISSUE THREAD

**Issue by ppitkin** [jishi/node-sonos-http-api#350]
Hi Jishi, Jplourde5,
Have finally got some time and installed the new release with the search facility.
I'm having a bit of a problem however in getting the system to create the library successfully.

In my first attempt the whole system messed up as I went and did a Sonos firmware update while it was running (I got board waiting for it to scan the library and went and started the Windows Sonos app which forced me to upgrade :-( ). This caused all sorts of issues with the api and I had to eventually kill it and restart to get it working again. Obviously my fault as I do not lock the IP addresses of the Sonos kit and they could well have received new values when they rebooted after the upgrade.

Anyway, once restarted I forced a load of the library (it takes far to long before the system automatically starts to scan the library after a restart) this loaded some 54448 tracks and 3209 albums. This seems low but could be to the sonos system not loading everything.

If you see the log extract below you will see that it "killed" itself after loading the albums????
____________________________Log Extract______________
...
Track Count 54000
Track Count 54448
Album Count 1000
Album Count 2000
Album Count 3000
Album Count 3209
Killed

npm ERR! Linux 4.4.21-v7+
npm ERR! argv "/home/pi/.nvm/versions/node/v6.9.1/bin/node" "/home/pi/.nvm/versions/node/v6.9.1/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@1.1.1 start: `node server.js`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the sonos-http-api@1.1.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sonos-http-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/node-sonos-http-api/npm-debug.log

___________End of Log Extract _______________________________________

I was then unable to restart the system as I kept getting the following error:

____________________________Log Extract______________
pi@SonosPi:~/node-sonos-http-api
$ npm start

> sonos-http-api@1.1.1 start /home/pi/node-sonos-http-api
> node server.js

2016-10-20T14:26:30.686Z INFO Presets loaded: { test: 
   { players: [ { roomName: 'patio', volume: 20 } ],
     state: 'PLAYING',
     favorite: '181.FM Good Time Oldies',
     uri: 'x-rincon-stream:RINCON_0000000000001500',
     playMode: 'SHUFFLE',
     pauseOthers: false } }
2016-10-20T14:26:30.849Z INFO http server listening on port 5005
undefined:1

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at handleLibrary (/home/pi/node-sonos-http-api/lib/music_services/libraryDef.js:279:25)
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:445:3)

npm ERR! Linux 4.4.21-v7+
npm ERR! argv "/home/pi/.nvm/versions/node/v6.9.1/bin/node" "/home/pi/.nvm/versions/node/v6.9.1/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@1.1.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sonos-http-api@1.1.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sonos-http-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/node-sonos-http-api/npm-debug.log

___________End of Log Extract _______________________________________

This appeared to be due to the creation of an empty library.json file in the /lib directory.
deleting that file then allowed the system to restart without error.

Question: When sending the command to create the library (e.g. /_player_/musicsearch/load) it doesn't seem logical putting in a player name in the URL as the library is not associated with a player but rather with the hub.

I also get an error thrown between loading tracks 2000 and 3000...

Track Count 2000
2016-10-20T15:16:57.596Z ERROR 
  TypeError: Cannot read property 'items' of undefined
    at loadLibrary.then.then (/home/pi/node-sonos-http-api/lib/music_services/libraryDef.js:236:47)
Track Count 3000

Would it be possible to indicate which album/track is having the issue when an 'undefined' error occurs so that I get some indication as to which track(s) need cleaning?

**Comment by ppitkin** [comment]
OK just run it again and the process was once again killed at exactly the same point.
This time however it created a library.json  file of 22.8 MB - too big to open in the PI standard editor!

When restarting the api it again errored but this time output some of the library.json file....
pi@SonosPi:~/node-sonos-http-api $ npm start

> sonos-http-api@1.1.1 start /home/pi/node-sonos-http-api
> node server.js

2016-10-20T15:52:47.031Z INFO Presets loaded: { test: 
   { players: [ { roomName: 'patio', volume: 20 } ],
     state: 'PLAYING',
     favorite: '181.FM Good Time Oldies',
     uri: 'x-rincon-stream:RINCON_0000000000001500',
     playMode: 'SHUFFLE',
     pauseOthers: false } }
2016-10-20T15:52:47.217Z INFO http server listening on port 5005
undefined:1
{"tracks":{"items":[{"artistTrackSearch":"Duke and Leonard - Just Do The rest You Can","trackName":"- Just Do The rest You Can","artistName":"Duke and Leonard","albumName":"Northern Soul Fever Volume 2","uri":"x-file-cifs://qnap659p2/Multimedia/Music/Various%20Artists/Northern%20Soul%20Fever%20Volume%202/(0215)%20Duke%20and%20Leonard%20-%20-%20Just%20Do%20The%20rest%20You%20Can.mp3","metadata":"<DIDL-Lite xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:upnp=\"urn:schemas-upnp-org:metadata-1-0/upnp/\"\n          xmlns:r=\"urn:schemas-rinconnetworks-com:metadata-1-0/\" xmlns=\"urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/\">\n          <item id=\"S://qnap659p2/Multimedia/Music/Various%20Artists/Northern%20Soul%20Fever%20Volume%202/(0215)%20Duke%20and%20Leonard%20-%20-%20Just%20Do%20The%20rest%20You%20Can.mp3\" parentID=\"A:ALBUMARTIST/Duke%20and%20Leonard/Northern%20Soul%20Fever%20Volume%202\" restricted=\"true\"><dc:title></dc:title><upnp:class>object.item.audioItem.musicTrack</upnp:class>\n  

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at handleLibrary (/home/pi/node-sonos-http-api/lib/music_services/libraryDef.js:279:25)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

npm ERR! Linux 4.4.21-v7+
npm ERR! argv "/home/pi/.nvm/versions/node/v6.9.1/bin/node" "/home/pi/.nvm/versions/node/v6.9.1/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@1.1.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sonos-http-api@1.1.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sonos-http-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/node-sonos-http-api/npm-debug.log

**Comment by jplourde5** [comment]
The error is happening where the process is reading in the data from your library in order to build the local search file.  My guess is that something may be interrupting the process or the library data has something in it that is causing a problem.  Try making sure that all of your Sonos devices are paused and issue the .../ROOM/musicsearch/library/load command, watch the console, and wait for it to finish before issuing anything else.  The other thing to do if it is failing in the same place every time is to see what is different about the data at that point in your library.

**Comment by ppitkin** [comment]
1)      The number of albums read is probably correct based on the number of tracks

2)      The “Killed” statement appears a few seconds after the last album count is output

3)      There is nothing running on any of the players (although it should be able to load even if something was playing J )

4)      There were no other commands issued while the load command was being executed.

 

It doesn’t explain why the server won’t restart (something wrong with the library.json file??? ). First time it was empty, second time it contained 22.8 MB of data.

 

Looking at the end of the library.json file it doesn’t look to be finished off correctly (it ends with a “<” character).

 

Any more ideas as to how I can track down the issue?

 

Thanks

Peter

**Comment by ppitkin** [comment]
OK I'm closing this as it was a problem with running out of resource on the RASPI.
Having now switched to using an VM mchine with much more memory and CPU power things are working.
Using my newly developed version of the code also allows me to scan my external library rather than the limited (problematical) Sonos one. I can also store the output into a mySQL database rather than a file/FUSE database.
