### ISSUE TITLE
Block-scoped declarations issue (possible spotify code tweak required)

### ISSUE THREAD

**Issue by ggscott** [jishi/node-sonos-http-api#355]
When attempting to start with latest build (3257e22c75b2b93f16984162221fd9c4eff58605) the following error comes up:

`SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
`

Here is the npm info:

```
npm ERR! Linux 4.4.8-300.fc23.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@1.1.4 start: `node server.js`
npm ERR! Exit status 1

```

I'm able to resolve this by inserting @line 1 `'use strict';` in lib/actions/spotify.js.  Unsure if this follows any inheritance you were expecting or breaks intended spotify use.

**Comment by jishi** [comment]
Yeah, I missed this when modifying some spotify functionaliy, it is fixed now.
