### ISSUE TITLE
Error upon npm start - please help

### ISSUE THREAD

**Issue by MarkDiddams** [jishi/node-sonos-http-api#359]
Hi,

I shall the following issue, any help would be greatly appreicated. i'm running npm start from the node-sonos-http-api directory.

fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/home/mark/node_modules/sonos-http-api/lib/actions/../../presets/'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at readPresetsFromDir (/home/mark/node_modules/sonos-http-api/lib/actions/preset.js:28:18)
    at initPresets (/home/mark/node_modules/sonos-http-api/lib/actions/preset.js:72:3)
    at module.exports (/home/mark/node_modules/sonos-http-api/lib/actions/preset.js:80:3)
    at HttpAPI.requireDir (/home/mark/node_modules/sonos-http-api/lib/sonos-http-api.js:46:5)
    at files.map.filter.forEach (/home/mark/node_modules/sonos-http-api/lib/helpers/require-dir.js:18:5)
    at Array.forEach (native)
    at module.exports (/home/mark/node_modules/sonos-http-api/lib/helpers/require-dir.js:17:6)
    at new HttpAPI (/home/mark/node_modules/sonos-http-api/lib/sonos-http-api.js:45:3)
    at Object.<anonymous> (/home/mark/node_modules/sonos-http-api/server.js:13:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@1.1.4 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sonos-http-api@1.1.4 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sonos-http-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mark/node_modules/sonos-http-api/npm-debug.log

Below is the npm-debug log as requested.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle sonos-http-api@1.1.4~prestart: sonos-http-api@1.1.4
6 silly lifecycle sonos-http-api@1.1.4~prestart: no script for prestart, continuing
7 info lifecycle sonos-http-api@1.1.4~start: sonos-http-api@1.1.4
8 verbose lifecycle sonos-http-api@1.1.4~start: unsafe-perm in lifecycle true
9 verbose lifecycle sonos-http-api@1.1.4~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/mark/node_modules/sonos-http-api/node_modules/.bin:/home/mark/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle sonos-http-api@1.1.4~start: CWD: /home/mark/node_modules/sonos-http-api
11 silly lifecycle sonos-http-api@1.1.4~start: Args: [ '-c', 'node server.js' ]
12 silly lifecycle sonos-http-api@1.1.4~start: Returned: code: 1  signal: null
13 info lifecycle sonos-http-api@1.1.4~start: Failed to exec start script
14 verbose stack Error: sonos-http-api@1.1.4 start: `node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid sonos-http-api@1.1.4
16 verbose cwd /home/mark/node_modules/sonos-http-api
17 error Linux 4.4.0-36-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error sonos-http-api@1.1.4 start: `node server.js`
22 error Exit status 1
23 error Failed at the sonos-http-api@1.1.4 start script 'node server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the sonos-http-api package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs sonos-http-api
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls sonos-http-api
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by MarkDiddams** [comment]
Figured it out

**Comment by jishi** [comment]
Do you have a folder called "presets"? If not, try creating one at the same
level as server.js and see if that resolves it.
