### ISSUE TITLE
Amazon Prime Music support

### ISSUE THREAD

**Issue by HouserThe** [jishi/node-sonos-http-api#360]
Hi Jishi,
first I would say that you have developed a great api for sonos.
I have used this for testing amazon alexa/echo integration and it works well.
Would it be possible to support the Amazon Prime Music service?
That would be great! Spotify and Apple Music are supported and I think Amazon Music
is also an interesting music service.

Regards
HouserThe

**Comment by jishi** [comment]
we'll first need to find out if they have a public search API we could use. The other services depend on the music services and their search APIs, not Sonos provided ones (since the credentials used is encrypted)

**Comment by HouserThe** [comment]
Ok I understand. I think there is no public Amazon Music Prime API. :(

**Comment by jplourde5** [comment]
I searched for a public API for an earlier request and came up empty.  I couldn't even find any info on an API with a login, which would also work, like we have with Pandora.  Let me know if you see one come available and I'll be happy to add support.

**Comment by HouserThe** [comment]
ok fine close this until amazon has published a api for prime music.
I love to play with your api. I have 3 dash buttons to control my sonos
and I hope tomorrow I get an anazon echo here in germany. That would be so great.
I have prepared the alexa skill to talk to your http api. Great combination.
So again many thanks for your effort and great work. Thumbs up!!!!
