### ISSUE TITLE
ungroup and join rooms not working

### ISSUE THREAD

**Issue by GregRocket** [jishi/node-sonos-http-api#361]
I'm using the latest build of node-sonos-http-api. These commands used to work on previous builds.

When I try to **ungroup** or **join** rooms I get errors sometimes. Sometimes I get {"status":"success"} but the result is incorrect.

Sometimes the correct room will ungroup but the error is still thrown. Other times the wrong room is ungrouped. 

My one room **OFFICE** does not ungroup but the console shows {"status":"success"} This room is the only room with two sonos play 1's  setup in Sonos as a "Stereo Pair"

Here are some errors I get after executing the command:
**http://myurl:5005/ungroup/media%20room**

{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error\n    at Object.invoke (/root/node-sonos-http-api-master/node_modules/sonos-discovery/lib/helpers/soap.js:95:10)\n    at Player.setAVTransport (/root/node-sonos-http-api-master/node_modules/sonos-discovery/lib/models/Player.js:644:15)\n    at attachTo (/root/node-sonos-http-api-master/lib/actions/group.js:33:17)\n    at Object.isolate (/root/node-sonos-http-api-master/lib/actions/group.js:40:12)\n    at handleAction (/root/node-sonos-http-api-master/lib/sonos-http-api.js:110:35)\n    at HttpAPI.requireDir.requestHandler.handleAction.then [as requestHandler] (/root/node-sonos-http-api-master/lib/sonos-http-api.js:87:5)\n    at /root/node-sonos-http-api-master/server.js:49:13\n    at Server.finish (/root/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:111:13)\n    at finish (/root/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:170:14)\n    at /root/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:144:17\n    at FSReqWrap.oncomplete (fs.js:82:15)"}

**http://myurl:5005/join/media%20room/hall%20bathroom**
{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error\n at Object.invoke (/root/node-sonos-http-api-master/node_modules/sonos-discovery/lib/helpers/soap.js:95:10)\n at Player.setAVTransport (/root/node-sonos-http-api-master/node_modules/sonos-discovery/lib/models/Player.js:644:15)\n at attachTo (/root/node-sonos-http-api-master/lib/actions/group.js:33:17)\n at Object.joinPlayer [as join] (/root/node-sonos-http-api-master/lib/actions/group.js:16:10)\n at handleAction (/root/node-sonos-http-api-master/lib/sonos-http-api.js:110:35)\n at HttpAPI.requireDir.requestHandler.handleAction.then [as requestHandler] (/root/node-sonos-http-api-master/lib/sonos-http-api.js:87:5)\n at /root/node-sonos-http-api-master/server.js:49:13\n at Server.finish (/root/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:111:13)\n at finish (/root/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:170:14)\n at /root/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:144:17\n at FSReqWrap.oncomplete (fs.js:82:15)"}

**Comment by jishi** [comment]
I think the order of the params are wrong. If you don't start with a
player, it will select a player at random to act on. Please verify the
Readme and see if you actually call them as expected

**Comment by GregRocket** [comment]
OK I changed order so /ROOM/ungroup and it works correctly most of the time.

Here I have grouped the rooms in alphabetical order. I assume Hall Bathroom is the coordinator room.

![01](https://cloud.githubusercontent.com/assets/12052578/19701520/9d54ec34-9ab0-11e6-9f47-aa22f0c74973.jpg)

Now I issue :5005/office/ungroup. The room does not ungroup and I see this error:

{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error\n at Object.invoke (/root/node-sonos-http-api-master/node_modules/sonos-discovery/lib/helpers/soap.js:95:10)\n at Player.setAVTransport (/root/node-sonos-http-api-master/node_modules/sonos-discovery/lib/models/Player.js:644:15)\n at attachTo (/root/node-sonos-http-api-master/lib/actions/group.js:33:17)\n at Object.isolate (/root/node-sonos-http-api-master/lib/actions/group.js:40:12)\n at handleAction (/root/node-sonos-http-api-master/lib/sonos-http-api.js:110:35)\n at HttpAPI.requireDir.requestHandler.handleAction.then [as requestHandler] (/root/node-sonos-http-api-master/lib/sonos-http-api.js:87:5)\n at /root/node-sonos-http-api-master/server.js:49:13\n at Server.finish (/root/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:111:13)\n at finish (/root/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:170:14)\n at /root/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:144:17\n at FSReqWrap.oncomplete (fs.js:82:15)"}

I then try 5005/hall%20bathroom/ungroup. No error and Hall Bathroom ungroups. Office jumps to top position and becomes coordinator.

I then try :5005/office/ungroup and no error, office ungroups, Media Room jumps to top position.

I then tried :5005/Ladies Room/ungroup and the room ungroups correctly but throws this error:
{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error\n at Object.invoke (/root/node-sonos-http-api-master/node_modules/sonos-discovery/lib/helpers/soap.js:95:10)\n at Player.setAVTransport (/root/node-sonos-http-api-master/node_modules/sonos-discovery/lib/models/Player.js:644:15)\n at attachTo (/root/node-sonos-http-api-master/lib/actions/group.js:33:17)\n at Object.isolate (/root/node-sonos-http-api-master/lib/actions/group.js:40:12)\n at handleAction (/root/node-sonos-http-api-master/lib/sonos-http-api.js:110:35)\n at HttpAPI.requireDir.requestHandler.handleAction.then [as requestHandler] (/root/node-sonos-http-api-master/lib/sonos-http-api.js:87:5)\n at /root/node-sonos-http-api-master/server.js:49:13\n at Server.finish (/root/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:111:13)\n at finish (/root/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:170:14)\n at /root/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:144:17\n at FSReqWrap.oncomplete (fs.js:82:15)"}

**Comment by jishi** [comment]
Not sure the reason for closing, but if you can describe reproducible steps for finding any errors, that would be helpful.

**Comment by GregRocket** [comment]
@jishi I didn't think I closed this issue but maybe I did. Since I mostly use presets, I just changed the order so that Office is the first room. Then I can ungroup office and other rooms and it works. So for now I'm not going to pursue this issue. Thanks!
