### ISSUE TITLE
Radio title isnt shown

### ISSUE THREAD

**Issue by dinkybluebug** [jishi/node-sonos-http-api#365]
Hi 

Ive noticed that since the update to the new version of Node that when I listen to radio stations on Sonos, that the current radio show title isnt shown. 

When I envoke localhost:5005/zones - I see the output below.  The title of BBC radio 2 in room 'kitchen' instead says "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0"

Do you know why this is?

  {
    "uuid": "RINCON_000E58B9149B01400",
    "coordinator": {
      "uuid": "RINCON_000E58B9149B01400",
      "state": {
        "currentTrack": {
          "title": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
          "albumArtUri": "/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0",
          "duration": 0,
          "uri": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
          "type": "radio",
          "absoluteAlbumArtUri": "http://192.168.1.6:1400/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0"
        },
        "nextTrack": {
          "artist": "",
          "title": "",
          "album": "",
          "albumArtUri": "",
          "duration": 0,
          "uri": ""
        },
        "volume": 70,
        "mute": false,
        "trackNo": 1,
        "elapsedTime": 0,
        "elapsedTimeFormatted": "00:00:00",
        "playbackState": "STOPPED",
        "playMode": {
          "repeat": "none",
          "shuffle": false,
          "crossfade": false
        }
      },
      "roomName": "Living Room",
      "coordinator": "RINCON_000E58B9149B01400",
      "groupState": {
        "volume": 70,
        "mute": false
      }
    },
    "members": [
      {
        "uuid": "RINCON_000E58B9149B01400",
        "state": {
          "currentTrack": {
            "title": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
            "albumArtUri": "/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0",
            "duration": 0,
            "uri": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
            "type": "radio",
            "absoluteAlbumArtUri": "http://192.168.1.6:1400/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0"
          },
          "nextTrack": {
            "artist": "",
            "title": "",
            "album": "",
            "albumArtUri": "",
            "duration": 0,
            "uri": ""
          },
          "volume": 70,
          "mute": false,
          "trackNo": 1,
          "elapsedTime": 0,
          "elapsedTimeFormatted": "00:00:00",
          "playbackState": "STOPPED",
          "playMode": {
            "repeat": "none",
            "shuffle": false,
            "crossfade": false
          }
        },
        "roomName": "Living Room",
        "coordinator": "RINCON_000E58B9149B01400",
        "groupState": {
          "volume": 70,
          "mute": false
        }
      }
    ]
  },
  {
    "uuid": "RINCON_B8E93721CD5201400",
    "coordinator": {
      "uuid": "RINCON_B8E93721CD5201400",
      "state": {
        "currentTrack": {
          "title": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
          "albumArtUri": "/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0",
          "duration": 0,
          "uri": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
          "type": "radio",
          "absoluteAlbumArtUri": "http://192.168.1.8:1400/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0"
        },
        "nextTrack": {
          "artist": "",
          "title": "",
          "album": "",
          "albumArtUri": "",
          "duration": 0,
          "uri": ""
        },
        "volume": 31,
        "mute": false,
        "trackNo": 1,
        "elapsedTime": 2988,
        "elapsedTimeFormatted": "00:49:48",
        "playbackState": "PLAYING",
        "playMode": {
          "repeat": "none",
          "shuffle": false,
          "crossfade": false
        }
      },
      "roomName": "Kitchen",
      "coordinator": "RINCON_B8E93721CD5201400",
      "groupState": {
        "volume": 32,
        "mute": false
      }
    },
    "members": [
      {
        "uuid": "RINCON_B8E9375058C601400",
        "state": {
          "currentTrack": {
            "title": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
            "albumArtUri": "/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0",
            "duration": 0,
            "uri": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
            "type": "radio",
            "absoluteAlbumArtUri": "http://192.168.1.8:1400/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0"
          },
          "nextTrack": {
            "artist": "",
            "title": "",
            "album": "",
            "albumArtUri": "",
            "duration": 0,
            "uri": ""
          },
          "volume": 41,
          "mute": false,
          "trackNo": 1,
          "elapsedTime": 2988,
          "elapsedTimeFormatted": "00:49:48",
          "playbackState": "PLAYING",
          "playMode": {
            "repeat": "none",
            "shuffle": false,
            "crossfade": false
          }
        },
        "roomName": "Bathroom",
        "coordinator": "RINCON_B8E93721CD5201400",
        "groupState": {
          "volume": 41,
          "mute": false
        }
      },
      {
        "uuid": "RINCON_B8E93721CD5201400",
        "state": {
          "currentTrack": {
            "title": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
            "albumArtUri": "/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0",
            "duration": 0,
            "uri": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
            "type": "radio",
            "absoluteAlbumArtUri": "http://192.168.1.8:1400/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0"
          },
          "nextTrack": {
            "artist": "",
            "title": "",
            "album": "",
            "albumArtUri": "",
            "duration": 0,
            "uri": ""
          },
          "volume": 31,
          "mute": false,
          "trackNo": 1,
          "elapsedTime": 2988,
          "elapsedTimeFormatted": "00:49:48",
          "playbackState": "PLAYING",
          "playMode": {
            "repeat": "none",
            "shuffle": false,
            "crossfade": false
          }
        },
        "roomName": "Kitchen",
        "coordinator": "RINCON_B8E93721CD5201400",
        "groupState": {
          "volume": 32,
          "mute": false
        }
      },
      {
        "uuid": "RINCON_000E58C229A401400",
        "state": {
          "currentTrack": {
            "title": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
            "albumArtUri": "/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0",
            "duration": 0,
            "uri": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
            "type": "radio",
            "absoluteAlbumArtUri": "http://192.168.1.8:1400/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0"
          },
          "nextTrack": {
            "artist": "",
            "title": "",
            "album": "",
            "albumArtUri": "",
            "duration": 0,
            "uri": ""
          },
          "volume": 24,
          "mute": false,
          "trackNo": 1,
          "elapsedTime": 2988,
          "elapsedTimeFormatted": "00:49:48",
          "playbackState": "PLAYING",
          "playMode": {
            "repeat": "none",
            "shuffle": false,
            "crossfade": false
          }
        },
        "roomName": "Bedroom",
        "coordinator": "RINCON_B8E93721CD5201400",
        "groupState": {
          "volume": 30,
          "mute": false
        }
      }
    ]
  }
]

**Comment by jishi** [comment]
There is some issue where while playback of station is not active, the "artist" property tells the radio station. When playing, "artist" seem to disappear and "title" instead tells what that station is currently playing. This is obviously a bug, but haven't yet looked into it. I probably need to change property names for them to make sense as well. Rendering these fields would then first check the "type" property, if that makes sense. However, limited JSON parsers in home automation system might have problems with that...

**Comment by jplourde5** [comment]
One thing to be aware of is that I found that certain special characters in the metadata <title> field will cause an exception.  I removed the title entry for musicSearch, unless it is a station, because of this.

**Comment by jishi** [comment]
@jplourde5 Did you get any example characters that would give issues? In my experience, unless it was control characters, it shouldn't give any issues if everything worked correctly

**Comment by jplourde5** [comment]
If I recall correctly, it was the ' and maybe a comma.  You might try inserting special characters into a title string one at a time to see what breaks. If I recall correctly, it was the problem where Sonos would display the URI as the title in the queue instead of the title that was specified.  I think that I even tried encoding the string but that didn't help.  It's been a month or two since I dealt with.  I thought that it was odd that the titles were left out in the original code and just assumed that you or someone else had run into the same problem earlier.  Sonos seems to grab the title itself from somewhere else when the title isn't specified in the metadata, but I don't think that worked for the radio/station title, which is why I still specify the title for the station type.

**Comment by dinkybluebug** [comment]
This is a new problem though - it worked before the recent update.  The radio titles were displaying before.

**Comment by jishi** [comment]
You need to be a bit more specific. Which recent update are you talking about? It was completely rewritten for the 1.0.0 release and that has been ongoing for over 6 months. It replaced the legacy version 2 months ago. 

I do know that sometimes "title" for radio stations isn't updated (basically, no info is received from the stream), and artist seem to fall out but this hasn't been touched afaik and has been the case in v1.x.x forever. I will take a look at the radio stations, I suggest you await that and make sure that magic-mirror module conforms to whatever format it will result in. 

If you are involved in the development of the magic-mirror module, you might also want to consider a re-write to use the underlying library `sonos-discovery` directly, which would remove the installation dependency of the http-api (since the magic mirror is based on node.js also, no?)

**Comment by dinkybluebug** [comment]
@jishi I m not sure - I was using the version that DIDNT work on node version 6+,  when using this, the radio station title disiplayed.  Then when the update was applied for node version 6+ - that version then didnt show the radio station anymore.  Im not involved in the magicmirror module - but I can pass over your comments

**Comment by dinkybluebug** [comment]
weirdly enough when you first start a radio station, it displays, but then after a short while, it disappears

[
  {
    "uuid": "RINCON_B8E93721CD5201400",
    "coordinator": {
      "uuid": "RINCON_B8E93721CD5201400",
      "state": {
        "currentTrack": {
          "artist": "BBC Radio 2",
          "title": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
          "albumArtUri": "/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0",
          "duration": 0,
          "uri": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
          "type": "radio",
          "absoluteAlbumArtUri": "http://192.168.1.8:1400/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0"
        },
        "nextTrack": {
          "artist": "",
          "title": "",
          "album": "",
          "albumArtUri": "",
          "duration": 0,
          "uri": ""
        },
        "volume": 31,
        "mute": false,
        "trackNo": 1,
        "elapsedTime": 1419,
        "elapsedTimeFormatted": "00:23:39",
        "playbackState": "PLAYING",
        "playMode": {
          "repeat": "none",
          "shuffle": false,
          "crossfade": false
        }
      },
      "roomName": "Kitchen",
      "coordinator": "RINCON_B8E93721CD5201400",
      "groupState": {
        "volume": 35,
        "mute": false
      }
    },
    "members": [
      {
        "uuid": "RINCON_000E58B9149B01400",
        "state": {
          "currentTrack": {
            "artist": "BBC Radio 2",
            "title": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
            "albumArtUri": "/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0",
            "duration": 0,
            "uri": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
            "type": "radio",
            "absoluteAlbumArtUri": "http://192.168.1.8:1400/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0"
          },
          "nextTrack": {
            "artist": "",
            "title": "",
            "album": "",
            "albumArtUri": "",
            "duration": 0,
            "uri": ""
          },
          "volume": 45,
          "mute": false,
          "trackNo": 1,
          "elapsedTime": 1419,
          "elapsedTimeFormatted": "00:23:39",
          "playbackState": "PLAYING",
          "playMode": {
            "repeat": "none",
            "shuffle": false,
            "crossfade": false
          }
        },
        "roomName": "Living Room",
        "coordinator": "RINCON_B8E93721CD5201400",
        "groupState": {
          "volume": 0,
          "mute": false
        }
      },
      {
        "uuid": "RINCON_000E58C229A401400",
        "state": {
          "currentTrack": {
            "artist": "BBC Radio 2",
            "title": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
            "albumArtUri": "/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0",
            "duration": 0,
            "uri": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
            "type": "radio",
            "absoluteAlbumArtUri": "http://192.168.1.8:1400/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0"
          },
          "nextTrack": {
            "artist": "",
            "title": "",
            "album": "",
            "albumArtUri": "",
            "duration": 0,
            "uri": ""
          },
          "volume": 24,
          "mute": false,
          "trackNo": 1,
          "elapsedTime": 1419,
          "elapsedTimeFormatted": "00:23:39",
          "playbackState": "PLAYING",
          "playMode": {
            "repeat": "none",
            "shuffle": false,
            "crossfade": false
          }
        },
        "roomName": "Bedroom",
        "coordinator": "RINCON_B8E93721CD5201400",
        "groupState": {
          "volume": 0,
          "mute": false
        }
      },
      {
        "uuid": "RINCON_B8E93721CD5201400",
        "state": {
          "currentTrack": {
            "artist": "BBC Radio 2",
            "title": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
            "albumArtUri": "/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0",
            "duration": 0,
            "uri": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
            "type": "radio",
            "absoluteAlbumArtUri": "http://192.168.1.8:1400/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0"
          },
          "nextTrack": {
            "artist": "",
            "title": "",
            "album": "",
            "albumArtUri": "",
            "duration": 0,
            "uri": ""
          },
          "volume": 31,
          "mute": false,
          "trackNo": 1,
          "elapsedTime": 1419,
          "elapsedTimeFormatted": "00:23:39",
          "playbackState": "PLAYING",
          "playMode": {
            "repeat": "none",
            "shuffle": false,
            "crossfade": false
          }
        },
        "roomName": "Kitchen",
        "coordinator": "RINCON_B8E93721CD5201400",
        "groupState": {
          "volume": 35,
          "mute": false
        }
      },
      {
        "uuid": "RINCON_B8E9375058C601400",
        "state": {
          "currentTrack": {
            "artist": "BBC Radio 2",
            "title": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
            "albumArtUri": "/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0",
            "duration": 0,
            "uri": "x-sonosapi-stream:s24940?sid=254&flags=8224&sn=0",
            "type": "radio",
            "absoluteAlbumArtUri": "http://192.168.1.8:1400/getaa?s=1&u=x-sonosapi-stream%3as24940%3fsid%3d254%26flags%3d8224%26sn%3d0"
          },
          "nextTrack": {
            "artist": "",
            "title": "",
            "album": "",
            "albumArtUri": "",
            "duration": 0,
            "uri": ""
          },
          "volume": 41,
          "mute": false,
          "trackNo": 1,
          "elapsedTime": 1419,
          "elapsedTimeFormatted": "00:23:39",
          "playbackState": "PLAYING",
          "playMode": {
            "repeat": "none",
            "shuffle": false,
            "crossfade": false
          }
        },
        "roomName": "Bathroom",
        "coordinator": "RINCON_B8E93721CD5201400",
        "groupState": {
          "volume": 0,
          "mute": false
        }
      }
    ]
  }
]

**Comment by jishi** [comment]
Made some fixes that should resolve this. Also added a "stationName" property which will contain the same as "artist" (for backward compatibility reasons), but with better semantics.
