### ISSUE TITLE
No Cache Directory

### ISSUE THREAD

**Issue by GregRocket** [jishi/node-sonos-http-api#367]
@jplourde5 Just installed latest build. Ran the load command to create library.json file. Came up with this error. I just created the directory and ran load again. But just thought you should know.

ERROR: {"errno":-2,"code":"ENOENT","syscall":"open","path":"/root/node-sonos-htt               p-api-master/cache/library.json"}
2016-11-03T19:28:46.935Z ERROR
  Error: ENOENT: no such file or directory, open '/root/node-sonos-http-api-mast               er/cache/library.json'
    at Error (native)

**Comment by jplourde5** [comment]
A new cache folder was created with the latest release to put the library.json file in, as well as any similar things in the future.  Make sure that the cache directory got created when you installed the new release.

**Comment by GregRocket** [comment]
@jplourde5 I searched from /node-sonos-htt p-api-master/ down for cache. The only directory named cache that came up was the one I created after the install. /node-sonos-htt p-api-master/cache/

The first attempt running load failed because the directory did not exist. After I created the directory cache, re-ran load, then the library.json was created.

**Comment by jishi** [comment]
I think I removed some initialization code in some commit, but I've restored the cache dir creation now so this shouldn't be a problem.
