### ISSUE TITLE
Small issue with "clips"

### ISSUE THREAD

**Issue by DJBenson** [jishi/node-sonos-http-api#371]
Hi

First of all, thank you so much for creating this API - I've been using it for ages and it's great to see the new features being added and the program actively developed.

I've got a new use case (thanks to the inclusion of "clips") which, when my doorbell is pressed, an RF signal is passed to my Raspberry Pi (running Domoticz) which in turn calls your API to play an MP3 of the chime.

I noticed this evening that after the chime had played, a track which was previously paused continued playing, I would expect the play state to persist after the chime finished playing.

e.g.

Pre-chime: Audio is paused
Chime: Clip is played
Post-chime: Audio is paused

EDIT: Below struck through to avoid confusion over the issue I'm reporting (left in as there is a response in relation to the below).

~~Also, I think it's been mentioned before but I'm not sure if there is anything you can do about it - when the API is called from a script (such as an Lua script in Domoticz) it takes a while for the API to return control to the script - I assume your API is waiting a certain amount of time before indicating success but this means I have to put the API call last in my script or it holds everything else up - the script in question does the following on the press of the doorbell;~~

~~Displays a CCTV overlay on each Kodi client in my house (called via the Kodi API)
Displays a notification in Kodi and on my iOS device (called via Domoticz)
Plays the chime by calling your API~~

~~Ideally, the chime should take precedence, but if I put the call to your API first, there is a significant delay (10-20 seconds) between the chime starting and the other events firing when they should be simultaneous (give or take).~~

**Comment by jishi** [comment]
I made a deliberate changes in 1.0 to make the request wait for announcement to finish, mostly because there are a lot of situations where you want to chain these things. If I understand correctly, you want to initiate the doorbell and then instantly move on to your other things? 

You have a few options for this: 
* wrap a curl call in a shell-script or similar and invoke it with `&` at the end which invokes it in the background 
* It might be possible for your LUA script to invoke a request and don't care about the response (asynchronous invocation or something)
* Use a request module for LUA that supports timeout, and set a very low timeout and ignore any timeout errors

**Comment by DJBenson** [comment]
Hi @jishi the actual defect was around the clips not resuming the play state correctly. It's my fault for putting two defects on the same log, the second one is a design decision which is fine but the first issue doesn't seem right to me.

**Comment by jishi** [comment]
Aha, so you are saying that a player that was paused, would change to playing state after the clip command? Okay, missed that. Will look into it.

**Comment by DJBenson** [comment]
Yeah, again sorry for the confusion. Ignore everything from "Also..." onwards and that's what I think is a defect (or not working as people might expect it to).

**Comment by jishi** [comment]
I can not reproduce this. Is this always reproducable for you or is is intermittent? I assumed you used `clip` and not `clipall` since you we're talking about a single player?

**Comment by DJBenson** [comment]
I've just tried to re-create this myself and it worked as expected.

**Comment by leecollings** [comment]
Hey @DJBenson, are you able to share which RF doorbell you have?
