### ISSUE TITLE
groupMute / groupUnmute not working

### ISSUE THREAD

**Issue by teadawg** [jishi/node-sonos-http-api#374]
The groupMute / groupUnmute actions are not working.

**Comment by robertw** [comment]
2016-11-11T19:28:23.814Z INFO Presets loaded: { example:
   { players:
      [ { roomName: 'Bathroom', volume: 40 },
        { roomName: 'Family Room', volume: 30 },
        { roomName: 'Office', volume: 20 },
        { roomName: 'Master Bedroom', volume: 30 },
        { roomName: 'Living Room', volume: 30 } ],
     playMode: { crossfade: false },
     pauseOthers: false,
     favorite: 'Carlos Radio' },
  robert:
   { players: [ { roomName: 'Living Room', volume: 55 } ],
     playMode: { crossfade: false },
     pauseOthers: false,
     favorite: 'Carlos Radio' } }
2016-11-11T19:28:23.947Z INFO http server listening on port 5005
/home/pi/sonosapi/lib/actions/mute.js:6
  return player.coordinator.groupMute();
                            ^

TypeError: player.coordinator.groupMute is not a function
    at Object.groupMute (/home/pi/sonosapi/lib/actions/mute.js:6:29)
    at handleAction (/home/pi/sonosapi/lib/sonos-http-api.js:110:35)
    at HttpAPI.requestHandler (/home/pi/sonosapi/lib/sonos-http-api.js:87:5)
    at /home/pi/sonosapi/server.js:50:13
    at Server.finish (/home/pi/sonosapi/node_modules/node-static/lib/node-static                        .js:111:13)
    at finish (/home/pi/sonosapi/node_modules/node-static/lib/node-static.js:170                        :14)
    at /home/pi/sonosapi/node_modules/node-static/lib/node-static.js:144:17
    at FSReqWrap.oncomplete (fs.js:123:15)

npm ERR! Linux 4.4.26-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@1.1.7 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sonos-http-api@1.1.7 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sonos-http-api packag                        e,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sonos-http-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/sonosapi/npm-debug.log

**Comment by jishi** [comment]
Should be fixed in master now.
