### ISSUE TITLE
Issue when trying to use SSL ("fs is not defined")

### ISSUE THREAD

**Issue by mdcampbell** [jishi/node-sonos-http-api#375]
After adding paths for my CERT and KEY files in ```settings.json```, I get the error ```fs is not defined```.

It looks like **`server.js`** is missing a ```const``` declaration for ```fs``` variable.  Adding ```const fs = require('fs');``` seemed to resolve it.

**Comment by jishi** [comment]
This is supposed to be fixed in the latest master. Which version are you
running?

**Comment by mdcampbell** [comment]
Sounds good.  Running "1.1.5" now.
