### ISSUE TITLE
Switch playing track over to different player

### ISSUE THREAD

**Issue by beeguy1234** [jishi/node-sonos-http-api#380]
The behaviour I'm looking for is the following steps : 
1. Track is playing on player A.
2. We group player B together with player A.  Track is now playing on both.
3. After a few seconds we ungroup player A, stopping the playback on A.  Track is now playing on B.  We have 'moved' the track and the playlist over from A to B.

This used to work on my system.  I was using v 0.18.1.  I used presets as follows : 
Grouping : 
{"players": [{ "roomName": "A"} ,{"roomName": "B", "volume": 80 }]}
Ungrouping : 
{"players": [{ "roomName": "A", "volume": 3}] , "state": "stopped"}

Currently (using v 1.1.7) I can't get this to work anymore (with the exact above presets, or variations of them).  The grouping works fine but after ungrouping, player B will not stick to the track/playlist taken from A.  It will return to its original track.  (Note : using grouping/ungrouping via the Sonos desktop app instead, this 'move' can still be done.)

Can the old behaviour be reinstated, or can an API be added to the same effect, please ?

**Comment by jishi** [comment]
So you we're using presets before to do this? Well, that was never supposed to work, and I'm not sure I would want to support that behavior, honestly. However, doing the following should work:

/PlayerA/join/PlayerB
/PlayerB/leave

I don't even think you would need to add any timeout if the requests would wait on each other, consider the following (Office is playing):

`curl http://localhost:5005/Kitchen/join/Office; curl http://localhost:5005/Office/leave`

This works on my machine. Would be easy to add a `move` to bring it down to 1 request, but I'm not sure if many would find it that useful. Also a bit unclear how that should work if you have several players grouped...

**Comment by beeguy1234** [comment]
Well yes that does it, thank you !  
The thing is I never knew about the join function.  First time I see it discussed.
Indeed, working with the presets felt hacky but I saw no other way.
