### ISSUE TITLE
Radio information not showing

### ISSUE THREAD

**Issue by NovaGL** [jishi/node-sonos-http-api#381]
Updated to latest version and now radio information doesn't show but shows in Sonos app, previously it did work.

`{"currentTrack":{"artist":"Buddha","title":"buddha_32","duration":0,"uri":"aac://sc01.scahw.com.au:80/buddha_32","type":"radio","stationName":"Buddha"},"nextTrack":{"artist":"","title":"","album":"","albumArtUri":"","duration":0,"uri":""},"volume":14,"mute":false,"trackNo":1,"elapsedTime":4,"elapsedTimeFormatted":"00:00:04","playbackState":"PLAYING","playMode":{"repeat":"none","shuffle":false,"crossfade":false}}`

http://imgur.com/rmxFwsd

**Comment by jishi** [comment]
I can not reproduce this, also that uri doesn't look like a tune-in station. Is this a custom radio station?

Also, make sure that you are actually running the newest version of sonos-discovery (`npm install --production`), it could be an old bug in the radio parsing (although since you have stationName it should be fairly new).

**Comment by NovaGL** [comment]
Yes it is a custom station can you please try sc01.scahw.com.au:80/buddha_32

Like I said old version works, tried deleting and starting from scratch still doesn't work.

**Comment by jishi** [comment]
I could reproduce it with that station. I have fixed the issue now. Please update and test it out!

**Comment by NovaGL** [comment]
Thanks! Will try when I get home

**Comment by NovaGL** [comment]
All working now :D Had to change some things in my script but at least it shows the data,

The reason I am doing it this way is the built in TuneIn station does not show song info so had to add it as a custom station
