### ISSUE TITLE
Command to switch playbar back to TV sound?

### ISSUE THREAD

**Issue by thauch** [jishi/node-sonos-http-api#382]
Is this possible? Or is this what you're talking about by the line-in, analog only?

**Comment by jishi** [comment]
It's possible, there is just no convenience method for it.

If you invoke:

`/PlayerName/setavtransporturi/x-sonos-htastream:[UUID of PLAYBAR]:spdif` followed by `/PlayerName/play` it would start the line-in of a PLAYBAR.

You can find the UUID of the player from the `/zones` output.
