### ISSUE TITLE
musicSearch and LibraryDef - my enhacements

### ISSUE THREAD

**Issue by ppitkin** [jishi/node-sonos-http-api#385]
Should it be of interest to anyone I have now a reasonably stable enhacement to the Library MusicSearch facility developed by jplourde5. 
What jplourde5 had developed was fantaistic but with my system I was really pushing it past its limits.
For 99.9% of the people out there the standard version will meet your needs and you don't need to even think about changing anything. For me however I have a very large music library (120,000+ tracks) and so I experienced a number of issues:
1) The standard Sonos library can hold only 65000 entries (including all your favorites etc). That means I can only store half my tracks.
2) The standard Sonos library has issues in that it can't deal with albums with the same name (but from different artists). Sonos has designed it to be track centric rather than album centric.
3) The library.json file that gets built is two large for handling effeciently on a RASPI 3 (sometimes crashes when building the library as runs out of resources, very slow searching (greater than 2 mins!)). I should point out that moving the whole solution onto a VM machine running on my NAS (which has lots of resource) it is VERY fast). To be recommended for anyone experiencing performance problems. VM is Debian Cinnamon.

So what have I done....
I have primarily modified the "musicSearch.js" and "LibraryDef.js" files to allow the following:
1) Instead of just the ability of scanning the Sonos library you can ask it to instead scan an external library. This library will need to have a local mount point on the machine running the node-sonos-http-api. You configure the location of the directory to be scanned in the settings.json file. The system will process the external library in exactly the same was as for the Sonos library. The search tags are built using the id3 tags form the music files themselves. Your tags will need to be fairly 'clean' for this to work well but it will tell you which files are missing the required information as it processes the entries in the directory. It recurses into sub directories of course. My library has the following directory structure Root/artistname/albumname/ 
2) I make a clear distinction between album artist and track artist. This makes searching much better - especially as it will handle compilation albums better.
3) I allow the use of a mySQL database to store the search keys instead of creating a Library.json file and loading that into the FUSE search DB's. This setup for you mySQL DB can be defined in the settings.json file. The FUSE system has a good fuzzy search capability. I have tried to match this in mySQL by using a combination of full text search and the use of SOUNDEX keys (SOUNDEX keys allow you to match on things that sound like the search phrase supplied). This seems to work surpisingly well. As for speed, on my system this will now start playing the track within 1-1.5 seconds after submitting the request.
4) I allow full use of the "artist:", "album:", "track:" keywords in the request string. You don't have to supply them but if you do it can give a much more accurate search result (especially when using the mySQL library). This was done mainly to enhance the Amazon Echo integration.

So what does this give you....
1) you can ask to play an album with a specific name: ."../library/album/album:Gold" This will return all the albums in the library with the name "Gold". It will ensure that the results are sorted by the Album, track and albumArtist so it ensures that album contents are kept together. (on the Echo: "Alexa, ask my sonos to play album gold")
2) you can ask to play an album with a specific name and by a specific albumArtist. "../library/album/album:Goldartist:chris rea" this will return the album Gold by Chris Rea. Again tracks are correctly ordered in the album. (on the Echo: "Alexa, ask my sonos to play album gold by chris rea" or "Alexa, ask my sonos to play album gold by artist chris rea")
3) you can ask to play a specific track from an album with a specific name and albumArtist. "../library/album/album:Goldartist:chris reatrack:open road" this will return the single track Open Road from the album Gold by Chris Rea.
4) you can ask to play all the albums from a specific albumArtist. "../library/album/artist:chris rea" this will return all the albums by Chris Rea. Again tracks are correctly ordered in each album and the album entries are kept together. (on the Echo: "Alexa, ask my sonos to play albums by chris rea" or "Alexa, ask my sonos to play albums by artist chris rea")
5) you can ask to play all the songs/tracks from a specific Artist. "../library/song/artist:chris rea" this will return all the songs by Chris Rea. I have left it doing the randomization of the play order. (on the Echo: "Alexa, ask my sonos to play songs by chris rea" or "Alexa, ask my sonos to play songs by artist chris rea" or "Alexa, ask my sonos to play tracks by chris rea")
6) you can ask to play a specific song/track "../library/song/track:on the beach" this will return all the tracks called "on the beach". This may return lots of diffent tracks called "on the beach" but by different artists. It will filter out duplicates by the same artist. (on the Echo: "Alexa, ask my sonos to play song on the beach" or "Alexa, ask my sonos to play track on the beach")
7) you can ask to play a specific song/track from a specific Artist. "../library/song/track:on the beachartist:chris rea" this will return all the tracks entitled "on the beach" by Chris Rea. (on the Echo: "Alexa, ask my sonos to play song on the beach by chris rea" or "Alexa, ask my sonos to play song on the beach by artist chris rea" or "Alexa, ask my sonos to play track on the beach by chris rea")

Notes: 
- If using the FUSE database the search continues to use just "Artist Album" or "Artist Track" and so not all the above option will work 100% accurately.
- If using the Sonos Library to build the search library (fuse or mySQL)  albumArtist = trackArtist and so it has issues with compilation albums or any album where there are multiple different artists on an album
- The "artist:", "album:", "track:" keywords can be supplied in any order.
- for an album search the "artist:" will be interpreted as the albumArtist. For a song search its interpreted as the track artist. 
- Its optional to use the tags (i.e. the current functionality still works as before) e.g. ".../library/album/chris rea gold" or ".../library/song/chris rea on the beach" etc.

Happy to distribute to anyone who's interested. Probably could benifit from some testing on different installations. It works on mine but there are maybe still some bugs of edge conditions that I may have missed.

peter

**Comment by jishi** [comment]
This is all very interesting and I'm impressed with the solution you have come up with. However, such a complex solution will probably be out of scope for most users, and too complex to setup for them, so I don't think it is for this project to pursue. However, if you can find a good way of isolating it (merely requiring a drop-in file into the "actions" folder) and are willing to maintain it, feel free to do so and I'll give it a mention in the README.

**Comment by ppitkin** [comment]
Hi Jishi, I wouldn't say it is complex - it is mearly an extension of the existing functionality.
As I mentioned in my post 99.9% of users would never need to use it as the standard setup is more than sufficient.
Not sure why you would want to isolate it as it is totally transparent to anyone who does not put the relevant settings into the setting.json file. All the existing functionality and behaviour is maintained.
It does by the way clear up a couple of small bugs that are in the standard release - most people would never come accross them.

Just wanted to make people aware that I have a soution if they are interested.

P.S. most of this track and album searching will become obsolete at the begining of next year when Amazon and Sonos release their fully integrated solution. There will be no need for any Alexa skill any more and you''ll be able to have Alexa play any of your music choices on any Sonos device - at least that is what is being promised.
I would be interested in hearing if anyone is actually using the Library play/search functionality from their own developed applications. I would assume that mostly presets and favorites are being used.

**Comment by jplourde5** [comment]
Very nice Peter.  Can you create a new def file maybe called externalDef and put your mods there?

A couple of minor tweaks to musicSearch would be required to support the new definition, but this way both solutions can coexist.  

Where can I see the changes that you made?
