### ISSUE TITLE
When playing a TTS message to a "group leader" player the group is dissolved.

### ISSUE THREAD

**Issue by Snille** [jishi/node-sonos-http-api#387]
Hi, thank you for this most excellent api.
I'm using it extensively with Alexa and HA-Bridge.

I noticed that when I play a messages via TTS to a player that is the "group leader" (in lack of a better word) the group is dissolved, execution takes a long time (though the messages is played on the selected player) and I get this message error message:
{"status":"error","error":"Cannot read property 'then' of undefined","stack":"TypeError: Cannot read property 'then' of undefined\n    at system.applyPreset.then.then.then.catch (/srv/node-sonos-http-api/lib/helpers/single-player-announcement.js:131:9)\n    at process._tickDomainCallback (internal/process/next_tick.js:129:7)"}

Then the group is not "reassembled" and whatever was playing does not resume. 
Let me know if you need more information.

Best regards Erik

**Comment by jishi** [comment]
Yeah, it seems completely broken now that I test it. I must have broken it a while back when I tried to improve my preset system to better support a different case. Thanks for reporting! I'll try and fix it as soon as I get the chance.

**Comment by jishi** [comment]
It works now according to my testing, please try it out and let me know if you still experiencing issues.

Btw, we are acquaintances :)

**Comment by Snille** [comment]
Works! :)
Nicely done! Changes the group leader while playing then plays the message and the joins again as a slave.

Good work!

Thank you!
