### ISSUE TITLE
currentTrack.artist returns radio station name when using Spotify Radio

### ISSUE THREAD

**Issue by jamiesteven** [jishi/node-sonos-http-api#388]
This may be related to changes made for #365. When I'm playing Spotify artist radio, currentTrack.artist is the name of the station, i.e. "Paul Simon Radio", and not the name of the artist currently playing.

I noticed that nextTrack.artist is correctly displaying the artist name, that is, of course until the song starts playing.

Also wanted to add how much I absolutely love this library... thank you so much for developing it and maintaining it!

**Comment by jishi** [comment]
Yes, there was a corner case for Spotify radio that I hadn't come across. Thanks for pointing it out!
