### ISSUE TITLE
Adding spotify tracks with "now" doesn't switch to queue playback

### ISSUE THREAD

**Issue by johot** [jishi/node-sonos-http-api#390]
Thanks for a real cool API, it's almost working perfectly for me.

For some reason I can't play any spotify songs until I play atleast once using the Sonos desktop app. Then it works all the time until I turn off my Sonos player, then I have to redo the whole procedure. I have only tested using Spotify so not sure if this affects other sources also.

My sequence is the following:

http://localhost:5005/preset/mypreset/
http://localhost:5005/roomname/clearqueue
http://localhost:5005/roomname/spotify/now/spotify:track:2L6orAlH8tBhiFTumIfMyF
http://localhost:5005/roomname/play

So in this case it would run the preset by creating a group and then clearing the queue. It would also add the song to the queue, but it would not play.

Now if I start this song in the sonos desktop app it starts playing and if I then run the command sequence again it will once again clear the queue, but this time it will start autoplaying the song.

Does this have anything to do with connecting to spotify or something? Do I need to add some extra setup command?

Thanks again!

**Comment by johot** [comment]
Follow up, I get the following reply from the api:

{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error\n    at Object.invoke (D:\\Downloads\\node-sonos-http-api-master\\node-sonos-http-api-master\\node_modules\\sonos-discovery\\lib\\helpers\\soap.js:95:10)\n    at Player.play (D:\\Downloads\\node-sonos-http-api-master\\node-sonos-http-api-master\\node_modules\\sonos-discovery\\lib\\models\\Player.js:383:15)\n    at Object.play (D:\\Downloads\\node-sonos-http-api-master\\node-sonos-http-api-master\\lib\\actions\\playpause.js:11:28)\n    at handleAction (D:\\Downloads\\node-sonos-http-api-master\\node-sonos-http-api-master\\lib\\sonos-http-api.js:110:35)\n    at HttpAPI.requestHandler (D:\\Downloads\\node-sonos-http-api-master\\node-sonos-http-api-master\\lib\\sonos-http-api.js:87:5)\n    at D:\\Downloads\\node-sonos-http-api-master\\node-sonos-http-api-master\\server.js:50:13\n    at Server.finish (D:\\Downloads\\node-sonos-http-api-master\\node-sonos-http-api-master\\node_modules\\node-static\\lib\\node-static.js:111:13)\n    at finish (D:\\Downloads\\node-sonos-http-api-master\\node-sonos-http-api-master\\node_modules\\node-static\\lib\\node-static.js:170:14)\n    at D:\\Downloads\\node-sonos-http-api-master\\node-sonos-http-api-master\\node_modules\\node-static\\lib\\node-static.js:144:17\n    at FSReqWrap.oncomplete (fs.js:123:15)"}

**Comment by jishi** [comment]
I'm unsure what the state of a newly booted player is, but it could be that it hasn't selected queue playback.

You could try this by adding the following to your preset:
```

  "uri": "x-rincon-queue:RINCON_00000000001400#0"

```

Replace RINCON_14000000001400 with the UUID of the player you have listed first in the preset (if multiple).

It should probably switch to queue playback when you invoke the spotify request, I have probably forgot to implement that. I guess you see the same behavior of you are playing a tune-in radio station before invoking these steps? Aka, radio keeps playing?

**Comment by johot** [comment]
Will test right away, thanks! I'll get back to you!

**Comment by johot** [comment]
Okey jishi, I just tried this but no difference. I added the following (checked my UUID by doing a /zones first):

 "state": "stopped",
  "uri": "x-rincon-stream:RINCON_B8E92772800D01400#0",

What you say about it not selecting the queue seems logical. I always turn my system off during night so that I why I am probabling seeing this problem more than others.

I haven't tried radiochannels yet, you mean I could use that as a workaround or will I get the same behavior?

Is there any hack I can make to get it to select queue? No such command exists right?

**Comment by jishi** [comment]
You wrote "x-rincon-stream" which indicates line-in. It should be "x-rincon-queue".

No, the radio was merely to prove my theory. You should see similar behavior if player is set to radio, and you try to execute your commands.

You can select queue using `setavtransporturi` but that is basically the same as specifying `uri` in the preset.

I should probably fix the spotify commands anyway, so they switch to queue playback implicitly anyway. It's not nice having to rely on these "hacks" :)

**Comment by johot** [comment]
It's working now! The x-rincon-queue thing did it!

Btw. before adding the fix to my preset I also tried playing a favorite, it had the same bug of not selecting a queue when cold booting my sonos playbar.

So what basically happened here? A command was sent to my sonos playbar to queue index #0?

About the setavtransporturi it's not really something I see as a part of the api?

But you will fix this in the official api now, and we can use the x-rincon thing in the meantime?

Thank you!

**Comment by jishi** [comment]
Hm, applying a favorite in the preset _should_ select queue playback if it's a playlist, otherwise it's a bug. 

The x-rincon-queue uri is basically how Sonos tells a player to play from the internal queue. Never understodd what the #0 means, it could be queue position but I don't think so. I think it references queue 0, because there is some sort of concept of multiple queues on the players but it isn't exposed in the controller to my knowledge. 

setavtransporturi seems to be ondocumented, but it might very well be since it is not very intuitive :)

**Comment by johot** [comment]
Thanks for the explanation :)

The favorite I created was a spotify playlist (dragged it into sonos favorites) so maybe the same thing applies? But I did that test very fast so can't be 100% sure.

**Comment by jishi** [comment]
I'll look into it, see if has the same issue. I'm trying to fix the spotify corner case right now, seems to be some other issue when you have a completely empty queue as well.

**Comment by johot** [comment]
Very nice, thanks for creating this api!

I've built my own "home central" thing with a screen, thanks to your api I could finally create a single press "christmas on" button that will dim my lights, turn on a chromecast fireplace and start playing spotify christmas music :P

**Comment by ppitkin** [comment]
Hi, I've also seen this during the testing I have done with the Library search. If you restart a player (pull power or firmware update) it will not queue or play anything until you have first tried to play something using a Sonos Controller. After that the api works without issue.

**Comment by jishi** [comment]
Yeah, all music services suffer from this, but I'll fix them one at a time. They should probably be refactored to share this common flow.
