### ISSUE TITLE
multiple sonos systems in same network

### ISSUE THREAD

**Issue by blackice2k3** [jishi/node-sonos-http-api#396]
I have two different sonos systems in the same network and I can not specify which one should be used. Sometimes it finds the correct one but often the other one. Is it possible to define one master ip of the sonos system?

**Comment by jishi** [comment]
I used to have support for configuring household id in the settings, but
seems like I didn't add it when I rewrote the underlying library. Makes
sense to add it again, but you are the first to request it up until now :)

**Comment by blackice2k3** [comment]
oh that would be perfect :)

**Comment by jishi** [comment]
With the latest master version and sonos-discovery 1.2.2 you can now define a "household" property in settings.json, like this:

settings.json: 
```
{
  "household": "Sonos_ab7d67898dcc5a6d"
}
```

To statically link the installation to a specific household. You can find your household if you go to the status pages on one of the players belonging to that household:

http://[IP of one player]:1400/status/netsettings.txt

You will have a property there called HouseholdID, which starts with "Sonos_" or "HHID_" (if you have an older installation).
