### ISSUE TITLE
Broken dependency

### ISSUE THREAD

**Issue by ggravlingen** [jishi/node-sonos-http-api#398]
Looks like this file has gone missing when doing npm install --production
https://github.com/jishi/node-sonos-discovery/archive/v1.2.5.tar.gz

**Comment by jishi** [comment]
Seems like I forgot to enter my passphrase when pushing the tags, my bad! All fixed now. Thanks for notifying me!

**Comment by ggravlingen** [comment]
Thanks, install works now but lead to another error. Will post separate issue.
