### ISSUE TITLE
Sonos login

### ISSUE THREAD

**Issue by Lytell** [jishi/node-sonos-http-api#402]
Just as a heads up I am very new to programing but wanted to see if I could complete this project.  

The issue I've ran into is I've been prompted to enter the sonos login and password.  What Ive done so far is installed the sones-http-api-1.0.1img.gz to the raspberry pi SD. When the raspberry pi boots I get to a prompt that says "sonos login:".  I don't know what the login name or the password is.  Please help.  Thanks so much for taking the time to help a noob.

**Comment by jishi** [comment]
That's the shell account for the Linux installation. It only has one super
user account named "root", which has no password. However, it is not
necessary to login for the system to be active, that is only for
administrative tasks. If you get the prompt, it is already running.

**Comment by Lytell** [comment]
Great! The account name "root" worked.  So using sones-http-api-1.0.1img.gz as the os for my raspberry pi is correct then?  As a beginner its hard for me to know exactly what to do.  Thanks again for all your help!!
