### ISSUE TITLE
One room stopped working

### ISSUE THREAD

**Issue by mconlow** [jishi/node-sonos-http-api#405]
Hi, I have what feels like a bizarre issue maybe someone can help me with. I have node-sonos-http-api running with the echo-sonos integration. 

A couple days ago, API calls to just one room, the "Living Room", stopped working. Calls to other rooms continue to work fine. The main thing that changed is that I upgraded the Sonos firmware to the latest release.

So, a request to https://192.168.1.123:5005/Living%20Room/Play returns a 200 OK but nothing happens.

Whereas https://192.168.1.123:5005/Bathroom/Play correctly starts playing music on the "Bathroom" speaker.

Any thoughts about what could have happened appreciated,

Mike

**Comment by jishi** [comment]
Does `/Living Room/state` return anything of interest? 

Without seeing any more detailed logs, it's hard to say. If you are getting a 200 OK that means that the request has successfully reached the Sonos player, so that one seems to think the command was successful... Does it work correctly with the official controller?

**Comment by mconlow** [comment]
Thanks for the quick reply. It does work correctly with the official controller. 

/Living Room/state returns the JSON about the player. Part of the response:

  "volume": 18,
  "mute": false,
  "trackNo": 1,
  "elapsedTime": 52,
  "elapsedTimeFormatted": "00:52",
  "zoneState": "PLAYING",
  "playerState": "PAUSED_PLAYBACK",
  "zonePlayMode": {
    "shuffle": false,
    "repeat": false,
    "crossfade": false

But the "Play" command continues to get a 200 but not do anything. 

As I continue to test this, I am now noticing that commands against the "Living Room" player are being executed on the "Bathroom" player.

**Comment by jishi** [comment]
Is it grouped with Bathroom? Maybe your units has switched IPs and coincidently been switched around? Not sure that my system would pick up on that if both IPs remains but to other players...

**Comment by mconlow** [comment]
API restart did the trick. Have had it running for so long didn't even think about that piece. Thanks!
