### ISSUE TITLE
Shuffle feature not working

### ISSUE THREAD

**Issue by Fuchstiger** [jishi/node-sonos-http-api#407]
Hi!
I am using the api and everything is working for me with the exception of the shuffle feature.
The using of this command: "http://localhost:5005/room/shuffle" doesnt work. I get a success output but nothing has changed.
I think the URL should work?

Update: If shuffle is on, i can deactivate it. But not the other way.

**Comment by jishi** [comment]
You need to specify /on or /off like this:

/roomname/shuffle/on

**Comment by Fuchstiger** [comment]
Ah Okay. That explains everything. Thanks for the fast reply! :)
