### ISSUE TITLE
Deprecation of UPnP Interface by Sonos

### ISSUE THREAD

**Issue by metrognomicon** [jishi/node-sonos-http-api#410]
Jishi - your project has been a real problem solver.  I'm concerned about its future because recently Sonos released a formal API to several major home automation manufacturers such as Lutron, Control4, Crestron, and possibly others.  I have been notified in statements by both Control4 and Crestron that the ability to control Sonos via UPnP is going away because of the new API.  Those manufacturers are not what I would consider highly credible sources and I have not received any communication directly from Sonos.  But if this is indeed the case I wanted to put it on your radar.

**Comment by jishi** [comment]
Hi! I'm aware of their migration into cloud based control (and have been for the last 2 years), but I'm kind of confused about all this talk about the "new api". I have had contact with iPort and their developer who built the xPress keypad and helped him understand the caveats of Sonos UPnP protocol, which kind of indicates that there actually isn't a "new" API per se. 

Also, switching over completely to a cloud based solution doesn't seem feasible, but sure, they could probably use a similar scheme for local controllers as well (they just connect directly to the players). 

Time will tell what happens. Hopefully I get onboard a private beta when that happens, which hopefully give me enough time to convert it, given that they are open about the spec. If they are switching to encrypted websockets with certificate pinning, it will be a pain to reverse-engineer (maybe even impossible).

**Comment by philhawthorne** [comment]
Wouldn't removing UPnP also remove the ability for local media hosted on PCs, Macs and NAS also remove the ability for people to play their local content directly on Sonos? 

This would seem like a dumb decision. Effectively making Sonos speakers only able to play streaming music services, instead of peoples local content.

**Comment by jishi** [comment]
Not really. Local media library doesn't rely on Sonos being UPnP conformant, since Sonos basically just read the samba-share directly when playing and indexing.

UPnP only give the possibility to "send" tracks to Sonos from other, UPnP/DLNA compliant client (like windows media player or similar)
