### ISSUE TITLE
uri is missing from queue information

### ISSUE THREAD

**Issue by knsv** [jishi/node-sonos-http-api#411]
The uri is not present in the data coming back after queue call to the rest API. Is this by design, it is present in the docs. Making a pull request for this, (simple fix). Take it or leave it :)

**Comment by jishi** [comment]
I think my idea was that it was presentation data mostly, since the uri doesn't have much real use without metadata for most services. 

What are you using it for? Maybe I'm missing some obvious use case.

**Comment by knsv** [comment]
I use it for saving the queue before some manipulations and restoring the queue and the playback after the manipulations.

Get Outlook for iOS




On Thu, Dec 15, 2016 at 1:30 PM +0100, "Jimmy Shimizu" <notifications@github.com> wrote:












I think my idea was that it was presentation data mostly, since the uri doesn't have much real use without metadata for most services.


What are you using it for? Maybe I'm missing some obvious use case.

**Comment by jishi** [comment]
Hm, I already have a "detailed" view of the queue:

/queue/detailed

Have you tested that? It will include all info about the queue.

**Comment by knsv** [comment]
That would work for me. I did not see that one in the docs, maybe I was to quick. J

 

Thanks for the update

 

/Knut

 

Från: Jimmy Shimizu <notifications@github.com>
Svara till: jishi/node-sonos-http-api <reply@reply.github.com>
Datum: torsdag 15 december 2016 16:38
Till: jishi/node-sonos-http-api <node-sonos-http-api@noreply.github.com>
Kopia: Knut Sveidqvist <knut@sveido.com>, Author <author@noreply.github.com>
Ämne: Re: [jishi/node-sonos-http-api] uri is missing from queue information (#411)

 

Hm, I already have a "detailed" view of the queue:

/queue/detailed

Have you tested that? It will include all info about the queue.
