### ISSUE TITLE
Directions for hosting API on Raspberry Pi (and opening ports for public access)?

### ISSUE THREAD

**Issue by mkayen** [jishi/node-sonos-http-api#416]
Thanks so much for making this, it works really well on my local machine! Next step for me is to host this on a raspberry pi made available over the open web. That way I can use the IFTTT maker channel to connect my Google Home to the Sonos (and therefore say 'Okay Google, tell sonos to play Jay-Z in the living room', both of which get passed as text strings from the Google Home to the URL.')

I see you have the raspberry pi code, but I'm not totally clear on the directions on how to install it. Given this is a node codebase, apache seems relatively hard to configure to operate with this. Is there recommended server software? I've tried with Nginx, but am unable to get the API to run there. Also, any directions on how to get the raspberry pi configured would be super helpful.

Thanks again!

**Comment by jishi** [comment]
node.js is self-hosting, so no need for a web server software like apache or nginx. 

If you only plan on running this software on your raspberry pi, the absolute easiest way is to just flash an SD-card with the pre-made image that you can find at https://github.com/jishi/node-sonos-http-api/releases/download/v1.0.1/sonos-http-api-1.0.1.img.gz

This is compressed using gzip, but can be extracted with most common archivers (7z, winrar, etc) easily. You need the raw .img file when writing to the SD card.

For instructions on how to prepare the SD-card, see https://www.raspberrypi.org/documentation/installation/installing-images/

For exposing this publically you will also require port forwarding in your router, as well as some sort of dynamic hostname. I think there are some detailed suggestions for this for the echo-sonos software: https://github.com/rgraciano/echo-sonos

**Comment by mkayen** [comment]
Thanks Jimmy, will follow your suggestions and resort back
