### ISSUE TITLE
changing the playbackState in a preset?

### ISSUE THREAD

**Issue by mtruni** [jishi/node-sonos-http-api#419]
Hello All,

I'm having problems getting the presets to change the playbackState. I'm not sure what the problem is so ill post as much as possible in the hope someone can help me get back on track.

Raspberry Pi, fresh install. 

When I call a preset. (http://192.168.2.22:5005/preset/example) 

I get this response in my browser. which i don't understand....

> {"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error\n    at Object.invoke (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/helpers/soap.js:95:10)\n    at /home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:606:19\n    at process._tickDomainCallback (node.js:409:9)"}

In the Sonos app I can check and the speakers are grouped and the new favorite station is listed but it is in a stopped state.

if i check the state in the browser.. http://192.168.2.22:5005/state

{"currentTrack":{"artist":"triple j","title":"x-sonosapi-stream:s25508?sid=254&flags=8224&sn=0","albumArtUri":"/getaa?s=1&u=x-sonosapi-stream%3as25508%3fsid%3d254%26flags%3d8224%26sn%3d0","duration":0,"uri":"x-sonosapi-stream:s25508?sid=254&flags=8224&sn=0","type":"radio","stationName":"triple j","absoluteAlbumArtUri":"http://192.168.2.13:1400/getaa?s=1&u=x-sonosapi-stream%3as25508%3fsid%3d254%26flags%3d8224%26sn%3d0"},"nextTrack":{"artist":"","title":"","album":"","albumArtUri":"","duration":0,"uri":""},"volume":10,"mute":false,"trackNo":1,"elapsedTime":0,"elapsedTimeFormatted":"00:00:00","**playbackState":"STOPPED",**"playMode":{"repeat":"none","shuffle":false,"crossfade":false}}

and my example.json file looks like this.

`{
  "players": [
    {
      "roomName": "Office",
      "volume": 10
    },
    {
      "roomName": "Living Room",
      "volume": 5
    }
  ],
  "playMode": {
 "playerState":"PLAYING",
    "shuffle": true,
    "repeat": "all",
    "crossfade": false
  },
  "pauseOthers": false,
"favorite": "triple j"
}`

I just cannot figure out how to change the playbackState.

Thank you very much for your help. I have searched for a forum to find some info without any luck. Is there a community where I can get some more info?

Kind Regards,
Mark

**Comment by mtruni** [comment]
Thank you very much jishi for getting me back on track. its working tip top.

Mark

**Comment by jishi** [comment]
Glad I could help. Enjoy!
