### ISSUE TITLE
no connection after power failure

### ISSUE THREAD

**Issue by Markkuuss** [jishi/node-sonos-http-api#42]
If a Sonos participant was unplugged and then reconnected, you can not access to this participant via the API until the node-http-api-sonos server has been restarted. Via the Sonos app it is possible to access this participant. To all other Sonos participants that were not dis- and reconnected, can still be accessed without any problems.

Is it possible to introduce a UPnP reconnect?

I have often the problem that a Sonos participant restarts (empty playlist) and it thus behaves like after a power failure.

**Comment by jishi** [comment]
I'm aware of the issue, but didn't put much effort into locating the source of it since I personally never move around my equipment. Of course, this is tiresome for a setup like yours, and I will probably fix it eventually.

However, if you have a player that often restart itself, you might want to look into that :) I do know that it restarts it's internal services if it identifies an IP change, that might give a clue to your behavior.

**Comment by Markkuuss** [comment]
The problem also occurs even if, for example, the router receives a software update or I unplug my switch for a short time. The problem described above can occur quite frequently. So I would be very happy if you'd fixed it.

**Comment by matiasgarciaisaia** [comment]
@jishi: do you know where could I start to work on this? I have no clue, but maybe with a little guidance I can do something.

**Comment by jishi** [comment]
@matiasgarciaisaia I think the basic idea is to identify when a players goes missing from the topology update, and handle it appropriately (meaning, forgetting about it). 

And the opposite, when a new player seem to occur in the topology update, it should add it and subscribe to all the events the same way it does during discovery.

Also, there is a special case, and that is when the player that you actually subscribed to for topology updates goes missing, in that scenario it needs to use another player to subscribe to. This would maybe be easiest to identify upon resubscription. 

Oh, and this goes into sonos-discovery.

There are probably some events that might be sent out when a device "goes missing", but that would require a lot more logic (and I'm not sure it would work better anyway).

**Comment by jishi** [comment]
This has more or less been fixed since 1.0.0. The corner case where the player responsible for topology changes goes away, will be fixed in 1.2.0. The underlying changes in sonos-discovery is already in place.

**Comment by jishi** [comment]
This should now been fixed in v1.2.0. However, it might take several minutes (<10min) for it to identify a dead endpoint because it can only happen during renewal of subscriptions which occurs every 10 minutes.
