### ISSUE TITLE
Cannot always use musicsearch for artist

### ISSUE THREAD

**Issue by Burnett2k** [jishi/node-sonos-http-api#423]
In your documentation you mention you can do a search for an artist, but that isn't always the case. BTW I'm using spotify.

The documentation shows this format:
`[/RoomName/musicsearch/{service}/{type}/{search term}](url)`

and mentions 'Perform a search for a song, **artist**, album or station and begin playing'

But, if you try and do something like:
`/master room/musicsearch/spotify/artist/lotus`

The api will return 'ERROR invalid type artist'

Your example actually shows artist searching by using /song/ instead so I switched to using that, but it doesn't always work. For example, when you do:
`/master room/musicsearch/spotify/song/lotus`
It plays some christina agulera song instead of the artist Lotus. My guess is that you are searching for song name first and then artist if you don't find a result.  I'd prefer to just have a separate command for artist.

Can we please add the /artist/ search functionality or can you let me know what I'm doing wrong??

**Comment by jplourde5** [comment]
artist is not a valid command type. Try .../song/artist:lotus
