### ISSUE TITLE
presets return error

### ISSUE THREAD

**Issue by gphr74** [jishi/node-sonos-http-api#425]
beginner here, so please forgive me if this is too obvious.

Everything seems to be running fine (e.g. I can use http for basic commands) but all presets call seem to fail. 

Here is what I have:

`> sonos-http-api@1.2.6 start /Users/guillaume/node-sonos-http-api-master
> node server.js

2016-12-30T16:30:51.181Z INFO no settings file found, will only use default settings
2016-12-30T16:30:51.626Z INFO Presets loaded: { example: 
   { players: [ { roomName: 'Kitchen', volume: 10 } ],
     playMode: { shuffle: true, repeat: 'all', crossfade: false },
     pauseOthers: true,
     favorite: 'France Inter' },
  morning: 
   { players: 
      [ { roomName: 'Kitchen', volume: 5 },
        { roomName: 'Living Room', volume: 25 } ],
     playMode: { shuffle: true, repeat: 'all', crossfade: false },
     pauseOthers: false,
     favorite: 'France Info' },
  presets: 
   { players: 
      [ { roomName: 'Living Room', volume: 10 },
        { roomName: 'Kitchen', volume: 10 } ],
     playMode: { shuffle: true, repeat: 'all', crossfade: false },
     pauseOthers: false,
     favorite: 'FIP' } }`

And this is the error I get when trying to use any of the tree presets above (in this instance, 'morning'):

`{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error\n    at Object.invoke (/Users/guillaume/node-sonos-http-api-master/node_modules/sonos-discovery/lib/helpers/soap.js:95:10)\n    at promise.then (/Users/guillaume/node-sonos-http-api-master/node_modules/sonos-discovery/lib/models/Player.js:606:19)\n    at process._tickDomainCallback (internal/process/next_tick.js:129:7)"}`

**Comment by jishi** [comment]
Are any of them radio stations? Don't define playmodes (especially
crossfade) if that is the case. They can all me omitted for radio, since
they wouldn't have any effect anyway.
