### ISSUE TITLE
sayall / clipall: individual volumes

### ISSUE THREAD

**Issue by henmedia** [jishi/node-sonos-http-api#426]
I use clipall to send a doorbell.mp3 simultaniously to all my speakers.
Also I use sayall to spell phone callers names in the whole building.

I understand that I either can set the volume as parameter or use the default volume.

But what I need is individual volumes for eachl speaker. What about setting the default volume in the configuration file which will be used if no volume is passed to the url!?

Or am I missing something and this can already be done?

Anyway ... good job - I love the *all commands which group and degroup my speakers and returns to previous states :-)

Stefan

**Comment by jishi** [comment]
You can configure default volume in settings.json, but not for individual speakers. I'm actually thinking about combining the preset function with the sayall/clipall or as a separate action to allow you to create a preset template for this command. This would give the ability to control which grouping you would want (e.g, excluding some speakers from an *all command), and also individual volume control. 

I guess that would solve your problem?

**Comment by henmedia** [comment]
yes, that would be fine as long as I can pass individual mp3 files / messages to playall / sayall

**Comment by jishi** [comment]
Yeah, would be easy to allow both scenarios. I'll keep this issue around and will close it once it's implemented.

**Comment by Khengsoon** [comment]
May I know how to utilize the clip?
the sample_clip.mp3 can it be online http://url.com/sample_clip.mp3 ? if not may I know where is the mp3 file stored location?

/Office/clip/sample_clip.mp3

Thanks jishi

**Comment by jishi** [comment]
@Khengsoon Once installed, you have a folder which is called `/static/clips` inside the sonos-http-api folder. Put any mp3 file in there, and you can reference it by the same file name with the `clip` or the  `clipall` command.

**Comment by Khengsoon** [comment]
Awesome! thanks @jishi

**Comment by lukehoverman** [comment]
Looking forward to this feature!

**Comment by jishi** [comment]
Hi guys, I have made an implementation for this that needs evaluation. It's not documented yet, but you can try it out with:

`/saypreset/[preset name]/[text you want to announce]`
`/clippreset/[preset name]/sample_clip.mp3`  

It will only use the player and volume configuration from the preset, everything else will be ignored.

**Comment by Khengsoon** [comment]
Hi Jimmy,

is the clip function depreciated?
1. I created a folder and place a mp3 file there /static/clips/doorbell.mp3
2. I call the url http://192.168.10.12/living/clip/doorbell.mp3

but seem not working. Need your advise which step I did wrongly.

Best Regards,
Kheng Soon
