### ISSUE TITLE
incorrect mute state

### ISSUE THREAD

**Issue by ewaucq** [jishi/node-sonos-http-api#43]
The following chain of commands gives an incorrect mute status on my system:

1st command:
http://localhost:5005/kitchen/mute
      => http://localhost:5005/kitchen/state gives "mute":true

2nd command:
http://localhost:5005/kitchen/volume/15
      => http://localhost:5005/kitchen/state gives "mute":false, when the sonos controller app correctly shows the room as still muted

I tried with solo room and grouped rooms, same result: changing the volume on a muted room keeps it muted for real but the state method returns 'mute:false'

Any clue? Is it just on my system?

**Comment by jishi** [comment]
should be resolved if sonos-discovery is updated. Try an npm install after update and see if that is enough. Otherwise, delete node_modules and try again.

**Comment by ewaucq** [comment]
works like a charm now! thanks for this
