### ISSUE TITLE
limit to say command ?

### ISSUE THREAD

**Issue by autofrank** [jishi/node-sonos-http-api#431]
Hi, 
Is there a limit to the number of words/characters that the say command will execute.
The following phrase succeeds 
" The weather is mist. The temperature is 10 degrees with a high of 10 and a low of 7. The humidity is 100 percent with a high or 100 and a low of 93. The pressure will vary between 1032 and 1033 millibars. The wind is 11 kmph coming from a south westerly direction. The house is currently 21.4 degrees. "

if I add another 30 characters it stops ?
Any thoughts ?
Thanks
-f

**Comment by autofrank** [comment]
okay - found this on the voicerss website

The textual content for converting to speech (length limited by 100KB) (mandatory).
Any idea how to figure out what is 100kb in words/characters?

**Comment by jishi** [comment]
I don't think you are hitting the textual length (100k is a lot of text) but rather a fixed timeout for say commands that is limited to 30 seconds. If 30 seconds is passed, It's considered out of synch and restores what was playing to not leave the player in a sad state (this does not apply for sayall).

I'm working on a better solution for this, and have made some progress (where I base it on the actual length of the generated track), but I haven't published it yet.

**Comment by jishi** [comment]
I have merged the improvements I have been working on and is part of 1.2.7. Test it and re-open issue if this problem still exist.
