### ISSUE TITLE
Changing Room/Player source to queue

### ISSUE THREAD

**Issue by rafale77** [jishi/node-sonos-http-api#436]
I can see that I can change the player source to line-in or a favorite/radio station. Is there a way to change the player to play the current queue without making any change to it?

**Comment by jishi** [comment]
Yes. If you invoke 
`/PlayerName/setavtransporturi/x-rincon-queue:RINCON_000000001400#0` 
(replace RINCON_000000001400 with the UUID of said player), it will go back to queue playback. If you want to restore the specific track you we're on when leaving, you need to keep track of the trackNo from the state and apply `/PlayerName/trackSeek/[trackNo index]` afterwards.

**Comment by jishi** [comment]
I could probably make a convenience function for restoring queue playback, but this is what would work, for now.

**Comment by jishi** [comment]
Maybe it would make sense to switch if actually invoking trackSeek, as stated in this issue: https://github.com/jishi/node-sonos-http-api/issues/376

Might be fairly intuitive.

**Comment by rafale77** [comment]
It would indeed. Did not look up this issue. I think it would make it easier.
