### ISSUE TITLE
Start automatically with Pi?

### ISSUE THREAD

**Issue by leecollings** [jishi/node-sonos-http-api#439]
Is there a way to start this `npm start` command automatically as a Forever service?

Also, how can I incorporate three calls into a script to run as an 'Action' in Domoticz?

**Comment by jishi** [comment]
I either use pm2 for it, but it might be overkill since it adds a bit of overhead. You can find instructions here: https://github.com/jishi/node-sonos-http-api/issues/20

For a more lightweight solution, read my comment here, that's what I did for the rpi-image I built:

https://github.com/jishi/node-sonos-http-api/issues/341

**Comment by jishi** [comment]
You'll need to forward the questions about Domoticz to their forum, I know there are a few people there using this.

**Comment by leecollings** [comment]
Thanks, I'm going to try running it under PM2 and see how that works. Will that automatically run if the Pi goes through a power cycle?

Also, is there any help you can give to combine a number of calls into a single call perhaps? Could this be implemented into a 'preset' as I see them featured within your files?

**Comment by jishi** [comment]
If installed correctly, yes. 

Most calls would wait for them to finish, so if you want to chain calls, you could add them to a bash script and just invoke them with curl, in series:

```
#!/bin/bash
curl http://localhost:5005/Office/volume/15
curl http://localhost:5005/Office/favorite/my_awesome_playlist
curl http://localhost:5005/Kitchen/join/Office
```

But, all of the above could be put in a preset, so you need to be more specific on what calls you want to combine in order for me to answer if a preset solves it.

**Comment by leecollings** [comment]
Hmm thanks for that, I'll try that.

In terms of presets, I had a quick read through them, and to me they seemed to be just presets of settings.

The calls I want to make are essentially:

/pauseall/
/clipall/doorbell.mp3
/resumeall/

Short and simple. Although last night it dawned on me that I may not need the first one at all, or do I?

The goal is, to resume anything that was already playing on any speaker after the doorbell MP3 is played.

**Comment by jishi** [comment]
Yeah, but that's exactly what the clipall is supposed to do, pause, play,
then resume.

**Comment by leecollings** [comment]
Oh really!? That's interesting, I'll try just the clipall command then whilst a speaker is playing and see what that does.

I would definitely say to include that in the reader file, as that's not entirely obvious and I think almost people would think they need to combine several commands.

**Comment by jishi** [comment]
It is still considered to be a bit experimental, there are a few corner cases that it doesn't handle at all (Spotify Direct/Connect) and restoring doesn't always succeed. I'm working on improving it.

Clarifying it in the README though sounds like a good suggestion.
