### ISSUE TITLE
won't start on my newl installed raspi

### ISSUE THREAD

**Issue by pjs255** [jishi/node-sonos-http-api#44]
I'm not sure what I'm doing wrong but I've installed to a new raspi (using "npm install") but when I try and run "node server.js" I get the following error. Any help appreciated. 

`no settings file found, will only use default settings`
`http server listening on port 5005`
`no preset file, ignoring... `
` `
`==== Stack trace ============================================`
`Security context: 0x4fd34659 <JS Object>#0#`
`    1: parse(aka parse) [/home/pi/node-sonos-http-api/node_modules/sonos-discovery/node_modules/easysax/easysax.js:~403] (this=0x4fd08091 <undefined>,xml=0x306c0bd1 <Very long string[1100]>#1#)`
`    2: parse [/home/pi/node-sonos-http-api/node_modules/sonos-discovery/node_modules/easysax/easysax.js:142] (this=0x306c1891 <an EasySAXParser>#2#,xml=0x306c0bd1 <Very long string[1100]>#1#)`
`    3: /* anonymous */ [/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/sonos.js:271] (this=0x306c0325 <an IncomingMessage>#3#)`
`    4: emit [events.js:92] (this=0x306c0325 <an IncomingMessage>#3#,type=0x3910f03d <String[3]: end>)`
`    5: /* anonymous */ [_stream_readable.js:944] (this=0x4fd34701 <JS Global Object>#4#)`
`    6: _tickCallback [node.js:442] (this=0x2d87d921 <a process>#5#)`
`==== Details ================================================`
`[1]: parse(aka parse) [/home/pi/node-sonos-http-api/node_modules/sonos-discovery/node_modules/easysax/easysax.js:~403] (this=0x4fd08091 <undefined>,xml=0x306c0bd1 <Very long string[1100]>#1#)...`

There is more to the error if needed.

**Comment by jishi** [comment]
Which version of node? This sounds like node is crashing pretty hard. How did you install linux on your pi, and which pi-model?

**Comment by pjs255** [comment]
It's a Pi 2 Model B running v0.10.36 of node and I installed linux using the NOOBS v1_3_12 distribution.
It seems to die during the "discovery" and handling of XML

**Comment by jishi** [comment]
How did you install node 0.10.36? Did you compile it yourself? Try using the precompiled version from here: http://nodejs.org/dist/v0.10.28/node-v0.10.28-linux-arm-pi.tar.gz

And see if the issue persists.

**Comment by pjs255** [comment]
I installed with the following commands:

`wget http://nodejs.org/dist/v0.10.36/node-v0.10.36.tar.gz`
`gunzip node-v0.10.36.tar.gz`
`tar -xvf node-v0.10.36.tar`
`cd node-v0.10.36/`
`./configure`
`make`
`make install`
`npm install`

I'll experiment with the precompiled version and see how it goes...

**Comment by pjs255** [comment]
I went back to basics and installed from scratch without incident. Issue closed.

**Comment by markusschweitzer** [comment]
Hi, I've got exactly the same issue - same system except that I'm using raspbian :/

Can you describe the steps how you solved it?

br,
markus

**Comment by jishi** [comment]
@markusschweitzer This seems to be triggered by a bug in node.js, so you need to specify how you installed raspbian, version etc, as well as the steps you took to install node.js, and maybe also the version that you are running:

node -v
