### ISSUE TITLE
how to change the state content

### ISSUE THREAD

**Issue by ddqp** [jishi/node-sonos-http-api#440]
I don't want it to show so many items, just want only  to know the volume level and playback status.

so I changed the "node-sonos-http-api/static/docs/spec.js" to change the state content, but nothing changed, it still give me a lot of items,  in http://local:5005/living_room/state

**Comment by jishi** [comment]
The state is defined from the underlying library sonos-discovery library. Easiest way to make it easier, would be to make a copied action that slims down the response object. Any file in the `action` folder will be read and parsed, so you can create your own, custom commands that way. 

But usually it's not a problem to have "extraneous" data when you programmatically consume stuff, so it's an odd requirement to have? Unless you are visually checking the state, but then there should be easier way of making it human readable (like a static HTML page that does an AJAX request against this API). You can drop any static files into the static folder of this project, and they would be hosted.

**Comment by ddqp** [comment]
thanks,
I got it. will have a try!
