### ISSUE TITLE
How to autostart node-sonos-http-api ?

### ISSUE THREAD

**Issue by michiel86** [jishi/node-sonos-http-api#443]
Hello, I finally got node-sonos-http-api working on my orange PI running Debian. There's one small thing I can't seem to figure out.
Every time after resetting my Orange PI I have to start node-sonos-http-api again using the npm start command. Is there a way to autostart node-sonos-http-api ?

When node-sonos-http-api start loading my local music library it stops after a while:

n2017-01-21T19:18:31.874Z INFO http server listening on port 5005
Loading Library
Track Count 0
Track Count 1000
Track Count 2000
Track Count 3000
Track Count 4000
Track Count 5000
Track Count 6000
Track Count 7000
Track Count 8000
Track Count 9000
Track Count 10000
Track Count 11000
Track Count 12000
Track Count 13000
Track Count 14000
Track Count 15000
Track Count 16000
Track Count 16357
ERROR: {"errno":-13,"code":"EACCES","syscall":"open","path":"/home/michiel/git/n                       ode-sonos-http-api/cache/library.json"}
2017-01-21T19:24:39.612Z ERROR
  Error: EACCES: permission denied, open '/home/michiel/git/node-sonos-http-api/                       cache/library.json'
    at Error (native)
 Any idea what is casing this prblem ?

Thank you !

**Comment by jishi** [comment]
Search among the closed tickets regarding autostart. There are several
discussions with different options for you. The most common approach is to
use pm2 to demonize the api.

**Comment by michiel86** [comment]
Thanks I'll look into it ! Any idea what going wrong when it's trying to load the library ?

**Comment by jishi** [comment]
Not without providing any logs :)

**Comment by michiel86** [comment]
Thank you for getting back to me, would you mind telling me where I can find the logs ?

**Comment by jishi** [comment]
It's the output you get when you start it in the terminal. I assume you get
some sort of error since you know there is some error with library loading?

**Comment by michiel86** [comment]
Do you mean the error I posted in the OP ?
ERROR: {"errno":-13,"code":"EACCES","syscall":"open","path":"/home/michiel/git/n ode-sonos-http-api/cache/library.json"}
2017-01-21T19:24:39.612Z ERROR
Error: EACCES: permission denied, open '/home/michiel/git/node-sonos-http-api/ cache/library.json'
at Error (native)

**Comment by jishi** [comment]
Ah, sorry. Missed that in the email notification. It's a permission error, make sure that the process running has write access to the cache folder. If unsure, just give it rw for all users. 

`chmod 777 /home/michiel/git/node-sonos-http-api/cache`

**Comment by michiel86** [comment]
I tried that unfortunately without any succes. When I go to http://192.168.1.47:5005/LIVING ROOM/musicsearch/library/load the webpage returns with this error after a while:

{"status":"error","error":"Cannot read property 'items' of undefined","stack":"TypeError: Cannot read property 'items' of undefined\n    at loadLibrary.then.then (/home/michiel/git/node-sonos-http-api/lib/music_services/libraryDef.js:220:47)"}

Any idea what else I can try ? Thanks for your response so far !

**Comment by jishi** [comment]
Hm, you actually have a library.json file already? Could that have been created with the process runnig as another user earlier? 

You should probably have called chmod with the recursive flag, to also change for all files and folders:

`chmod -R 777 /home/michiel/git/node-sonos-http-api/cache`

If that doesn't help, I suggest clearing the whole cache folder to start afresh.

**Comment by michiel86** [comment]
Yes, it creates a library.json file in the cache directory when I go to /LIVING ROOM/musicsearch/library/load 
I reinstalled node-sonos-http-api this time it already stops at Track count 0 
**2017-01-23T21:05:13.278Z INFO http server listening on port 5005
Loading Library
Track Count 0
Track Count 0**
I gave full 777 permission to the cache directory and the library.json file which doesn't change anything :(
I feel like I'm running out of options, is there anything else I can try ?

**Comment by jishi** [comment]
Well, now you get a different error. I'm not very familiar with the music search addition, that was a contribution by @jplourde5 and I have yet to work with it. Maybe has has some ideas?

**Comment by jplourde5** [comment]
I haven't seen that error before.  Is there any chance that you are running out of space?

Another possibility is that you have a corrupted or strange record in the Sonos library and is choking because of a missing variable.

What happens if you run the app from a computer instead of the pi?

**Comment by michiel86** [comment]
Thank you both for getting back to me, I installed node on my Windows notebook and ran the library scan again. The result is exactly the same as on my Pi. So I guess it has to do with one or multiple records in my library. Is there any possibility to see which file(s) is causing this issue ?
[img]http://www.imghost.nl/download/node-sonos.png[/img]

**Comment by jishi** [comment]
If you can start it with trace logging and send the logs, I would get a raw representation of the data from your library, and maybe see what chokes it. 

In windows cmd (I think):

`set NODE_LOG_LEVEL=trace`
`npm start > trace.log`

Start the loading of the library, wait for some time (so you know that this error occurs), then quit it, and email the trace.log file to jimmy at shimizu.se

**Comment by jishi** [comment]
I had forgotten about this issue. But looking at the latest log, and your last post here, it no longer seems to find any tracks in your Sonos library. Are you sure that you actually see any tracks in your Sonos client for your own library? Or did you clear it or factory reset your system or something?

**Comment by micheld93** [comment]
> Thank you both for getting back to me, I installed node on my Windows notebook and ran the library scan again. The result is exactly the same as on my Pi. So I guess it has to do with one or multiple records in my library. Is there any possibility to see which file(s) is causing this issue ?
> ![node-sonos](https://cloud.githubusercontent.com/assets/19407298/22247115/6a493730-e238-11e6-8e51-24454d227a28.png)

The same output appears with newest Raspberry Pi OS (Bullseye) as well.  Interestingly, the home bridge plug-in "Homebridge Sonos" still works correctly but it is not possible to open the localhost site in a web browser. With `sudo systemctl status sonosapi.service` I get this output:

```
Dez 02 11:29:45 homebridge systemd[1]: sonosapi.service: Failed with result 'exit-code'.
Dez 02 11:29:55 homebridge systemd[1]: sonosapi.service: Scheduled restart job, restart counter is at 5227.
Dez 02 11:29:55 homebridge systemd[1]: Stopped Sonos HTTP API Daemon.
Dez 02 11:29:55 homebridge systemd[9149]: sonosapi.service: Failed to locate executable /home/pi/node-sonos-http-api-master/server.js: Permission denied
Dez 02 11:29:55 homebridge systemd[9149]: sonosapi.service: Failed at step EXEC spawning /home/pi/node-sonos-http-api-master/server.js: Permission denied
Dez 02 11:29:55 homebridge systemd[1]: Started Sonos HTTP API Daemon.
Dez 02 11:29:55 homebridge systemd[1]: sonosapi.service: Main process exited, code=exited, status=203/EXEC
Dez 02 11:29:55 homebridge systemd[1]: sonosapi.service: Failed with result 'exit-code'.
```
