### ISSUE TITLE
Returning State of All Zones in One Command

### ISSUE THREAD

**Issue by eg33** [jishi/node-sonos-http-api#444]
Hi,

I am extremely grateful for this api. I'm using this for home automation.

What I would love to see (or maybe it exists and I can't see) is returning **ALL zone/player statuses** in one JSON string.

I see in Issue #94 that you are expecting to use "root" room as the last coordinator, so I would suggest that `/state/all` be used to return all zones with statuses separated into different zones/rooms.

This will greatly help with me checking in on the system as a whole without the need to iterate through each room.

If this exists, please let me know how I can call the function.

Thank you

**Comment by jishi** [comment]
Could you explain why you want to get info about all players in one
request? For what purpose? I'm trying to understand if that is a common
need, or if there is actually some other solution that might be better.

There is /zones, but that doesn't contain detailed information from the
coordinator.

**Comment by eg33** [comment]
You're absolutely right. I missed the `/zones` function. I believe this will suit my needs. Mostly I just would like to see what zones are currently playing and I thought `/state` was the proper way to get this.

Thank you for your quick reply. "Problem" solved 👍
