### ISSUE TITLE
crashes when URL written to track.uri (I think)

### ISSUE THREAD

**Issue by bbrendon** [jishi/node-sonos-http-api#445]
http://pastebin.com/raw/Wc6h3TLh

I just set this up earlier today and went to dinner then came back and now it's not working. Is something in the "cloud" down that is causing this? I even reinstalled it. Very strange.

**Comment by bbrendon** [comment]
I figured out a work-around. I played started/stopped pandora on all my speakers and then it worked. I think there was something residual saved in the speaker that sonos-http-api couldn't parse and caused it to crash.

**Comment by bbrendon** [comment]
This is happening consistently. If my other HA system plays something on sonos it appears node-sonos-http-api doesn't like the value in track.uri and crashes. I think the value that causes issue is ``http://10.x.x.x/play.mp3`` but I can't be sure -- I'm not an expert how the fields match up.

**Comment by jishi** [comment]
Sounds to me that your players frequently has a playback state that it doesn't manage to parse. 

Sounds like your HA-system has some sort of TTS support for Sonos? Is that correct? When the app starts crashing, if you could start it with trace logging enabled (for linux/MacOS):

`NODE_LOG_LEVEL=trace node server.js > crash.log`

And then email that crash.log file to me ( jimmy at shimizu.se ) I can take a look.

**Comment by bbrendon** [comment]
Done. I emailed you.
