### ISSUE TITLE
Since Sonos Update 7.1 no access to zones/playlists/favourites

### ISSUE THREAD

**Issue by Sillec123** [jishi/node-sonos-http-api#448]
Since the last update i only can reach the main site over host:5005 but if i click on zone, favourites, playlist or somethingelse i get an http error.

**Comment by jishi** [comment]
Really? Hm, I saw the update yesterday but didn't upgrade yet... 

Have you restarted your API? If you are running an older version, it might not rediscover your system if all IPs changes. Since an upgrade includes a reboot of all players, it might have lost the system completely.

**Comment by clearminds** [comment]
They have changed the API and locked down things... :/

**Comment by jishi** [comment]
But I'm using the 7.1 mobile client with a 7.0 system and that works fine. I'll have to investigate further when I get home.

**Comment by clearminds** [comment]
You can find more information here: http://www.cepro.com/article/new_sonos_api_disrupts_home_automation_integration_but_lays_solid_foundatio

**Comment by Sillec123** [comment]
Very strange, in the first minutes i can use get zones, favourites and playlists. But if i send a custom command like /roomname/favourite/radio the complete interface gets down.


Log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@4.1.1
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle sonos-http-api@1.2.6~prestart: sonos-http-api@1.2.6
6 silly lifecycle sonos-http-api@1.2.6~prestart: no script for prestart, continuing
7 info lifecycle sonos-http-api@1.2.6~start: sonos-http-api@1.2.6
8 verbose lifecycle sonos-http-api@1.2.6~start: unsafe-perm in lifecycle true
9 verbose lifecycle sonos-http-api@1.2.6~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/MagicMirror/modules/node-sonos-http-api/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle sonos-http-api@1.2.6~start: CWD: /root/MagicMirror/modules/node-sonos-http-api
11 silly lifecycle sonos-http-api@1.2.6~start: Args: [ '-c', 'node server.js' ]
12 silly lifecycle sonos-http-api@1.2.6~start: Returned: code: 1  signal: null
13 info lifecycle sonos-http-api@1.2.6~start: Failed to exec start script
14 verbose stack Error: sonos-http-api@1.2.6 start: `node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid sonos-http-api@1.2.6
16 verbose cwd /root/MagicMirror/modules/node-sonos-http-api
17 error Linux 4.4.26-v7+
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.9.1
20 error npm  v4.1.1
21 error code ELIFECYCLE
22 error sonos-http-api@1.2.6 start: `node server.js`
22 error Exit status 1
23 error Failed at the sonos-http-api@1.2.6 start script 'node server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the sonos-http-api package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs sonos-http-api
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls sonos-http-api
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by jishi** [comment]
@clearminds That is actually old news, and doesn't seem to be related to the 7.1 rollout. 

@Sillec123 could you please start it without npm, just `node server.js`? I can't figure out the exit cause from that output.

**Comment by Sillec123** [comment]
If i start it again over ssh , everything works.

**Comment by clearminds** [comment]
@jishi Oh! Just felt like it would be related - when I updated my system to 7.1 via app, and then started 7.0 sonos client, a lot of strange things happend til I also updated the windows client to 7.1. Let's hope it isn't related and it hasn't changed anything. :)

**Comment by leecollings** [comment]
Is this 'update' mentioned the iOS app or the actual Sonos system update?

I'm reluctant to update my Sonos now in fear of this not working, as I intend to use this heavily within Domoticz.

**Comment by jishi** [comment]
False alarm, no issue with 7.1 that I can see. Something else must be acting up because of the update, the usual recycle scheme (modem, router, players) is a good start for those of you that have problems.
