### ISSUE TITLE
Possible? Snapshot current Zone States, Group Zones, Play Alarm Sound, Ungroup Zones and recovery to snapshot?

### ISSUE THREAD

**Issue by Sillec123** [jishi/node-sonos-http-api#449]
Hey,

has someone make the following:
- Snapshot of all zones (stated)
- Group Zone 1, 2
-Play new Sound on Group
- Ungroup Zone 1,2
- Recovery Snapshot

Example:

Speaker 1 plays a playlist with track xx at xx second
Speaker 2 plays radio
Speaker 3 is paused

My smarthome triggers an alarm. A script makes snapshots of the speakers and grouped them to play an alarm sound. After that it will ungroup them and the old state will be the same.

Speaker 1 plays the playlist with track xx at xx second
Speaker 2 plays the old radio station
Speaker 3 is paused

**Comment by jishi** [comment]
You can do that with clipall, albeit you can't currently control which it will play the clip on (it will use all of them).

The plan is to support say and clip commands for a preset, which would allow you to use selected players and also individual volumes during the announcement/clip. I think that would support what you are asking.

**Comment by jishi** [comment]
See https://github.com/jishi/node-sonos-http-api/issues/270
