### ISSUE TITLE
XML encode for OpenRemote

### ISSUE THREAD

**Issue by Markkuuss** [jishi/node-sonos-http-api#45]
Is it possible to insert a XML-encoding like this:
xmlEntities.encode(nodeValue)

I want to use "absoluteAlbumArtURI" as an OpenRemote-sensor. But the OpenRemote data is stored as XML file. Thus, there are problems with the XML file, if the "&" and other characters are not stored encoded.

**Comment by jishi** [comment]
well, I respond with valid JSON-data, and it doesn't make sense to "adjust" that just to fit the need for OpenRemote. i would say that it is actually the responsibility of the tool in charge of fetching the state data, and encode it if transferred to XML, and it surprises me that OpenRemote wouldn't handle this correctly. How are you reading out the state info, and what creates the XML file?

**Comment by Markkuuss** [comment]
I use in OpenRemote the webview element that has a custom sensor as a source. The command for the sensor looks like this. 
![command](https://cloud.githubusercontent.com/assets/10926460/6233897/9c91c200-b6d6-11e4-92b6-32676afa2aea.JPG)

If the characters are not encoded as follows, the screens in OpenRemote do not show any content received by the sensors.

char	XML
<	&lt;
>	&gt;
&	&amp;
"	&quot;
'	&apos;

**Comment by jishi** [comment]
This sounds more like a bug in OpenRemote. If OpenRemote reads JSON-data, it should escape it accordingly before storing it into XML, otherwise it is broken. If I start XML-encoding my JSON-data, everyone else will start having issues instead.

**Comment by jishi** [comment]
Bug in external system.
