### ISSUE TITLE
Changing value returned for State

### ISSUE THREAD

**Issue by Ce1gE** [jishi/node-sonos-http-api#450]
Is there an easy way to modify the values returned for 'playbackstate'. This currently returns for example 'PAUSED_PLAYBACK'. Id like to modify this to be a numeric value

i.e. 1 = Playing, 2 = Paused etc

The reason for this is the home automation I'm using (Loxone) can only recognise numerical values currently and the fix for this is very convoluted resulting in converting text to ASCII and then back to text.

I only want the Loxone server to monitor the state and send commands when required based on current state.

**Comment by jishi** [comment]
It's fairly easy to make your own actions and do whatever you please with them. If this is an actual call, to `/room/state`, you can just make your own custom state, by copying `lib/actions/state.js`, where you add an extra step that transforms volume to a numeric value for you, and then register that action with a different name (e.g `custom_state`).

If it is for the webhook however, then it's not as trivial.

**Comment by Ce1gE** [comment]
Thank you @jishi 
Ok I have got a customstate function which works just returning the state. when I try to modify whats returned though it causes the process to restart. I'm struggling here !! :( 
Its been many years since I coded like this so a bit rusty and relying on google searches.

Any way to extract just the 'playbackState' to a variable and then compare this and return a number

A bit like 
if (playbackState -eq 'STOPPED")
var1 = 0
if (playbackState -eq 'PAUSED_PLAYBACK")
var1 = 1
if (playbackState -eq 'PLAYING")
var1 = 2

Return Var1

So far I have
function customstate(player) {
 const customState = Promise.resolve(player.state);
   return customState;
}
but like I say if I try and do anything else it causes  the process to restart

anything would be greatly appreciated.

**Comment by jishi** [comment]
Dealing with Promises can be tricky for the uninvited :). Here you go:

```
'use strict';
const playbackStateMap = {
  STOPPED: 0,
  PAUSED_PLAYBACK: 1,
  PLAYING: 2,
};

function transform(state) {
  const clonedState = Object.assign({}, state);
  clonedState.playbackState = playbackStateMap[state.playbackState];
  return clonedState;
}

function state(player) {
  return Promise.resolve(transform(player.state));
}

module.exports = function (api) {
  api.registerAction('custom_state', state);
}
```

This register an action called `custom_state` which does what you as for. The `Object.assign({}, state);` is because the state object is "immutable", so I'm making a clone of it. Hope that helps!
