### ISSUE TITLE
sonos node on synology NAS

### ISSUE THREAD

**Issue by JohanSpijker** [jishi/node-sonos-http-api#451]
Hello,
Do you think we can install the http node on an synology nas drive ?
Greetings, Johan

**Comment by jishi** [comment]
I think there  are several people running it on the synology, both directly and with Docker. See

https://github.com/jishi/node-sonos-http-api/issues?utf8=%E2%9C%93&q=is%3Aissue%20synology

I don't have any more detailed info about how installation is done, and I don't own a synology NAS myself. Do note that there are both Intel and ARM based NAS:es, and the installation process might differ between them. also, you need to have at least node 4.x.x installed, and I think the official node.js package from Synology is still on 0.12.x which is too old.
