### ISSUE TITLE
Cant call Favorites??

### ISSUE THREAD

**Issue by AdamCapes** [jishi/node-sonos-http-api#452]
So playlists work fine and i can call xxxxx:5005/favorites which returns my favorites  but when i try and call one i get the error below.  Any ideas?

{"status":"error","error":"Favorite not found","stack":"Error: Favorite not found\n    at system.getFavorites.then.then (/home/adam/Desktop/node-sonos-http-api-master/node_modules/sonos-discovery/lib/prototypes/Player/replaceWithFavorite.js:21:15)\n    at process._tickDomainCallback (internal/process/next_tick.js:129:7)"}

**Comment by jishi** [comment]
Can you provide example of the call, and the output of favorites? It is supposed to be case insensitive, but I might be wrong. Also, if you have any special characters in the favorite names, that can probably confuse things.

**Comment by AdamCapes** [comment]
Hi Jishi.  Thanks for helping. My call is :5005/favorite/BBCRadio2 and the favorites output is:

["BBC Radio 2","You Don't Know Me"]

I've tried with and without spaces and + in between but no joy.

**Comment by jishi** [comment]
try `:5005/favorite/BBC%20Radio%202`

Space is url encoded with %20, + sign is a legacy way of encoding querystring parameters, and are treated as literal +-signs in a URL path. Not sure where you implement this (which language you are using or tool), but doing `encodeURIComponent('BBC Radio 2')` would be the way to do it in javascript.

**Comment by AdamCapes** [comment]
%20 works!  Thanks again.  Im using it with the Echo integration here https://github.com/rgraciano/echo-sonos but its not working for some reason.  Don't suppose you'd know why?  but no worries if not, ill investigate that side some more.

**Comment by AdamCapes** [comment]
Ignore me, sorted it
