### ISSUE TITLE
Add/remove speakers to groups

### ISSUE THREAD

**Issue by gkjpettet** [jishi/node-sonos-http-api#453]
Would you consider adding the ability to add or remove a speaker to or from a group? Perhaps the API could look something like this:

```
http://localhost:5005/group/create/{groupName}
http://localhost:5005/group/remove/{groupName}
http://localhost:5005/{room name}/joinGroup/{groupName}
http://localhost:5005/{room name}/leaveGroup/{groupName}
```

**Comment by jishi** [comment]
It already exists, I just seem to not have documented it. See https://github.com/jishi/node-sonos-http-api/blob/master/lib/actions/group.js#L46-L53

Basically, you reference a group, by any player name that is part of that group. Then you can use join/leave commands to add/remove players.

**Comment by gkjpettet** [comment]
Fantastic! Great to see it already exists. I'll toy around with it. Such a fantastic project mate. Much appreciated.
