### ISSUE TITLE
cant play from library

### ISSUE THREAD

**Issue by DirtySurti** [jishi/node-sonos-http-api#455]
Hi, I can get my echo dot to play to my Sonos a predefined playlist fine.

However if I ask to play by track name or artist or album name from my library on my NAS then it doesn't work.

Any ideas anyone pls ?

**Comment by jishi** [comment]
You need to figure out the exact HTTP call, otherwise it is impossible to have any idea of whats wrong.

**Comment by DirtySurti** [comment]
in lambada logs its calling /Living%20Room/musicsearch/library/song/artist/timbaland

if i paste that into my browser using my NAS ip I get error:

{"error":"action 'musicsearch' not found"}

**Comment by jishi** [comment]
Sounds like you are not running the latest version of the http-api. Try switching to chris-sns Docker image, that one is automatically built when I push new stuff to my repo. 

But it also looks wrong that it sends /song/ AND /artist/, but that seems more like a bug in echo-sonos.

**Comment by DirtySurti** [comment]
I am using https://hub.docker.com/r/riemers/sonos_http_api/
guess it out of date - will swap to chris-sns

**Comment by DirtySurti** [comment]
ok replaced docker image....and now in logs in lambada its calling
/Living%20Room/musicsearch/library/song/artist%3ANelly%20Furtado/
called that locally and get error:

{"status":"error","error":"Cannot read property 'items' of undefined","stack":"TypeError: Cannot read property 'items' of undefined\n    at loadLibrary.then.then (/app/lib/music_services/libraryDef.js:224:47)"}

**Comment by jishi** [comment]
Have you actually triggered an initial loading of your local library first? It requires that as a manual step, IIRC

**Comment by DirtySurti** [comment]
Sorry how do i do that ?

**Comment by jishi** [comment]
Basically /musicsearch/library/load but according to documentation it should do that automatically if not already loaded. Do you have a library.json in your cache folder?

**Comment by jplourde5** [comment]
The problem is the /artist/ which is not a valid command.

Should be

...song/timbaland

The routine tries to figure out on its own based on the fuzzy search results whether the request is for an artist or song

For some of the services you can include an artist hint if you are getting sketchy results, but it is

...song/artist:timbaland

I can't remember if I supported hints for the library or not.  The hint support originated from their existence in some of the music service search engines.

**Comment by DirtySurti** [comment]
@jishi I don't have library.json
whem I call http://192.168.1.118:5005/musicsearch/library/load I get : 

{"status":"error","error":"Cannot read property 'tracks' of undefined","stack":"TypeError: Cannot read property 'tracks' of undefined\n    at loadLibrary.then.then (/app/lib/music_services/libraryDef.js:224:40)\n    at process._tickDomainCallback (internal/process/next_tick.js:129:7)"}

**Comment by jplourde5** [comment]
You still need to include the room in path when you call the library load. Doesn't load by room but some room needs to be in the path.

Also make sure that you can see the cache folder where the library needs to be created.

Make sure that you can play the library through the Sonos app.

Look at the instructions very carefully, especially in regards to how the urls are constructed.

**Comment by DirtySurti** [comment]
tried and got error for: http://192.168.1.118:5005/living%20room/musicsearch/library/load/

{"status":"error","error":"Cannot read property 'items' of undefined","stack":"TypeError: Cannot read property 'items' of undefined\n    at loadLibrary.then.then (/app/lib/music_services/libraryDef.js:224:47)"}

**Comment by DirtySurti** [comment]
@jishi what should the contents of library.json be ?

**Comment by jishi** [comment]
It should contain your local tracks. But that's irrelvant if you don't even have that file. Soudns to me like you have some permission problems with the cache folder (inside or outside of your docker container), so start by trying to investigate that.

**Comment by DirtySurti** [comment]
ok I can see in dockers logs:
Error: EACCES: permission denied, open '/app/cache/library.json'
stdout
19:28:35
    at Error (native)

**Comment by DirtySurti** [comment]
anyone  know how I can amend permissions on the above ?

**Comment by jishi** [comment]
Just give r+w permissions for that folder to everyone. I assume you are mounting that to a folder on the Docker host machine? 

I suggest you read up on docker volume mounting and basic file permissions.

**Comment by DirtySurti** [comment]
Yes I have mounted that location in the host NAS as per Chris instructions. Thanks for the pointers

**Comment by jplourde5** [comment]
Also leave the slash off of the end of load.  It may cause a problem.

Should be:

http://192.168.1.118:5005/living%20room/musicsearch/library/load

**Comment by DirtySurti** [comment]
@jplourde5 its a permissions issue looking at the logging in docket in my Synology. Unfortunately I have no clue how to fix them issues as no nothing about Docker to be honest

**Comment by jishi** [comment]
If you used the `-v /tmp/cache:/app/cache` switch, just do the following:

`chmod 777 /tmp/cache`

It all depends on how you started the docker image.

**Comment by DirtySurti** [comment]
Hi used instructions as per 
https://hub.docker.com/r/chrisns/docker-node-sonos-http-api/

**Comment by jishi** [comment]
Yeah, but it references 'pwd' which is the current folder you are starting it from, so unless you can be more specific than that, I can't help.

**Comment by DirtySurti** [comment]
I think I have it working. It's created and populated file library.json !
