### ISSUE TITLE
Error when installing Node Sonos HTTP API

### ISSUE THREAD

**Issue by drekkie** [jishi/node-sonos-http-api#456]
When I use the command npm install --production I get command not found. What is wrong?

pi@raspberrypi:~/node-sonos-http-api $ sudo apt-get install nodejs
Reading package lists... Done
Building dependency tree
Reading state information... Done
nodejs is already the newest version.
nodejs set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
pi@raspberrypi:~/node-sonos-http-api $ npm install --production
-bash: npm: command not found

**Comment by jishi** [comment]
the raspbian jessie `nodejs`package is too old to use with this project, it is version 0.12.x, and you need 4.x.x or higher. Uninstall it and install the official node.js binaries:

for Pi 1: https://nodejs.org/dist/v6.9.4/node-v6.9.4-linux-armv6l.tar.xz
for Pi 2/3: https://nodejs.org/dist/v6.9.4/node-v6.9.4-linux-armv7l.tar.xz

You can also use version 7.4.0 if you want, however that comes with npm version 4 which I haven't tested personally. 

Remove the current nodejs apt package, to avoid conflicts. Install the xz archive tool if you haven't already (it is required to unzip the above files): 
`apt-get install xz-utils`

Easiest way to install it, would be to put the above file in /tmp, then do:

`cd /usr`
`tar --strip-components 1 -xJf /tmp/node-v6.9.4-linux-armv7l.tar.xz`

That would unzip all the required files in locations that would be available through the PATH env variable. You may choose to put it in `/usr/local`, but /usr/local/bin isn't usually in the PATH env, I do the above for simplicity.
