### ISSUE TITLE
Cannot read property aviTransportUri of undefined

### ISSUE THREAD

**Issue by kshartman** [jishi/node-sonos-http-api#458]
I get this a lot on presets:

{"status":"error","error":"Cannot read property 'avTransportUri' of undefined","stack":"TypeError: Cannot read property 'avTransportUri' of undefined\n    at /usr/local/src/v3/sonos-http-api/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:55:17\n    at Array.reduce (native)\n    at groupWithCoordinator (/usr/local/src/v3/sonos-http-api/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:53:6)\n    at /usr/local/src/v3/sonos-http-api/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:113:12"}

Example Preset:

{
    "players": [
        { "roomName": "Kitchen", "volume": 40},
        { "roomName": "SunRoom", "volume": 40},
        { "roomName": "LivingRoom", "volume": 40},
        { "roomName": "ShanesOffice", "volume": 40}
    ],
    "shuffle": false,
    "repeat": "all",
    "crossfade": false,
    "favorite": "Boot Liquor",
    "pauseOthers": false
}

Boot Liquor is a tunein radiostation favorite.  It works perfectly if I invoke it as favorite rather than preset but then I can't control the speaker selection which is the issue here I believe.

**Comment by jishi** [comment]
Does all of the defined players in your preset still exist? Sounds like you are referencing players that the api no longer are aware of. I can probably add a filtering to avoid crashes under these circumstances, but first and foremost, I think your preset is wrong. 

Also, try restarting the API, and see if the problem still exist.

**Comment by leonmoonen** [comment]
FYI, I had a similar issue, indeed after changing a player name and forgetting that I had to update it in the preset. Instead of filtering the non-existing players (which would hide the naming problem), would it be an option to generate a more informative error so people know what to check?
