### ISSUE TITLE
current track duration is always 0

### ISSUE THREAD

**Issue by ewaucq** [jishi/node-sonos-http-api#46]
After installing the latest version (following issues #43) there seems to have an issue with the value of the current track duration: it is always 0 
I remember that this duration was 0 when playing a radio stream (tunein) but was correctly set when playing local files or from spotify. Now it's 0 whatever I'm playing.
(note: next track duration value is fine)
Thanks

**Comment by jishi** [comment]
I reverted the dependency to 0.15.1 for now until I fix the pull request
