### ISSUE TITLE
Webhook not working for external url

### ISSUE THREAD

**Issue by mykdavis** [jishi/node-sonos-http-api#460]
When using the webhook and the test_endpoint.js the hook works really well but as soon as I change to an external link it doesn't post to the url.

Is there any log I can look at to see any issues?

FYI I am using an raspberry pi.

**Comment by jishi** [comment]
Shouldn't be an issue, unless that endpoint uses HTTPS and has an invalid or self-signed certificate?

Try calling curl or wget from an ssh session to the same endpoint, see what it says.

**Comment by mykdavis** [comment]
Ah curl returns 302, but when I enable CURLOPT_FOLLOWLOCATION it works

**Comment by jishi** [comment]
Can't you call the concrete url that it redirects to? Not sure if a POST is supposed to follow redirects blindly...
