### ISSUE TITLE
On syntax error in settings.json, log reports settings not found instead of settings invalid

### ISSUE THREAD

**Issue by pauxus** [jishi/node-sonos-http-api#465]
When settings.json has an syntax error (most common case: trailing comma because of copy and paste, the log only reads: 

`INFO no settings file found, will only use default settings`

It would be nicer if the log reported something like "settings found, but unreadable".

**Comment by jishi** [comment]
I've distinguished between missing file and parse error now. I also use a JSON5 parser to be more forgiving in the parsing, allowing normal javascript object notation (thus allowing trailing commas and such).
