### ISSUE TITLE
URI error after using 'say' command with % in side the string.

### ISSUE THREAD

**Issue by Burnett2k** [jishi/node-sonos-http-api#466]
Hi Jishi,
Every morning I hit a quote of the day api and today something interesting happened. It returned this string **'Life is 10% what happens to us and 90% how we react to it.'** .  The error is happening when I run the 'say' command on this string.  I get a URI error where the system is confused thinking I am passing in a url encoded string when I am not.

To further test and see if this was a limitation of AWS polly, I loaded up the website and pasted in the text.  Polly is actually smart enough to know a % means 'percent' and she reads it perfectly. I was pretty sure she would since I also have her 'say' weather to me which may be something like 60°F and that doesn't throw an error. Do you know if something can be changed with your validation to allow for % to be in the string? Of course I could remove special characters, but in this case the quote would make no sense without the word 'percent' in it.

One last thing, when this error occurs my Sonos speaker seems to stop sending webhook data and i have to restart the application. Is that type of error something that should really hang the system up?

ERROR MESSAGE BELOW
----------------------------
URIError: The encoded phrase quote%20of%20the%20day%20is%20by:%20Dennis%20P.%20Kimbro.%20It%20is:%20Life%20is%2010%%20what%20happens%20to%20us%20and%2090%%20how%20we%20react%20to%20it. could not be URI decoded. Make sure your url encoded values (%xx) are within valid ranges. xx should be hexadecimal representations
    at decodeURIComponent (native)
    at Object.say (C:\sonos\node-sonos-http-api\lib\actions\say.js:16:12)
    at handleAction (C:\sonos\node-sonos-http-api\lib\sonos-http-api.js:110:35)
    at HttpAPI.requireDir.requestHandler.handleAction.then [as requestHandler] (C:\sonos\node-sonos-http-api\lib\sonos-http-api.js:87:5)
    at C:\sonos\node-sonos-http-api\server.js:50:13
    at Server.finish (C:\sonos\node-sonos-http-api\node_modules\node-static\lib\node-static.js:111:13)
    at finish (C:\sonos\node-sonos-http-api\node_modules\node-static\lib\node-static.js:170:14)
    at C:\sonos\node-sonos-http-api\node_modules\node-static\lib\node-static.js:178:20
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)

Thanks!

**Comment by jishi** [comment]
You need to url-encode the % sign with `%25`. What do you use to urlencode the phrase? (since you actually get %20 for space)

**Comment by Burnett2k** [comment]
I'm not using anything for URL encoding. Your examples made it look as though you can just pass in a string without any issues.Maybe that is because they are plain letters with nothing that needs to be encoded? I don't see anything in the readme about URL encoding, so I didn't know it was required.

Are you suggesting all I need to do is find a way to URL encode to get things working? If so, that should be easy.

**Comment by jishi** [comment]
Since it is a GET request, it needs to conform to a valid HTTP URL. Implicitly, that means that the phrase need to be url encoded. I could probably clarify that better in the README. 

For Javascript, you should use `encodeURIComponent()`. Watch out for the regular one for PHP, that one is broken and doesn't conform to spec (it actually makes a form encoding, not url encoding) . It has a compliant one called `rawurlencode()` which should work.

**Comment by Burnett2k** [comment]
Perfect thanks for the information. As you can tell this is not my expertise so I didn't realize there was that limitation. Will try this soon!
