### ISSUE TITLE
query on http response from say command  

### ISSUE THREAD

**Issue by autofrank** [jishi/node-sonos-http-api#468]
Hi,
I searched but couldn't find this on the current issues, open or closed

I'm looking for more information on the response from Say http request
Is it a json, a table or a string, 
I couldn't see any 200/201 code 
any special headers or content types ?

If I run it from a browser it executes correctly and I get a {"status":"success"} in the browser.
I'm trying to trap in lua when it fails but the usual method for capturing and decoding/parsing the response aren't working. (working with other api calls)
In fact when I run it from my HA system (code below), it executes correctly but I get a OPERATION - canceled error response. I've tried extending the request timeout to 20 seconds but no luck

Any assistance appreciated
```
local http = net.HTTPClient()
    http:request("http://192.168.1.89:5005/bed5_office/say/Hello/Amy/5", {
  	options = { method = 'GET', headers = {}, timeout = 20000 },
      success = function(status)
      print("success: "..success)
      print("status: "..status)
      fibaro:debug("s-s: "..status.status)
      if status.status ~= 200 and status.status ~= 201 then print("failed"); end
   		response = status.data    	
  		print("res: "..response)
   		result  = json.decode(response)
   		print("printTbl(fav):")
		printTbl(results)
      		
      	end,
      error = function(err)
      print('[ERROR] ' .. err)
     end
    })
```

Thanks
-f

**Comment by jishi** [comment]
The response is always JSON. It should respond with a `Content-Type: application/json` to indicate this.

It should respond with a 200 OK if successful, or 500 Error if not successful (not sure about that part though, but that was my intention)

I'm not familiar with lua so I don't have a good explanation for your behavior. Do you see the success or status logging at all?

**Comment by autofrank** [comment]
Thanks I have the content type as json but I'm not seing anything with success or status. I have the code w9rking for a different api and am capturing the success/status OK. The other strange thing is I'm not even seeing the 200 response code if I wireshark it.
Is there anyway you could confirm it's working as you would expect 
Thanks 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Jimmy Shimizu <notifications@github.com> Date: 21/02/2017  17:27  (GMT+00:00) To: jishi/node-sonos-http-api <node-sonos-http-api@noreply.github.com> Cc: autofrank <frank.tp.smith@gmail.com>, Author <author@noreply.github.com> Subject: Re: [jishi/node-sonos-http-api] query on http response from say command (#468) 
The response is always JSON. It should respond with a Content-Type: application/json to indicate this.
It should respond with a 200 OK if successful, or 500 Error if not successful (not sure about that part though, but that was my intention)
I'm not familiar with lua so I don't have a good explanation for your behavior. Do you see the success or status logging at all?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jishi/node-sonos-http-api","title":"jishi/node-sonos-http-api","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jishi/node-sonos-http-api"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jishi in #468: The response is always JSON. It should respond with a `Content-Type: application/json` to indicate this.\r\n\r\nIt should respond with a 200 OK if successful, or 500 Error if not successful (not sure about that part though, but that was my intention)\r\n\r\nI'm not familiar with lua so I don't have a good explanation for your behavior. Do you see the success or status logging at all? "}],"action":{"name":"View Issue","url":"https://github.com/jishi/node-sonos-http-api/issues/468#issuecomment-281414894"}}}

**Comment by jishi** [comment]
Well, if your browser works, I would argue that apparently it works. Try using the same code snippet with a different endpoint without changing anything else than the url, with something like https://httpbin.org/get

And see if that works. I don't have Fibaro nor anything running LUA so it's impossible for me to test your case.

**Comment by autofrank** [comment]
You're correct.I dug a bit deeper in the trace and can see the 200 status code and the status of success
Sorry about that -f


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Jimmy Shimizu <notifications@github.com> Date: 21/02/2017  18:57  (GMT+00:00) To: jishi/node-sonos-http-api <node-sonos-http-api@noreply.github.com> Cc: autofrank <frank.tp.smith@gmail.com>, Author <author@noreply.github.com> Subject: Re: [jishi/node-sonos-http-api] query on http response from say command (#468) 
Well, if your browser works, I would argue that apparently it works. Try using the same code snippet with a different endpoint without changing anything else than the url, with something like https://httpbin.org/get
And see if that works. I don't have Fibaro nor anything running LUA so it's impossible for me to test your case.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jishi/node-sonos-http-api","title":"jishi/node-sonos-http-api","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jishi/node-sonos-http-api"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jishi in #468: Well, if your browser works, I would argue that apparently it works. Try using the same code snippet with a different endpoint without changing anything else than the url, with something like https://httpbin.org/get\r\n\r\nAnd see if that works. I don't have Fibaro nor anything running LUA so it's impossible for me to test your case."}],"action":{"name":"View Issue","url":"https://github.com/jishi/node-sonos-http-api/issues/468#issuecomment-281441880"}}}

**Comment by autofrank** [comment]
A little more digging revealed an oddity

Correct command syntax for volume/+1 gives a 200 and status = success
![code200](https://cloud.githubusercontent.com/assets/20369477/23184755/ed5d24d2-f878-11e6-9e3a-394a402d53de.PNG)

minor error in the url svolume/+2 gives me a 500 and a status = error

![code500](https://cloud.githubusercontent.com/assets/20369477/23184791/127038f4-f879-11e6-9de3-52cba8fef152.PNG)

Change to the say command and I the command works but I don't get either a Status code or a status message and after the timeout I get the Operation cenceled

![op cancelled](https://cloud.githubusercontent.com/assets/20369477/23184856/425fa1c6-f879-11e6-85b5-30a932a3e88f.PNG)


I wonder is there some thing different because the Say command is processed outside the API itself where as the Volume/+2 is processed by your api

any ideas ?
Thanks
-f

**Comment by jishi** [comment]
Hm, well, say commands always wait for the tts to finish playing (to allow chaining of requests). So if a tts audio file is 20 seconds, it will take at least 20 seconds to finish, but probably a couple of seconds more than that. 

For TTS you would need to have a timeout that is long enough for the TTS to finish. I don't have a way of "responding fast". The old version always did that, and that had other drawbacks.

**Comment by autofrank** [comment]
thanks and makes sense
the example I sent on was was just saying 'Hello'  and the timeout is 10 seconds.
I extended it to 30 seconds and no luck but I extended it to 60 seconds and success !!!
interesting that a simple hello phrase take 40-50 second turnaround for status even though the phase is delivered in 1-2 seconds.

out of curiosity.. From a timing perspective how and when do you decide toe success/fail code and status message. ?

**Comment by autofrank** [comment]
Thanks I think I can work with that...I can calculate the string length and adjust the time out on the fly so all good 
-frank 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Jimmy Shimizu <notifications@github.com> Date: 21/02/2017  21:08  (GMT+00:00) To: jishi/node-sonos-http-api <node-sonos-http-api@noreply.github.com> Cc: autofrank <frank.tp.smith@gmail.com>, Author <author@noreply.github.com> Subject: Re: [jishi/node-sonos-http-api] query on http response from say command (#468) 
Hm, well, say commands always wait for the tts to finish playing (to allow chaining of requests). So if a tts audio file is 20 seconds, it will take at least 20 seconds to finish, but probably a couple of seconds more than that.
For TTS you would need to have a timeout that is long enough for the TTS to finish. I don't have a way of "responding fast". The old version always did that, and that had other drawbacks.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jishi/node-sonos-http-api","title":"jishi/node-sonos-http-api","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jishi/node-sonos-http-api"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jishi in #468: Hm, well, say commands always wait for the tts to finish playing (to allow chaining of requests). So if a tts audio file is 20 seconds, it will take at least 20 seconds to finish, but probably a couple of seconds more than that. \r\n\r\nFor TTS you would need to have a timeout that is long enough for the TTS to finish. I don't have a way of \"responding fast\". The old version always did that, and that had other drawbacks."}],"action":{"name":"View Issue","url":"https://github.com/jishi/node-sonos-http-api/issues/468#issuecomment-281480812"}}}

**Comment by autofrank** [comment]
thanks

**Comment by jishi** [comment]
Sounds odd that it should take that much time. If you have a lot of zones, the grouping can take some time, but not 20 seconds... unless you have a very strong interference, but then your playback should suffer as well :)

From a timing perspective, the response (code and content) will arrive after it has started restoring the previous state and playback has been started on the coordinator. So it waits for everything except the grouping to complete.

**Comment by autofrank** [comment]
Hi
I did some more testing last and it has come down but I'm not sure why TBH,
it's now around 15 seconds
All my testing was done on one zone with no grouping/ungrouping

I'll do some more over the next few days but I think it should be okay.

Thanks again
-f
