### ISSUE TITLE
Night mode crash

### ISSUE THREAD

**Issue by NovaGL** [jishi/node-sonos-http-api#473]
I am getting player.nightmode is not a function and then the node crashes and has to be restarted.

Same applies for speechenhancement any ideas?

**Comment by jishi** [comment]
Did you run npm install to get the latest sonos-discovery package?

**Comment by NovaGL** [comment]
Thanks. Always the simple stuff i forget. Will the status be added to the state page or how should i look it up

**Comment by jishi** [comment]
I will add it in the near future :)
