### ISSUE TITLE
How to evaluate "group-state"

### ISSUE THREAD

**Issue by DJPicasso** [jishi/node-sonos-http-api#479]
Hi Jishi,
is there a possibility to evalute a group-state? Similar to the state-functionality.
E.g.: I have 4 speaker (office, living, kitchen, bedroom). If I join office to living and kitchen to living, living will be the coordinator of that group.
It seems that "zones.js" delivers the information but how is that evaluable from zones.json?
Or are there other possibilities to get the group-state or -structure?
Any hint or idea?
BR
DJ

**Comment by jishi** [comment]
Hm, you have the `/zones` command, that will give you the current topology. Is that what you want? `/roomname/state` is per-player data, while `/zones` is for the whole system.

**Comment by DJPicasso** [comment]
Hi Jishi,
thanks for your quick answer. I had the hope that there would be an easier way to get the group topology than to analyse the /zones response.
BR
DJ

**Comment by jishi** [comment]
Well, if you describe what it is you are trying to achieve instead, I might be able to give a better answer
