### ISSUE TITLE
wrong player/zone states

### ISSUE THREAD

**Issue by Markkuuss** [jishi/node-sonos-http-api#48]
Since the latest version the player / zone states are not set correctly. They are always in STOPPED.
"zoneState": "STOPPED",
"playerState": "STOPPED",

Also the times do not seem to be set correctly.
"elapsedTime": 0,
"elapsedTimeFormatted": "00:00",

I'm using node v0.10.26.

**Comment by jishi** [comment]
I reverted the depency to 0.15.1 for now.
