### ISSUE TITLE
Provide grouping info in state action

### ISSUE THREAD

**Issue by CannyDuck** [jishi/node-sonos-http-api#482]
Please provide grouping information for the state action.

**Comment by jishi** [comment]
Could you please provide more context to what you would like to see? It might make sense which player that is the coordinator, but fail to se the usefulness of it. Are you thinking about all other players that are part of the same group?

All of this info is already available in the `/zones` command, albeit it includes all zones.

**Comment by CannyDuck** [comment]
I would retrieve the status of a player and check several fields before performing an action that is dependent of the field information. For my use case it would be enough getting an boolean value if the player is part of a group or not. It would be a shortcut instead of perform another request to zones.

**Comment by jishi** [comment]
I'm not sure if this is gonna be relevant for anyone else but you. It's fairly easy to write your own state function, and add properties as you seem fit, and the info about being grouped or not should not be that hard to figure out. I can give you some guidance if you like.
