### ISSUE TITLE
Random Errors in Log

### ISSUE THREAD

**Issue by peterbaumert** [jishi/node-sonos-http-api#484]
Hi,

I am getting regular Errors in the Log file but everything seems to be working fine.
Just wanted to let you know ;)

Apr 03 13:29:15 npm[24059]: 2017-04-03T11:29:15.985Z ERROR
Apr 03 13:29:15 npm[24059]: Error
Apr 03 13:29:15 npm[24059]: at Object.invoke (/var/sonosapi/node_modules/sonos-discovery/lib/helpers/soap.js:95:10)
Apr 03 13:29:15 npm[24059]: at Player.pause (/var/sonosapi/node_modules/sonos-discovery/lib/models/Player.js:449:15)
Apr 03 13:29:15 npm[24059]: at Object.pause (/var/sonosapi/lib/actions/playpause.js:16:29)
Apr 03 13:29:15 npm[24059]: at handleAction (/var/sonosapi/lib/sonos-http-api.js:110:35)
Apr 03 13:29:15 npm[24059]: at HttpAPI.requireDir.requestHandler.handleAction.then [as requestHandler] (/var/sonosapi/lib/sonos-http-api.js:87:5)
Apr 03 13:29:15 npm[24059]: at /var/sonosapi/server.js:50:13
Apr 03 13:29:15 npm[24059]: at Server.finish (/var/sonosapi/node_modules/node-static/lib/node-static.js:111:13)
Apr 03 13:29:15 npm[24059]: at finish (/var/sonosapi/node_modules/node-static/lib/node-static.js:170:14)
Apr 03 13:29:15 npm[24059]: at /var/sonosapi/node_modules/node-static/lib/node-static.js:144:17
Apr 03 13:29:15 npm[24059]: at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by jishi** [comment]
Thanks for reporting this. I finally figured out why the error was blank. Fixing in next version.
