### ISSUE TITLE
Webhook data: who invoked an action

### ISSUE THREAD

**Issue by michaelowens** [jishi/node-sonos-http-api#485]
Hi! Love the webhook, gives a lot of information for logging.

Is it possible to get information on which user invoked an action? Does Sonos give any information on this at all? I noticed in the logs there are tokens for every user, but I can't seem to find anything online on logging who changes music. Even an IP address, mac address, token, computer name, anything would be useful.

We use Sonos at work, and sadly there are always rotten apples who mess with other rooms' sonos.

None the less, keep up the work!

**Comment by jishi** [comment]
Not that I'm aware of. This is a struggle for other parts as well, for instance when you adjust the volume, and you also update your internal "value" for what the new volume would be, but it is also evented a couple of hundred ms later giving weird race conditions. I did some investigation about it, never got any indication that it worked, and I also asked a guy that worked at Sonos, and he didn't know of any way either. 

I could however, indicate if it was the http api or another controller what triggered it (with a good estimate). also, if it was invoked via the http api, which src IP or similar, probably. Not sure how useful it would be though.
