### ISSUE TITLE
server not starting 

### ISSUE THREAD

**Issue by fischermatte** [jishi/node-sonos-http-api#49]
I followed the two steps from the readme.md with `npm install` and `node server.js`. `npm install` seems to do everything as expected. executing `node server.js` throws no error, but afterwards no server is running. it is just coming back to command line input. any idea?

**Comment by fischermatte** [comment]
Forgot to mention: I am running it on linux (mint 17), having npm installed via package manager.

**Comment by jishi** [comment]
You forgot to tell me which node version. You shouldn't return to the command line, sounds like node just unexpectedly quits. What platform are you running on? x86?

**Comment by fischermatte** [comment]
thx for quick reply. i just figured it out - it conflicted with another node installation on my machine. when i type `nodejs server.js` it works! now i need to remap the node command to nodejs. seems to be a ubuntu thing...

**Comment by jishi** [comment]
Ah, right, they already have a package which provides another node command, that's why they renamed it. You don't actually need to remap it though.
