### ISSUE TITLE
Add current song to favorites or a playlist

### ISSUE THREAD

**Issue by rnbk** [jishi/node-sonos-http-api#492]
Hello,

first of all I would like to thank you for the great work you're  doing with this project, it really improved my Sonos experience dramatically meanwhile!

I created a small application which allows me to control Sonos by using hotkeys triggered by a Logitech Harmony remote and I would like to also be able to add the current song playing to the Sonos favorites or - even better - to a specific Sonos playlist.
I was not able to implement this function yet using the current actions available (please correct me if I missed something...), therefore I would like to ask you to add an action which is able to send the current song playing (state -> currentTrack) to the Sonos favorites or to a specific playlist passed as a parameter (e.g. `http://localhost:5005/living room/addCurrentTrack/my favorite playlist`) .
I'd be very  greatful if we could find a solution for my request, thank you in advance!

Best regards,

Kornelius

**Comment by jishi** [comment]
You are correct that it doesn't work with current actions today. It's a good suggestion, and it has been raised before https://github.com/jishi/node-sonos-http-api/issues/168, so I'm closing this in favor of that issue. If you have any comments, please add them there.
