### ISSUE TITLE
Only show first x number in Queue

### ISSUE THREAD

**Issue by NovaGL** [jishi/node-sonos-http-api#493]
Wondering if this is possible.

Sometimes I have a queue that is thousands of songs. This delays the response.

Is it possible to limit the result to only show the first 50 items or so.

**Comment by jishi** [comment]
This was actually how it was done previously, but I changed it for simplicity. The underlying call to `browse()` actually takes a start index and a length.

How much of a delay are you seeing? And what are the implications? Just wondering if  pagination, or a cached response is the best way to go. Pagination always introduces extra complexity for implementations, and that might not be what you want.

**Comment by NovaGL** [comment]
I sometimes do browse all songs which makes the browser crash as there is thousands of them since we can't select an item from the queue. I would like either pagination or limit like you would do in an Sql statement

**Comment by jishi** [comment]
See README for instructions on how to use limit and offset with the queue action.
