### ISSUE TITLE
"Error: Cannot find module 'basic-auth'" at startup

### ISSUE THREAD

**Issue by KVandaele** [jishi/node-sonos-http-api#494]
Hi,

I tried the sonos-api on my Pi3, but at npm start, I get the follow error.
Any help appreciated!

Thx!

pi@raspberrypi:~/node-sonos-http-api $ npm start

> sonos-http-api@1.4.1 start /home/pi/node-sonos-http-api
> node server.js

module.js:472
    throw err;
    ^

**Error: Cannot find module 'basic-auth'**
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/node-sonos-http-api/server.js:5:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

npm ERR! Linux 4.4.50-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@1.4.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sonos-http-api@1.4.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sonos-http-api packag                                   e,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sonos-http-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in                                   stall?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/node-sonos-http-api/npm-debug.log

**Comment by jishi** [comment]
sounds like you didn't install the dependencies first. When standing in the folder that contains the `package.json` file, run `npm install --production` one time, then try starting it.

**Comment by KVandaele** [comment]
Thx 4 the reply! Tried this, but resulting in an other error:

pi@raspberrypi:~/node-sonos-http-api $ npm install --production
npm ERR! Linux 4.4.50-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--production"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! file /home/pi/.npm/node-static/0.7.9/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: /home/pi/.npm/node-static/0.7.9/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/node-sonos-http-api/npm-debug.log

I ran the command in the node-sonos-http-api directory.
Any other idea? Thx!

**Comment by jishi** [comment]
Not sure why it complains at `File: /home/pi/.npm/node-static/0.7.9/package/package.json`

You could try and wipe the /home/pi/.npm folder, not sure why it would look in there, maybe npm has ended up in some weird state. You could also try and downgrade npm to version 3 to see if that helps.

**Comment by KVandaele** [comment]
You made my day!! Deleting the .npm dir fixed the issue.
Final question: how can I start the package at system boot on my Raspberry Pi?

Thx a lot for all the help!
Koen

**Comment by jishi** [comment]
Easiest is probably to use pm2, see https://github.com/jishi/node-sonos-http-api/issues/20
