### ISSUE TITLE
VoiceRSS - unable to play

### ISSUE THREAD

**Issue by gizbod** [jishi/node-sonos-http-api#497]
When invoking the say command i get this feedback on the sonos app.
any ideas?

I just tried to get it to say 'hello'

![img_8279](https://cloud.githubusercontent.com/assets/18351060/26023849/66413914-37bd-11e7-97af-f3e6a96d63b7.PNG)

**Comment by jishi** [comment]
Try to find the file that has been downloaded and open it in a Text editor.
It probably contains an error message that explains why it doesn't work

**Comment by gizbod** [comment]
would it download the file on to my RPi somewhere?

**Comment by gizbod** [comment]
ok, the error is "the language does not support"

**Comment by gizbod** [comment]
I just realised i was missing the language code on the command.
Thanks for the prompt response
