### ISSUE TITLE
Announce volume only at 40

### ISSUE THREAD

**Issue by gizbod** [jishi/node-sonos-http-api#499]
When using any say command, the volume remains at 40%.
I have added a new default to settings.json and tried adding a volume parameter to the end of the command as per the read me.

no errors are thrown up in any circumstance and it seems like it runs as it should just the volume does not change regardless.

**Comment by jishi** [comment]
I can't reproduce this. 

Does it successfully restore what was playing before, on the speaker (after the announcement)? 

What is the source playing, prior to invoking the `say`command?

**Comment by gizbod** [comment]
Yes it successful restores what was playing before including volume. 
Generally the source is spotify but also tried with TV on the playbar. 
I will try with other sources when home this evening to try and rule that out.

**Comment by jishi** [comment]
Could you run the process with verbose logging on? 

`NODE_LOG_LEVEL=trace node server.js`

Or on windows powershell 
```
$env:NODE_LOG_LEVEL='trace'
node server.js
```

Then call the say command, and give me the log output? You might need to pipe it to a file and email it to me

`NODE_LOG_LEVEL=trace node server.js > debug.log`

Then email `debug.log` to jimmy at shimizu.se

**Comment by gizbod** [comment]
I have sent you an email Jimmy.
Joe

**Comment by gizbod** [comment]
Thanks Jimmy, updating the version solved this problem.
