### ISSUE TITLE
Question: Change Album Art Quality?

### ISSUE THREAD

**Issue by digitalmud** [jishi/node-sonos-http-api#50]
This is really more of a question than an issue:

Is it possible to get higher quality / resolution artwork?

Thanks,

C

**Comment by jishi** [comment]
It's technically possible, using Sonos SMAPI to fetch high-res coverart for most music services except Amazon (they require authentication). 

When I built my dashboard solution, I used Spotify WebAPI (since I only use Spotify here) to fetch their highres cover art using the Spotify URI.

**Comment by neophob** [comment]
Can you give us some more ideas about this solution? would it be possible to get high res coverimages from streaming services (like soundcloud)?

I think you're referencing this document: http://musicpartners.sonos.com/?q=node/366. any plans that this will be included?

**Comment by jishi** [comment]
AFAIK most services provide high-res covers, but Amazon requires authentication. One must first find the actual endpoint and url scheme that is used to request them, which is supposed to be provided by the SMAPI somehow. I haven't investigated it further than that.
