### ISSUE TITLE
Say command with spaces does not work anymore?

### ISSUE THREAD

**Issue by joystick666** [jishi/node-sonos-http-api#500]
Hi,
since the latest release upgrade, I have the issue that the simple say command is throwing an error because of spaces in the text. (e.g. /room/say/this is a test)
When I use %20 („/room/say/this%20is%20%20test“) in the url everything works though...

**Comment by jishi** [comment]
How are you calling it? Using a browser or something else? The correct way of sending spaces is by using %20, it's up to the request library to actually convert it to a valid URL. In the case of a browser, it does that automatically.

**Comment by joystick666** [comment]
Yeah I know, that. I am calling it from a browser (Safari or Chrome on Mac). Its not that big issue, i just noticed that it does not seem to work as before.

**Comment by jishi** [comment]
If I have references in the documentation that indicate that it's valid syntax, I might wanna change that. Thanks for reporting.
