### ISSUE TITLE
Option to send TTS or Clip to Group

### ISSUE THREAD

**Issue by JsChiSurf** [jishi/node-sonos-http-api#501]
I've been playing with this for a few weeks now and love the capabilities.  It has allowed me to offload this functionality from my Vera home controller and remove its plugin, to free up some resources.

I send a lot of TTS and MP3 files to my sonos speakers for various events, and I really only want to send to one speaker on each floor (3 floor townhome).

Right now, I can either send to 1 speaker, via the "say" or "clip" command, or ALL speakers via the "sayall" or "clipall" command.  It would be great if we could somehow use the "join" feature to create a "group", and then perhaps name the "group" so that could send the command to just those collective speakers.

The join command works great for creating a group / collection of speakers, but even after doing so, if I select one of the speakers (rooms) in the group with the "say" or "clip" command, it will (obviously) still only play to that speaker (singling it out, playing, and then returning it to the group).

Thanks for your hard work and consideration.

**Comment by jishi** [comment]
Yeah, the idea is to allow referencing a preset as a source for announce topology, see https://github.com/jishi/node-sonos-http-api/issues/426

That would probably cover your case?

**Comment by JsChiSurf** [comment]
Thanks for the quick response and I apologize for not seeing this one in the current list before posting.

This gets the "gist" of what I am hoping for, with one exception.  There may be times when I indeed may want to use the 'sayall/clipall' command and indeed send to all speakers.

What about, when using a preset option, the preset defines a custom/virtual "room" so that when used, using the 'say' command (instead of sayall), will send to the custom/virtual "room" in the preset, which contains just your selected speakers?

That is, the preset could be named "3Floors" (or whatever), which is a group of 3 speakers / rooms, which would be called as http://XXX:5005/3Floors/say/Hello+World/70.

In this way, 'sayall/clipall' could be preserved for when you want to actually sent to EVERY speaker.

Not sure of feasibility, but figured I'd throw it out there.

**Comment by jishi** [comment]
I didn't plan on removing the sayall/clipall or the say/clip commands. The preset alternative would merely complement those two, when you want a more granular control of how you announce it. One could argue that a preset version would give the same functionality as sayall, byt sayall is very convenient since it requires zero configuration. :)

**Comment by JsChiSurf** [comment]
Ah, okay, perhaps I misread the other response.

It had sounded like the preset would re-define what was used for the 'sayall' command, instead of sending to all speakers, when using 'sayall', to just those in the preset.  If not, then I'm on the same page and would be exactly what I am looking for. 

So the preset defined would be referenced differently then, than when using 'say' or 'sayall'?

Thanks.

**Comment by jishi** [comment]
I'm thinking that it would be:

`/saypreset/presetname/hi%20there!` 

or something. So basically just a new action.

**Comment by JsChiSurf** [comment]
Perfect!  Thanks for the clarification.  This would be a great addition I think.
