### ISSUE TITLE
Can this perform any faster?

### ISSUE THREAD

**Issue by leecollings** [jishi/node-sonos-http-api#502]
I'm using this tool within DOmoticz, to fire events on my sonos speakers depending on switches/events being fired within Domoticz.

Put simply, I have a doorbell switch that features a script as the ON command. Within the script I have a call to pause my Sky Box via another service hosted on my Pi, and a clipall command sent to my sonos speakers.

The problem is, the waiting time from when the command is sent to the speakers, to when the reply is received and the sound is made, is about 5 seconds, which is far too long.

I'm using a simple `curl http://127.0.0.1:5005/clipall/doorbell.mp3` to send to the speakers.

Is there a faster, almost instant way of immediately playing the clip on the speakers using the clipall command?

**Comment by jishi** [comment]
I deliberately changed it to wait for the announce to finish, to allow people to chain these calls with other calls. 

If you are just doing "simple" calls, doesn't it support appending a '&' to it for running it as a background call? Of course, with the drawback of not knowing if it fails or succeeds. 

I could probably implement a secondary parameter otherwise, which would at least know if the call successfully started the announcement or not. On a second note, doesn't domoticz support direct HTTP calls, without going through a curl? That might behave differently on your system.

**Comment by leecollings** [comment]
I understand it would help if you were to see my entire script file, but I'm unable to provide that right now.

However, I did have an ampersand, but at the end of the file (which is after the line for the Sky HD box). Would this need to be on everyline of the script to run (or command)?

And yes Domoticz does support direct HTTP calls, but surely that means I can only have one call entered in the ON command field of the switch? I've read about the slave devices, Maybe I could set up the Sonos call as a dummy switch, and set the doorbell to fire that also, as well as the script command for the Sky box?

**Comment by jishi** [comment]
I don't use Domoticz, so I can't say what would be the limitations with another approach. If this is in a script combined with other actions, I see how that might be harder to use. 

If this is part of a script, you would need to have an ampersand for the curl command if you want to fire of the subsequent actions immediately, yes, byt the global ampersand should at least detach the script execution from domoticz. It might however not be supported depending on how domoticz executes your script

**Comment by leecollings** [comment]
Okay, well thanks for your input anyway.

So ultimately, there isn't a way to speed up the time taken between the HTTP request being sent, and received from your end?

**Comment by jishi** [comment]
As I said, it would be possible to change it, so it returns the request as soon as playback starts. But that is a breaking change, and needs to be optional (either via some sort of http header, or an extra parameter). 

There is probably several people relying on the request to actually wait for the announcement to finish, and they would be sad if I just made the change you are requesting :) 

I suggest, trying to see if the ampersand after `curl` works for you, if not, I'll consider adding some sort of parameter to get a more immediate response from this call.

**Comment by leecollings** [comment]
I've been able to dig out what my script file may look like (it might not be exactly, but this is from what I've found from me posting on forums).

(The script before I added Sonos)
`#!/bin/bash
sky-remote-cli 10.0.0.5 pause &`

(And my attempt in adding Sonos)
`#!/bin/bash
sky-remote-cli 10.0.0.5 pause
curl http://127.0.0.1/clipall/doorbell.mp3 &`

Where would you advise the ampersands are placed?

**Comment by jishi** [comment]
I mean, I would expect that to work, but if you had a ampersand after pause previously, you probably want it in both places:

```
#!/bin/bash
sky-remote-cli 10.0.0.5 pause &
curl http://127.0.0.1/clipall/doorbell.mp3 &
```

That way it would fire of pause, NOT wait, and then fire of the call to Sonos, and NOT wait, and the script would be finished. That would be my expecation, at least, but I might not fully understand how shell script execution in domoticz work.

**Comment by leecollings** [comment]
Understood, I will try that and see how it responds.
In the meantime, if you're able to develop a feature to allow to immediately respond, I would definitely like to try that.

**Comment by leecollings** [comment]
Another question I have, is as I'm running your script, and Domoticz on the same machine, is there a faster, more localised way of callign the action, rather than an HTTP request?

And If not, is the method I'm using (by using the local IP 127.0.0.1) the fastest method, or should I be using something else?

**Comment by jishi** [comment]
No, since this is an HTTP API, that is the only option. There is an underlying node.js library that can be implemented directly, but I don't think that would help with domoticz. Also, the HTTP overhead on a local machine is negligible so I wouldn't worry about it. 

However, invoking a separate shell and calling curl has more overhead than a direct HTTP request from domoticz, I imagine. But since you already need a shell to call the sky-remote-cli, you've already "wasted" resources and adding the curl call to that has little additional overhead.

**Comment by leecollings** [comment]
So, what would be your recommendation to get both actions firing quickly from one script? If I can have both events fired at the exact same time, rather than in sequence, that would be great.

**Comment by jishi** [comment]
Well, I would expect:

```
#!/bin/bash
sky-remote-cli 10.0.0.5 pause &
curl http://127.0.0.1/clipall/doorbell.mp3 &
```

to fire in parallell and exit directly. Does that not work?

**Comment by leecollings** [comment]
DOesn't seem to work any better than previously, but not to worry.

I've decided to ditch the script and Sky command for now, and simply use the HTTP call directly in the 'ON' action for the switch in Domoticz.

So, if you're able to provide a parameter option to make the call execute immediately without waiting for a response, I would love to try that. Perhaps in a new branch or a dev branch if there's one around?

**Comment by jishi** [comment]
Sure, it could be provided globally, but then you would not know if the request failed or timed out against the Sonos players. I would argue that it only makes sense for the announcement calls, clip/clipall/say/sayall

**Comment by leecollings** [comment]
I would say it might be useful for any actions that don't require any feedback that's essential.

For example, on another switch in our bedroom, I have created a scene called ALL OFF, where the lights turn off, but I also trigger the 'Pause' command for our bedroom speaker. This has a few second delay, I would imagine because it awaits the response.

It would be nice to speed this up too if possible?

**Comment by jishi** [comment]
I'll keep that in mind and see what makes sense from an implementation perspective.

It's always possible to create "custom" actions that bypasses this also. For instance, if you look at https://github.com/jishi/node-sonos-http-api/blob/master/lib/actions/playpause.js#L15-L17,

If that instead would be: 

```
function pause(player) {
  player.coordinator.pause();
  return Promise.resolve();
}
```

It would not wait. If you create your own pause function (by dropping a new file into the `actions` folder) and call it something else, you could use that. Because it would be it's own file, it would not be overwritten by an upgrade.

**Comment by leecollings** [comment]
Thanks for the tip, could I use this for the clipall command in a similar way then?

**Comment by jishi** [comment]
Yeah, however that function is a bit more complex, but the same principle applies :)

**Comment by leecollings** [comment]
Hey there,

Just wondering if you managed to implement a parameter as of yet, to try and return immediately without waiting for a success call?

**Comment by leecollings** [comment]
JUst thinking a bit more, and reading some of your replies... particularly the new action file.

I found the clipall.js file, and obviously I think this is the one I want to base on. But if I create a new file, would I need to include the entire contents of the original clipall file? eg.

'use strict';
const settings = require('../../settings');
const allPlayerAnnouncement = require('../helpers/all-player-announcement');

let port;

```
function playClipOnAll(player, values) {
  const clipFileName = values[0];
  let announceVolume = settings.announceVolume || 40;

  if (/^\d+$/i.test(values[1])) {
    // first parameter is volume
    announceVolume = values[1];
  }

  return allPlayerAnnouncement(player.system, `http://${player.system.localEndpoint}:${port}/clips/${clipFileName}`, announceVolume);
}

module.exports = function (api) {
  port = api.getPort();
  api.registerAction('clipall', playClipOnAll);
}
```

And then just add the `return Promise.resolve();` directly after `return allPlayerAnnouncement`? I'm not sure that would work would it?

**Comment by leecollings** [comment]
Hey man, wondering if you have had a chance to look at my previous message, or if not, if you wouldn't mind taking a quick look when you can. Also perhaps an update on your modification of adding a parameter to return the call.

Would this allow the system to instantly output the message as soon as the request is received, or is there still a delay in sending the http request?

**Comment by jishi** [comment]
Sorry, I thought I replied to you, but apparently forgot it. 

You can't return twice in a function, so you should do like this:

```
allPlayerAnnouncement(player.system, `http://${player.system.localEndpoint}:${port}/clips/${clipFileName}`, announceVolume);
return Promise.resolve();
```

That would start the invocation of the announcement without waiting for it, and then immediately return with a successful promise. 

I haven't looked into the general "return immediately" stuff, but I have given it some thought to try and figure out what makes sense.

**Comment by leecollings** [comment]
Hey, I copied the clipall.js file in the actions folder and named it doorbell.js, and made the adjustment as you listed above.

However, when I run the call in a browser I immediately get a status:error returned. I tried npm restart, but it still displays this.

I can assume th doorbell.js file isn't being loaded when the plugin loads. Is there something else I need to do to load this new file everytime?

**Comment by jishi** [comment]
Ah, sorry, forgot to mention that there is no guaranteed load order of the action files. So, you would need to change:

`api.registerAction('clipall', playClipOnAll);`
to
`api.registerAction('immediate_clipall', playClipOnAll);`

or something and use `/immediate_clipall/doorbell.mp3` to be sure that you are calling your custom action. the original clipall is probably loaded after your file, so your version is never used.

**Comment by leecollings** [comment]
Well yeah that's what I did, in a sense, although I renamed
immediate_clipall to doorbell so I could use :5005/doorbell/doorbell.mp3

The JSON result came back as error, but I think it worked, as I then did a
/state call, and that displayed doorbell.mp3 (I wasn't at home when I did
this, I did it remotely, just to see the logs).

But I think this may be working then, need to test in a RL environment.



Kind regards,



Lee Collings | Graphic Designer & Web Developer
www.leecollings.co

This email and any attachments to it may be confidential and are intended
solely for the use of the individual to whom it is addressed. Any views or
opinions expressed are solely those of the author and do not necessarily
represent those of Lee Collings Co Ltd. If you are not the intended
recipient of this email, you must neither take any action based upon its
contents, nor copy or show it to anyone. Please contact the sender if you
believe you have received this email in error.

**Comment by leecollings** [comment]
Hey, firstly I wanna say sorry for causing such a long issue! I feel bad now as it's not really an issue!

However, I've created a doorbell action, and it does play. However, the delay is still about 15 seconds from the button push to the sound announcing.

Is there any way to turn on output logging to see the various states of the script working at all?

I also tried with the standard clipall, and even just clip with one speaker, all of which produce a delay of 15 seconds.

The file is a mp3 file in the static folder. Would this be cauisng any delay? Are there any file formats that could be read faster perhaps?

**Comment by leecollings** [comment]
This is what I have:

```
'use strict';
const settings = require('../../settings');
const allPlayerAnnouncement = require('../helpers/all-player-announcement');

let port;

function playClipOnAll(player, values) {
  const clipFileName = values[0];
  let announceVolume = settings.announceVolume || 40;

  if (/^\d+$/i.test(values[1])) {
    // first parameter is volume
    announceVolume = values[1];
  }

  allPlayerAnnouncement(player.system, `http://${player.system.localEndpoint}:$$
  return Promise.resolve();
}

module.exports = function (api) {
  port = api.getPort();
  api.registerAction('doorbell', playClipOnAll);
}
```

**Comment by JsChiSurf** [comment]
FWIW, and I'm not downplaying whatever might be causing lag in your environment, but I run a similar setup, where I play a 10 second mp3 file via /clipall, when the doorbell rings, and the clip starts almost immediately.

This is with the stock codebase for this module, however, the call for when the doorbell rings is to a PHP page that then calls this module asynchronously for immediate return to my home automation system (which shouldn't make a difference in terms of kick off lag).

**Comment by leecollings** [comment]
Hmm that's annoying then.

So when you fire the http address in a browser of clip all, the MP3 is grouped and played instantly?

**Comment by leecollings** [comment]
Can you share your php code you're using to fire the request?

**Comment by JsChiSurf** [comment]
Yes, things play pretty instantly.  Even when calling directly from the browser (regardless of using PHP to make the call):

https://www.youtube.com/watch?v=HAMxyUQOokY

My PHP code just allows my home automation system to get an immediate "200" response, w/o having to wait for the clip to finish, thinking something went wrong / timed out.  I don't care about the result (assume it has worked), and thus just want a return ASAP, once the /clipall command has been issued.

PHP looks like this (again, not that I think it should matter):

async_get("192.168.1.136","5005","/clipall/ding_dong.mp3/50","30");

function async_get($host, $port, $endpoint, $connectTimeout) {

  $request =  "GET $endpoint HTTP/1.1\r\n";
  $request .= "Host: $host\r\n";
  $request .= "Connection: Close\r\n";
  $request .= "\r\n";
  $errno = null;
  $errstr = null;
  $port = $port;
  if (($fp = @fsockopen($host, $port, $errno, $errstr, $connectTimeout)) == false) {
    return;
  }
  fputs($fp,$request);
  fclose($fp);

}
