### ISSUE TITLE
Authentification required for spotify Artist search

### ISSUE THREAD

**Issue by StarNab** [jishi/node-sonos-http-api#508]
Hi,

I discovered the hard way that unauthenticated API calls where not allowed anymore beginning today : https://developer.spotify.com/news-stories/2017/01/27/removing-unauthenticated-calls-to-the-web-api/ 

As I started playing with your application yesterday the timing was a bit tricky at first :) 

Is a solution planned ?

(I'm new to github excuse if I miss any point)

**Comment by jishi** [comment]
Hm, this was news to me too, and that is unfortunate. I would need to implement an oauth-flow then to get a hold of a token...

**Comment by jplourde5** [comment]
Let me know if you implement oAuth and I'll incorporate the needed token into the search calls.

**Comment by StarNab** [comment]
@jplourde5 does that mean there will be one token for the application as a whole ? Not a "per-user" token ?

**Comment by StarNab** [comment]
Maybe I misunderstood but for Spotify API, authorization tokens are dynamically generated based on a client_id and client_secret_key ( https://developer.spotify.com/web-api/authorization-guide/#implicit-grant-flow )
I've tried implementing that on my own with no success. Blame my low knowledge on nodejs

**Comment by jplourde5** [comment]
Took a quick look. Like Jishi said, he would have to implement an oath flow that involves registering the API solution with Spotify and getting issued a Client ID.  After that, there would need to be a workflow in the api that allows the user to approve the link and a token would be obtained, saved, and used for each Spotify call.  Looks like the change to the Spotify functionality simply requires another parameter to be added to the URI's.  Unfortunately many services already require this so adding this capability will probably be a good thing.  There is some risk that providers may not be willing to hand out a client id for this app though, in which case there is no fix.

**Comment by jplourde5** [comment]
Jishi needs to register the app and get an ID fore nsha. That ID is required to allow the user to approve the app and get a unique token to be used on subsequent calls. The client Id for the app would be the same for everyone, but the token will be unique for each user of the API.

**Comment by jplourde5** [comment]
Good news. It is very quick and easy to create an app in your Spotify account and get the needed client Id and key. In fact, we could make every user create an app entry and obtain their own ID and keys. It would be more convenient for everyone though if there was just one Id/key for the app that everyone used.

**Comment by jplourde5** [comment]
App registration URL https://developer.spotify.com/my-applications/#!/applications

**Comment by StarNab** [comment]
Yes that would make more sense. I got mine ready. On the other hand i Kinda succeeded  to have the whole thing working on my end

**Comment by jplourde5** [comment]
Well, every user will have to create their own app registration because the redirect URL has to be in the app's registration whitelist and everyone will have a different URL. This also means that the nsha must be exposed to the Internet.

**Comment by jplourde5** [comment]
Which flow did you use? The Client flow?

**Comment by StarNab** [comment]
I used Client Credentials Flow. I'm unable to retrieve the token from the javascript code though. But it works fine with a curl call. So for testing purpose I'm manually generating it but the concept is OK. I might just use a cron to generate the token in the end

**Comment by pettersamuelsen** [comment]
I'm currently working on a PR for this. Hopefully it'll be ready within the next couple of days.

**Comment by jishi** [comment]
Resolved. See README on how to add authentication for Spotify.
