### ISSUE TITLE
How to send status update to other devices?

### ISSUE THREAD

**Issue by daveng68** [jishi/node-sonos-http-api#51]
Hi!

First I want to tell you that your work is really impressive! Great job there!!

I haves more a question than an issue. Could you point me on how to add notification to other devices? What I'm trying to do is to send an http request to update the status in real time.

For example, I have an amp that I can control through a box that send IR codes and that I can trigger through http request. My goal would be that if I start/stop the Sonos player that is hooked to that amp, to send an http request to turn the amp on/off.
How could I add this to your existing code? I've tried to looked into it, but I don't know enough about node to figure it out?
Many thanks for any help!

David

**Comment by jishi** [comment]
Hi, thank you for your kind words. It's nice to see that people find it useful.

Your problem isn't easily fixed without some rewrites, and you would need to modify the application a bit to achieve what you want. 

I would probably isolate it as a separate application, using the node-sonos-discovery module directly. It will trigger a change event, when a player changes state (from play, to pause, and vice versa), which could be used to turn your amp on and off (with a delay, preferrably). However, you need to take grouping etc into account, since it will only be the coordinator that sends the event, and you need to know which coordinator that is in charge of the amp you are controlling. It's doable, but requires some logic that might not be as straight-forward as one would hope.

What is the level of your programming skills?

**Comment by daveng68** [comment]
Hi!

Thanks for responding so quickly!
Yeah, I though about the grouping issue...

My programming skills are not too shabby but I just discovered node and I'm not quite familiar with it yet. And I haven't been able to figure out yet how to listen for an event. I've started to look into node for this reason, but it's still unclear for me. This real time thing is bit confusing for me...

What I have done so far is monitor regularly the state of the player and when I see a change I would trigger the amp. But I don't like it so much, since I'm constantly polling the state waiting for a change of state and I would rather listen for the event.

Thanks again!

David Nguyen


Le 7 avr. 2015 à 18:02, Jimmy Shimizu <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi, thank you for your kind words. It's nice to see that people find it useful.

Your problem isn't easily fixed without some rewrites, and you would need to modify the application a bit to achieve what you want.

I would probably isolate it as a separate application, using the node-sonos-discovery module directly. It will trigger a change event, when a player changes state (from play, to pause, and vice versa), which could be used to turn your amp on and off (with a delay, preferrably). However, you need to take grouping etc into account, since it will only be the coordinator that sends the event, and you need to know which coordinator that is in charge of the amp you are controlling. It's doable, but requires some logic that might not be as straight-forward as one would hope.

What is the level of your programming skills?

**Comment by jishi** [comment]
I have been planning on adding a configurable URL-hook to the http api, which would partly solve your issue (but you would still need to build the logic somewhere). I can make an outline of an a node.js application and give you the implementation positions where you would add your HTTP requests, if that would help.

**Comment by daveng68** [comment]
I'm working on the logic right now: getting the zone my player belongs to and the coordinator of this zone. This works so far. If I send the name of my player, I get its coordinator in return.
So now I need to listen to the event, see if the event comes from the say coordinator and if so trigger the amp.

If you can make an outline of a node.js application, that would be more than great! Thanks!!

David Nguyen


Le 7 avr. 2015 à 19:34, Jimmy Shimizu <notifications@github.com<mailto:notifications@github.com>> a écrit :


I have been planning on adding a configurable URL-hook to the http api, which would partly solve your issue (but you would still need to build the logic somewhere). I can make an outline of an a node.js application and give you the implementation positions where you would add your HTTP requests, if that would help.

**Comment by jishi** [comment]
Hi, I created a simple stub here:

https://github.com/jishi/sonos-event-stub

Fork it and see if ti fits your need!

**Comment by daveng68** [comment]
Tu!

Thanks so much.
I will check that!

David Nguyen

Le 10 avr. 2015 ? 20:54, Jimmy Shimizu <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Hi, I created a simple stub here:

https://github.com/jishi/sonos-event-stub

Fork it and see if ti fits your need!

-

**Comment by daveng68** [comment]
Hi!

Works perfectly.
Thanks a lot for the help!!

David Nguyen


Le 10 avr. 2015 à 20:54, Jimmy Shimizu <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi, I created a simple stub here:

https://github.com/jishi/sonos-event-stub

Fork it and see if ti fits your need!
