### ISSUE TITLE
Album Art URL gets repeatedly appended to

### ISSUE THREAD

**Issue by jiphex** [jishi/node-sonos-http-api#52]
There's some kind of a bug in `lib/action/state.js` which means that if you keep requesting the state of a zone which is playing a stream of some kind, the Album Art URL gets repeatedly (erroneously) appended to itself, so after a while it can look like this:
<pre>
May% curl boris.tlyk.eu:5005/kitchen/state
{"currentTrack":{"artist":"","title":"x-sonosapi-stream:s44491?sid=254&flags=32","album":"","albumArtURI":"http://10.100.100.99:1400http://10.100.100.99:1400http://10.100.100.99:1400http://10.100.100.99:1400http://10.100.100.99:1400http://10.100.100.99:1400http://10.100.100.99:1400http://10.100.100.99:1400http://10.100.100.99:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400/getaa?s=1&u=x-sonosapi-stream%3as44491%3fsid%3d254%26flags%3d32","duration":0,"uri":"x-rincon-mp3radio://bbcmedia.ic.llnwd.net/stream/bbcmedia_6music_mf_p?s=1429005507&e=1429019907&h=f4f73492b70c9b0668151a62f347c0da"},"nextTrack":{"artist":"","title":"bbcmedia_6music_mf_q?s=1429005507&e=1429019907&h=a604344f65e40f553630f83b8564d426","album":"","albumArtURI":"http://10.100.100.99:1400http://10.100.100.99:1400http://10.100.100.99:1400http://10.100.100.99:1400http://10.100.100.99:1400http://10.100.100.99:1400http://10.100.100.99:1400http://10.100.100.99:1400http://10.100.100.99:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400http://10.100.100.71:1400","duration":"0","uri":"x-rincon-mp3radio://bbcmedia.ic.llnwd.net/stream/bbcmedia_6music_mf_q?s=1429005507&e=1429019907&h=a604344f65e40f553630f83b8564d426"},"volume":8,"mute":false,"trackNo":1,"elapsedTime":1895,"elapsedTimeFormatted":"31:35","zoneState":"PLAYING","playerState":"PLAYING","zonePlayMode":{"shuffle":false,"repeat":false,"crossfade":false}}%
</pre>

Will try and write a fix for this at some point if I get round to it.

**Comment by jishi** [comment]
I believe this is already fixed. Please make sure that you are running the
latest version of both the http api and discovery and check again.

**Comment by jiphex** [comment]
Ah it is, thanks.
