### ISSUE TITLE
Multiple player say command

### ISSUE THREAD

**Issue by PointPubMedia** [jishi/node-sonos-http-api#520]
Jimmy,

Any chance in the near future to be able to "say" something to multiple player but not all of them?

Since having a Sonos Playbar in the living room, when I'm using the sayall command, it switch the playbar from TV to TTS and having the same issue with the player outside on the patio.

It will be nice to be able to use the say command using more than one player in the same call.

Can be something like,
http://IP:5005:/Kitchen,Living Room, Basement/This is a test/70

**Comment by jishi** [comment]
Heh, you have already requested that in https://github.com/jishi/node-sonos-http-api/issues/270

The plan is to allow you to reference a preset to use as a template for the say command, with volumes and grouping. 

Don't have an estimate for it yet, though.
