### ISSUE TITLE
spotify error when first run

### ISSUE THREAD

**Issue by devans1964** [jishi/node-sonos-http-api#523]
I have installed latest version, successfully run npm install --production. 
When I run npm start
I get error

/Users/dave/apps/sonos/lib/music_services/spotifyDef.js:58
const mapResponse = ({ access_token, token_type, expires_in }) => ({

I have spotify credentials in settings.json

 {
        "spotify": {
            "clientId": "a3780ef36115462bbd7674xxxxxxxx",
            "clientSecret": "3827bf8a738445129ecc7880xxxxxxxx"
          }
}

I get the same issue on both Raspberry Pi and Mac OS

I am a Spotify EU user - not sure if that makes a difference

**Comment by jishi** [comment]
Some of the contributed code needs node 6. I haven't had time to fix it
yet, but if you can upgrade to node 6,that would be a quick solution for
now.

**Comment by jishi** [comment]
Fixed in latest version.
