### ISSUE TITLE
Applying presets is working but returning an error

### ISSUE THREAD

**Issue by oliverconstance** [jishi/node-sonos-http-api#524]
I have created two new presets file inside the presets folder, and include one example below:

`{
  "players": [
    {
      "roomName": "Living Room",
      "volume": 40
    },
    {
      "roomName": "Kitchen",
      "volume": 40
    },
    {
      "roomName": "Bedroom",
      "volume": 10
    }
  ],
  "playMode": {
    "shuffle": true,
    "repeat": "all",
    "crossfade": false
  },
  "pauseOthers": false,
  "favorite": "All Rooms"
}`

When I call /preset I get back an array with my file names, so that seems to work

Then when I call, for example /preset/all_rooms it does actually work (in terms of it updating the members within a given coordinator, which I can see when I call /zones). However, I always get back the response payload, and it always stops any music I have playing: 
`
{
    "status": "error",
    "error": "Favorite not found",
    "stack": "Error: Favorite not found\n    at system.getFavorites.then.then (C:\\Users\\Oliver\\Documents\\GitHub\\node-sonos-http-api\\node_modules\\sonos-discovery\\lib\\prototypes\\Player\\replaceWithFavorite.js:21:15)\n    at process._tickDomainCallback (internal/process/next_tick.js:129:7)"
}
`

Any thoughts / advice / wisdom much appreciated

**Comment by jishi** [comment]
By specifying `"favorite": "All Rooms"` you tell it to search for a Sonos favorite called "All Rooms" and use that as source/queue. It can apparently not find it, and it is also a weird name so I'm guessing you expect the favorite option to mean something else. If you just want it to play whatever "Living Room" would resume if pressing play, just remove the `favorite` option/property.
