### ISSUE TITLE
Beginner's Guide

### ISSUE THREAD

**Issue by cpives2008** [jishi/node-sonos-http-api#530]
Just wondering if anyone can do/ has already done a beginner's guide to installing this on a Rapsberry Pi? I'm wanting to use this in conjunction with the Homebridge-http plugin to control my Sonos

**Comment by jishi** [comment]
Besides http://jishi.github.io/node-sonos-http-api/ there are a few guides written by various people. If you don't intend to run something else on that pi, the absolute easiest solution is to just flash the pre-made image onto an SD-card and use that (works on all pi models). 

I can't find one right now, but I also think I have answered a few issues with a similar request previously. For installing node.js on raspbian: https://github.com/jishi/node-sonos-http-api/issues/456 and then, for installing the http api (without git) https://github.com/jishi/node-sonos-http-api/issues/106

**Comment by cpives2008** [comment]
ok, so i cloned the repo, but when i go on from there, i get this:

pi@raspberrypi:/usr/local/lib/node_modules $ sudo npm install --production
npm ERR! code ENOLOCAL
npm ERR! Could not install from "" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-06-28T20_36_00_235Z-debug.log
pi@raspberrypi:/usr/local/lib/node_modules $

**Comment by JayPalm** [comment]
try running `$ sudo npm install --production` from the node-sonos-http-api folder instead of the node_modules folder.

**Comment by jishi** [comment]
Yes, what he says. Not sure why you are running this in `/usr/local/lib/node_modules`, you can clone the repo anywhere, and then enter the created folder and run `npm install --production`
