### ISSUE TITLE
Working fine lost power now i get this message please help

### ISSUE THREAD

**Issue by Slepperpon** [jishi/node-sonos-http-api#533]
> sonos-http-api@1.4.1 start /home/pi/node_modules/sonos-http-api
> node server.js

2017-07-14T21:07:14.510Z INFO Presets loaded: {}
/home/pi/node_modules/sonos-http-api/node_modules/aws-sdk/clients/codestar.js:3
var Service = require(..+lib/service');
                      ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/node_modules/sonos-http-api/node_modules/aws-sdk/clients/all.js:101:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)

npm ERR! Linux 4.4.50-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sonos-http-api@1.4.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sonos-http-api@1.4.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sonos-http-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.npm/_logs/2017-07-14T21_07_16_164Z-debug.log

**Comment by jishi** [comment]
You have installed it weirdly, since the sonos-http-api is within a
node_modules folder. But besides that, something seems to be off with the
aws-sdk module. Have you upgraded node or something which might have
affected things? Only suggestion I can give is to clear the node_modules
folder for the sonos-http-api and re-install the dependencies with npm
install again.

**Comment by Slepperpon** [comment]
New to this how would I go about that?

________________________________

**Comment by jishi** [comment]
Easiest way is to use git.

`git clone https://github.com/jishi/node-sonos-http-api.git`
`cd node-sonos-http-api`
`npm install --production` 

You can also download the master zip archive (if you don't want to use git). Download https://github.com/jishi/node-sonos-http-api/archive/master.zip, unzip it to your preferred folder, and run the `npm install --production` from there.
