### ISSUE TITLE
"Say" Sometimes Cuts Off Way Too Early.

### ISSUE THREAD

**Issue by overclockedtoday** [jishi/node-sonos-http-api#535]
Firstly, thanks so much or the amazing API. It is amazing to be able to integrate this into our home automation setup.

I am using the "Say" feature to provide dynamic weather updates to selected Sonos speakers. However, about 50% of the time or more, the audio message cuts off very shortly after starting. The API provides a response of 200 much sooner than the message takes to complete. Other times, it works perfectly fine.

Any idea on where I should troubleshoot? I have tried changing the SonosNet channel and moving my Sonos bridge. I don't normally have connectivity issues, so I am not sure what else to look at.

Thanks very much!

**Comment by jishi** [comment]
Are you running the latest version? 

Does it restore the original playback, even when cutting out? 

I did an improvement a while ago, where it will try to figure out the length of the clip and use that +3 seconds as a fallback if I can't identify that the clip playback has stopped (sometimes that event never occur). Previously this was hardcoded to 30 seconds, which for obvious reasons didn't work very well :) 

If you could identify any correlation between the times this happens (length of track, a specific track (tts clip)), maybe even get a hold of that specific clip that would be great. 

Also, of you run the api with verbose logging, it might give a hint of what it actually does when it cuts out. To run verbose, start it with the ENV variable `NODE_LOG_LEVEL=trace`, in linux and MacOS you can do it like this:

`NODE_LOG_LEVEL=trace npm start > debug.log`

For windows powershell, do this:
`$env:NODE_LOG_LEVEL='trace'`
`npm start > debug.log`

Try to reproduce the cut out, and once it occured, stop it and send the debug.log file to me on jimmy at shimizu.se

**Comment by overclockedtoday** [comment]
Thanks so much for the response! I can get you some of the log data asap when I get home. I am just traveling on business for a few days.

I can answer a few of your questions though now:
- I am using the latest version
- There appears to be no correlation between size of file and whether or not it plays back in its entirety. I have had it happen with both small and large files. I have also had it happen for both "Say" and "Clip" - however, it appears to happen with "Clip" much more infrequently and is only usually a problem with net-new files (i.e. happens the first time playing the file, but rarely happens when playing that same file a second or third time).
- The audio that was playing before "Say" was sent, has always started correctly right after "Say" has completed.  However, when I left this morning, the "Say" file was playing perfectly every time I tried it (5 times or so) but the playback of the TuneIn Radio I had playing before the "Say" command was issued was not resuming. This is a brand new problem that I have not experienced up until this morning. I will restart the API when I get home to see if I can get it to auto-resume again.
- Happy to send you any audio files and log files that I can to help out. I should be home in the next two days.

Again, thanks so much. I absolutely love your project and would be happy to support it in any way that I can.

**Comment by overclockedtoday** [comment]
Just sent you an email with a zip folder containing the logs and MP3 audio files generated by Amazon Polly. Sorry for the delay but I am back home now and can respond in a much more timely manner.

Thanks so much!

**Comment by autofrank** [comment]
Hi, 
I am also running 1.4.1 and experiencing the same issue.
No correlation to size of file or when it is played. No other say command being executed at the time

Thanks
_f

**Comment by JsChiSurf** [comment]
FWIW, this sounds pretty much like the issue I also reported on earlier.

**Comment by jishi** [comment]
@JsChiSurf Could be.

@overclockedtoday I looked at your logs, and it is evident that my anticipation of how long the TTS track is is wrong. It seems to think that it's zero seconds, adding a 2 second grace period to this and tries to restore the TTS after 2 seconds because it thinks it never sent a stop signal. 

I think it is some kind of race condition, where the internal state has yet to update (although, it has received the event according to the log). I'll see if I can lock it down and find a reliable solution for it.

**Comment by overclockedtoday** [comment]
Amazing! Thanks so much @jishi! Please let me know if there is anything I can do on my end to assist.

Thanks again!

**Comment by autofrank** [comment]
Thanks @jishi 
Thanks for looking into this ...

I'd like to add one more possibility. I have been running the api for several months now and this only appears to be happening recently for me and I haven't change the api rev in the interim. The only thing that has changed is that I am not also running a HA Bridge fro Alexa (software from bwsystems) on the same Pi so I wonder could it be a resource issue ?
I think mine is a Pi 2
I might try and get a second Pi and move the HA bridge off it and see if it makes any difference

**Comment by jishi** [comment]
Seems unlikely, according to my observations, it seems more like it is too fast :) resource starvation could even be beneficial. 

But either way, it should work reliably regardless.

**Comment by autofrank** [comment]
Understood and thanks

**Comment by jishi** [comment]
Hi guys. Sorry for the delay, but I have made some major changes now which _should_ increase reliability. I can only reproduce this very intermittently in my own setup, but with the latest changes in master I haven't been able to reproduce it once yet. Please upgrade and see if stuff improves.

**Comment by JsChiSurf** [comment]
Thanks for this.

Without being in a new release, is our best bet to just download / replace our existing files in the /lib/actions folder of the repo?

**Comment by jishi** [comment]
You can always download the latest master branch as a zip. Just extract that over your current folder if you didn't use git. https://github.com/jishi/node-sonos-http-api/archive/master.zip

If you used git to install it, just run `git pull`. 

Followed by installing the new dependencies, `npm install --production`

**Comment by JsChiSurf** [comment]
Got it, thanks.

**Comment by jishi** [comment]
I can make a release if that simplifies stuff, but I usually only do that when I want the raspberry pi installs to auto-update.

**Comment by JsChiSurf** [comment]
It's up to you.  I typically use npm on my PI to maintain packages, etc.

**Comment by overclockedtoday** [comment]
Awesome! Thanks so much! I will test this out and let you know if I come across anything.

Also, what is the best way to make a donation for your amazing work? PayPal? If so, what address?

**Comment by jishi** [comment]
There is a PayPal donate button in the README, which is visible on the main github page :)

And as a reminder, there is the gitter.im chat as well, please consider joining if you have questions or want to help out others trying to use this api.
