### ISSUE TITLE
One preset works but other doesn't

### ISSUE THREAD

**Issue by pcgirl** [jishi/node-sonos-http-api#538]
I have two presets setup in the Presets folder.  I use them to make a call from my Smartthings application to turn music on to certain presets for different things.  It was working fine but then for some reason it wasn't playing the presets when I requested.  I noticed errors being displayed from the server.  So I stopped the server and started it again.  I did make changes to one of the presets and I noticed I was missing a comma on a line, so I corrected it and restarted the server.  The presets seem to load ok but when I try to run them by putting http://192.168.1.102:5005/presets/Dogs into my browser, I am getting the following error:
 |  
-- | --
status | "error"
error | "Got status 500 when invoking /MediaRenderer/AVTransport/Control"
stack | "Error\n    at Object.invoke (c:\\Node\\node-sonos\\node_modules\\sonos-discovery\\lib\\helpers\\soap.js:94:10)\n    at Player.setPlayMode (c:\\Node\\node-sonos\\node_modules\\sonos-discovery\\lib\\models\\Player.js:584:15)\n    at c:\\Node\\node-sonos\\node_modules\\sonos-discovery\\lib\\prototypes\\SonosSystem\\applyPreset.js:120:46\n    at process._tickCallback (node.js:369:9)"

The other preset seems to work fine.  I can't see what the issue is and I have checked the code and it seems to be fine.  Any ideas what is causing this issue?
This is the one that works:
{
  "players": [
    {
      "roomName": "Kitchen",
      "volume": 15
    },
    {
      "roomName": "Master Bedroom",
      "volume": 15
	},
	{"roomName": "Lauren's Room",
      "volume": 15
	}
	],
  "playMode": {
    "shuffle": true,
    "repeat": "all",
    "crossfade": false
  },
  "pauseOthers": false,
  "playlist": "Acoustic Chill"
}

And this is the one that doesn't work:
{
  "players": [
    {
      "roomName": "Kitchen",
      "volume": 15
    },
    {
      "roomName": "Master Bedroom",
      "volume": 15
    },
    {
      "roomName": "Lauren's Room",
      "volume": 15
    }

  ],
  "playMode": {
    "shuffle": true,
    "repeat": "all",
    "crossfade": false
  },
  "pauseOthers": false,
  "favorite": "Q107"
}

Thanks for your help!
Jane

**Comment by lukehoverman** [comment]
I don't mean to hijack this thread but I am also using Smartthings to control this API. I would love to hear from other Smartthings' users on how they communicate with the Node Sonos API (custom device type, CoRE, etc).

**Comment by pcgirl** [comment]
I use it in CoRE with a GET web request to my server and the preset.  I make a request when everyone has left the house to put the music on for the dogs.  How do you use it?

Thanks,

Jane Johnson

On Jul 20, 2017, at 2:56 PM, lukehoverman <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't mean to hijack this thread but I am also using Smartthings to control this API. I would love to hear from other Smartthings' users on how they communicate with the Node Sonos API (custom device type, CoRE, etc).

**Comment by jishi** [comment]
What kind of source is the `Q107` favorite? Seems like it throw an error when trying to apply the playMode. Does that playmode make sense for that source? Having any playmode for a radio channel for instance, doesn't make any sense. Try removing the playMode completely from that preset, and see if that works. Then re-add them one at a time and see which one breaks.

**Comment by pcgirl** [comment]
Q107 is a radio station.  I have it set in my favorites in Sonos.  Will it not work with a radio station?


Thanks,
Jane Johnson


________________________________

**Comment by jishi** [comment]
It works with a radio station. You just can't combine playmodes with radio stations, since they don't make sense. However, it should ignore those errors on newer versions. You seem to be running some outdated version because the stack trace doesn't correspond with the latest version of the code.

Either remove the playmodes from presets where you have radio, or upgrade.

**Comment by pcgirl** [comment]
Is the upgrade on your github?

Thanks,

Jane Johnson

On Jul 21, 2017, at 10:05 AM, Jimmy Shimizu <notifications@github.com<mailto:notifications@github.com>> wrote:


It works with a radio station. You just can't combine playmodes with radio stations, since they don't make sense. However, it should ignore those errors on newer versions. You seem to be running some outdated version because the stack trace doesn't correspond with the latest version of the code.

Either remove the playmodes from presets where you have radio, or upgrade.

**Comment by jishi** [comment]
The latest version is always the master branch. It sort of depends on how you installed it, how you would go about upgrading. Either just `git pull` the latest changes followed by an `npm install --production` to also update all new dependencies, or download the zip version and extract over your current install, followed by an `npm install --production`

**Comment by lukehoverman** [comment]
In regards to Smartthings, I cobbled together a device type so I can use CoRE to to send a command and corresponding variables to make it a bit easier on forming the URLs. I did write a smartapp to play random playlists on a certain trigger but now it's easy to have CoRE pick a random item from a list.

**Comment by pcgirl** [comment]
Thanks,
Jane Johnson
++++++++++++++++++
A+ Computer Services
(905) 317-0540
++++++++++++++++++

From: Jane Johnson
Sent: Thursday, January 04, 2018 12:45 PM
To: Jane Johnson <jane@a-plus-computers.ca>
Subject: RE: [jishi/node-sonos-http-api] Problem with presets returning an error (#571)

Did you figure out what the problem is with the one player not working but the other one working even though they both have an apostrophe in them?

Thanks,
Jane Johnson

From: Jane Johnson
Sent: Wednesday, December 06, 2017 8:50 AM
To: jishi/node-sonos-http-api <reply@reply.github.com>
Subject: RE: [jishi/node-sonos-http-api] Problem with presets returning an error (#571)

Hi Jimmy,

So I took out the Ryan’s Bedroom from the preset and it did work.  However, the Lauren’s Room is still in the preset and it is working.  Does it have anything to do with the fact that I added this player recently?

Thanks,
Jane Johnson
++++++++++++++++++
A+ Computer Services
(905) 317-0540
++++++++++++++++++
