### ISSUE TITLE
Autostart "node start"

### ISSUE THREAD

**Issue by Ferrari2** [jishi/node-sonos-http-api#539]
Hi

I have unfortunately used many hours trying to autostart the sonos http server, like "npm start" in the library "/home/pi/node-sonos-http-api" on startup/reboot of the RPi3 - but no luck.

I have been around using "/etc/rc.local" but all I tried didn't work.

Any suggestions please

Kind regards
Ferrari

**Comment by GregRocket** [comment]
I use pm2
https://github.com/Unitech/pm2

Install pm2
change to directory where node-sonos-http-api is installed on your RPi3
Issue command:
**pm2 start npm --name "node" -- start**

Then issue command:
**pm2 save**

the sonos api should auto start on reboot now.

That's how I do it and this has worked for me without issue for some time.

Useful pm2 commands:
  pm2 list
  pm2 delete 0
  pm2 stop all
  pm2 start all

**Comment by Ferrari2** [comment]
Hi

Thank you for the ”pm2” advice.

I couldn’t make it work properly but thanks to your advice, I make this working fine for the autostartup:

npm start
sudo service --status-all
npm install -g pm2
pm2 startup
pm2 start server.js -x --name "sonos-api"
pm2 dump

**Comment by dadeppa** [comment]
I tried to get it started automatically as well. Up to now I failed, maybe the pm2 is a good advise.

Before, I didn't have any clue of Linux and stuff like that. I downloaded the premade image and it worked well. As I am that kind of guy, that like to understand, how things work, I have setup my own alpine Linux on a raspberry pi 3 and got http sonos running. But I didn't manage to start it on Boot. So I have searched the internet for help.

I found about the possibility to start a service and create an own one. So I tried several scripts; up to now, the possibility working most was the following:

cd'ing to /ect/local.d/
created a new file, called sonos.start, content:

#!/bin/sh
cd /usr/node-sonos-http-api
exec npm start

Then I ran rc-update local default, to get the local service running after boot.

This worked, the service is started after boot, but unfortunately, I could not login via SSH any more...

So I had a look at the premade image and found out, that there is an euqal way to start it. 

jishi placed a http-api.start in the services folder and there he started an sh script start_hhtp_api.sh

this script contained the following code:

```
#!/bin/sh
while (true); do
    /usr/bin/node /flash/apps/sonos-http-api/server.js >> /flash/logs/http-api.log
    sleep 10
done
```
As I do not understand the code, I couldn't adapt it on my installation, so this is where I am stuck at the moment...

**Comment by jishi** [comment]
IIRC the local scripts need to exit, otherwise it blocks the bootup. 

If you look at the alpine image I provide, I call the `start_http_api.sh` with a trailing `&` which means that it will run it in background, not blocking the `http-api.start` script.

Then, the `start_http_api.sh` handles the startup of the api instead. I can explain the script line by line:

```
#!/bin/sh
# Enter an infinite loop, to provide a very simplistic restart logic
while (true); do
    # Start the api, and forward the console output to a log file
    # This call will actually block the script, until the app ois stopped (with kill or similar), or crashes 
    /usr/bin/node /flash/apps/sonos-http-api/server.js >> /flash/logs/http-api.log
    # This will only be invoked if the app crashes or gets killed. I add a sleep to avoid a repeated start/crash/start etc
    sleep 10
    # After the 10 second sleep, the infinite loop will re run, trying to start the api again.
done
```

So basically, to get SSH to work, use  
```
#!/bin/sh
cd /usr/node-sonos-http-api
exec npm start &
```
(Note the `&` at the end)
However, if you also want some sort of restart logic, try to mimic the approach I use with two separate scripts.

**Comment by dadeppa** [comment]
Thank you (again) for your kind help. I will try this at home this evening.

**Comment by dadeppa** [comment]
Okay, I tried it with the simple exec and it worked. As a matter of the simplicity there is no restart script like in your version. 

So I tried to adopt your way, but I did not manage to get it to work. 

I even tried to combine pm2 and the exec:

```
#!/bin/sh
cd /usr/node-sonos-http-api
exec pm2 start server.js -x --name "sonos"
```
But this did not work for me :'(  I thought I had outfoxed the system... but I failed :laughing: 

I even copied the pm2 process as local service and added a .start in the end and changed the pm2 home dir to a directory in the persistent storage. But this did not work for me, too.

Do you have installed pm2 on your build, too?

I know, this is not pretty much about your sonos api, but I want to learn how to get it to work and I am very thankful for your kind help!

**Comment by jishi** [comment]
No, I didn't use pm2 on my raspberry because I felt it was a bit overkill and used more resources than necessary. It also wasn't totally straight forward to make it run as a service (as you noticed) so I didn't bother.

`/usr/bin/node /flash/apps/sonos-http-api/server.js >> /flash/logs/http-api.log`

This is basically invoking `node server.js` if you did `cd` into the folder, but since this folder is ran upon boot and with no knowledge of what the current working directory is, or which command are in your path, I use absolute paths both for the `node` command, as well as the `server.js` file.

`npm start` is just a convenience shortcut to the above, but it also clutters the logging so I avoided that.

**Comment by dadeppa** [comment]
jishi ... thanks for your patience.

I asked about pm2, because I found it installed in an apkovl file on your image:
\0.fat\sonos.apkovl.tar.gz\sonos.apkovl.tar\etc\.pm2\

you are right, that this will be an overkill, but: I want to add other node modules to my pie, this is the reason I started struggeling around with an own build. 
I have a plc running in my house, which controls the sonos subsystem via your api. I want to add an HMI that runs as a web service via nodejs on the raspberry pi as well.

So I will give this another try with pm2, if it will not work, I continue following your approach.

**Comment by jishi** [comment]
Alpine seems to be using openrc as a startup system, so you should try to install the startup scripts using: 

`pm2 startup openrc`

And see if that works. I think you might get into trouble with the read-only filesystem and the overlay, where a pm2 module that is installed globally might not be persisted when doing `lbu_commit`. Not sure how to resolve that, but you could probably find other people that have similar issues with custom installed software in Alpine for the pi.

**Comment by jishi** [comment]
The remnant you found was probably me trying to get pm2 to work, but as I said, I gave up and realized it was unnecessary for my needs :) It is however an awesome process manager for node.js.

**Comment by dadeppa** [comment]
Yes, this is correct. You can use pm2 to deal with this automatically, it will load settings for Gentoo linux.

I added your api to pm2:
```
rpi:/usr/node-sonos-http-api-master# pm2 start npm --name "node" -- start
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2] Starting /usr/bin/npm in fork_mode (1 instance)
[PM2] Done.
┌──────────┬────┬──────┬──────┬────────┬─────────┬────────┬──────┬───────────┬──────┬──────────┐
│ App name │ id │ mode │ pid  │ status │ restart │ uptime │ cpu  │ mem       │ user │ watching │
├──────────┼────┼──────┼──────┼────────┼─────────┼────────┼──────┼───────────┼──────┼──────────┤
│ node     │ 0  │ fork │ 1773 │ online │ 0       │ 0s     │ 142% │ 10.0 MB   │ root │ disabled │
└──────────┴────┴──────┴──────┴────────┴─────────┴────────┴──────┴───────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

I then installed pm2 startup script, with no args, so autodetect run / boot system:

```
pm2 startup
[PM2] Init System found: openrc
Platform openrc
Template
#!/sbin/openrc-run
# Copyright 2017 the PM2 project authors. All rights reserved.
# Init script automatically generated by pm2 startup

description="Production process manager for Node.js apps with a built-in load balancer."

extra_started_commands="reload"

PM2="/usr/lib/node_modules/pm2/bin/pm2"
user=${PM2_USER:-root}
export PM2_HOME=$(eval echo ~${user})"/.pm2/"
# Options for start-stop-daemon (default start function)
command=${PM2}
command_user=${user}
command_args="resurrect"
pidfile=${PM2_HOME}/pm2.pid

run_pm2_as_user() {
        einfo "${PM2} $@"
        eval su -l ${user} -c \'${PM2} $@\'
}

depend() {
        need net
        need localmount
        after bootmisc
}

start_post() {
        if [ "${user}" == "root" ]; then
                ewarn "PM2: Better run this daemon as a non root user. To set this user create"
                ewarn "PM2: /etc/conf.d/pm2 file and define 'PM2_USER=user' there."
                ewarn "PM2: Note user MUST have home directory for PM2 logs/state/etc..."
        fi
        einfo "PM2: Process Manager started. To start services run:"
        einfo "PM2: # su -l ${user} -c '$PM2 start /path/to/app'"
}

stop() {
        ebegin "Stopping PM2 process manager..."
        run_pm2_as_user dump
        run_pm2_as_user delete all
        run_pm2_as_user kill
        eend $?
}

reload() {
        ebegin "Reloading pm2"
        run_pm2_as_user reload all
        eend $?
}

# vim: ts=4

Target path
/etc/init.d/pm2
Command list
[ 'chmod +x /etc/init.d/pm2', 'rc-update add pm2 default' ]
[PM2] Writing init configuration in /etc/init.d/pm2
[PM2] Making script booting at startup...
>>> Executing chmod +x /etc/init.d/pm2
[DONE]
>>> Executing rc-update add pm2 default
 * rc-update: pm2 already installed in runlevel `default'; skipping
[DONE]
+---------------------------------------+
[PM2] Freeze a process list on reboot via:
$ pm2 save

[PM2] Remove init script via:
$ pm2 unstartup openrc
```

Followed by pm2 save to freeze my app list as a startup list:
```
rpi:/usr/node-sonos-http-api-master# pm2 save
[PM2] Saving current process list...
[PM2] Successfully saved in /root/.pm2/dump.pm2
rpi:/usr/node-sonos-http-api-master#
```

Yesterday, I added the .pm2 folder to my lbu by:
`lbu add /root/.pm2`

I checked, if startup is correct by:
```
rpi:/usr/node-sonos-http-api-master# rc-update add pm2
 * rc-update: pm2 already installed in runlevel `default'; skipping
rpi:/usr/node-sonos-http-api-master#
```

After this I updated the rc:
```
rpi:/usr/node-sonos-http-api-master# rc-update -u
 * Caching service dependencies ...                                                                                                                              [ ok ]
rpi:/usr/node-sonos-http-api-master#
```

Followed by a local backup:
```
rpi:/usr/node-sonos-http-api-master# lbu commit -d
tar: root/.pm2/rpc.sock: socket ignored
tar: root/.pm2/pub.sock: socket ignored
rpi:/usr/node-sonos-http-api-master#
```

So, the two socket files are ignored... that is a part, I have to figure out...

Finally, I typed `reboot `and waited for the pi to come up again:
```
rpi:~# pm2 list
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
rpi:~#
```

So, very disappointing in the end, all this did NOT work... 
and here I am stuck again

**Comment by dadeppa** [comment]
YEAH!

I did those steps again and added /etc/init.d/pm2 to the local backup, then:

```
rpi:/etc/init.d# reboot
rpi:/etc/init.d#
login as: root
root@10.1.1.128's password:
Welcome to Alpine!

The Alpine Wiki contains a large amount of how-to guides and general
information about administrating Alpine systems.
See <http://wiki.alpinelinux.org>.

You can setup the system with the command: setup-alpine

You may change this message by editing /etc/motd.

rpi:~# pm2 list
┌──────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├──────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ node     │ 0  │ fork │ 1386 │ online │ 0       │ 50s    │ 0%  │ 26.2 MB   │ root │ disabled │
└──────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
rpi:~#
```

Never been that glad finding a row in a table ... since university where I found myself in the "passed the exam" table :laughing: 

Thank you all so much, it all worked out... I will reboot several times again and the, if this stays...

**Comment by jishi** [comment]
Hm, weird, I thought all of /etc was part of the lbu overlay. It might expect it to be installed with the apks which seems to be re-applied every reboot, and since the pm2 init file is added manually, it goes missing. Glad you sorted it out, it could be useful to me as well for future upgrades of the image!
