### ISSUE TITLE
cannot communicate to dev

### ISSUE THREAD

**Issue by bogdanfer** [jishi/node-sonos-http-api#54]
hi, after running node server.js I am getting the following:

`no settings file found, will only use default settings
binding SSDP to port 2319
discovering all IPs from lo0
discovering all IPs from en0
discovering all IPs from awdl0
relevant IPs { '192.168.1.79': null }
notification server listening on port 3500
http server listening on port 5005
no preset file, ignoring...
scanning for players in ip 192.168.1.79`

and then when trying to make a GET on localhost:5005 with /zones, 
I am getting this: 

`node-sonos-http-api/lib/actions/zones.js:2
  callback(player.discovery.getZones());
                 ^
TypeError: Cannot read property 'discovery' of null`

any ideas?

**Comment by jishi** [comment]
This looks like it doesn't find any players on your network. Please verify that the device running is on the same network as your sonos players. I might help if you describe your home network (which router, wifi, how is sonos connected, via WiFi or SonosNet and what device you are running this on and how it is connected to the network).

**Comment by bogdanfer** [comment]
it's a bit strange, it used to work 1-2 months ago and now, while trying to connect via terminal, my Sonos app works (on Mac). I'll give it another try and get back with results. thanks for the response.

**Comment by rgraciano** [comment]
Might not be your issue, but this happens if you have the Sonos client open on the same machine as your Node server. I had this problem on OS X Yosemite

**Comment by Trudeaucj** [comment]
Closing the Sonos client on OS X Yosemite fixed this for me as well.

**Comment by jishi** [comment]
An update to this. The firewall in OS X Yosemite will block this. I haven't found a way to allow it through yet. If you have another scenario (other platform, firewall off), please let me know and explain the setup.

**Comment by potherca** [comment]
I had the same issue (Sonos client open). Maybe this should be added to the readme?

**Comment by jishi** [comment]
I should perhaps just up the port number from 1901 instead, there is no real benefit of having it as exactly that except for already defined firewall rules.

**Comment by jishi** [comment]
changed port binding to 1905 to not conflict on OS X for now.

**Comment by potherca** [comment]
:+1:
