### ISSUE TITLE
Clip-error: You need to register an API key to use this feature

### ISSUE THREAD

**Issue by s0161038** [jishi/node-sonos-http-api#540]
When I try to play an mp3 file with the the clip command, I always get the message you have to register an API key to enable this feature. All the say commands work perfectly. 

I have registered an key at voicerrs and created an extra settings.json fille in the presets folder with the api key but I still get the spoken message: ' you need to register an API key to enable this feature' when i try to play a mp3.

**Comment by jishi** [comment]
The clip action doesn't use any API key... so that seems a bit odd...?

Could you explain exactly how you are invoking this?

**Comment by s0161038** [comment]
I use the command
sonos:5005/clipall/Doorbell.mp3 

And the Doorbell.mp3 is stored in the static/clip folder next to the sample mp3, which plays correctly if i call it with: sonos:5005/clipall/Sample.mp3

**Comment by jishi** [comment]
The sample works? hm, I guess there is something wrong with the Doorbell.mp3 in that case... Have you tried listening to it with some media player on your computer?

I actually don't seem to ever play that missing api key file in the latest code base, makes me wonder what version you are running too? Could you check which version it says in the `package.json` file?

**Comment by s0161038** [comment]
As you mentioned i tried to the MP3 and apparently it got corrupted. I replaced it and everything works fine.

Thanks!
