### ISSUE TITLE
Status 408 returned

### ISSUE THREAD

**Issue by JsChiSurf** [jishi/node-sonos-http-api#542]
Just this morning, I started getting the following when trying to invoke a tts call:

status: "error"
error : "Got status 408 when invoking /synthesize"
stack : "Error at /home/pi/downloads/node-sonos-http-api/lib/tts-providers/microsoft.js:76:12"

Don't know if anyone else is seeing this (ie from the Microsoft side).

I changed my settings.json to use AWS and it worked fine.  Perhaps my access has expired / been blocked to the Microsoft API (API says I have 36 days remaining).

**Comment by jishi** [comment]
Unsure what it means. I don't use microsoft personally, so I can't vouch for it to still be functional. That said, it still list the free tier, maybe you've exceeded the free quota of 5000 transactions per month?

**Comment by JsChiSurf** [comment]
408 seems to imply the "issue" is coming from the client side, which is strange, as I've never had a problme until this morning.  There's definitely no way I'm averaging 166 TTS's / day.  Probably 10 at best, in terms of rate limiting.

Wondering if anyone else who uses Microsoft is seeing the same thing right now.

**Comment by jishi** [comment]
408 is according to HTTP standard just "Request timeout", but I couldn't find any documentation from Microsoft regarding this in the text to speech API.

They might have discontinued the selected voice or something, or the audio format, not sure. Try changing voice and audio quality (here https://github.com/jishi/node-sonos-http-api/blob/master/lib/tts-providers/microsoft.js#L83) and see if it changes anything.

**Comment by jishi** [comment]
Also, the length of the SSML can be at max 1024 characters. Are you within those bounds?

**Comment by JsChiSurf** [comment]
Standard "hello world" stuff right now, just for testing.  Never more than a short sentence when running in "automated" mode.

Right, regarding 408, but the request timeout is related to the client side, not the server side request / response ("The client did not produce a request within the time that the server was prepared to wait.").

Current voice / quality setting in microsoft.js appears to still be valid:

https://docs.microsoft.com/en-us/azure/cognitive-services/speech/api-reference-rest/bingvoiceoutput

I tried a handful of those in the list all with the same result.  Not sure what is going on now.  One would think something has had to of changed on their side, but unsure what.  Will keep playing around.  

For now, Amazon is working, but not my preferred voice :-(

**Comment by jishi** [comment]
I can probably make some tests when I get home, to see if I get the same issue.

**Comment by JsChiSurf** [comment]
Appreciate it.  As mentioned, I'm going to go through docs and see if anything has changed.  Most research for those I've seen getting 408s in the past were due to malformed requests, which we know, at least, originally, was not the issue (again, unless something has changed server side).

Also, just to make sure it is not just me, I am going to sign up for a new account to get a different API Key and see what happens.

**Comment by JsChiSurf** [comment]
Update: FWIW, just signed up with a new Bing account, thus receiving a new API key, same result :-(

**Comment by jishi** [comment]
I ran some test and I experience the same thing as you. But the weird thing is that the timeout must occur on their end, because I get no response at all, until after 14 seconds, when it responds with 408 timed out and the body `Request timed out (> 14000 ms)`

Must be something else going on in their end...

**Comment by JsChiSurf** [comment]
Yep, thanks for confirming.  I put in a handful of logger statements, especially to verify the token was still getting generating, and could see that it just can't seem to get past the /synthesize step.  Thought perhaps could be an SSL certificate expiration issue, but when visiting the URL in a browser, it appears valid, so not sure what is going on.  Hopefully it will "heal" itself shortly.  Thanks again.

**Comment by JsChiSurf** [comment]
So, I've been playing with and trying to debug this for a bit now, and the only conclusion I am come up with is that form some reason the HTTP request library is no longer playing nice with the '/synthesize' call (despite working fine (to a different URL / domain) for the token request call.

In using their own home-brewed samples in both PHP and node:

https://github.com/Azure-Samples/Cognitive-Speech-TTS/tree/master/Samples-Http

This stock code is running just fine can returning a valid wav file as expected.  When you look at their included HTTP calls, the parameters look exactly the same (with some slight seemingly irrelevant variances).  The only difference I see, then, is their use of a different HTTP library to formulate the calls.

**Comment by jishi** [comment]
Hah, figures. I don't sent a content-length header, that makes the speech system sad, for obvious reason. I added it now, although my request helper should probably deal with that regardless.

**Comment by jishi** [comment]
Good persistance and idea to look at the samples. The obvious test should probably have been to replay the requests in some other tool (like postman), then it became pretty clear that you we're right in your assertion all along :)

**Comment by JsChiSurf** [comment]
I swear to you while debugging I did just that, i.e. adding a header value for content-length, for the length  of the SSML data being posted, after seeing this in the PHP example, but didn't seem to have any luck.

When I look at their node.js example, I don't seem them passing length either, which is strange, so didn't thing this would have been the issue:

https://github.com/Azure-Samples/Cognitive-Speech-TTS/blob/master/Samples-Http/NodeJS/TTSService.js

So I'm still a bit perplexed both as to why this resolved (it has), as well as why, if this is the case, it worked in the first place!

**Comment by jishi** [comment]
My guess is the reason that the samples work is because the request library it uses, populates content-length automatically.

Very odd that your debugging didn't resolve it, although when evaluting various means for debugging it has been more than one occasion where I forgot to reload the app ;)

**Comment by JsChiSurf** [comment]
Ha, Ha, I bet you're right regarding reloading of the app... :-)
