### ISSUE TITLE
Beginners Help: Pandora Login

### ISSUE THREAD

**Issue by ookami85** [jishi/node-sonos-http-api#548]
Thanks for this awesome tool! I have gotten pretty much everything setup on a RPi2 using the current setup guide. I am however having trouble with where to place the Pandora login information in the setting.js file to have it work properly to search with the /room/pandora/play/[station] command. Any assistance or an example file would be greatly appreciated. 

Gene

**Comment by jplourde5** [comment]
Check the settings.json section in the Readme. You will see a section for entering your Pandora user ID and pw.

**Comment by ookami85** [comment]
@jplourde5 
I have tried to add my Pandora info. using the readme options, however, it does not seem to register. I am using the default file with the following placement added:

}

var settings = {
  port: 5005,
  securePort: 5006,
  cacheDir: path.resolve(__dirname, 'cache'),
  webroot: path.resolve(__dirname, 'static'),
  presetDir: path.resolve(__dirname, 'presets'),
  announceVolume: 40
},
"announceVolume": 40,
"pandora": {
"username": "my username",
"password": "my password"

};

Am I doing something incorrectly? Do I need to removed some of the settings in the default file and replace more things from the example file?

Thanks for the assist. 

Gene

**Comment by jishi** [comment]
You shouldn't modify the settings.js file manually. You should create a file called `settings.json` in the same folder, and add the credentials you want. 

However, what you did "should" work, but the syntax looks wonky, and I'm surprised it loads at all.

**Comment by jishi** [comment]
Also, please join the gitter chat for questions like this, then you can be assisted by other users that has already got this working. https://gitter.im/node-sonos-http-api/Lobby

**Comment by ookami85** [comment]
@jishi 
Doh! I completely overlooked that this was to go into a new settings.json file and not the setting.js...O_O.  I created the settings.json, add my pandora info., and all is working now. I'm off to setup echo-sonos. I'll be sure to use the Lobby going forward if I have any issues once I move on  to the different say options. Thanks!
