### ISSUE TITLE
Microsoft TTS

### ISSUE THREAD

**Issue by PointPubMedia** [jishi/node-sonos-http-api#551]
@jishi ,

Got an issue with MS TTS 

`{"status":"error","error":"Got status 401 when invoking /sts/v1.0/issueToken","stack":"Error\n    at generateBearerToken (/opt/node-sonos-http-api/lib/tts-providers/microsoft.js:23:10)\n    at microsoft (/opt/node-sonos-http-api/lib/tts-providers/microsoft.js:70:15)\n    at promise.then (/opt/node-sonos-http-api/lib/helpers/try-download-tts.js:17:14)\n    at <anonymous>"}`

**Comment by jishi** [comment]
Sounds like your Microsoft credentials has expired?

**Comment by PointPubMedia** [comment]
Looks like we need to migrate our account from the old platform to the new azure!  Sorry for wasting your time!

**Comment by jishi** [comment]
No need for me to change endpoints?
