### ISSUE TITLE
error in start whit npm start

### ISSUE THREAD

**Issue by Mazze85** [jishi/node-sonos-http-api#552]
/home/pi/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:35
});
^
SyntaxError: Unexpected token }
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/node-sonos-http-api-master/server.js:9:20)
    at Module._compile (module.js:541:32)

npm ERR! Linux 4.9.41+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@1.4.5 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sonos-http-api@1.4.5 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sonos-http-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/node-sonos-http-api-master/npm-debug.log

What is the Problem ? rPi 1

**Comment by jishi** [comment]
Sounds like there is a syntax issue with the node-static npm package? Maybe it is outdated, did you install this fresh right now or have you upgraded from an older version?

Try to remove the node_modules folder and run `npm install --production` again.

**Comment by Mazze85** [comment]
i think the Problem is my node, when i start  npm install --production  

i become first:
pi@raspberrypi:~/node-sonos-http-api-master $ npm install --production
(node:903) fs: re-evaluating native module sources is not supported. If you are                                 using the graceful-fs module, please update it to a more recent version.
(node:903) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:903) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:903) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:903) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:903) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:903) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:903) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:903) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
fetchMetadata → resolveWi

What node Version i did Need ?

**Comment by Mazze85** [comment]
okay, the Problem was my PI1 on my PI3 it works.

**Comment by jishi** [comment]
Weird, shouldn't matter. Anything Node 4.x or up is supposed to work. I've ran it successfully on a pi1 too. You could try and re-install node.js on it, maybe something has acted up during installation.
