### ISSUE TITLE
Feature Request: GetBass/SetBass & GetTreble/SetTreble

### ISSUE THREAD

**Issue by noxhirsch** [jishi/node-sonos-http-api#554]
Hi,
it would be really cool to have a function for reading and setting the bass and treble levels as in this PHP script:
https://github.com/Liver64/PHP-Sonos-and-Loxone/blob/master/System/PHPSonos.php (the functions are called GetBass, SetBass, GetTreble & SetTreble in this script)
Regards,
Nox

**Comment by jishi** [comment]
Weird that I never implemented this. I did implement the PLAYBAR specific equalizer settings, these should basically be the same.

However, the bass/treble levels will be part of the state command, and also emitted when changed (on the webhook). Makes more sense than querying them individually.

**Comment by rexyiy** [comment]
Yes, please! I really need this function ;)

> it would be really cool to have a function for reading and setting the bass and treble levels as in this PHP script:
https://github.com/Liver64/PHP-Sonos-and-Loxone/blob/master/System/PHPSonos.php (the functions are called GetBass, SetBass, GetTreble & SetTreble in this script)

**Comment by jishi** [comment]
FYI, this will be the next feature I will implement.

**Comment by rexyiy** [comment]
Thank you in advance <3
