### ISSUE TITLE
Sayall and resume playing - not working with tuneln

### ISSUE THREAD

**Issue by mr-istian** [jishi/node-sonos-http-api#56]
Hi,
When using the sayall function while playing a spotify playlist or any other playlist the music stoppes, says what it is supposed to say, and then it resumes playing the playlist. However, when playing a radio channel with tuneln and execute the sayall command the music/radio stoppes and says what it was supposed to say but when done it does not go back to play the radio station that was playing before.... Is this possible to fix?

**Comment by jishi** [comment]
Better late than never. This has been fixed in the beta branch now, if you are still using this, please try it out by checking out the beta branch instead, and update your dependencies.
