### ISSUE TITLE
Error on npm install --production

### ISSUE THREAD

**Issue by rhalbheer** [jishi/node-sonos-http-api#566]
All,
I really like the software but somehow fight each time I am trying to set a new RPI up. This time, I failed miserably when I run npm install -- production with the following errors:
`npm WARN package.json sonos-discovery@1.5.1 No license field.
npm WARN package.json fuse.js@2.7.4 license should be a valid SPDX license expression
npm ERR! tar.unpack untar error /root/.npm/async/2.6.0/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/node-sonos-http-api-master/node_modules/music-metadata/node_modules/fs-extra/lib'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  music-metadata@0.8.7 { [Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/node-sonos-http-api-master/node_modules/music-metadata/node_modules/fs-extra/lib']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/pi/node-sonos-http-api-master/node_modules/music-metadata/node_modules/fs-extra/lib' }
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'types/es6-promise' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'strtok3'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.9.41-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--production"
npm ERR! cwd /home/pi/node-sonos-http-api-master
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! tar.unpack untar error /root/.npm/mingo/1.3.3/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/node-sonos-http-api-master/node_modules/music-metadata/node_modules/save/node_modules/event-stream/test'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  save@2.3.1 { [Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/node-sonos-http-api-master/node_modules/music-metadata/node_modules/save/node_modules/event-stream/test']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/pi/node-sonos-http-api-master/node_modules/music-metadata/node_modules/save/node_modules/event-stream/test' }
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/node-sonos-http-api-master/npm-debug.log
npm ERR! not ok code 0
`
Sorry, I really tried to solve it myself.....
Thank you for any pointer

**Comment by jishi** [comment]
Hm... Is there any specific reason you are running node 4.8? If you still
want to run that, try upgrading to npm 2 with (as root)

npm install -g npm@2

And try again by deleting the node_modules folder and run npm install
--production again

Otherwise upgrade to node 8 and see if that helps.

Are you planning on running other stuff on this rpi? Otherwise you can
always use the pre-configured rpi image that runs the system as readonly
from the SD card to spare the wear on it.

**Comment by rhalbheer** [comment]
Thank you.
No I am not. I just took the RPI image and ran an upgrade.
Where do I find the preconfigured image?
Roger



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by jishi** [comment]
It's the 1.0.1 version but it will auto update the first night it runs to
1.4.3. If you want to run the absolute latest version you would have to
update it manually, but I'll probably tag a release in the near future.

**Comment by rhalbheer** [comment]
I know leverage the image you proposed. Thank you
