### ISSUE TITLE
Support Needed with IFTTT

### ISSUE THREAD

**Issue by stargazer200529** [jishi/node-sonos-http-api#570]
This works great!

I want to integrate it with IFTTT so I can use google assistant to control Sonos.

I can't seem to get it to work. There seems to be an issue with retrieving the URL.

I currently have the url as http://my-ip-addresss:5005/Bathroom/{{TextField}}
I'm not use to working with IP addresses, I basically used what's listed when I type into google "What's my IP address"

This doesn't seem to be working, any suggestions?

**Comment by bosyd** [comment]
Do you have a static IP address with your ISP?  If not, it would be good to setup DDNS as this is what I did and the integration is working perfectly.  Also, have you opened port 5005 in your firewall?


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by jishi** [comment]
This is the exact reason why I created the bronos-client ( http://www.bronos.net/ ) to avoid having to deal with the complexity of port forwarding, dynamic DNS and the likes. I suggest you check that out.

You don't have to use a raspberry pi, you can install it on the same machine as you run the http-api if you want.

**Comment by bosyd** [comment]
Very cool, I did not know this existed.  I have tried it out and it works well.

However, I still have to use the DDNS and port forwarding for my Philips Hue setup as there is a bug with Google Home when the Philips application marks a buls as unavailable (GH does not turnit on whereas the IFTTT commands bypasses the Philips status)


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by stargazer200529** [comment]
Bronos works like a charm!! Thanks!
