### ISSUE TITLE
Issue with next and previous Commande

### ISSUE THREAD

**Issue by fufu74** [jishi/node-sonos-http-api#572]
Hello,

I have an error when sending those 2 command. The sonos is a Play1.

I'm sending the following command
http://ServerIP:5005/Name of Speaker/next/

I'm receiving the following errors.

For Next:

  | {"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error\n    at Object.invoke (C:\\xampp\\htdocs\\sonos\\node_modules\\sonos-discovery\\lib\\helpers\\soap.js:94:10)\n    at Player.nextTrack (C:\\xampp\\htdocs\\sonos\\node_modules\\sonos-discovery\\lib\\models\\Player.js:399:15)\n    at Object.next (C:\\xampp\\htdocs\\sonos\\lib\\actions\\nextprevious.js:2:29)\n    at handleAction (C:\\xampp\\htdocs\\sonos\\lib\\sonos-http-api.js:110:35)\n    at HttpAPI.requestHandler (C:\\xampp\\htdocs\\sonos\\lib\\sonos-http-api.js:87:5)\n    at C:\\xampp\\htdocs\\sonos\\server.js:80:13\n    at Server.finish (C:\\xampp\\htdocs\\sonos\\node_modules\\node-static\\lib\\node-static.js:111:13)\n    at finish (C:\\xampp\\htdocs\\sonos\\node_modules\\node-static\\lib\\node-static.js:170:14)\n    at C:\\xampp\\htdocs\\sonos\\node_modules\\node-static\\lib\\node-static.js:144:17\n    at FSReqWrap.oncomplete (fs.js:152:21)"}
-- | --

And for Previous

  | {"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error\n    at Object.invoke (C:\\xampp\\htdocs\\sonos\\node_modules\\sonos-discovery\\lib\\helpers\\soap.js:94:10)\n    at Player.previousTrack (C:\\xampp\\htdocs\\sonos\\node_modules\\sonos-discovery\\lib\\models\\Player.js:405:15)\n    at Object.previous (C:\\xampp\\htdocs\\sonos\\lib\\actions\\nextprevious.js:6:29)\n    at handleAction (C:\\xampp\\htdocs\\sonos\\lib\\sonos-http-api.js:110:35)\n    at HttpAPI.requestHandler (C:\\xampp\\htdocs\\sonos\\lib\\sonos-http-api.js:87:5)\n    at C:\\xampp\\htdocs\\sonos\\server.js:80:13\n    at Server.finish (C:\\xampp\\htdocs\\sonos\\node_modules\\node-static\\lib\\node-static.js:111:13)\n    at finish (C:\\xampp\\htdocs\\sonos\\node_modules\\node-static\\lib\\node-static.js:170:14)\n    at C:\\xampp\\htdocs\\sonos\\node_modules\\node-static\\lib\\node-static.js:144:17\n    at FSReqWrap.oncomplete (fs.js:152:21)"}
-- | --

**Comment by jishi** [comment]
Those are errors from the player. Are you sure you are playing from a queue and not a radio station? What is the source? Is it using Spotify direct or something similar (controlled from a native music service app or similar)?

**Comment by fufu74** [comment]
Hello,

An update on this ticket.

You're right, it's a error from me. The playlist was originally sent from a nas  (Qnap qith Qmusic App). If I send the playlist with "node-sonos-http-api", then all functions are working properly
