### ISSUE TITLE
Preset Volume with New Play One Alexa

### ISSUE THREAD

**Issue by GregRocket** [jishi/node-sonos-http-api#583]
I have a preset that just sets volumes for a group of rooms. This preset has worked for a long time. For the Holidays I received a new Sonos Play One with Alexa. I setup the new player's room name as "Front Room" The problem is the volume does not change for the new play one using this preset.json.

Preset Name "loud.json"
{
      "players": [
                { "roomName": "Office", "volume": 30},
		{ "roomName": "Master Bedroom", "volume": 50},
		{ "roomName": "Ladies Room", "volume": 50},
		**{ "roomName": "Front Room", "volume": 50},**
		{ "roomName": "Master Bathroom", "volume": 50},
		{ "roomName": "Media Room", "volume": 65},
		{ "roomName": "Hall Bathroom", "volume": 40}
      ],
      "pauseOthers": false
}

If I run the above preset all the rooms volumes will adjust except for "Front Room"

Now, oddly. this preset will adjust the volume for "**Front Room**" along with all other rooms.

{
      "players": [
        { "roomName": "Office", "volume": 12},
		{ "roomName": "Master Bedroom", "volume": 30},
		{ "roomName": "Ladies Room", "volume": 30},
		**{ "roomName": "Front Room", "volume": 30},**
		{ "roomName": "Master Bathroom", "volume": 30},
		{ "roomName": "Media Room", "volume": 40},
		{ "roomName": "Hall Bathroom", "volume": 30}
      ],
          "favorite": "Classic Soft Rock",
          "uri": "x-rincon-stream:RINCON_0000000000001500",
	  "playMode": {
	  "repeat": "all",
          "shuffle": true,
	  "crossfade": false
      },
          "pauseOthers": false
}

I can adjust the **Front Room** also using URL command.
http://localhost:5005/front room/volume/50 

Node Sonos Version 1.6.0

**Comment by jishi** [comment]
Can you check what the log says when you invoke the preset that doesn't
work?

Also double check that you don't have leading/trailing or double spaces,
just for sanity.

**Comment by GregRocket** [comment]
I checked for leading/trailing/double spaces and did not find any.

Can you please tell me where the name and location of log file I need to view. Thanks.

**Comment by jishi** [comment]
Depends on how you run it. It is written to the console when you run the
software manually. If you run my pi image it will be in /flash/logs I
think, and f you run it with pm2 you can get log output with the pm2
command (pm2 logs)

**Comment by GregRocket** [comment]
OK I figured it out. I copied the json to the wrong directory. I can't believe I did that. Sorry for bothering you but thank you for your fast response.
