### ISSUE TITLE
Installation Question

### ISSUE THREAD

**Issue by mikimikeCH** [jishi/node-sonos-http-api#59]
Hi

I hade server.js running fine on my raspberry pi 2. After about one day it stopt and i couldn't run it again. 

I thougt it would be best to install everything new. So i reinstalled the raspbian noob pack.

After installation of node / npm i installed node server.js again.

This time it wouldn't run at all. (no settings found)

What do i need for a stable run?

Can someone tell me all the tasks i have to do?

What is the recommended node version? link?

I hope you can help me.

Greetings from Switzerland

**Comment by jishi** [comment]
I have some reports where they experience the same issues that you are describing. My suggestion would be the following:

Install minibian (unless you need a graphical interface)
https://minibianpi.wordpress.com/

Install a precompiled version of node.js (0.12.2)
http://conoroneill.net/node-v0122-for-arm-v6v7-including-raspberry-pi-raspberry-pi-2-and-odroid-c1

Just unzip it to /usr/local/bin or add the bin-path to your $PATH env.

Let me know if that works. I haven't received any thorough error report regarding this, it might be related to NOOBS, the pi2 or some other wonkiness with the network interface. It would be good to get a report back how this would pan out for you. 

The "No settings found" message is just informative. It just tells that you don't have any configuration overrides, and is fine. However, it doesn't seem to find your system using the SSDP discovery part. Are you running your pi2 wired or using a wireless interface?

**Comment by mikimikeCH** [comment]
Thank you for your fast answer.
I reinstalled a clean raspbian image because i like the graphical interface.

I also managed to installed the precomiled version of node.js you have linked me. But when i tried to run it i hade some errors because of missing libs etc,

after a google search in found a command to install jessie instead of wheezy after the installation (40min) i could finally run your server.js now everthing works fine for the past two days:-)

Connected by LAN cable;-)

Thank you so much:-)

**Comment by jishi** [comment]
Weird that you would get a library issue with the precompiled version. To my understanding, node.js has very few external dependencies. I have installed that precompiled version on several different linux distributions including minibian, raspbian, mintlinux and also openelec.

Either way, I'm closing this since you seemed to have resolved your issue.
