### ISSUE TITLE
Test needed

### ISSUE THREAD

**Issue by lsegalla** [jishi/node-sonos-http-api#600]
Hi, first time for me here with github, node.js and sonos.
I installed everything on a raspberry pi and I'm trying to control my sonos systems with it.
I got lots of errors but until now I was able to fix everything.

Now I'm accessing the console of node.js and I get no errors but when I try to use some command (for example: http://localhost:5005/room/pauseall or other similar commands I get no answer and the sonos doesn't seem to receive any command

I'd like to test to see if something is working, as I get no errors.
Any advice?

**Comment by joohann** [comment]
Problem with RP is the version of node is a old version. 
Did you do a version check? (I have 9.6.1 running)
#node -v

1. Clear NPM's cache:
#sudo npm cache clean -f
2. Install a little helper called 'n'
#sudo npm install -g n
3. Install latest stable Node.js version
#sudo n stable

**Comment by jishi** [comment]
This sounds more like traffic is blocked. After you've started the API, invoke this command on the rpi: 

`netstat -ntpl`

Which would list all listening ports and how it's bound to the interfaces. Also might be good to do an:

`iptables -L`

And check if your installation has iptables enabled by default.

**Comment by jishi** [comment]
No more feedback.
