### ISSUE TITLE
Feature request: /<zone>/<1st command>/volume/XX

### ISSUE THREAD

**Issue by evertide** [jishi/node-sonos-http-api#602]
Hi,

Really like the API and use it in a home automation environment for e.g. if people walk into the house playing their favorite radio station via tunein.

The feature request is to add a second command e.g. volume in the same http API call as the first one.

This prevents two API calls for one setting the volume right and two selecting the radio station or maybe even only a different volume for the say command.

regards

**Comment by jishi** [comment]
Why is two API calls a problem? It doesn't make sense to me to make the requests more complex only for the reason that you don't want to send two requests. If you want to combine multiple actions into one call, you always have the preset system to deal with most scenarios, wouldn't that be applicable here?

However, the `say` command already have an optional volume parameter, because it's an announce and you actually want a temporary volume change for it.

**Comment by evertide** [comment]
Hi, a Valid point on the complex part. 
From my point since I use the api call in home automation software ( Domoticz) I can only push one command when a home automation switch is operated. So I can either have the home automation software run a script in which I can execute commands or I can do a single http request but lack a constant start volume. My prefers would be the http call because else I have to have a script for every radio station.

**Comment by jishi** [comment]
If a preset isn't sufficient for your need (you can even construct presets on the fly if you want to, but it isn't very well documented), then you can always construct your own custom actions too.

For a dynamic preset, just do:
`/preset/{"players":[{"roomName":"room1","volume": 15}],"favorite":"my favorite name"}`

(You might need to entity encode it correctly): 
`/preset/%7B%22players%22%3A%5B%7B%22roomName%22%3A%22room1%22%2C%22volume%22%3A%2015%7D%5D%2C%22favorite%22%3A%22my%20favorite%20name%22%7D`

However, presets doesn't support music services shortcuts (like tunein stations), but only favorites and playlists (and raw URIs, but that doesn't work with tunein)

If you want to make a custom action, you can basically copy (with any filename, but in the same folder) https://github.com/jishi/node-sonos-http-api/blob/master/lib/actions/tunein.js and change the following:

```
  if (action == 'play') {
    return player.coordinator.setAVTransport(uri, metadata)
      .then(() => player.coordinator.play());
  }
```

to

```
  if (action == 'play') {
    return player.coordinator.setAVTransport(uri, metadata)
      .then(() => player.coordinator.play())
      .then(() => player.setVolume(values[2]));
  }
```

And also register it under a new name: 
```
// api.registerAction('tunein', tuneIn);
api.registerAction('custom_tunein', tuneIn);
```

Then you can call this with `/room/custom_tunein/[station_id]/[volume]`

If I introduced a POST call that could take an arbitrary large payload, it would be much easier to combine multiple calls in a good manner. That could probably work as well, and would be much cleaner. However, some actions wouldn't be compatible to run together, which would be hard to document.

**Comment by jishi** [comment]
Closing since this is doable with dynamic presets.
