### ISSUE TITLE
Detect zone randomly

### ISSUE THREAD

**Issue by Khengsoon** [jishi/node-sonos-http-api#603]
## Before you submit an issue

Search among the current open _and_ closed issues for an answer to your question before submitting an issue! 

If you are looking for assistance with installing or just general questions, reach out on the gitter chat (https://gitter.im/node-sonos-http-api/Lobby) instead of filing an issue. It's easier for me if issues are primarily fokused on bugs and feature requests, and hopefully other people can assist you in the chat. 

If your question is Docker related, please file the issue at the https://github.com/chrisns/docker-node-sonos-http-api and also, make sure you have tested that image before asking a question. This is the only image that has any correlation to this project, and is guaranteed to be up to date.

If your question has anything to do with Amazon Echo, it is probably better suited at https://github.com/rgraciano/echo-sonos. If you have questions about the requests sent to this library, figure out the exact request that is sent from the Alexa Skill (through the logs) and include that in the issue.

Thank you!

**Comment by Khengsoon** [comment]
Hi Jishi,

I have 4 Sonos play1, I named them a,b,c, and d. I noticed some time the API randomly detect the zone from http://192.168.1.81:5005/zones. not all zones show up when I call the URL. May I know is this a bug? or I did something wrong?


Best Regards,
Kheng Soon

**Comment by jishi** [comment]
Shouldn't occur, do you see the same behavior in the official controller? The discover pattern for this API and the official controller is the same, it subscribes to topology changes from the first player it finds and will use the same information to know about which players you have and how they are grouped. Do you power cycle the players often or do you have a lot of wireless interference where you live?

I order to give you a better answer you probably need to enable more logging and send me the excerpt of the log from the time of observation of this problem.

**Comment by Khengsoon** [comment]
Hi Jimmy,

May I know the official controller you mean Sonos official apps?

Now my Sonos apps have 2 speaker and another 2 speaker is not inside. maybe
later I do another round of pairing I inform you again.

Thanks for your prompt reply.

Best Regards,
Kheng Soon

**Comment by jishi** [comment]
Yes, I meant the official Sonos controller (on computer or phone). If the app only shows you either two players, sounds like you have setup a split system unintentionally. Just re-add the missing players to the currently visible players and you should be fine :)

**Comment by Khengsoon** [comment]
Hi Jimmy,

Okay noted with thanks.

I update you once everything is fine

Best Regards
Kheng Soon

**Comment by Khengsoon** [comment]
Hi Jimmy,

After I added 4 speakers into my Sonos apps all works fine now. 

Thank you very much
Kheng Soon
