### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by jompa68** [jishi/node-sonos-http-api#608]
When trying from browser i get this error and no TTS is working.

{"status":"error","error":"Download from google TTS failed with status 404, undefined","stack":"Error: Download from google TTS failed with status 404, undefined\n    at ClientRequest.callback (/flash/apps/sonos-http-api/lib/tts-providers/default/google.js:40:16)\n    at ClientRequest.g (events.js:260:16)\n    at emitOne (events.js:77:13)\n    at ClientRequest.emit (events.js:169:7)\n    at HTTPParser.parserOnIncomingClient (_http_client.js:433:21)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)\n    at Socket.socketOnData (_http_client.js:322:20)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:153:18)\n    at Socket.Readable.push (_stream_readable.js:111:10)\n    at TCP.onread (net.js:536:20)"}

**Comment by jompa68** [comment]
Found the problem. Earlier i did use "Astrid" for swedish TTS but seems to be changed to "sv-se"

**Comment by jishi** [comment]
I think Astrid is for Amazon Polly, you seem to be using the default Google
provider (because lack of config in settings.json)

**Comment by jompa68** [comment]
Yes it is Amazon, i forget that it was that. Did setup a new rPi and forgotten to add settings.json with my aws settings.
I have done that now but it will not encode the string correct. Says a lot of %20%20 and so on. What can that be? I got it to work in my first rPi but cannot find out what i have miss.

**Comment by jishi** [comment]
Delete it and try again

**Comment by jompa68** [comment]
Yes, that did the trick.  Deleted and reboot and all working like i want . Thanks for your help @jishi
