### ISSUE TITLE
Issues with calling multiple HTTP requests

### ISSUE THREAD

**Issue by maddox** [jishi/node-sonos-http-api#610]
Heya, I have a project I'm about to release on GitHub that utilizes the Sonos HTTP API.

It queues music for users and conditionally sets `random` and `shuffle` based on their settings.

The problem is, when queuing the music, I need to do all of this. Set the shuffle state, set the repeat state, clear the queue, queue the music, and then play the queue. I understand that everything is async, so even though I get a response from Sonos HTTP API, that doesn't mean the request is complete on the Sonos system. 

Because of this, I'm having issues clearing the queue, queueing a list with a provider endpoint (`applemusic/next/album:1240361817`), and playing it. Sometimes it will not play. I'm pretty sure at this point it's because when the play endpoint is called, the queue hasn't actually populated yet, so playback never happens.

Is there a good strategy to avoid this at all?

**Comment by jishi** [comment]
All HTTP actions should wait until finished, meaning chaining them should be possible. I would need a reproducible example to troubleshoot this.

I'm pretty sure that adding to a queue actually does wait on the request to Sonos, even when it takes a long time. It might take too long though, and actually return an error.

**Comment by maddox** [comment]
> It might take too long though, and actually return an error

I think I'm seeing this sometimes.

[Here's the actual code](https://github.com/maddox/magic-cards/blob/master/scanner/actions/SonosAction.js#L7) on the project I'm using it with. You can see that right now I'm actually commenting everything out and just setting the repeat setting and processing the query for queuing.

`this.card.uri` in this code would be `/applemusic/now/album:1240361817` eventually resolving to something like `/Office/applemusic/now/album:1240361817`.

I'd prefer to be using `/next/` instead of `/now/` so I can clear the queue, queue the item, and manually `play`. The goal is to have the only thing in the queue, be the thing I'm queueing.

**Comment by maddox** [comment]
OK, it looks like my implementation was terrible, lol. I got things working better and they're working serially.

But, like I've seen in the past, I'm having issues making requests to set `shuffle` and `repeat` modes. If I do one or the other, the results are correct. If I try to set both serially, I get weird results. Sometimes their states are set, and sometimes they aren't ¯\(°_o)/¯.

Is there something known about this?

**Comment by maddox** [comment]
OK, playing with a little more, if I changed the order, I got better results:

```js
    const request = async () => {
      await this.clearQueue()
      await this.setShuffle(contentConfig.shuffle)
      await this.request(this.card.uri)
      await this.setRepeat(contentConfig.repeat)
    }

    request()
```

Setting `repeat` after the queue was created, helped. Maybe it was the fact that an action happened between the request for `shuffle` and `repeat`. 

Hopefully all of this babbling by me in this issue can help someone else in the future, heh.
