### ISSUE TITLE
Enhancement (not sure if possible with native sonos api's): Ability to have output be a 'mix' of line in and one other music service

### ISSUE THREAD

**Issue by jzajac2** [jishi/node-sonos-http-api#612]
Enhancement (not sure if possible with native sonos api's): Ability to have output be a 'mix' of line in and one other music service.
This might sound like a ridiculous request, and maybe it is and you can educate me. Use case: As a heavy sonos user who uses spotify, amazon, apple, etc services I would also like output from a line in (such as my computer) to be added to output/mix. For example, so I can listen to music but also hear any alerts coming from my computer (email, chat, etc)

**Comment by jishi** [comment]
No, this won't be possible. If you are running Windows, you could do https://github.com/jishi/Jishi.StreamToSonos which works somewhat. I never spent much time trying to make it 100% robust though. It just streams your system audio from your computer.
