### ISSUE TITLE
Endpoint for setting play mode?

### ISSUE THREAD

**Issue by maddox** [jishi/node-sonos-http-api#613]
When a player is set to play from a radio station and you add to the queue, it can't play that queue until it's play mode is set to use the queue again. 

Is there an endpoint to tell the player to use the queue so we can do this remotely?

**Comment by jishi** [comment]
There is no pre-made endpoint for it, but you can use the setavtransporturi action to do the same thing (albeit undocumented):

`/RoomName/setavtransporturi/x-rincon-queue:UUID_OF_PLAYER:#0`

Would make sense to add a shortcut to it. Not sure if a `/trackseek/1` would restore queue playback as well, implicitly.

**Comment by maddox** [comment]
Oof, thanks. I don't actually have the UUID of the player, just the name. But I guess I could do a quick fetch of it before doing this command. 

Yeah, something built in would be super helpful.

Thanks!

**Comment by maddox** [comment]
OK, after a ton of testing I figured it out. I hadn't encoded the `#` and there's no `:` in front of it, and `SetAVTransportURI` needs to be capitalized.

`/Kitchen/SetAVTransportURI/x-rincon-queue:RINCON_7828CA11EB1001400%230 `

:boom:

**Comment by throweggs** [comment]
Im having a similar issue, how did you guys find the UUID of a player? 

thanks for you help

**Comment by jishi** [comment]
Uuid is listed in the /zones call.

**Comment by throweggs** [comment]
O! d'oh, thanks so much!
