### ISSUE TITLE
Cannot request state after reset Sonos

### ISSUE THREAD

**Issue by ToHo14** [jishi/node-sonos-http-api#615]
I have a Sonos Connect named "Wohnzimmer" (and a few other Sonos devices). I used node-sonos-http-api for the last months with the Sonos Connect and it worked pretty well. Now I reseted my Sonos Connect and also chaned the name to "Garten". After that I'm not able to get the Connect working again in the API:

http://10.10.3.53:5005/wohnzimmer/play
http://10.10.3.53:5005/wohnzimmer/pause
etc. works well. But with the old name!

http://10.10.3.53:5005/wohnzimmer/state does return the state before resetting the Sonos Connect

http://10.10.3.53:5005/garten/play
http://10.10.3.53:5005/garten/pause
http://10.10.3.53:5005/garten/state
etc. All returns an error.

Is this a bug or has it to be reseted somehow?

**Comment by jishi** [comment]
I would have guessed that it would update the name. What version are you running? More robust topology discovery was introduced in one of the later versions. But you can always just restart the http-api and it would discover the system correctly with the new name, I suppose.

**Comment by ToHo14** [comment]
Thanks for the reply. I have the latest version. A restart doesn't solve the problem, but a restart without having the Sonos Connect turned on (no power) and then turn it on later resolved the problem. At least I guess that was the solution.
