### ISSUE TITLE
Encoding issue in 'state' response

### ISSUE THREAD

**Issue by whvanderpost** [jishi/node-sonos-http-api#616]
Hi,

I'm consuming the API from software that is used to create touchscreen visualizations ([iRidium](https://www.iridiummobile.net/)), and it mostly works like a charm!
The only thing I'm having trouble with is when any of the fields in the /state response contain accented characters. The visualization software has the option to work with JavaScript "behind the scenes", so you can talk to an api from JS, parse the results in JS and finally write values to textboxes for example. I use JSON.parse to parse the object returned by /state.
If I view the /state response in Chrome, I get (snippet):
```
{
  "artist":"Veul Gère",
  "album":"11 Jaor Blèère Meej Veul Gère!",
}
```
After I parse this response in JS I get:
```
{
  "artist":"Veul GÃ¨re", 
  "album":"11 Jaor BlÃ¨Ã¨re Meej Veul GÃ¨re!"
}
```
As you can see all accented characters have a problem.
Do you explicitly specify the encoding used in the response? I've used the developer tools in Chrome to check the response, but it looks like there are no headers defined.... can you help me with this?

**Comment by jishi** [comment]
It's supposed to send a Content-Type header, see https://github.com/jishi/node-sonos-http-api/blob/master/lib/sonos-http-api.js#L88

JSON is according to the standard utf-8, and that is what I'm sending. What you seem to be seeing is utf-8 that has been decoded using latin1 (ISO-8859-1) hence the weird dual characters. It seems like iRidium isn't obeying the Content-Type header, or you need to explicitly state how it should decode the body.

**Comment by whvanderpost** [comment]
I'm in conclave with the people of iRidium about this issue, they claim that the servers (I've created a simple C# console application that returns a simplified JSON object as an UTF-8 string) don't return UTF-8 strings.

**Comment by whvanderpost** [comment]
I'm in conclave with the people of iRidium about this issue, they claim that the servers (I've created a simple C# console application that returns a simplified JSON object as an UTF-8 string) don't return UTF-8 strings.

Accidentally closed the issue. Don't know if it's useful to keep it open tough.. I'll let you decide.

**Comment by andyfitter** [comment]
I've been having problems consuming the webhook feed in Java on Android if it contains accented characters. It appears to be down to the Content type not including a charset field. I realise it ought to default to UTF-8, but it doesn't appear to. Would it be possible to change the header to the standard "Content-type: application/json; charset=utf-8" to try to brute force notify the server of the correct charset?
