### ISSUE TITLE
URL encoding problems with /say

### ISSUE THREAD

**Issue by zeedjej** [jishi/node-sonos-http-api#617]
The TTS reads the actual percentage encoding string when using /say
With /sayall everything works fine.

example:

http://192.168.0.128:5005/bedroom/say/Hello how are you/en/60 makes the speaker say Hello%20how%20are%20you

If I use /sayall the sentence is read correctly even if I use %20 in the URL

**Comment by jishi** [comment]
I assume you are using the pre-made image? Either way, check to see if you have a `say_v2.js` file in the `lib/actions` folder and delete it, then restart it. It's some remnant from a test commit that doesn't get cleared out from the image.

**Comment by zeedjej** [comment]
Thats correct. Removing the file solved the problem. Thanks a lot!
