### ISSUE TITLE
TTS failed

### ISSUE THREAD

**Issue by miwa4711** [jishi/node-sonos-http-api#618]
Hi, need your help.

Tried to setup TTS via http://www.voicerss.org as decribed. 
Got API key, works fine with 

Created settings.json with my key but got following error message

http://api.voicerss.org/?key=xxxxxxxxxxxx&f=22khz_16bit_mono&hl=en-gb&src=This%20is%20a%20test
![screenshot](https://user-images.githubusercontent.com/35166466/40934757-234b4a96-6836-11e8-9722-c4a3c7465917.JPG)
![screenshot_dir](https://user-images.githubusercontent.com/35166466/40934758-2374d096-6836-11e8-9b5a-e178d0c078ba.JPG)

Thanks in advance.

Regards 
Michael

**Comment by jishi** [comment]
How are you running it? Sounds like permission errors in file system. The TTS tries to write a cached version of the audio file into `/home/pi/node-sonos-http-api/static/tts` so that folder needs to have write permissions for the user that the http-api is running as, or use 777.

**Comment by miwa4711** [comment]
Hi, you were right. Permissions changed, TTS works fine.
Thanks.
