### ISSUE TITLE
Say command not working

### ISSUE THREAD

**Issue by daromotica** [jishi/node-sonos-http-api#62]
Hello Jishi, Thank you for the hard work on the node js http api.
I use it with openhab for my home automation because the standard songs binding is giving me less functionality so really great ! 

But i am facing the problem that the say functionality is not working because each time i get prompted for a captcha when i am going to the translate.google.com site.

This because of the many requests my home automation server does to the website.

do you know a workaround for this issue ?

Thank you for the hard work sofar !!!
roy hofman
royhofman1989@gmail.com

**Comment by jishi** [comment]
Hi. I'm not sure the exactly which limits the translate service has, or if your captcha has been activated for your IP semi-permantently because of your frequency of requests.

They do have a paid plan, and by creating a public API key for your account, one could integrate their REST-service for translating instead. This is however a major rewrite, and creating the keys are far from user friendly. They also seem to require you to sign up for billing through their developer console, and the charge is $20 for 1M characters (linear charging, so 500 000 characters will bill you $10), and it is charged monthly.  

What kind of messages are you using for TTS? I recall that I actually cache identical phrases indefinitely, but maybe you are creating different phrases for each TTS?

**Comment by daromotica** [comment]
Thanks for your fast reply,

In total i use about 3 phrases, and they are processed for about 14 times a week.
So that should not be the deal i think.For me it is not a problem to pay for this service because i really like my smart home to speak to me about certain things.

When i buy a public api key, is it easy to implement this in the node js script ? for example add an HTTP Get parameter to the existing translate link ?

Thank you

Roy

**Comment by jishi** [comment]
No, sorry. The paid version uses a completely different API so it needs to be rewritten to support it. 

I'm receiving a captcha as well now, so maybe they have changed something on their end, and the new API is required. The google integration was more a hijack of their translating system, and was probably never meant to be used like this. Perhaps one could look at other alternatives, http://www.voicerss.org/ being one.

**Comment by linde** [comment]
this diff fixes it for me:

-  var tts_request = 'http://translate.google.com/translate_tts?ie=UTF-8&q=' + phrase + '&tl=' + languag
+  // var tts_request = 'http://translate.google.com/translate_tts?ie=UTF-8&q=' + phrase + '&tl=' + lang
+
+  var tts_request = 'http://www.voicerss.org/controls/speech.ashx?hl=en-us&c=mp3&src=' + phrase;
+

**Comment by linde** [comment]
this one might be better, it is meant to be a free service:

  var tts_request = 'http://tts-api.com/tts.mp3?q=' + phrase;

**Comment by jishi** [comment]
I looked into tts-api as well, but it is terribly slow, and the voice is very unnatural. I also think it is good to have a paid option to ensure the quality of the service. It also has support for multiple languages (see Languages section here http://www.voicerss.org/api/documentation.aspx)

**Comment by daromotica** [comment]
I think it is great, i am willing to pay to ensure quality of this service :+1:

**Comment by tekkkon** [comment]
some feedback
1. you need to get a api key with voicerss.org and follow the http required parameters
2. try 16khz and 16 bit for the audio format

here is what works for me
var tts_request = 'http://api.voicerss.org/?key=YOUR_API_KEY_HERE&hl=en-us&c=mp3&f=16khz_16bit_mono&src=' + phrase;

**Comment by jishi** [comment]
I got a contribution with a home-made api that is merged for now. Will implement voicerss in the near future and replace it.

**Comment by TheHavocHero** [comment]
I got the var tts_request = 'http://api.voicerss.org/?key=YOUR_API_KEY_HERE&hl=en-us&c=mp3&f=16khz_16bit_mono&src=' + phrase; to work, but cannot figure out how to get the volume louder when the TTS speaks. In the say.js file, var announceVolume does not seem to do anything.
