### ISSUE TITLE
Special Characters

### ISSUE THREAD

**Issue by turnepf** [jishi/node-sonos-http-api#621]
I have a few presets that are exactly alike except for special characters in the favorite name. When the favorite has a "é" in the name I get an error. For example, one of the favorites is: 

_Café con Leche_

The URL still works fine, but the error is disconcerting. Any ideas?

Note, if I use the playlist directly thru the URL like so:

http://192.168.7.209:5005/living%20room/favorite/Café%20con%20Leche

...it works fine. 

Thanks in advance for any suggestions!

**Comment by jishi** [comment]
Where are you invoking it from when it doesn't work? Character encoding comes into play when you use those characters in a URL, you can circumvent that by using an url-encoded url that encodes it according to utf-8, so `Caf%C3%A9%20con%20Leche` should work (é would be %C3%A9 according to utf-8 encoding). That way you don't depend on the character encoding that the invoking system uses, but enforces utf-8.

**Comment by jishi** [comment]
Find it odd that it would work but throw an error though, if it doesn't match the string, it shouldn't fint the favorite? What is the error?

**Comment by turnepf** [comment]
Sorry, I missed your responses. I think it may have been a red herring. I did change the json file names to not use special characters and still use them in the playlist names and they work. I actually just think my json wasn't formed well. For whatever reason I'm back in business. Thanks for the response!
