### ISSUE TITLE
error: 'action \'tts\' not found'

### ISSUE THREAD

**Issue by egs2003** [jishi/node-sonos-http-api#622]
If I start api, I got the following error

2018-06-24T13:32:48.515Z ERROR
  { error: 'action \'tts\' not found' }

**Comment by jishi** [comment]
There is no action called tts, this message should popup whenever you try to invoke it, right? The commands are named say, sayall, saypreset

**Comment by egs2003** [comment]
I got it all time

Jimmy Shimizu <notifications@github.com> schrieb am Mo., 25. Juni 2018,
13:11:
