### ISSUE TITLE
error - failed: Address family not supported by protocol.

### ISSUE THREAD

**Issue by themessings** [jishi/node-sonos-http-api#63]
After installing node I was able to run the server.js file but have yet to successfully test the system.  Each time I try to run a test I get the connection error below

pi@raspberrypi ~ $ wget http://localhost:5005/resumeall
--2015-07-29 03:04:03--  http://localhost:5005/resumeall
Resolving localhost (localhost)... 127.0.0.1, ::1
Connecting to localhost (localhost)|127.0.0.1|:5005... failed: Connection refused.
Connecting to localhost (localhost)|::1|:5005... failed: Address family not supported by protocol.

any thoughts?

**Comment by jishi** [comment]
That doesn't seem like a problem associated with the node-package. The "Address family" is just when it tries to connect using ipv6 which seems to be incorrectly configured on your machine.

What you are getting over ipv4, is "connection refused" which seems like the api is not running at all. How do you start it? Could you invoke 

netstat -ntpl 

after you have started it?

**Comment by themessings** [comment]
Thanks for your quick response,  Here is what I get when I run netstat -ntpl

pi@raspberrypi ~ $ node server.js
no settings file found, will only use default settings
http server listening on port 5005
module.js:489
    throw err;
          ^
SyntaxError: /home/pi/presets.json: Unexpected token ]
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:486:27)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /home/pi/lib/actions/preset.js:23:17
    at FSReqWrap.cb [as oncomplete] (fs.js:226:19)
pi@raspberrypi ~ $ netstat -ntpl
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -               
pi@raspberrypi ~ $

**Comment by jishi** [comment]
Well, you have an error in your presets.json. Run the content through an
online json validator or formatter and it will probably tell you where the
error is.

**Comment by themessings** [comment]
Just checked the preset file and it looks to be valid.  Any ideas?


VALID

Formatted JSON Data
{
   "test":{
      "players":[
         {
            "roomName":"Master Bedroom",
            "volume":30
         }
      ],
      "state":"PLAYING",
      "favorite":"Rock",
      "uri":"x-rincon-stream:RINCON_0000000000001500",
      "playMode":"SHUFFLE",
      "pauseOthers":true
   },
   "rap":{
      "players":[
         {
            "roomName":"Dining Room",
            "volume":30
         },
         {
            "roomName":"Living Room",
            "volume":30
         },
         {
            "roomName":"Master Bedroom",
            "volume":30
         },
         {
            "roomName":"Kitchen5",
            "volume":40
         },
         {
            "roomName":"KitchenWall",
            "volume":50
         }
      ],
      "state":"PLAYING",
      "favorite":"Rap",
      "uri":"x-rincon-stream:RINCON_0000000000001500",
      "playMode":"SHUFFLE",
      "pauseOthers":true
   },
   "pop rap":{
      "players":[
         {
            "roomName":"Dining Room",
            "volume":30
         },
         {
            "roomName":"Living Room",
            "volume":30
         },
         {
            "roomName":"Master Bedroom",
            "volume":30
         },
         {
            "roomName":"Kitchen5",
            "volume":40
         },
         {
            "roomName":"KitchenWall",
            "volume":50
         }
      ],
      "state":"PLAYING",
      "favorite":"Rap (Pop)",
      "uri":"x-rincon-stream:RINCON_0000000000001500",
      "playMode":"SHUFFLE",
      "pauseOthers":true
   },
   "rock":{
      "players":[
         {
            "roomName":"Dining Room",
            "volume":30
         },
         {
            "roomName":"Living Room",
            "volume":30
         },
         {
            "roomName":"Kitchen5",
            "volume":40
         },
         {
            "roomName":"Master Bedroom",
            "volume":30
         },
         {
            "roomName":"KitchenWall",
            "volume":50
         }
      ],
      "state":"PLAYING",
      "favorite":"Rock",
      "uri":"x-rincon-stream:RINCON_0000000000001500",
      "playMode":"SHUFFLE",
      "pauseOthers":true
   }
}

**Comment by themessings** [comment]
OK - I lied.  My presets were jacked up.  When I copied over to test them I
copied the original which was of course valid.  The new file is fixed and
valid but when I test the command it locks up.

pi@raspberrypi ~ $ wget http://yourserverip:5005/zones
--2015-08-01 17:50:07--  http://yourserverip:5005/zones
Resolving yourserverip (yourserverip)... 198.105.254.228, 198.105.244.228
Connecting to yourserverip (yourserverip)|198.105.254.228|:5005...

Hangs there until a disconnect.

**Comment by jishi** [comment]
You are connecting to a public IP. I don't think your raspberry pi is using
that IP? Try with local host to start with. If you need to connect to your
external IP, you must make sure that you have forwarded it in your router,
but I guess that you don't want that.

**Comment by themessings** [comment]
Still seems to be getting the same error if I use "localhost"

Connecting to 192.168.0.36 port 22, please wait...
login as:
pi@192.168.0.36's password:
Linux raspberrypi 3.18.11-v7+ #781 SMP PREEMPT Tue Apr 21 18:07:59 BST
2015 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sat Aug  1 17:52:39 2015 from 192.168.0.21

pi@raspberrypi ~ $ wget http://localhost:5005/zones
--2015-08-01 18:49:06--  http://localhost:5005/zones
Resolving localhost (localhost)... 127.0.0.1, ::1
Connecting to localhost (localhost)|127.0.0.1|:5005... failed:
Connection refused.
Connecting to localhost (localhost)|::1|:5005... failed: Address
family not supported by protocol.
pi@raspberrypi ~ $

On Aug 1, 2015 1:55 PM, "Jimmy Shimizu" <notifications@github.com> wrote:
>
> You are connecting to a public IP. I don't think your raspberry pi is
using
> that IP? Try with local host to start with. If you need to connect to your
> external IP, you must make sure that you have forwarded it in your router,
> but I guess that you don't want that.
>
> On Aug 1, 2015 7:52 PM, "themessings" <notifications@github.com> wrote:
>
> > OK - I lied. My presets were jacked up. When I copied over to test them
I
> > copied the original which was of course valid. The new file is fixed and
> > valid but when I test the command it locks up.
> >
> > pi@raspberrypi ~ $ wget http://yourserverip:5005/zones
> > --2015-08-01 17:50:07-- http://yourserverip:5005/zones
> > Resolving yourserverip (yourserverip)... 198.105.254.228,
198.105.244.228
> > Connecting to yourserverip (yourserverip)|198.105.254.228|:5005...
> >
> > Hangs there until a disconnect.
> >
> >
> > On Sat, Aug 1, 2015 at 1:34 PM, Joel Messing <themessings@gmail.com>
> > wrote:
> >
> > > Just checked the preset file and it looks to be valid. Any ideas?
> > >
> > >
> > > VALID
> > >
> > > Formatted JSON Data
> > > {
> > > "test":{
> > > "players":[
> > > {
> > > "roomName":"Master Bedroom",
> > > "volume":30
> > > }
> > > ],
> > > "state":"PLAYING",
> > > "favorite":"Rock",
> > > "uri":"x-rincon-stream:RINCON_0000000000001500",
> > > "playMode":"SHUFFLE",
> > > "pauseOthers":true
> > > },
> > > "rap":{
> > > "players":[
> > > {
> > > "roomName":"Dining Room",
> > > "volume":30
> > > },
> > > {
> > > "roomName":"Living Room",
> > > "volume":30
> > > },
> > > {
> > > "roomName":"Master Bedroom",
> > > "volume":30
> > > },
> > > {
> > > "roomName":"Kitchen5",
> > > "volume":40
> > > },
> > > {
> > > "roomName":"KitchenWall",
> > > "volume":50
> > > }
> > > ],
> > > "state":"PLAYING",
> > > "favorite":"Rap",
> > > "uri":"x-rincon-stream:RINCON_0000000000001500",
> > > "playMode":"SHUFFLE",
> > > "pauseOthers":true
> > > },
> > > "pop rap":{
> > > "players":[
> > > {
> > > "roomName":"Dining Room",
> > > "volume":30
> > > },
> > > {
> > > "roomName":"Living Room",
> > > "volume":30
> > > },
> > > {
> > > "roomName":"Master Bedroom",
> > > "volume":30
> > > },
> > > {
> > > "roomName":"Kitchen5",
> > > "volume":40
> > > },
> > > {
> > > "roomName":"KitchenWall",
> > > "volume":50
> > > }
> > > ],
> > > "state":"PLAYING",
> > > "favorite":"Rap (Pop)",
> > > "uri":"x-rincon-stream:RINCON_0000000000001500",
> > > "playMode":"SHUFFLE",
> > > "pauseOthers":true
> > > },
> > > "rock":{
> > > "players":[
> > > {
> > > "roomName":"Dining Room",
> > > "volume":30
> > > },
> > > {
> > > "roomName":"Living Room",
> > > "volume":30
> > > },
> > > {
> > > "roomName":"Kitchen5",
> > > "volume":40
> > > },
> > > {
> > > "roomName":"Master Bedroom",
> > > "volume":30
> > > },
> > > {
> > > "roomName":"KitchenWall",
> > > "volume":50
> > > }
> > > ],
> > > "state":"PLAYING",
> > > "favorite":"Rock",
> > > "uri":"x-rincon-stream:RINCON_0000000000001500",
> > > "playMode":"SHUFFLE",
> > > "pauseOthers":true
> > > }
> > > }
> > >
> > > On Sat, Aug 1, 2015 at 9:59 AM, Jimmy Shimizu <
notifications@github.com>
> > > wrote:
> > >
> > >> Well, you have an error in your presets.json. Run the content
through an
> > >> online json validator or formatter and it will probably tell you
where
> > the
> > >> error is.
> > >> On Aug 1, 2015 15:19, "themessings" <notifications@github.com> wrote:
> > >>
> > >> > Thanks for your quick response, Here is what I get when I run
netstat
> > >> -ntpl
> > >> >
> > >> > pi@raspberrypi ~ $ node server.js
> > >> > no settings file found, will only use default settings
> > >> > http server listening on port 5005
> > >> > module.js:489
> > >> > throw err;
> > >> > ^
> > >> > SyntaxError: /home/pi/presets.json: Unexpected token ]
> > >> > at Object.parse (native)
> > >> > at Object.Module._extensions..json (module.js:486:27)
> > >> > at Module.load (module.js:355:32)
> > >> > at Function.Module._load (module.js:310:12)
> > >> > at Module.require (module.js:365:17)
> > >> > at require (module.js:384:17)
> > >> > at /home/pi/lib/actions/preset.js:23:17
> > >> > at FSReqWrap.cb as oncomplete
> > >> > pi@raspberrypi ~ $ netstat -ntpl
> > >> > (Not all processes could be identified, non-owned process info
> > >> > will not be shown, you would have to be root to see it all.)
> > >> > Active Internet connections (only servers)
> > >> > Proto Recv-Q Send-Q Local Address Foreign Address State PID/Program
> > name
> > >> > tcp 0 0 0.0.0.0:445 0.0.0.0:* LISTEN -
> > >> >
> > >> > tcp 0 0 0.0.0.0:139 0.0.0.0:* LISTEN -
> > >> >
> > >> > tcp 0 0 0.0.0.0:22 0.0.0.0:* LISTEN -
> > >> >
> > >> > pi@raspberrypi ~ $
> > >> >
> > >> > —
> > >> > Reply to this email directly or view it on GitHub
> > >> > <
> > >>
> >
https://github.com/jishi/node-sonos-http-api/issues/63#issuecomment-126915196
> > >> >
> > >> > .
> > >>
> > >> >
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <
> >
https://github.com/jishi/node-sonos-http-api/issues/63#issuecomment-126917326
>
> > >
> > >> .
> > >>
> > >
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
https://github.com/jishi/node-sonos-http-api/issues/63#issuecomment-126941978

**Comment by jishi** [comment]
Well, you need to keep it running, and then do a wget. What's the output
when you run node?

**Comment by themessings** [comment]
Tried playing around with it some more but still getting the same error.
"Error: Cannot find module 'sonos-discovery'"


pi@raspberrypi ~ $ node server.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'sonos-discovery'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/pi/server.js:4:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**Comment by jishi** [comment]
You haven't installed the dependencies.

Run "npm install" first.

**Comment by themessings** [comment]
Jimmy,  First I wanted to say thanks for helping me through all of this.  I
am learning my way through these issues and really appreciate the help.

The bad news is that I am still coming up with the same errors.  I am
running  npm version 2.11.2 and node version 0.12.6

Output below. Any thoughts?

pi@raspberrypi ~ $ sudo npm -v
2.11.2
pi@raspberrypi ~ $ node -v
v0.12.6


pi@raspberrypi ~ $ sudo npm install
npm WARN package.json sonos-http-api@0.16.0 No license field.
npm WARN engine require-fu@1.0.0: wanted: {"node":"0.10.x"} (current:
{"node":"0
                       .12.6","npm":"2.11.2"})
require-fu@1.0.0 node_modules/require-fu

async@0.2.10 node_modules/async

node-static@0.7.7 node_modules/node-static
├── mime@1.3.4
├── colors@1.1.2
└── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)

sonos-discovery@0.15.3 node_modules/sonos-discovery
├── easysax@0.1.14
├── html-entities@1.0.10
└── winston@0.8.3 (cycle@1.0.3, stack-trace@0.0.9, isstream@0.1.2,
eyes@0.1.8, c
                         olors@0.6.2, pkginfo@0.3.0)
pi@raspberrypi ~ $ node server.js
no settings file found, will only use default settings
http server listening on port 5005
module.js:489
    throw err;
          ^
SyntaxError: /home/pi/presets.json: Unexpected token ]
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:486:27)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /home/pi/lib/actions/preset.js:23:17
    at FSReqWrap.cb [as oncomplete] (fs.js:226:19)
pi@raspberrypi ~ $ wget http://localhost:5005/kitchen/play
--2015-08-03 22:06:13--  http://localhost:5005/kitchen/play
Resolving localhost (localhost)... 127.0.0.1, ::1
Connecting to localhost (localhost)|127.0.0.1|:5005... failed: Connection
refused.
Connecting to localhost (localhost)|::1|:5005... failed: Address family not
supported by protocol.

**Comment by jishi** [comment]
Well, you still have an invalid presets.json, so you need to try and fix that once more.
