### ISSUE TITLE
since last update it crash

### ISSUE THREAD

**Issue by PointPubMedia** [jishi/node-sonos-http-api#636]
Hi,

Since the last update, when I start it and try to reach the web interface, it crash with that.

/opt/node-sonos-http-api/node_modules/node-static/lib/node-static.js:348
                      mime.lookup(files[0]) ||
                           ^

TypeError: mime.lookup is not a function
    at Server.respond (/opt/node-sonos-http-api/node_modules/node-static/lib/node-static.js:348:28)
    at /opt/node-sonos-http-api/node_modules/node-static/lib/node-static.js:64:22
    at FSReqWrap.oncomplete (fs.js:153:5)

**Comment by jishi** [comment]
Sounds like it installed mime@2.x.x on your machine, where package.json states ^1.4.0 (any minor version).

Did you by chance run something like `npm upgrade` or similar that changed the dependency versions?

**Comment by PointPubMedia** [comment]
yeah you're right...  is it better to just "restore" ? ;)

**Comment by jishi** [comment]
Well, if it isn't compatible with the new versions, it won't work without modifications :), so I'd say stick with the specified versions in package.json unless you want to fix the issues caused by migrating (and send a PR)
