### ISSUE TITLE
Feature request TTS to multiple speakers, not all

### ISSUE THREAD

**Issue by adeighton** [jishi/node-sonos-http-api#637]
This is an awesome utility, thank you.  One feature that would be nice would be to direct TTS announcements to a group of speakers (say, all speakers on first floor) rather than /sayall/ or /[Room]/.  Ideally it would read the current state of the speakers, group the requested ones into a group, play the speech, and then restore the groups as they previously were.

**Comment by jishi** [comment]
This is already supported, you can address a preset for the TTS announce, and the announcement will apply the preset before announcing. Look at `saypreset` action.

**Comment by adeighton** [comment]
Got it, thank you!
