### ISSUE TITLE
Album art url is broken with /state call and SubSonic server

### ISSUE THREAD

**Issue by andyfitter** [jishi/node-sonos-http-api#639]
I'm attempting to call the /state endpoint to retrieve the currently playing track data. In general it works fine from all music sources apart from one. However if the current track is playing from my local SubSonic server the Album art URL returned appears to be invalid. This is an example:

http://192.168.200.200:1400/getaa?s=1&u=x-sonosprog-http%3a3490.mp4%3fsid%3d240%26flags%3d32%26sn%3d23

I've tried both the original version and un-escaping it and they both return a '404'. 

What confuses me is that the official Sonos players and other third party playback apps manage to display the Album art perfectly well.

**Comment by jishi** [comment]
http://192.168.200.200:1400/getaa?s=1&amp;u=x-sonosprog-http%3a3490.mp4%3fsid%3d240%26flags%3d32%26sn%3d23

Does that url work? The Metadata for those tracks looks pretty normal, so I'm drawing a bit of a blank.

**Comment by andyfitter** [comment]
Thanks Jimmy. I’ll take a look in the morning. 

Am I right in thinking that in this case the client (pc/mac/iPhone) is making a request to the Sonos device to retrieve the album art, and this request should just be http/https? In theory, if I could proxy it I could see the requested url made by the client and compare with the url returned by your api? This is what I tried earlier but nothing was visible in the ‘Charles’ proxy. Maybe I need to dig in with wire shark.

**Comment by jishi** [comment]
The requests against your sonos players are unencrypted and on your Lan so
it won't use the global proxy settings. Wireshark would show it though.

**Comment by andyfitter** [comment]
Hi Jimmy. The URL you sent last night fails with a 404 too sadly.

I Wireshark captured the traffic when starting a specific track on Subsonic, played via the Mac native Sonos player, and then also called your API’s whilst playing to see what was returned. The track is ’Theme from Harrys Game’. Here’s the result of your API

{"volume":32,"mute":false,"equalizer":{"bass":0,"treble":0,"loudness":true},"currentTrack":{"artist":"Clannad","title":"Theme From Harry's Game","album":"Past Present","albumArtUri":"/getaa?s=1&u=x-sonos-http%3a1232.mp4%3fsid%3d240%26flags%3d32%26sn%3d23","duration":150,"uri":"x-sonos-http:1232.mp4?sid=240&flags=32&sn=23","trackUri":"x-sonos-http:1232.mp4?sid=240&flags=32&sn=23","type":"track","stationName":"","absoluteAlbumArtUri":"http://192.168.200.204:1400/getaa?s=1&u=x-sonos-http%3a1232.mp4%3fsid%3d240%26flags%3d32%26sn%3d23"},"nextTrack":{"artist":"Clannad","title":"Closer To Your Heart","album":"Past Present","albumArtUri":"/getaa?s=1&u=x-sonos-http%3a1227.mp4%3fsid%3d240%26flags%3d32%26sn%3d23","duration":211,"uri":"x-sonos-http:1227.mp4?sid=240&flags=32&sn=23","trackUri":"x-sonos-http:1227.mp4?sid=240&flags=32&sn=23","absoluteAlbumArtUri":"http://192.168.200.204:1400/getaa?s=1&u=x-sonos-http%3a1227.mp4%3fsid%3d240%26flags%3d32%26sn%3d23"},"trackNo":1,"elapsedTime":30,"elapsedTimeFormatted":"00:00:30","playbackState":"PLAYING","playMode":{"repeat":"none","shuffle":false,"crossfade":false}}

And I’ve attached the Wireshark dump. Hopefully it might be of use. I noticed in amongst the soap data something along the lines of UPNPalbumArtURI. Maybe that is of relevance?
 

Andrew Fitter

**Comment by jishi** [comment]
@andyfitter There is no attachment, could you email it to me? A wireshark dump could be sensitive :) You might wanna filter out only the sonos traffic (port 3400, 3500, 1400)

**Comment by andyfitter** [comment]
Weird - it definitely looks attached from here. Should only contain traffic to port 1400, if you need more I’ll happily do another one. Should be attached this time.

**Comment by jishi** [comment]
Hm, I can only see that you replied via email, but the 1400 requests are only commands to the players. I think the relevant info might be in the events that are sent back to the controller which would be 3500 (on mac, I think, or 3400). 

It would be better to email me directly.

**Comment by andyfitter** [comment]
Cheers Jimmy I’ll investigate further. Didn’t realise the GitHub mails had got mixed with the personal addressed ones. Will be more careful in the future.

Andrew Fitter
andy@fittersystems.com

**Comment by andyfitter** [comment]
Any news on this issue? 

Andy.

**Comment by jishi** [comment]
No, not yet. Currently I'm on vacation so no work is being done on this,
but looking at the dump, it should be fairly easy to fix.

**Comment by andyfitter** [comment]
Cheers Jimmy, that’s great to hear. Have a good holiday.

**Comment by jishi** [comment]
Pushed a change that uses the EnqueuedTransportURIMetadata album art if exists. Not sure if this will work in all cases, and it's hard to know "when" to use it since in your example you already have a track album art (that apparently doesn't work). But I'd assume most sources doesn't populate the Enqueued album art, we'll see how many that starts complaining :)

**Comment by jishi** [comment]
(remember to re-install dependencies since the change is actually in sonos-discovery. Just running `npm install --production`  will be enough)
