### ISSUE TITLE
Playpause command not working anymore

### ISSUE THREAD

**Issue by lrmate** [jishi/node-sonos-http-api#645]
'play' and 'pause' are working correctly.
'playpause' has stopped working somewhere in august

**Comment by badantlerday** [comment]
I just noticed that to. Any info on why? Is it connected to Sonos opening their API?

**Comment by jishi** [comment]
Playpause is the same actions as play and pause, just with an initial state
check to see what state it is in. Then I assume that check is failing for
some reason or the state update.

What does your /state call say about playback status? It should say
'PLAYING' or 'PAUSED'

**Comment by badantlerday** [comment]
hmm. wierd. I've tried it a couple of times and it didn't work. I did some rebooting again and now it works better again. The state is 'STOPPED' thats wierd. I have 3 players grouped. But as I said it works again. :)

**Comment by lrmate** [comment]
Yes, it is STOPPED indeed while playing a radio stream via TuneIn

**Comment by jishi** [comment]
Okay, that seems like something is iffy. I'm on vacation but will check
when I get back.

**Comment by badantlerday** [comment]
This past days I have not had any problems.

'playpause' starts Radio when state is 'STOPPED'.
'playpause' starts queue when state is 'PAUSED_PLAYBACK'

just wanted to let you know. keep up the awesome job!

**Comment by lrmate** [comment]
It's working again over here too!
/State also gives correct "STOPPED" or "PLAYING" state

{..."type":"radio","stationName":"538",...."playbackState":"PLAYING"...}
