### ISSUE TITLE
No command line after running node server.js

### ISSUE THREAD

**Issue by themessings** [jishi/node-sonos-http-api#65]
Should I see a command prompt to test the server after running node server.js?  Seems to just lock up.

pi@raspberrypi ~ $ npm install
npm WARN package.json sonos-http-api@0.16.0 No license field.
pi@raspberrypi ~ $ node server.js
no settings file found, will only use default settings
http server listening on port 5005
loaded presets { test:
   { players: [ [Object] ],
     state: 'PLAYING',
     favorite: 'Rock',
     uri: 'x-rincon-stream:RINCON_0000000000001500',
     playMode: 'SHUFFLE',
     pauseOthers: true },
  rap:
   { players: [ [Object], [Object], [Object], [Object], [Object] ],
     state: 'PLAYING',
     favorite: 'Rap',
     uri: 'x-rincon-stream:RINCON_0000000000001500',
     playMode: 'SHUFFLE',
     pauseOthers: true },
  'pop rap':
   { players: [ [Object], [Object], [Object], [Object], [Object] ],
     state: 'PLAYING',
     favorite: 'Rap (Pop)',
     uri: 'x-rincon-stream:RINCON_0000000000001500',
     playMode: 'SHUFFLE',
     pauseOthers: true },
  rock:
   { players: [ [Object], [Object], [Object], [Object], [Object] ],
     state: 'PLAYING',
     favorite: 'Rock',
     uri: 'x-rincon-stream:RINCON_0000000000001500',
     playMode: 'SHUFFLE',
     pauseOthers: true } }

**Comment by jishi** [comment]
No, no command prompt. This process needs to be running, and then you should be able to test using your browser or similar and invoke the commands. However, it should output some more info when it actually discovered your system, so there might be some issue with the SSDP discovery that take place. 

Please describe how the device (and what device) that you try and invoke this on is connected to your network and what other components are part of it.
