### ISSUE TITLE
How to configure AWS-Polly as TTS?

### ISSUE THREAD

**Issue by masipulami** [jishi/node-sonos-http-api#658]
I tried to follow your guide.

Yesterday I installed homeean with the sonos-api on my raspberry.

I can control my speakers now. That's great.

However I would like to switch TTS service to AWS Polly.

So I tried to follow your instructions.

- Created a folder .aws with file credentials under /home/pi as it was not yet existing and added the following inside:

{
  "aws": {
	"credentials": {
	  "region": "eu-west-1",
	  "accessKeyId": "my accessKeyId",
	  "secretAccessKey": "my secretAccessKey"
	},
	"name": "Vickie"
  }
}

Then I restarted the service using:
sudo systemctl restart sonos-api

But it still uses the same voice as before.

What am I doing wrong? Do I have to adapt some additional configuration somewhere?

Thanks in advance for your feedback.

**Comment by jishi** [comment]
You need to put that content in the settings.json file that should be in
the root folder of sonos http api, the same place as server.js file. If you
don't have one, create it and put thst content in it. If you already have
it, you need to merge thst content so it is part of the settings object.

**Comment by masipulami** [comment]
Thanks.

That's what I've just done:

root@raspberrypi:/# cd opt/node-sonos-http-api
root@raspberrypi:/opt/node-sonos-http-api# vi settings.json

added the following content:

{
"aws": {
"credentials": {
"region": "eu-west-1",
"accessKeyId": "my accessKeyId",
"secretAccessKey": "my secretAccessKey"
},
"name": "Vickie"
}
}

root@raspberrypi:/opt/node-sonos-http-api# sudo systemctl restart sonos-api

Still it does not change to Polly when I open URL:

http://192.168.178.44:5005/k%C3%BCche/say/Die%20Post%20ist%20da/de-de/15

So I have to reboot the Pi?

**Comment by jishi** [comment]
You need to restart the app for the new settings file to be read, not sure how you've setup the systemd script so not sure if your command actually restarts it. 

When the app starts, it's gonna print out the loaded settings object, that's one way to verify that it actually loads what you expect it to load. You will have to verify where stdout ends up when you start it via systemd, I'm not familiar enough with it to answer that. 

Another thing to verify is the actual audio files that are downloaded into /static/tts and see if they start with `polly-`

**Comment by masipulami** [comment]
I've just rebooted.

Now something has changed.

However I get the following error when opening http://192.168.178.44:5005/k%C3%BCche/say/Die%20Post%20ist%20da/de-de/15:

{
status: "error",
error: "1 validation error detected: Value 'de-de' at 'voiceId' failed to satisfy constraint: Member must satisfy enum value set: [Nicole, Enrique, Tatyana, Carmen, Lotte, Russell, Geraint, Mads, Penelope, Joanna, Matthew, Brian, Maxim, Ricardo, Ruben, Seoyeon, Giorgio, Lea, Carla, Naja, Astrid, Maja, Ivy, Chantal, Kimberly, Amy, Vicki, Marlene, Ewa, Conchita, Karl, Mathieu, Miguel, Justin, Jacek, Ines, Takumi, Cristiano, Gwyneth, Mizuki, Celine, Jan, Zhiyu, Liv, Joey, Filiz, Dora, Raveena, Salli, Aditi, Vitoria, Emma, Hans, Kendra]",
stack: "ValidationException: 1 validation error detected: Value 'de-de' at 'voiceId' failed to satisfy constraint: Member must satisfy enum value set: [Nicole, Enrique, Tatyana, Carmen, Lotte, Russell, Geraint, Mads, Penelope, Joanna, Matthew, Brian, Maxim, Ricardo, Ruben, Seoyeon, Giorgio, Lea, Carla, Naja, Astrid, Maja, Ivy, Chantal, Kimberly, Amy, Vicki, Marlene, Ewa, Conchita, Karl, Mathieu, Miguel, Justin, Jacek, Ines, Takumi, Cristiano, Gwyneth, Mizuki, Celine, Jan, Zhiyu, Liv, Joey, Filiz, Dora, Raveena, Salli, Aditi, Vitoria, Emma, Hans, Kendra] at Object.extractError (/opt/node-sonos-http-api/node_modules/aws-sdk/lib/protocol/json.js:48:27) at Request.extractError (/opt/node-sonos-http-api/node_modules/aws-sdk/lib/protocol/rest_json.js:52:8) at Request.callListeners (/opt/node-sonos-http-api/node_modules/aws-sdk/lib/sequential_executor.js:105:20) at Request.emit (/opt/node-sonos-http-api/node_modules/aws-sdk/lib/sequential_executor.js:77:10) at Request.emit (/opt/node-sonos-http-api/node_modules/aws-sdk/lib/request.js:683:14) at Request.transition (/opt/node-sonos-http-api/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo (/opt/node-sonos-http-api/node_modules/aws-sdk/lib/state_machine.js:14:12) at /opt/node-sonos-http-api/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/opt/node-sonos-http-api/node_modules/aws-sdk/lib/request.js:38:9) at Request.<anonymous> (/opt/node-sonos-http-api/node_modules/aws-sdk/lib/request.js:685:12) at Request.callListeners (/opt/node-sonos-http-api/node_modules/aws-sdk/lib/sequential_executor.js:115:18) at Request.emit (/opt/node-sonos-http-api/node_modules/aws-sdk/lib/sequential_executor.js:77:10) at Request.emit (/opt/node-sonos-http-api/node_modules/aws-sdk/lib/request.js:683:14) at Request.transition (/opt/node-sonos-http-api/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo (/opt/node-sonos-http-api/node_modules/aws-sdk/lib/state_machine.js:14:12) at /opt/node-sonos-http-api/node_modules/aws-sdk/lib/state_machine.js:26:10"
}

**Comment by jishi** [comment]
The syntax for each TTS provider is different. For Polley, different voices
are used for different languages. Just remove de-de from the url and it
will use the voice you configured.

**Comment by masipulami** [comment]
Great. Now it worked. Thanks.
