### ISSUE TITLE
Backup  and restore Sonos Backup

### ISSUE THREAD

**Issue by jkohlin** [jishi/node-sonos-http-api#662]
Sorry for the open close mess 😔. Accidentally submitted too soon

 I know that this is strictly a GET API, so perhaps this is not possible, However would it be possible to at least exports a backup JSON file of all my settings, playlists and so on? 
If it’s possible to also recreate playlists and favorites that would be super.

**Comment by jkohlin** [comment]
Reason?
I have to factory reset my CONNECT😟 and all my favorites and playlists will be gone.

**Comment by jishi** [comment]
It is technically feasible, but I haven't looked into it deeply enough to know how hard it is to restore it.

Maybe it's just easier for you to borrow a player from someone that you register in the system, and then factory reset. Worst case you can buy one and return it afterwards :)

As long as you don't factory reset all players, the should keep playlists and favorites in sync. It is kind of weird that the controllers doesn't support this, to be honest.

**Comment by jkohlin** [comment]
True, but good news then, I didn’t know all units have a “backup”. Thanks for responding.
