### ISSUE TITLE
I am getting this error when I use 'saypreset'

### ISSUE THREAD

**Issue by pcgirl** [jishi/node-sonos-http-api#666]
I have setup a preset named speakers so that I can play a TTS to just certain speakers.  Although, It seems to work it is giving an error.  Not sure if this is affecting anything.  The error is:
2018-12-08T14:15:46.592Z ERROR
TypeError: Cannot read property '_state' of undefined
at Player.get (/app/node_modules/sonos-discovery/lib/models/Player.js:188:49)
at parseTrackMetadata.then.then.then.then.then (/app/node_modules/sonos-discovery/lib/models/Player.js:318:18)
at process._tickDomainCallback (internal/process/next_tick.js:135:7)

Here is the preset:
{
  "players": [
    {
      "roomName": "Kitchen",
      "volume": 50
    },
    {
      "roomName": "Master Bedroom",
      "volume": 50
	},
	{
		"roomName": "Lauren's Room",
      "volume": 50
	},
	{
      "roomName": "Ryans Bedroom",
      "volume": 50
    },
	{
      "roomName": "Workout Room",
      "volume": 50
    }
	],
  "playMode": {
    "shuffle": false,
    "repeat": "false",
    "crossfade": false
  },
  "pauseOthers": false,
}

**Comment by jishi** [comment]
Is any of the players unavailable? Or is any of them not getting the
announcement?
