### ISSUE TITLE
jishi-node-sonos-http-api-v1.0.1-0-g0d03be9.zip IS NOT COMPLETE!!!

### ISSUE THREAD

**Issue by bednim** [jishi/node-sonos-http-api#667]
Jishi - I don't know how to reach out to you so I'm doing it here... your jishi-node-sonos-http-api-v1.0.1-0-g0d03be9.zip file is not complete - it is missing clip and sub actions for example! But luckily your master.zip file is fully complete and these commands works fine!

**Comment by jishi** [comment]
1.0.1 is a very old version, I'm not sure where you downloaded that from? The latest release made on github is 1.4.3, but master is also significantly newer. Most people just use the latest master zip.

**Comment by bednim** [comment]
@jishi - I got it from your website -
http://jishi.github.io/node-sonos-http-api/ - top download link! I now use
your master version. No wonder sub/clip actions never worked on my
installation. Now, since I use most recent one, all works as should.
