### ISSUE TITLE
Players not resuming music after speaking a message

### ISSUE THREAD

**Issue by pcgirl** [jishi/node-sonos-http-api#668]
## Before you submit an issue

Not sure if this is something in the application that I am using this in but when I was using the GET request URL in Smartthings, it would resume the music after the speech but I am now using Hubitat Elevation home automation hub and when I use the GET request in a Rule in Rule Machine, it doesn't resume the music that is playing.  Is this something that is coded into the GET request in the app or does it have something to do with the node-sonos?

**Comment by jishi** [comment]
That's weird, whatever source calling the request should not matter for the behavior, if they are in fact identical requests. You aren't invoking multiple requests from Hubitat for some reason? That might confuse it?
