### ISSUE TITLE
Dependency: music-metadata v3 incompatible to node v4

### ISSUE THREAD

**Issue by tillmon** [jishi/node-sonos-http-api#669]
music-metadata v3 is incompatible to node v4, however the README states:

> This application requires node 4.0.0 or higher!

Only music-metadata v1 is compatible with node v4. It works with music-metadata v1, but I did not test all functions.

**Comment by jishi** [comment]
Hm, seems like I accidentally upgraded it at some update, I recall someone else having the same issue when they upgraded the dependencies. I'll update the dependency spec, thanks for reporting

**Comment by Borewit** [comment]
@jishi, I am sorry to notice latest releases of [music-metadata](https://github.com/borewit/music-metadata) left you in the dark.

Is the Node 4 compatibility requirement still valid?

If this is the case, and this is not something which is likely to change anywhere soon, would you be interested in a special backwards ported version for Node 4 compatibility?
