### ISSUE TITLE
I get a 404 on any request but web gui works fine.

### ISSUE THREAD

**Issue by clafa** [jishi/node-sonos-http-api#67]
GET http://192.168.1.3:5005/Toalett/favorite/P1 404 (Not Found)
Navigated to http://192.168.1.3:5005/Toalett/favorite/P1

I will try to debug to see what is sent / received on the client / server side.

**Comment by jishi** [comment]
Which web gui are you talking about? And how do you invoke these requests?

**Comment by clafa** [comment]
My bad. I think I mixed up your http-api and your web controller. Close this.

Thank you Jishi for your work and great support!
