### ISSUE TITLE
Play a Apple Music Playlist

### ISSUE THREAD

**Issue by suxus-zz** [jishi/node-sonos-http-api#676]
Hello

Is it possible to play a Apple Music Playlist over the Sonos API?

`
/RoomName/applemusic/{now,next,queue}/song:{songID}
/RoomName/applemusic/{now,next,queue}/album:{albumID}
`

Songs and Album are possible, but playlists?

Greeting

**Comment by jishi** [comment]
I'm unfamiliar with the implementation, I wasn't the one building it. I also don't have Apple Music, which makes it hard to reverse engineer.

**Comment by snorrelo** [comment]
Not a fix, but a workaround: Add the Apple Music playlist(s) to favourites and play them from there. /roomname/favorites to view and /roomname/favorite/playlistname to play. Works with both your own and other Apple Music playlists.
