### ISSUE TITLE
Using Swagger UI - Can't read from server error.

### ISSUE THREAD

**Issue by csawall** [jishi/node-sonos-http-api#68]
I've been researching and testing for days. I'm not sure what else to try.  I cannot get the Swagger UI to work.  I get this error:

Can't read from server. It may not have the appropriate access-control-origin settings.

I don't think I need CORS enabled, based on what I've read, but I'm trying it anyways, but it still doesn't work.  The curl test:

curl -I "http://192.168.2.253/nodesonos/static/docs/api-docs"
HTTP/1.1 200 OK
Date: Wed, 26 Aug 2015 22:52:59 GMT
Server: Apache/2.2.22 (Debian)
Last-Modified: Wed, 26 Aug 2015 21:29:17 GMT
ETag: "2c5e6-216-51e3d8b00159a"
Accept-Ranges: bytes
Content-Length: 534
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: *

My understanding is I only needed to have the "Origin" set to make this work, but I added the "Headers" as a test.  This is in my apache2 conf.d/security file, under the <Directory> section.  Specifically, I currently added:

Header set Access-Control-Allow-Origin "*"  (<-- note that this is quote asterisk quote - it's not showing up when I save this comment / issue)
Header set Access-Control-Allow-Headers "*"  (<-- same for this, quote asterisk quote)

Also, if needed, the node server runs fine.  I'm running: sudo node server.js.  The system is responsive and I can access http://192.168.2.253:5005/ correctly.  If I try to access the Swagger UI via this listener, http://192.168.2.253:5005/docs/, I get the same error / response.

I'm open to ideas on this one!  Thoughts?

Thanks!

**Comment by jishi** [comment]
Yeah, swagger seem to have a lot of hardcoded paths that points to localhost, that's why.

I have had a merge request pending for a long time that I haven't looked at, I merged it now so maybe you can try and update it and see it it works? It is supposedly fixing this issue.

**Comment by csawall** [comment]
Resolved!  Thank you, sir!
