### ISSUE TITLE
Play/Set TuneIn radio

### ISSUE THREAD

**Issue by cocofo** [jishi/node-sonos-http-api#681]
Hi

I'm trying to play or set a TuneIn radio on my Sonos but I get a "status":"error" when using for instance : http://192.168.100.119:5005/Living%20Room/tunein/play/44491

I've tried with different IDs, with or without the "S" before the ID and I always get the same result
I've the node-sonos-http-api image installed on a Raspberry PI

Thanks !

**Comment by jishi** [comment]
Can you provide logs for the time when you try to invoke this? It should be
accessible over samba share (windows file sharing) from the rpi. I don't
remember the path right now and can't look it up, so you'll have to look
around for it.

**Comment by cocofo** [comment]
Hi

That's what the "http-api.log" file says  :

2019-03-01T08:21:56.546Z ERROR
  { error: 'action \'tunein\' not found' }
2019-03-01T08:23:06.604Z ERROR
  { error: 'action \'tunein\' not found' }

Thanks

Le ven. 1 mars 2019 à 09:00, Jimmy Shimizu <notifications@github.com> a
écrit :

> Can you provide logs for the time when you try to invoke this? It should be
> accessible over samba share (windows file sharing) from the rpi. I don't
> remember the path right now and can't look it up, so you'll have to look
> around for it.
>

**Comment by jishi** [comment]
Which version are you running? Look in the package.json file and see what
version it says

**Comment by cocofo** [comment]
I've downloaded it yesterday from
http://jishi.github.io/node-sonos-http-api/

In the packason.json it says :

"name": "sonos-http-api",
  "version": "1.0.1",

>

**Comment by jishi** [comment]
Do turn it off at night? It should auto-update (but maybe it is just once a
week) to 1.4.3. You could run the update script manually or just unzip the
1.4.3 release on top of the old one. Tunein wasn't in 1.0.1

**Comment by cocofo** [comment]
OK I'll give it a shot ! I just downloaded the image yesterday and didn't think to run updates, sorry
Thanks

**Comment by cocofo** [comment]
Yes it works after the update ! Thank you so much for your quick support !!!!

Only thing that doesn't seem to work with TuneIn, it's the set option
http://192.168.100.119:5005/Living%20Room/tunein/set/44491

2019-03-01T12:45:22.355Z ERROR Expected TuneIn station id

But for me the tuneine/play is more than perfect !

Thank you again

**Comment by jishi** [comment]
Yeah, seems like `set` is not part of the 1.4.3 version. I should release a new version and probably update the rpi image, but most users just install the latest master branch.

**Comment by cocofo** [comment]
Ok, I will do the same and use the master ;) I downloaded the Rpi version
because it was a fast way to test it with my automation system without too
much hassle :)
Thank you so much for your prompt help !

>

**Comment by martin072** [comment]
Old post, but for me I had to put an 's' before the station, i.e. ../tunein/play/s44491
Using it for more than a year without any problems

**Comment by coolspot18** [comment]
> Old post, but for me I had to put an 's' before the station, i.e. ../tunein/play/s44491 Using it for more than a year without any problems

I think the current version of the API doesn't like it when you put an s. I had to drop the s in the station id for it to work.
