### ISSUE TITLE
Sending a web GET request with a variable

### ISSUE THREAD

**Issue by pcgirl** [jishi/node-sonos-http-api#685]
I am trying to send a web GET request to make certain speakers setup in a "speakers" preset say different phrases when people are arriving home or leaving.  In WebCore I have a variable setup to have random sayings.  The variable is called announce.  So when I put in the GET statement I have it like this.  http://192.168.1.102:5005/saypreset/speakers/{announce}.  It speaks what is in the variable but then it also says announce=Long+time+no+see.  Here is what shows in the npm window:  announce file for phrase "Long time no see?announce=Long+time+no+see" does not s
eem to exist, downloading

Is there a way to get it to just say what is in the variable?

**Comment by jishi** [comment]
So WebCore appends `?announce=Long+time+no+see` to the request? Can you disable that? 

It would be possible to "exclude" the query string from the announcement on the server side too, worst case.

**Comment by pcgirl** [comment]
Don't worry about this issue right now.  I really need to get the whole TTS to sonos working first.
