### ISSUE TITLE
voiceRSS ist working, but Sonos can't play the file

### ISSUE THREAD

**Issue by cbrandtner** [jishi/node-sonos-http-api#686]
Hi there,

I get them same message like in issue #497 in my Sonos-App ("... not correctly coded").
VoiceRSS is working and I can playback the downloaded file on my Ubuntu with VLC.
But Sonos stopps the running playback, is silent for several seconds and then resumes playback.
Playing mp3 using "clip" is working with different MP3 files, but not with the files I'm getting from VoiceRSS. Changing the parameters for f==22khz... in http://api.voicerss.org/?key=${settings.voicerss}&f=22khz_16bit_mono&hl=${language}&src=${encodeURIComponent(phrase)}`  or adding c=mp3 does not change anything. Audacity allway says the MP3 I got for VoiceRSS is 8khz / 8bit/mono.
Any ideas?
Chris

**Comment by jishi** [comment]
I haven't had time to look at it, but I'm planning on looking into it. Similar issue: https://github.com/jishi/node-sonos-http-api/issues/682

**Comment by cbrandtner** [comment]
Hi, 
I have analyzed the issue a litte bit:
1. it ist working with mp3-files 22khz - 16 Bit mono, as the file missing_api_key.mp3 is coded
2. the mp3-files I got back from voicerss, that are cached in ~/node-sonos-http-api-master/static/tts, are coded 44khz 32 bit mono float. Sonos can't playback them.
Changing the parameter f= ,,, as mentioned above has no effect. 
3. I have installed the Raspi completly from scratch to be sure I didn't change the config by accident, but the problem still exists  
Hope this will help you fix the issue. Thanx
Chris

**Comment by JayVee2** [comment]
I can fully reproduce this error reported by Chris.
Took me a long time to analyze, as VoiceRSS somehow killed my profile first and I had to apply for a new key.

VoiceRSS service is working. However the  MP3 produced for some reason cannot by played by Sonos anymore. 
This can easily be reproduced when MP3 files are copied  from ~/node-sonos-http-api-master/static/tts into the Sonos Music library.

Files produced with default TTS work fines.
I tried the following VoiceRSS codings:
8khz_8bit_mono (VoiceRSS default)
22khz_16bit_mono/stereo
12khz_16bit_mono/stereo
11khz_16bit_mono/stereo, and some more...

Seems to be a problem on the VoiceRSS encoding, even if Windows plays all files created.

So I'm unsure if this can be fixed here.

**Comment by JayVee2** [comment]
OK, problem solved:

VoiceRSS reports: The request returns a WAV file. Please use explicitly the audio codec MP3.

File: ~/node-sonos-http-api-master/lib-tts-providers/voicerss.js:
Line#19: add "&c=MP3"
`const ttsRequestUrl = `http://api.voicerss.org/?key=${settings.voicerss}&f=22khz_16bit_mono&hl=${language}&src=${encodeURIComponent(phrase)}&c=MP3`;

**Comment by jishi** [comment]
Fixed. You need to delete all broken files from `static/tss` otherwise it will load a broken, cached version on duplicated phrases.

**Comment by cbrandtner** [comment]
Great Job, thx!
