### ISSUE TITLE
playpauseall and togglemuteall 

### ISSUE THREAD

**Issue by dutchsea** [jishi/node-sonos-http-api#690]
Hi, would be nice in my view to add playpauseall (or groupPlaypause)  togglemuteall (or groupTogglemute) to the "actions supported" so similar to pauseall. 

So toggle between play and pause for all rooms and same for mute/unmute.

**Comment by jishi** [comment]
Not sure what the group functions are supposed to do differently than the
current playpause, since that affects the group?

A playpauseall could be useful, but not sure what the expectation should be
if some group is playing, and some other group is paused?

**Comment by dutchsea** [comment]
What I am trying to set-up (in Domoticz) is a selector switch that has one play/pause button that effects all rooms simultaniously. (One button for play pause saves space compared to 2 separate buttons for play and pause). And same create 1 mute/unmute button for all rooms together.  

My idea is to have one command that pauses all rooms and when send again it lets al rooms play again. Now I think about this a bit more, its probably more difficult than I initially thought. 
Such a command needs to work on multiple groups and will depend on status of the group (playing or paused) like you already mention in your post. (Ideally the command would only pause rooms playing and un-pause same rooms when send again)

A "muteUnmuteall" may be easier? Just mute all rooms and unmute all rooms when same command is send again, independent of previous state of mute though likely dependent on previous mute state as well.

**Comment by jishi** [comment]
The problem is that you are expecting the action to depend on the last
action you did for that call, but any number of changes could have been
made by other means (directly on the player, from the controller, other api
calls) which make me think it wouldn't work very good in reality.

**Comment by dutchsea** [comment]
Clear! Thanks for looking into this so quickly. (New at this and learning by doing)
