### ISSUE TITLE
HTTP command not working using node.js on NAS Synology

### ISSUE THREAD

**Issue by rhino111** [jishi/node-sonos-http-api#70]
Hello,

I've a problem using node-sonos-http-api on my NAS Sinology

* I've a DS415Play NAS Synology
* I've installed Node.JS V0.12.4 on the NAS
* I've installed NPM on the NAS
* Connected via Terminal from OS X 
** I did a ssh root@<nas_ip>
** I did a "git clone" of node-sonos-http-api
** I've  installed all the dependencies using "npm install"
* In the "Server.JS" file, I've changed the listening port from 5005 to 6000
* I've started "Server.JS"
-> It ran and showed me a lot of information

When I try to issue an URL such a "http://<nas_ip>:6000/zones" I've a "Safari can't open the page" error
![server js log](https://cloud.githubusercontent.com/assets/14790718/10030345/8ea21d9c-6177-11e5-8637-1c015320a0c8.jpg)

I've checked the access rights on the folders "node-sonos-http-api" and they seem correct
I wonder why I could do/check

Thank you for your help,

Renauld

**Comment by jishi** [comment]
Was that the exact url you entered in safari? Because it is missing the IP,
example:

http://192.168.0.155:6000/zones

Use the IP of your NAS, or if it has a hostname.

**Comment by rhino111** [comment]
Hello,

Sorry, I made a mistake in my first post
The URL I input in Safari is "http://192.168.100.3:6000/zones"

Reagrds,

**Comment by jishi** [comment]
Well, it apparently seems to be running (unless you close the session where you started the api), so either it is blocked by some firewall rules on your NAS or your computer. Maybe provide a netstat output from your nas (netstat -na) or similar (which needs to be ran on another session while the api is running). You probably need to find a way of running the node process in background as well.

**Comment by rhino111** [comment]
Hello all,

Eventually I've installed the API on a Raspberry and it works fine

Thank you,

**Comment by jishi** [comment]
I'm guessing the Synology had some firewall rules that blocked the traffic. Anyway, nice that you resorted it with the rpi.
