### ISSUE TITLE
Please add HDMI controller 

### ISSUE THREAD

**Issue by joohann** [jishi/node-sonos-http-api#700]
Would be nice for the SONOS Beam to able to controle TV turning it on/off <3

**Comment by jishi** [comment]
Does the beam support that from the Sonos app?

**Comment by MarvinSchenkel** [comment]
Hi @jishi,

Is there any way you can look into this feature again (now that you own a beam :) ). Would be great to automatically turn off the TV when I go to sleep.

Much appreciated!

- Marvin
