### ISSUE TITLE
sudden discovery issue

### ISSUE THREAD

**Issue by snakescb** [jishi/node-sonos-http-api#701]
Hi all,

worked flawless for months, and suddenly stop working this night. Tried to reinstall and troubleshoot with the logs, but I just cannot discover players anymore wihtout any obvious reason. Also I went through all the common resolution tips in issue 77 without success. iPhone App in the same WIFI works fine. Any idea what just happend? My ubuntu server made some updates this night, not sure if this changed something. Any Idea how to troubleshoot?

Regards, Christian

**Comment by jishi** [comment]
Can you give me the output of "ifconfig" to start with? Maybe that will
explain something.

**Comment by snakescb** [comment]
sure, thanks for answer. NW settings have not changed. The API is running on a Ubuntu 18.04 VM on VMWare with fixed IP address. Sonos players ares in a different VLAN, but everything works properly through igmp proxy and opened ports in firewall. The firewall log does not show any blocked traffic. Also, if I connect my iPhone to the same subnet as the ubuntu server, it can connect to the players without issue. Ah, and I also made sure the ubuntu firewall is not blocking anything here.

BTW, thanks for your great API! It is driving my full smarthome... so it became pretty important over the years ;-)

ens160: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.64.50.4  netmask 255.255.255.0  broadcast 10.64.50.255
        inet6 fe80::20c:29ff:fe67:e801  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:67:e8:01  txqueuelen 1000  (Ethernet)
        RX packets 54888  bytes 39637806 (39.6 MB)
        RX errors 0  dropped 9  overruns 0  frame 0
        TX packets 48370  bytes 5623745 (5.6 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by jishi** [comment]
Aha, so you have quite the unusual network setup. Is there any log for
igmpproxy? I have never used it, but I'm assuming it forwards multicast
traffic between the nets. It would be interesting to see the difference in
logs between the iPhone connecting and when the api tries it.

Have you checked to see if your sonos system updated? Or the version of
igmpproxy?

**Comment by snakescb** [comment]
I will try to find if I can find logs on the router and paste them here if I can. For sure the router (and therefore the igmp proxy) did not upgrade recently. My Sonos Player is on 10.2 Build 50165071, not sure how to check if this has updated.

Also, I will put my players to the same subnet as the server, and let you know if it helps, just to make sure  it is not related to a router issue. 

Is there any way to check if the API is actually searching for players?

Cheers

**Comment by jishi** [comment]
If you can tcpdump udp traffic for Port 1900 you should see the discovery
packets that the api is sending. They should contain the string "M-SEARCH"
if I recall correctly, it's standard ssdp.

**Comment by snakescb** [comment]
ok... definitely turns out to be a router issue tough igmpproxy or the firewall are not reporting anything, and the iphone in the same wifi works... Sorry for bothering you... will investigate what is going on. But ingeneral: Controller and player in different subnets: it works... but is no fun...

**Comment by Keesromkes** [comment]
I got this working by manually updating the 'sonos-discovery' package in node_modules -- apparantly the --production install of the API installs v1.0.0 of the node-sonos-discovery package. 

There must've been reasons for this, but it 'fixed' my setup, and instantly got me going again.
