### ISSUE TITLE
Spotify search returns success, but no music data

### ISSUE THREAD

**Issue by Erik099** [jishi/node-sonos-http-api#708]
Love this app!

just one issue though... spotify id and secret are all setup correctly. When i attempt to search:

/musicsearch/spotify/song/red+hot+chili+peppers

i get only a status object back:

{"status":"success"}

Im expecting an object with search matches. ideas?

thanks!

**Comment by jishi** [comment]
I'm pretty sure the behavior is supposed to queue the whole search result, not to return a list of tracks.

**Comment by Erik099** [comment]
ok, so it appears this is by design; the search will just play the track if it finds a match (i did confirm this works).

If anyone has extended this functionality to include returning a list of tracks, please let me know. Any implementation looking to replicate standard search use cases, will want a result set. I think the bigger missing piece here that the app doesnt make any assumptions about user experience and related data. In the case where a user searches for music, the result set should be available for the user to pick and choose what goes to the queue.

**Comment by Erik099** [comment]
Closing this, as it is not an issue. thank you.
