### ISSUE TITLE
Question: how to switch playbar back to TV ?

### ISSUE THREAD

**Issue by hukedev** [jishi/node-sonos-http-api#709]
Everything works as expected with this library.
I'm using playbars, sub's, amp's and play:5 devices to control volume, join and leave zone.

But when i want to switch the playbars back to TV i did not find a way.

Is there any solution available (except the sonus app's) ?

**Comment by jishi** [comment]
You can use this workaround https://github.com/jishi/node-sonos-http-api/issues/382

**Comment by hukedev** [comment]
Thank you for the fast response.

I'll try to parse the necessary UUID's from /zones to be able to use the /zone/setavtransporturi command.

**Comment by jishi** [comment]
The uuid is hard-coded from factory for a given player, so that is not
bound to change unless you replace it.

**Comment by hukedev** [comment]
As UUID's are parsed by library already i simply added a new action called `spdif` based on `linein`:

```
'use strict';

function spdif(player, values) {
  const sourcePlayerName = values[0];
  let lineinSourcePlayer = player;

  if (sourcePlayerName) {
    lineinSourcePlayer = player.system.getPlayer(decodeURIComponent(sourcePlayerName));
  }

  if (!lineinSourcePlayer) {
    return Promise.reject(new Error(`Could not find player ${sourcePlayerName}`));
  }

  const uri = `x-sonos-htastream:${lineinSourcePlayer.uuid}:spdif`;

  return player.coordinator.setAVTransport(uri)
    .then(() => player.coordinator.play());
}

module.exports = function (api) {
  api.registerAction('spdif', spdif);
}
```

So, for switching to SPDIF on playbars i'm calling this:

`serverip:5005/zonename/spdif`
