### ISSUE TITLE
Server stopping when closing terminal

### ISSUE THREAD

**Issue by goldsmid** [jishi/node-sonos-http-api#72]
How do you get the server to continue operating after you log out of the terminal or make it start up and stay on as part of the Synology DSM reboot?

**Comment by mszoernyi** [comment]
Autostart for DSM: http://majikshoe.blogspot.de/2014/12/starting-service-on-synology-dsm-5.html

If you want to let it run but close your terminal use `[screen](https://www.rackaid.com/blog/linux-screen-tutorial-and-how-to/)` or `[tmux](https://wiki.archlinux.org/index.php/Tmux)`

**Comment by jishi** [comment]
I wont be able to help you with this, @mszoernyi gave some nice pointers but I suggest you direct this question to some Synology forum, they might be able to help.
