### ISSUE TITLE
Spotify app 'Connect to a device' crashes the api

### ISSUE THREAD

**Issue by sgraystar** [jishi/node-sonos-http-api#723]
We have been using the API with Spotify happily for some time, controlling playback within the Sonos app without any problem.

However my son prefers to use Spotify directly and when connecting to a Sonos device in the Spotify IOS app, or in Spotify on his PC, it crashes the API.
It does not matter which Sonos device, connecting to any speaker on the network causes a crash.
If Spotify is already directly playing on any speaker then the API fails to start with errors.

Logs attached.
Cheers

[crash_when_launch_spotify.txt](https://github.com/jishi/node-sonos-http-api/files/3701623/crash_when_launch_spotify.txt)
[2019-10-08T08_02_48_401Z-debug.log](https://github.com/jishi/node-sonos-http-api/files/3701624/2019-10-08T08_02_48_401Z-debug.log)
[crash_on_start_while_spotify.txt](https://github.com/jishi/node-sonos-http-api/files/3701625/crash_on_start_while_spotify.txt)
[2019-10-08T07_56_48_373Z-debug.log](https://github.com/jishi/node-sonos-http-api/files/3701626/2019-10-08T07_56_48_373Z-debug.log)

**Comment by StevenBoelhouwer** [comment]
You need to update the node-modules. Do a npm update in the node sonos http api folder.

**Comment by sgraystar** [comment]
That was easy, all fixed, thanks.
