### ISSUE TITLE
Got status 500 when invoking /MediaRenderer/AVTransport/Control

### ISSUE THREAD

**Issue by sli-cka** [jishi/node-sonos-http-api#732]
When I try to Linein my living room speakers to the HDMI connected TV, i receive the following error:

  | "Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control\n    at Object.invoke (/home/pi/node-sonos-http-api-master/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)\n    at Player.setAVTransport (/home/pi/node-sonos-http-api-master/node_modules/sonos-discovery/lib/models/Player.js:727:15)\n    at Object.linein (/home/pi/node-sonos-http-api-master/lib/actions/linein.js:17:29)\n    at handleAction (/home/pi/node-sonos-http-api-master/lib/sonos-http-api.js:117:35)\n    at HttpAPI.requestHandler (/home/pi/node-sonos-http-api-master/lib/sonos-http-api.js:94:21)\n    at /home/pi/node-sonos-http-api-master/server.js:50:13\n    at Server.finish (/home/pi/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:111:13)\n    at finish (/home/pi/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:170:14)\n    at /home/pi/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:144:17\n    at FSReqWrap.oncomplete (fs.js:153:21)"
-- | --

Can you help me solving this issue?

**Comment by jishi** [comment]
the linein action doesn't work with HDMI pr SPDIF inputs. I'm not familiar with how the HDMI input works, since I don't own a beam myself. 

There is a workaround (see https://github.com/jishi/node-sonos-http-api/issues/109) but I'm not sure how it works with an HDMI device. 

If you could send me the /roomname/status output when you have the hdmi linein selected for your beam, then it would tell me the exact avtransporturi needed to use the workaround. (replacing x-sonos-htastream:RINCON_XXXXXXXXXXXX01400:spdif)

**Comment by sli-cka** [comment]
Hi jishi,

thanks for your quick reply and this great api.
Here is the status output of /roomname/status/ 

`{"volume":26,"mute":false,"equalizer":{"bass":-5,"treble":0,"loudness":false,"speechEnhancement":false,"nightMode":true},"currentTrack":{"duration":0,"uri":"x-sonos-htastream:RINCON_347E5C9129B101400:spdif","trackUri":"x-sonos-htastream:RINCON_347E5C9129B101400:spdif","type":"line_in","stationName":""},"nextTrack":{"artist":"","title":"","album":"","albumArtUri":"","duration":0,"uri":""},"trackNo":1,"elapsedTime":1145,"elapsedTimeFormatted":"00:19:05","playbackState":"PLAYING","playMode":{"repeat":"none","shuffle":false,"crossfade":false}}`

Greetings

**Comment by jishi** [comment]
Okay, looks like it is the same as for the playbar, so the workaround in
the issue I mentioned would work.

**Comment by sli-cka** [comment]
Ok, just found out that replacing /Roomname/lineine with /Roomname/setavtransporturi/x-sonos-htastream:RINCON_347E5C9129B101400:spdif is a workaround. Thanks for your help.
