### ISSUE TITLE
How to setup a present.json

### ISSUE THREAD

**Issue by mszoernyi** [jishi/node-sonos-http-api#74]
How to setup a proper `presets.json`? This is my try but it wont get executed. While calling the preset url the server doesn't log anything.

```
{
  "welcome-home": {
  {
    "players": [
      { "roomName": "Living Room", "volume": 15},
      {"roomName": "Bathroom", "volume": 10},
      {"roomName": "Kitchen", "volume": 10}
    ],
    "state": "playing",
    "favorite": "welcome-home",
    "playMode": "SHUFFLE",
    "pauseOthers": true
  }
}
```

calling with `http://pi:5005/preset/welcome-home`

While server startup the preset seems to be loaded

```
Nov 01 22:29:18 raspberrypi node[3789]: loaded presets { WH:
Nov 01 22:29:18 raspberrypi node[3789]: { players: [ [Object], [Object] ],
Nov 01 22:29:18 raspberrypi node[3789]: state: 'playing',
Nov 01 22:29:18 raspberrypi node[3789]: favorite: 'welcome-home',
Nov 01 22:29:18 raspberrypi node[3789]: playMode: 'SHUFFLE',
Nov 01 22:29:18 raspberrypi node[3789]: pauseOthers: true } }
```

**Comment by jishi** [comment]
Well, according to the output, you seem to have called your preset "WH" and not "welcome-home".

**Comment by mszoernyi** [comment]
ah sorry this was the second try renaming it. copied in the process. But doesn't work with either of them. Changed them from `welcome-home` to `WM` didn't work either and back again. Thought maybe the dash is an issue.

**Comment by mszoernyi** [comment]
Ok it seems like the `favorite` part doesn't work. Left just grouping of rooms works. The preset structure is correct.
