### ISSUE TITLE
Update Link to download on website

### ISSUE THREAD

**Issue by pwaldhauer** [jishi/node-sonos-http-api#746]
The "Download as .zip"-Button on http://jishi.github.io/node-sonos-http-api/ links to a v1.0.1. This old version does not really work.

It took me months to sort this out until I tried to load the current version from Github...

**Comment by bednim** [comment]
@pwaldhauer i've done same, reported it as well, I was sure jishi would change that link.

**Comment by jishi** [comment]
Sorry about that. That web page got sort of forgotten, and also since most people are using master the releases has also fallen behind.
