### ISSUE TITLE
How to uninstall the sonos-http-api

### ISSUE THREAD

**Issue by Pip32** [jishi/node-sonos-http-api#748]
Hey folks,

do anyone know how to uninstall the sonos-http-api ?
Sorry for the nooby question, hadn't had a deep dive on the JS and npm/node till now.

Doesn't work properly for me, just wanted to remove the whole api from the system.

Running on RP 3+ with Raspbian full.

Thanks,

**Comment by jishi** [comment]
If you just downloaded it and ran npm install, you can just remove the sonos-http-api folder, nothing else has been added to your system by the api.

If you also tried to make it start at boot time using pm2, you can uninstall pm2 by invoking `npm uninstall -g pm2`

**Comment by Pip32** [comment]
Thanks for the super fast response!
