### ISSUE TITLE
Not getting preset using line-in to work

### ISSUE THREAD

**Issue by MikeGermany** [jishi/node-sonos-http-api#753]
Hello pros,

sorry for the following question. I was despreately looking for any answer / solution working for me. Nothing did work.

I try to build a preset file where all other speakers use the line-in of my connect ZP90.
Another preset file just playing my favorite radio station does work fine.

Calling raspi:5005/zones I get the (part of) response:
`{"uuid":"RINCON_48A6B812FB0201400","state":{"volume":37,"mute":false,"equalizer":{"bass":0,"treble":0,"loudness":true},"currentTrack":{"title":"Audio Component","duration":0,"uri":"x-rincon-stream:RINCON_949F3E24D2A601400","trackUri":"x-rincon-stream:RINCON_949F3E24D2A601400","type":"line_in","stationName":""},"nextTrack":{"artist":"","title":"","album":"","albumArtUri":"","duration":0,"uri":""},"trackNo":1,"elapsedTime":0,"elapsedTimeFormatted":"00:00:00","playbackState":"PAUSED_PLAYBACK","playMode":{"repeat":"none","shuffle":false,"crossfade":false}},"roomName":"Schlafzimmer","coordinator":"RINCON_48A6B812FB0201400","groupState":{"volume":40,"mute":false}}`

The preset file looks like:
`{
  "players": [
    { "roomName": "Schlafzimmer", "volume": 35 },
    { "roomName": "Küche", "volume": 40 },
    { "roomName": "ElterBad", "volume": 35 },
    { "roomName": "Mobil", "volume": 35 }
  ],

  "uri": "x-rincon-stream:RINCON_949F3E24D2A601400",
  "playMode": {
          "repeat":"none",
          "shuffle":false,
          "crossfade":false
          }
}
`

But when I call raspi:5005/preset/preset.json I do get the following error message:
`{"status":"error","error":"Cannot read property 'avTransportUri' of undefined","stack":"TypeError: Cannot read property 'avTransportUri' of undefined\n    at players.slice.reduce (/home/pi/node-sonos-http-api-master/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:55:18)\n    at Array.reduce (<anonymous>)\n    at groupWithCoordinator (/home/pi/node-sonos-http-api-master/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:53:6)\n    at promise.then (/home/pi/node-sonos-http-api-master/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:113:12)"}`

I do not know, what my problem is.
The serial number of the ZP90 is correct (949F3E24D2A6:F) the port number (1400) should be correct and should work.

Please give me an advice.

Thank you very much
-Mike

**Comment by jishi** [comment]
Sounds like the internal state of the api is broken. Have you tried
restarting the api and see if the error is still there? Which version are
you running (check package.json)?

**Comment by MikeGermany** [comment]
Hello jishi,
thanx! The problem sat just 50 cm in front of the display.
A room name was misspelled !!!!! 
Sorry.... 
Best wishes!!!
-Mike

**Comment by jishi** [comment]
Could probably provide a better error message for that, good info, glad it was an easy mistake :)
