### ISSUE TITLE
is there a way to change the "success" message after each action

### ISSUE THREAD

**Issue by sw764206** [jishi/node-sonos-http-api#761]
is there a way to change the "success" message after each action and modify the code so that it doesn't open that message and possible redirects back to a specific URL (the URL of my home dashboard on my wall panel?)

**Comment by jishi** [comment]
The code responsible for the response is this: 

https://github.com/jishi/node-sonos-http-api/blob/master/lib/sonos-http-api.js#L102

You would have to modify that to instead send a 302 statusCode, and a `Location:` header pointing to your dashboard.

**Comment by jishi** [comment]
Actually, it's this piece

https://github.com/jishi/node-sonos-http-api/blob/master/lib/sonos-http-api.js#L84-L90

But you would have to deal with errors (e.g, a 500 code) somehow.
