### ISSUE TITLE
Spotify “end session” command through api

### ISSUE THREAD

**Issue by Nayhtohn** [jishi/node-sonos-http-api#778]
## Before you submit an issue

Search among the current open _and_ closed issues for an answer to your question before submitting an issue! 

If you are looking for assistance with installing or just general questions, reach out on the gitter chat (https://gitter.im/node-sonos-http-api/Lobby) instead of filing an issue. It's easier for me if issues are primarily fokused on bugs and feature requests, and hopefully other people can assist you in the chat. 

If your question is Docker related, please file the issue at the https://github.com/chrisns/docker-node-sonos-http-api and also, make sure you have tested that image before asking a question. This is the only image that has any correlation to this project, and is guaranteed to be up to date.

If your question has anything to do with Amazon Echo, it is probably better suited at https://github.com/rgraciano/echo-sonos. If you have questions about the requests sent to this library, figure out the exact request that is sent from the Alexa Skill (through the logs) and include that in the issue.

Thank you!

**Comment by Nayhtohn** [comment]
I’m wondering if you can help with an issue I’m running into:

When I have a queue setup from the Sonos app the emulator works fine, but when I start a song from the Spotify app it doesn’t work and I have to go into the Sonos app and press “end session” before the emulator can work.

I can’t see on the Sonos api a command for end session, and clearqueue doesn’t seem to work - do you know if such a command exists? Or how I can watch the api command line when I press a button in the app to see what it tells the system to do?

Thanks,
Ben

**Comment by hankhank10** [comment]
Hi Ben, I think you've raised an issue on the wrong repo. If you could direct this to hankhank10/vinylemulator I'll try to fix it my end first of all. If we can't get it working and it does prove to be an issue with @jishi 's repo we can re-raise here

@jishi please close this issue, thanks

**Comment by jishi** [comment]
😂 I was confused there for a bit. Glad you pointed it out @hankhank10
