### ISSUE TITLE
Is this plugin still being actively supported?

### ISSUE THREAD

**Issue by jsiegenthaler** [jishi/node-sonos-http-api#784]
Lots of issues and the original developer appears not to frequent this any more. Does anyone know the status?

I'd love to hear of support and enhancements such as Microsoft Azure TTS services...

**Comment by mochi-co** [comment]
@jishi pops in now and then, but I suspect is understandably busy with real life and maintaining a big project like this can take a lot of time.

However, there's quite a few PRs which would be great to merge into the main branch. Perhaps @jishi could consider giving someone close to the project write access so we can keep the enhancements going in the meantime

**Comment by jsiegenthaler** [comment]
Then @mochi-co. It would be great if another person could assist with this project. There's a number of items which are old and stale and need updating.

**Comment by JayVee2** [comment]
Adding new files/functions out of existing pull requests would be great!!

@jishi : Thanks for great library!!

**Comment by jsiegenthaler** [comment]
I'd like to help, I can bring the documentation up to date and assist with simple stuff, like keeping dependencies up to date. I'll close this issue now, and hope that you'll respond
