### ISSUE TITLE
Command "shuffle" is not working.

### ISSUE THREAD

**Issue by lukenukemmp3** [jishi/node-sonos-http-api#785]
Hey there,

first of all: thank you. This is absolutely amazing and enables so much automations, which I love.

There is one small issue: the command shuffle seems not to be working, although I get the "success"-message from the server.

**Comment by jsiegenthaler** [comment]
Unfortunately the original developer does not appear to support this project any more. Issues have remained open and unresolved for over 3 years.... I wish there was some way that this project could be brought up to date

**Comment by ggscott** [comment]
> Unfortunately the original developer does not appear to support this project any more. Issues have remained open and unresolved for over 3 years.... I wish there was some way that this project could be brought up to date

@jsiegenthaler I haven't heard of @jishi abandoning the project. If anything, its been working like a champ and maybe just needs tending to improve use cases, here or there.  

To your point, maybe some auto tending of tickets that have been opened with no feedback or the "I don't know how to install - hepl gm~ kind of tickets might allow those of us with free time to be able to assist with PRs, etc.

**Comment by jsiegenthaler** [comment]
Hmmm. Unfortunately I've had no response to any questions to jishi, and I note that issues and pull requests remain open for a very long time, years in some cases. And no new releases have been made in a very long time. 

Some features are now so old they no longer work as the services they use have been deprecated.

If only the developer would sign in once a month and close open issues and update notes, then it would paint a completely different picture.

**Comment by lukenukemmp3** [comment]
The answer as always is a user failure. I just didnt used the /on or /off option.
