### ISSUE TITLE
Ikea Symfonisk

### ISSUE THREAD

**Issue by DominikReber** [jishi/node-sonos-http-api#788]
Hi

Is this api also supporting IKEA Symfonisk-Speakers? (which use Sonos tech)

Thanks a lot

**Comment by jsiegenthaler** [comment]
Yes, I have. Ikea Symfonisk and Sonos One SL speakers and they all work exactly the same with the http Sonos plugin.

**Comment by DominikReber** [comment]
This is great news, thanks a lot
