### ISSUE TITLE
Remove command not working

### ISSUE THREAD

**Issue by parth0295** [jishi/node-sonos-http-api#793]
Hello all,

Any thoughts on why I can't seem to get the following command to work: "192.168.4.24:5005/remove/Bathroom"... the add command with the same syntax works perfectly every time but am having trouble with remove.

## Before you submit an issue

Search among the current open _and_ closed issues for an answer to your question before submitting an issue! 

If you are looking for assistance with installing or just general questions, reach out on the gitter chat (https://gitter.im/node-sonos-http-api/Lobby) instead of filing an issue. It's easier for me if issues are primarily fokused on bugs and feature requests, and hopefully other people can assist you in the chat. 

If your question is Docker related, please file the issue at the https://github.com/chrisns/docker-node-sonos-http-api and also, make sure you have tested that image before asking a question. This is the only image that has any correlation to this project, and is guaranteed to be up to date.

If your question has anything to do with Amazon Echo, it is probably better suited at https://github.com/rgraciano/echo-sonos. If you have questions about the requests sent to this library, figure out the exact request that is sent from the Alexa Skill (through the logs) and include that in the issue.

Thank you!

**Comment by jishi** [comment]
This command is in the wrong order.

It's `RoomName/leave` (or isolate, ungroup) and it will trigger this player to leave any group it belongs to. There is no `remove` command AFAIK.

**Comment by parth0295** [comment]
@jishi Thanks! I appreciate all your work! The "remove" command is listed under the sonos API page that appears when I open the server IP. 

https://imgur.com/MZ4TOr4

**Comment by jishi** [comment]
Yeah, that documentation is obviously wrong, I think I modified the logic a bit before merging this feature, but forgot to update the docs. Thanks for telling me!
