### ISSUE TITLE
Clearing cache (library.json)

### ISSUE THREAD

**Issue by Thyraz** [jishi/node-sonos-http-api#797]
Is there any way to force a relaod of the library.json?
Or should it be done automatically in some way?

Today I added some content to the local Sonos library and startet a reinde through the Sonos app.
After that I was able to see and play the content in the app.
But I couldn't start the albums from node-sonos-http-api.

I rebootet the server and my whole Sonos system, but it still wasn't able to find the albums.
Then I shutdown node-sonos-http-api, deleted cache/library.json and startet it again.
After that everything worked fine.

So not sure if there's something wrong on my side, or this is a bug.
I even tried to run the reindex command of node-sonos-http-api in hope it would rebuild the library.json afterwards, but that also didn't help.

Any ideas?

**Comment by emufan** [comment]
/<device>/musicsearch/library/load

as explained here as well: https://github.com/jishi/node-sonos-http-api
