### ISSUE TITLE
Could @jishi  consider letting other contributors help with this plugin?

### ISSUE THREAD

**Issue by jsiegenthaler** [jishi/node-sonos-http-api#800]
Could @jishi  consider letting other contributors help with this plugin?

It is now April 2021, and there are so many issues, so many pull requests, and so much outdated information on this plugin

I'd be happy to help update whatever I can.

It's sad to see this plugin falling into disrepair...

**Comment by jishi** [comment]
Hi, I'm definitely open to allow contributors to help out. But so far none has reached out to me about it. 

It would also include maintaining the underlying node-sonos-discovery source and the tests with it, thus also making sure there is test coverage for any new features and/or fixes that gets applied... which is most of the work, usually. 😣

**Comment by jsiegenthaler** [comment]
I would like to help update the README on the master branch. It contains very old, outdated information.
It is also missing installation instructions, and for beginners this makes this node module very difficult to install.

**Comment by jsiegenthaler** [comment]
Hello @jishi : any news on letting me update at least the README for you? It is over a year outdated....

**Comment by MalHarwood** [comment]
@jishi hand up here too .. lets clear that backlog!

**Comment by jishi** [comment]
Feels like you don't fully understand github. Normally people fork the repository, make changes, then start a pull request against this repository and I will be able to aprove, decline and merge the changes. 

That will either way be the first step into maybe allowing collaborators to merge changes themselves. I need to know that people can do quality changes otherwise this will fall apart pretty quickly. 

I have negative free time at the moment for any personal contribution, but checking and merging PRs I can do if they are well written and well documented and has a general purpose.

**Comment by jsiegenthaler** [comment]
Hi @jishi 
I appreciate that a project requires time and attention, as I too have multiple projects on GitHub.

I don't want to appear overly negative here, but there are currently 17 pull requests open, and some of them go back for over 5 years. That's what is giving me the impression that this project is not being worked on.

I'd love to help where I can - I cannot do everything, but I can certainly work in some areas. However, you are the gatekeeper, and I am reluctant to invest my own time if my pull request also ends up in the "untouched and unloved" pile.

**Comment by MalHarwood** [comment]
@jishi and @jsiegenthaler 

Agree with you both ..

But also looking at the issues list ... things like #767 should be closed, etc to just clean things up .. 

As far as those 17 open pull requests .. I am going through them now to see if there is anything I can do to help get them included ...

**Comment by jsiegenthaler** [comment]
Closing this issue as @jishi repsonded
