### ISSUE TITLE
Shuffle broken?

### ISSUE THREAD

**Issue by icurnvs** [jishi/node-sonos-http-api#836]
Shuffle appears to be broken on new installs.

I've replicated this multiple times now.  I've installed this on a pi 4 model b w/ the pi os 32 bit.
No issues installing node js and the install and start node-sonos-http-api works as well and I'm able to get to the http ui.  Everything I've tested appears to work, except shuffle.  When trying to set shuffle off or on, i get the following error:
`{"status":"error","error":"mode is not defined","stack":"ReferenceError: mode is not defined\n    at /home/tyler/node-sonos-http-api/lib/actions/playmode.js:26:42\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}`
I've tested other funtions within playmode.js (repeat and crossfade) and they return success. Doing anything with shuffle, however, throws an error.

Apologies if i'm missing any information - I'm new to posting on github.

**Comment by icurnvs** [comment]
Must have been user error. Although I seem to not be able to manually toggle this in the URL, it is behaving as expected after a fresh install of node-sonos-nfc.

**Comment by chuil** [comment]
Also have the same issue...
