### ISSUE TITLE
Say in two or more rooms

### ISSUE THREAD

**Issue by hallerdavid** [jishi/node-sonos-http-api#855]
Hello! Is there a simple way to TTS or Clip in two or more rooms?

I have one speaker in my garage for automating the packages and post, but i don´t want to have this speaker in "clipall" or "playall". 

So i want to do something like /livingroom&&kitchen&&kino/clip/gong.mp3

I think its the wrong way to group and ungroup the speakers, because you never know what the actual groups are and get them back to this point after the sound / gong / whatever.

**Comment by jishi** [comment]
You can use a preset to trigger a subset, but it still groups them just to
play in sync. If you are fine with announcements out of sync, you can just
invoke them individually?
