### ISSUE TITLE
Spotify Radio/autoplay support

### ISSUE THREAD

**Issue by samueljim** [jishi/node-sonos-http-api#867]
How difficult it would it be to integrate a keep playing function after the queue has ended where it automatically adds more similar songs? I hate that after the queue is done, the music just stops and I want something like YouTube autoplay to keep the party going 🥳

**Comment by jishi** [comment]
This would be very hard, since not even the native Sonos client does that and Spotify probably doesn't expose that functionality. It would have to find "similar songs" via some API and keep populating the queue.
