### ISSUE TITLE
Buffer() is deprecated

### ISSUE THREAD

**Issue by crissmil** [jishi/node-sonos-http-api#875]
Hi Joshi!

Please assist on below error after latest Sonos update:

2023-08-29T06:47:00.430Z ERROR 
  { error: "action 'living%20room' not found" }
(node:12959) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2023-08-29T06:47:11.791Z ERROR 
  { error: "action 'living%20room' not found" }

**Comment by jishi** [comment]
The buffer error is unrelated to your problem.

The command you are sending are either interpreted wrong, or you are
sending an faulty command.

It shouldn't parse living room as an action, but rather a room. Show me
what you are calling.

**Comment by crissmil** [comment]
Thanks for your prompt reply.
I found the problem. It was Home app from my iPhone which changed the Sonos rooms names. 
Changed back to previous names fixed the problem.

But before this I replaced 'new Buffer' with 'Buffer.from' into below 2 files and got rid of deprecated Buffer():
spotifyDef.js
sonos-http-api.js
