### ISSUE TITLE
Language paremeter in say command does not alter the speaker language

### ISSUE THREAD

**Issue by Marty56** [jishi/node-sonos-http-api#88]
It seems that setting the language parameter has no effect on output in "say" command.
The voice seems to be always using english as output which makes the output hardly understandable.

I have been testing it using "de" as language parameter to receive German output.

**Comment by jishi** [comment]
Yeah, this got lost when we couldn't use google translate API anymore. I will implement voicerss which is a registered service (there is a free plan as well, but you need to register) which will have language support again.

**Comment by jishi** [comment]
Closing this, please follow https://github.com/jishi/node-sonos-http-api/issues/97 for progress.
