### ISSUE TITLE
Playing audio/mpeg stream

### ISSUE THREAD

**Issue by dimityrivanov** [jishi/node-sonos-http-api#906]
Hello I am trying to play audio/mpeg stream threw the Sonos API using avltransport directly but it seems I can only make it work with radiomp3 is there any special tag that I have to parse to the avltransport to make it work ?

**Comment by jishi** [comment]
I don't have any useful information about that. It was a long time ago I experimented with it, and I know there was some quirks in trying to set custom avtransport-uris.

Best is if you can actually make it work from the official app and replicate it. I do remember that the actual file suffix on the urls did affect how the players parsed the stream, and I recall I managed to play raw wav files but the url had to end in ".wav" for it to accept it. For mpeg audio, I guess mpa or mp4 or similar might be required.

**Comment by dimityrivanov** [comment]
@jishi To be honest I wanted to play YouTube music from the audio streams I am getting from YouTube explode but no luck so far to check what is the Uri from the Sonos app because for some reason I can't connect it with my YouTube account it says always empty playlist...

**Comment by jishi** [comment]
Do share your findings for other to indulge in!

**Comment by dimityrivanov** [comment]
@jishi Well the Sonos needs a link that points to HTTP server where it ends at /media.mp3 or mp4 then you just need to extract the url media of the video in YouTube in MP4 format it can be just audio only and when the Sonos hits the custom /media.mp4 url you have to execute 301 redirect with express to the url of the YouTube mp4 audio only stream and job is done I do that by using the action 'setavtransporturi/'here I add my http custom url and leave the redirect to do its job''
