### ISSUE TITLE
preset file

### ISSUE THREAD

**Issue by robertw** [jishi/node-sonos-http-api#95]
since i updated wen i run preset it works fine the first time i make a call all the players link and play but if i call another preset only a few players will link not all i have 9 players in each preset i need to reboot the server and then they all ink but only one time the next call fails on linking 2 players each time very strange. But rebooting clears the problem any thoughts thanks

**Comment by jishi** [comment]
could you please provide some more details on the the two presets that you are alternating between? 

are you invoking these two during a short time interval?

**Comment by robertw** [comment]
Good dayhere is the json file i am using i first invoke hrock and then the
hjazz waiting aprox 1 - 2 min and then i tried waiting 5 min no difference
it does unlink al players but wil not relink as per the next preset untill
i reboot


i dont see any erros on the screen

may thanks

On Thu, Dec 3, 2015 at 3:26 PM, Jimmy Shimizu <notifications@github.com>
wrote:

> could you please provide some more details on the the two presets that you
> are alternating between?
>
> are you invoking these two during a short time interval?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jishi/node-sonos-http-api/issues/95#issuecomment-161772911>
> .
>



-- 
Regards

Robert

**Comment by robertw** [comment]
After looking further into it it maybe that there 2 paired left and right
setups and i believe i did not have paired in the system before.......

On Fri, Dec 4, 2015 at 8:05 AM, Robert Wyman <wymanrobert@gmail.com> wrote:

> Good dayhere is the json file i am using i first invoke hrock and then the
> hjazz waiting aprox 1 - 2 min and then i tried waiting 5 min no difference
> it does unlink al players but wil not relink as per the next preset untill
> i reboot
>
>
> i dont see any erros on the screen
>
> may thanks
>
> On Thu, Dec 3, 2015 at 3:26 PM, Jimmy Shimizu <notifications@github.com>
> wrote:
>
>> could you please provide some more details on the the two presets that
>> you are alternating between?
>>
>> are you invoking these two during a short time interval?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jishi/node-sonos-http-api/issues/95#issuecomment-161772911>
>> .
>>
>
>
>
> --
> Regards
>
> Robert
>



-- 
Regards

Robert

**Comment by jishi** [comment]
I don't see the preset. Could you explain your topology? Does the issue return when you pair them again? Do note that you need to restart the http-api if you remove or modify the player setup in any way (like pairs or removing players completely).

**Comment by robertw** [comment]
{

    "office": {

      "players": [

        { "roomName": "Office", "volume": 30}

      ],

      "state": "PLAYING",

      "favorite": "Sting Radio",

      "playMode": "NORMAL",

      "pauseOthers": true

    },

   "hrock": {

      "players": [

        { "roomName": "Office", "volume": 30},

        { "roomName": "Family Room", "volume": 30},

        { "roomName": "Living Room", "volume": 30},

        { "roomName": "Master Bedroom", "volume": 30},

        { "roomName": "Bathroom", "volume": 40},

        { "roomName": "Portable", "volume": 50}

      ],

      "state": "PLAYING",

      "favorite": "Santana Radio",

      "playMode": "NORMAL",

      "pauseOthers": true

    },

    "hjazz": {

      "players": [

        { "roomName": "Office", "volume": 30},

        { "roomName": "Family Room", "volume": 30},

        { "roomName": "Living Room", "volume": 30},

        { "roomName": "Master Bedroom", "volume": 30},

        { "roomName": "Bathroom", "volume": 40},

      { "roomName": "Patio", "volume": 40},

        { "roomName": "Portable", "volume": 50}

      ],

      "state": "PLAYING",

      "favorite": "Fourplay Radio",

      "playMode": "NORMAL",

      "pauseOthers": true

    },

    "hparty": {

      "players": [

        { "roomName": "Office", "volume": 30},

        { "roomName": "Family Room", "volume": 30},

        { "roomName": "Living Room", "volume": 30},

        { "roomName": "Master Bedroom", "volume": 30},

        { "roomName": "Bathroom", "volume": 40},

      { "roomName": "Patio", "volume": 40},

        { "roomName": "Portable", "volume": 50}

      ],

      "state": "PLAYING",

      "favorite": "Rock",

      "playMode": "NORMAL",

      "pauseOthers": true

    }



the portable and patio are paired if i try to send a soap string works just
fine so i know it is not my network if i remove the paired devices of
course i reboot and every works smooth the preset works the first time
after bootup but if i change to another preset it works some times and
other it only link 2 zones and hangs and always hangs on the paired and
then i need to reboot

On Fri, Dec 4, 2015 at 11:32 AM, Jimmy Shimizu <notifications@github.com>
wrote:

> I don't see the preset. Could you explain your topology? Does the issue
> return when you pair them again? Do note that you need to restart the
> http-api if you remove or modify the player setup in any way (like pairs or
> removing players completely).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jishi/node-sonos-http-api/issues/95#issuecomment-162013129>
> .
>



-- 
Regards

Robert

**Comment by jishi** [comment]
Hm, so what you are describing is this:

When you pair Patio and Portable, effectively removing one of them (let's say it's Portable). When my api will try and invoke commands to the Portable, it will fail. You say that you reboot the http api after you pair them up, which means that I should "skip" that player since it isn't aware of it, but it fails the first time, but after a reboot of the http-api, it works?

I don't really have an idea why that is at the moment, I probably need to try and reproduce this for myself in order to fix it.

**Comment by robertw** [comment]
Sorry for the delay been out of town not really just ssimple change form on preset to another it will hang on the paired zone it will work fine on intail call but if more are made it hangs and needs to be rebooted .......Thanks

**Comment by robertw** [comment]
Thanks I closed this by mistake sorry
