### ISSUE TITLE
Implement voicerss with registered key

### ISSUE THREAD

**Issue by jishi** [jishi/node-sonos-http-api#97]
Allow the use of voicerss.org and adding an API key (free or paid).

**Comment by jolerius** [comment]
Is it possible yet? To integrate with voicerss.org?
So we actually can have it speak correctly?

**Comment by joystick666** [comment]
yeah waiting for this aswell :) However, merry christmas

**Comment by rhalbheer** [comment]
I added just a few lines of code to tryDownloadTTS:
instead of your "nerd.host" line I added:
  var url_lang;
  switch (language) {
  case "de":
     url_lang = "de-de";
     break;
  default:
     url_lang = "en-us";
  }

  var tts_request = 'http://www.voicerss.org/controls/speech.ashx?hl=' + url_lang + '&src=' + phrase;

as you can see, I wanted not to change the calling URLs, therefore added the switch statement for the two languages I need. There are nicer ways to do this, but I need only these two. It works w/o key.

**Comment by potherca** [comment]
As discussed over on #73, moving the URL to a `config.js` seems desirable. From there it should be trivial to add an entry to hold an API key.

This would also allow user to use a different TTS Server if they wanted, as they could change the URL.

Some [shoe-horning](https://en.wikipedia.org/wiki/Shoehorn#Turn_of_phrase) might be required to get a URL scheme/logic that works for _any_ server (regardless of the API) but I'm sure we can come up with  something smart enough to deal with that.

**Comment by m0rph13** [comment]
When testing with voice RSS, you need to change the speech audio format as Sonos will not like the default '8khz_8bit_mono'. 
`8khz_8bit_mono`

**Comment by jishi** [comment]
I made a simple implementation for now. You need to add your registered key into the settings, please see the README for more info.

**Comment by TheHavocHero** [comment]
Got it all working and the volume is working right now! Love the fact that the current song will resume after the TTS is played. 

On another note, sorry for not asking this in the right place, but can you point me in the right direction on how to get node-sonos-http-api to work with Docker? I am using a Synology NAS. I have an Ubuntu image running in a container. Do I need to copy the docker files you provide into my image filesystem? Sorry, I am new to Docker. Thanks in advance. I love the work you have done.
